SELECT 
A.DATA_ACESSO,
C.NOME,
C.USUARIO,
C.EMAIL,
D.NOME AS SISTEMA,
B.PAGINA,
B.PAGINA_URL,
A.IP, 
A.NAVEGADOR
FROM CADU..SISTEMAS_MONITOR_LOG A
INNER JOIN CADU..SISTEMAS_MONITOR B ON A.ID_MONITOR = B.ID_MONITOR
INNER JOIN CADU..USUARIOS C ON A.ID_USUARIO = C.ID_USUARIO
INNER JOIN CADU..SISTEMAS D ON B.ID_SISTEMA = D.ID_SISTEMA
WHERE D.NOME = 'Dashboard Gestão Móvel' --AND PAGINA LIKE '%Mapa%'/*AND PAGINA_URL LIKE '%P1%'*/
AND A.DATA_ACESSO >= '2021-06-28' 
ORDER BY A.DATA_ACESSO DESC
-----------------------------------------------------------------------------
--QTDE DE ACESSOS POR USUÁRIO
-----------------------------------------------------------------------------
DECLARE @HOJE DATE = GETDATE()
SELECT
C.NOME,
COUNT(C.NOME) AS QTDE_ACESSOS

FROM CADU..SISTEMAS_MONITOR_LOG A
INNER JOIN CADU..SISTEMAS_MONITOR B ON A.ID_MONITOR = B.ID_MONITOR
INNER JOIN CADU..USUARIOS C ON A.ID_USUARIO = C.ID_USUARIO
INNER JOIN CADU..SISTEMAS D ON B.ID_SISTEMA = D.ID_SISTEMA
WHERE D.NOME = 'Dashboard Gestão Móvel' AND PAGINA LIKE '%Executivo%' AND A.DATA_ACESSO >= @HOJE
GROUP BY C.NOME
ORDER BY QTDE_ACESSOS DESC
--------------------------------------------------------------------------
--PÁGINAS MAIS ACESSADAS
--------------------------------------------------------------------------
DECLARE @HOJE DATE = GETDATE()
SELECT
B.PAGINA,
COUNT(B.PAGINA) AS QTDE_ACESSOS

FROM CADU..SISTEMAS_MONITOR_LOG A
INNER JOIN CADU..SISTEMAS_MONITOR B ON A.ID_MONITOR = B.ID_MONITOR
INNER JOIN CADU..USUARIOS C ON A.ID_USUARIO = C.ID_USUARIO
INNER JOIN CADU..SISTEMAS D ON B.ID_SISTEMA = D.ID_SISTEMA
WHERE D.NOME = 'Dashboard Gestão Móvel' AND PAGINA LIKE '%Executivo%' AND A.DATA_ACESSO >= @HOJE
GROUP BY B.PAGINA
ORDER BY QTDE_ACESSOS DESC

