-- ==================================================================
-- AFETACAO DE ERBs POR TIPO DE REDE E GESTOR ATUAL
-- ==================================================================
SELECT TOP 10
    'TOTAL' AS IMPACTO,
    B.TIPO_REDE,
    B.GESTOR_ATUAL,
    COUNT(DISTINCT CONCAT(C.UF, C.SIGLA_SITE)) AS AFETACAO_SITES,
    COUNT(DISTINCT CONCAT(C.UF, C.EQUIPAMENTO)) AS AFETACAO_ERBS
FROM 
    REDE_EXTERNA..TBL_GRAFO_EVENTOS A
    INNER JOIN REDE_EXTERNA..TBL_EVENTOS_ATIVOS_SIGITM B ON A.TA_REFERENCIA = B.EVENTO
    INNER JOIN REDE_EXTERNA..TBL_EVENTOS_ATIVOS_SIGITM C ON A.TA_PARA = C.EVENTO
WHERE 
    C.TIPO_REDE = 'ERB / REPETIDOR' 
    AND C.PRIORIDADE = 1 
    AND C.IMPACTO = 'TOTAL'
GROUP BY B.TIPO_REDE, B.GESTOR_ATUAL
UNION ALL
SELECT TOP 10
    'PARCIAL' AS IMPACTO,
    B.TIPO_REDE,
    B.GESTOR_ATUAL,
    COUNT(DISTINCT CONCAT(C.UF, C.SIGLA_SITE)) AS AFETACAO_SITES,
    COUNT(DISTINCT CONCAT(C.UF, C.EQUIPAMENTO)) AS AFETACAO_ERBS
FROM 
    REDE_EXTERNA..TBL_GRAFO_EVENTOS A
    INNER JOIN REDE_EXTERNA..TBL_EVENTOS_ATIVOS_SIGITM B ON A.TA_REFERENCIA = B.EVENTO
    INNER JOIN REDE_EXTERNA..TBL_EVENTOS_ATIVOS_SIGITM C ON A.TA_PARA = C.EVENTO
WHERE 
    C.TIPO_REDE = 'ERB / REPETIDOR' 
    AND C.PRIORIDADE = 2 
    AND C.IMPACTO = 'PARCIAL' 
    AND C.TIPO_BILHETE NOT LIKE '%INFRA%'
    AND B.SIGLA_SITE <> '1234'
GROUP BY B.TIPO_REDE, B.GESTOR_ATUAL
ORDER BY 1 DESC, 5 DESC


-- ==================================================
-- SITES COM MAIOR AFETAÇÃO
-- ==================================================
SELECT
    'TOTAL' AS IMPACTO,
    B.UF,
    B.SIGLA_SITE,
    COUNT(DISTINCT CONCAT(C.UF, C.SIGLA_SITE)) AS AFETACAO_SITES,
    COUNT(DISTINCT CONCAT(C.UF, C.EQUIPAMENTO)) AS AFETACAO_ERBS
FROM 
    REDE_EXTERNA..TBL_GRAFO_EVENTOS A
    INNER JOIN REDE_EXTERNA..TBL_EVENTOS_ATIVOS_SIGITM B ON A.TA_REFERENCIA = B.EVENTO
    INNER JOIN REDE_EXTERNA..TBL_EVENTOS_ATIVOS_SIGITM C ON A.TA_PARA = C.EVENTO
WHERE 
    C.TIPO_REDE = 'ERB / REPETIDOR' 
    AND C.PRIORIDADE = 1 
    AND C.IMPACTO = 'TOTAL'
    AND B.SIGLA_SITE <> '1234'
GROUP BY B.UF, B.SIGLA_SITE
UNION ALL
SELECT
    'PARCIAL' AS IMPACTO,
    B.UF,
    B.SIGLA_SITE,
    COUNT(DISTINCT CONCAT(C.UF, C.SIGLA_SITE)) AS AFETACAO_SITES,
    COUNT(DISTINCT CONCAT(C.UF, C.EQUIPAMENTO)) AS AFETACAO_ERBS
FROM 
    REDE_EXTERNA..TBL_GRAFO_EVENTOS A
    INNER JOIN REDE_EXTERNA..TBL_EVENTOS_ATIVOS_SIGITM B ON A.TA_REFERENCIA = B.EVENTO
    INNER JOIN REDE_EXTERNA..TBL_EVENTOS_ATIVOS_SIGITM C ON A.TA_PARA = C.EVENTO
WHERE 
    C.TIPO_REDE = 'ERB / REPETIDOR' 
    AND C.PRIORIDADE = 2 
    AND C.IMPACTO = 'PARCIAL' 
    AND C.TIPO_BILHETE NOT LIKE '%INFRA%'
    AND B.SIGLA_SITE <> '1234'
GROUP BY B.UF, B.SIGLA_SITE
ORDER BY AFETACAO_ERBS DESC


-- ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
-- ==================================================================
-- GESTORES COM MAIOR AFETACAO
-- ==================================================================
SELECT
    'TOTAL' AS IMPACTO,
    B.GESTOR_ATUAL,
    COUNT(DISTINCT CONCAT(C.UF, C.SIGLA_SITE)) AS AFETACAO_SITES,
    COUNT(DISTINCT CONCAT(C.UF, C.EQUIPAMENTO)) AS AFETACAO_ERBS
FROM 
    REDE_EXTERNA..TBL_GRAFO_EVENTOS A
    INNER JOIN REDE_EXTERNA..TBL_EVENTOS_ATIVOS_SIGITM B ON A.TA_REFERENCIA = B.EVENTO
    INNER JOIN REDE_EXTERNA..TBL_EVENTOS_ATIVOS_SIGITM C ON A.TA_PARA = C.EVENTO
WHERE 
    C.TIPO_REDE = 'Erb / Repetidor' 
    AND C.PRIORIDADE = 1 
    AND C.IMPACTO = 'TOTAL'
GROUP BY B.GESTOR_ATUAL
UNION ALL
SELECT
    'PARCIAL' AS IMPACTO,
    B.GESTOR_ATUAL,
    COUNT(DISTINCT CONCAT(C.UF, C.SIGLA_SITE)) AS AFETACAO_SITES,
    COUNT(DISTINCT CONCAT(C.UF, C.EQUIPAMENTO)) AS AFETACAO_ERBS
FROM 
    REDE_EXTERNA..TBL_GRAFO_EVENTOS A
    INNER JOIN REDE_EXTERNA..TBL_EVENTOS_ATIVOS_SIGITM B ON A.TA_REFERENCIA = B.EVENTO
    INNER JOIN REDE_EXTERNA..TBL_EVENTOS_ATIVOS_SIGITM C ON A.TA_PARA = C.EVENTO
WHERE 
    C.TIPO_REDE = 'ERB / REPETIDOR' 
    AND C.PRIORIDADE = 2 
    AND C.IMPACTO = 'PARCIAL' 
    AND C.TIPO_BILHETE NOT LIKE '%INFRA%'
    AND B.SIGLA_SITE <> '1234'
GROUP BY B.GESTOR_ATUAL
ORDER BY 1 DESC, 4 DESC

-- ==================================================================
-- GESTORES, ERBS AFETADAS E TAs
-- ==================================================================
SELECT
    'TOTAL' AS IMPACTO,
    A.TA_REFERENCIA,
    B.GESTOR_ATUAL,
    C.UF,
    C.EQUIPAMENTO,
    COUNT(DISTINCT CONCAT(C.UF, C.SIGLA_SITE)) AS AFETACAO_SITES,
    COUNT(DISTINCT CONCAT(C.UF, C.EQUIPAMENTO)) AS AFETACAO_ERBS
FROM 
    REDE_EXTERNA..TBL_GRAFO_EVENTOS A
    INNER JOIN REDE_EXTERNA..TBL_EVENTOS_ATIVOS_SIGITM B ON A.TA_REFERENCIA = B.EVENTO
    INNER JOIN REDE_EXTERNA..TBL_EVENTOS_ATIVOS_SIGITM C ON A.TA_PARA = C.EVENTO
WHERE 
    C.TIPO_REDE = 'Erb / Repetidor' 
    AND C.PRIORIDADE = 1 
    AND C.IMPACTO = 'TOTAL'
GROUP BY B.GESTOR_ATUAL, A.TA_REFERENCIA, C.UF, C.EQUIPAMENTO
UNION ALL
SELECT
    'PARCIAL' AS IMPACTO,
    A.TA_REFERENCIA,
    B.GESTOR_ATUAL,
    C.UF,
    C.EQUIPAMENTO,
    COUNT(DISTINCT CONCAT(C.UF, C.SIGLA_SITE)) AS AFETACAO_SITES,
    COUNT(DISTINCT CONCAT(C.UF, C.EQUIPAMENTO)) AS AFETACAO_ERBS
FROM 
    REDE_EXTERNA..TBL_GRAFO_EVENTOS A
    INNER JOIN REDE_EXTERNA..TBL_EVENTOS_ATIVOS_SIGITM B ON A.TA_REFERENCIA = B.EVENTO
    INNER JOIN REDE_EXTERNA..TBL_EVENTOS_ATIVOS_SIGITM C ON A.TA_PARA = C.EVENTO
WHERE 
    C.TIPO_REDE = 'ERB / REPETIDOR' 
    AND C.PRIORIDADE = 2 
    AND C.IMPACTO = 'PARCIAL' 
    AND C.TIPO_BILHETE NOT LIKE '%INFRA%'
    AND B.SIGLA_SITE <> '1234'
GROUP BY B.GESTOR_ATUAL, A.TA_REFERENCIA, C.UF, C.EQUIPAMENTO
ORDER BY 2