-- ==================================================
-- P1 REAL TIME - BACKLOG - versao 2
-- ==================================================
WITH DATAS AS (
    SELECT TOP 12
        ROW_NUMBER() OVER (ORDER BY DATA_REFERENCIA DESC) AS DT,
        DATA_REFERENCIA
    FROM REDE_EXTERNA..TBL_EVENTOS_ATIVOS_SIGITM WITH(NOLOCK)
    GROUP BY DATA_REFERENCIA
    ORDER BY DATA_REFERENCIA DESC
),
HORA AS (
    SELECT
        C.DATA_REFERENCIA,
        'BACKLOG' AS GESTOR,
        CASE WHEN A.UF = 'SP' THEN D.NOME_REGIONAL
             WHEN UF IN ('AC','DF','GO','MS','MT','RO','TO') THEN 'CO'
             WHEN UF IN ('MG','ES','RJ') THEN 'SUD'
             WHEN UF IN ('AL','CE','PB','PE','PI','RN','BA','SE') THEN 'NE'
             WHEN UF IN ('AM','AP','MA','PA','RR') THEN 'NO'
             WHEN UF IN ('PR','RS','SC') THEN 'SUL'
        END AS REGIONAL,
        COUNT(DISTINCT UF+EQUIPAMENTO) AS HORA
    FROM REDE_EXTERNA..TBL_EVENTOS_ATIVOS_SIGITM A WITH(NOLOCK)
    INNER JOIN DATAS C ON A.DATA_REFERENCIA = C.DATA_REFERENCIA
    LEFT JOIN INDICADORES_CORAN..AUX_CLASSIFICACAO_GESTORES B WITH(NOLOCK) ON A.GESTOR_EVENTO_REFERENCIA = B.GRUPO
    LEFT JOIN INDICADORES_CORAN..TBA_DIVISAO_MUNICIPIOS_SP_FIXA D ON A.UF = 'SP' AND A.MUNICIPIO = D.MUNICIPIO
    WHERE A.TIPO_PLANTA = 'Móvel' 
        AND A.TIPO_REDE = 'ERB / Repetidor' 
        AND A.PRIORIDADE = 1 
        AND B.CLASSIFICACAO_GRUPO = 'NOC'
    GROUP BY C.DATA_REFERENCIA, D.NOME_REGIONAL, UF, B.CLASSIFICACAO_GRUPO
)

SELECT
    REGIONAL,
    GESTOR,
    SUM(CASE WHEN DATAS.DT = 1 THEN HORA ELSE 0 END) AS HORA_1,
    SUM(CASE WHEN DATAS.DT = 2 THEN HORA ELSE 0 END) AS HORA_2,
    SUM(CASE WHEN DATAS.DT = 3 THEN HORA ELSE 0 END) AS HORA_3,
    SUM(CASE WHEN DATAS.DT = 4 THEN HORA ELSE 0 END) AS HORA_4,
    SUM(CASE WHEN DATAS.DT = 5 THEN HORA ELSE 0 END) AS HORA_5,
    SUM(CASE WHEN DATAS.DT = 6 THEN HORA ELSE 0 END) AS HORA_6,
    SUM(CASE WHEN DATAS.DT = 7 THEN HORA ELSE 0 END) AS HORA_7,
    SUM(CASE WHEN DATAS.DT = 8 THEN HORA ELSE 0 END) AS HORA_8,
    SUM(CASE WHEN DATAS.DT = 9 THEN HORA ELSE 0 END) AS HORA_9,
    SUM(CASE WHEN DATAS.DT = 10 THEN HORA ELSE 0 END) AS HORA_10,
    SUM(CASE WHEN DATAS.DT = 11 THEN HORA ELSE 0 END) AS HORA_11,
    SUM(CASE WHEN DATAS.DT = 12 THEN HORA ELSE 0 END) AS HORA_12
FROM HORA
INNER JOIN DATAS ON HORA.DATA_REFERENCIA = DATAS.DATA_REFERENCIA
GROUP BY GESTOR, REGIONAL







SELECT
        A.DATA_REFERENCIA
        ,'BACKLOG' AS GESTOR
        ,A.*
        ,B.*
        -- ,COUNT(DISTINCT UF+EQUIPAMENTO) AS HORA
    FROM REDE_EXTERNA..TBL_EVENTOS_ATIVOS_SIGITM A WITH(NOLOCK)
    -- INNER JOIN DATAS C ON A.DATA_REFERENCIA = C.DATA_REFERENCIA
    LEFT JOIN INDICADORES_CORAN..AUX_CLASSIFICACAO_GESTORES B WITH(NOLOCK) ON A.GESTOR_EVENTO_REFERENCIA = B.GRUPO
    WHERE A.TIPO_PLANTA = 'Móvel' 
        AND A.TIPO_REDE = 'ERB / Repetidor' 
        AND A.PRIORIDADE = 1 
        -- AND B.CLASSIFICACAO_GRUPO = 'NOC'
        AND A.DATA_REFERENCIA = '2024-06-18 15:00:44.000'
        AND UF IS NULL
    -- GROUP BY A.DATA_REFERENCIA, B.CLASSIFICACAO_GRUPO

