--Baseline estratificado
SELECT
DIA,
MES,
ANO,
UF,
CLASS AS CLASSIFICACAO,
COUNT(CLASS) AS QTDE
--LEGENDA = 'Mês Atual'
FROM (
        SELECT
                    DAY(DATA_ENCERRAMENTO) AS DIA,
					MONTH(DATA_ENCERRAMENTO) AS MES,
					YEAR(DATA_ENCERRAMENTO) AS ANO,
					                    UF,
                   CASE WHEN TIPO_REDE IN ('Metro Baixa' , 'DWDM', 'Rádio','SDH') THEN 'TX'
                        WHEN TIPO_REDE IN ('ERB / Repetidor') THEN 'RF'
                        WHEN TIPO_REDE IN ('Climatização', 'Energia') THEN 'INFRA'
                        WHEN TIPO_REDE IN ('Óptica') THEN 'REDE EXTERNA'
                        WHEN TIPO_REDE IN ('Serviço de Internet', 'Determinística', 'IP', 'ADSL', 'Central', 'BSC / RNC') THEN 'OUTROS'
                        WHEN TIPO_REDE = 'ERB / Repetidor' AND TIPO_BILHETE = 'ASTRO DOL' THEN 'DOL'
                   END AS CLASS
                FROM INDICADORES_CORAN..TBL_EVENTOS_FECHADOS WITH(NOLOCK)
                WHERE ANO IN (YEAR(GETDATE()),YEAR(GETDATE())-1,YEAR(GETDATE())-2) AND FLAG_BASELINE = 1 AND UF <> '-'
    )A
GROUP BY ANO, MES, DIA, UF, CLASS
--ORDER BY UF, MES, DIA
--+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
--
--+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
-- MES ATUAL
SELECT
DIA,
MES= MONTH(GETDATE()),
ANO = YEAR(GETDATE()),
UF,
EVENTOS,
LEGENDA = 'Mês Atual',
SUM(EVENTOS) OVER (PARTITION BY UF ORDER BY DIA ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS EVENTOS_ACUMULADO
FROM (
    SELECT
    DAY(DATA_ENCERRAMENTO) AS DIA,
    UF,
    COUNT(DISTINCT EVENTO) AS EVENTOS
    FROM INDICADORES_CORAN..TBL_EVENTOS_FECHADOS WITH(NOLOCK)
    WHERE ANO = YEAR(GETDATE()) AND MES = MONTH(GETDATE()) AND FLAG_BASELINE = 1 AND UF <> '-'
    GROUP BY DAY(DATA_ENCERRAMENTO), UF
)A WHERE DIA <> DAY(GETDATE())

	UNION ALL

-- MES ANTERIOR
SELECT
DIA,
MES= MONTH(GETDATE())-1,
ANO = YEAR(GETDATE()),
UF,
EVENTOS,
LEGENDA = 'Mês Anterior',
SUM(EVENTOS) OVER (PARTITION BY UF ORDER BY DIA ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS EVENTOS_ACUMULADO
FROM (
    SELECT
    DAY(DATA_ENCERRAMENTO) AS DIA,
    UF,
    COUNT(DISTINCT EVENTO) AS EVENTOS
    FROM INDICADORES_CORAN..TBL_EVENTOS_FECHADOS WITH(NOLOCK)
    WHERE ANO = YEAR(GETDATE()) AND MES= MONTH(GETDATE())-1 AND FLAG_BASELINE = 1 AND UF <> '-'
    GROUP BY DAY(DATA_ENCERRAMENTO), UF
)A 


	UNION ALL


-- ANO ANTERIOR MES ATUAL
SELECT
DIA,
MES= MONTH(GETDATE()),
ANO = YEAR(GETDATE())-1,
UF,
EVENTOS,
LEGENDA = 'Ano Anterior',
SUM(EVENTOS) OVER (PARTITION BY UF ORDER BY DIA ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS EVENTOS_ACUMULADO
FROM (
    SELECT
    DAY(DATA_ENCERRAMENTO) AS DIA,
    UF,
    COUNT(DISTINCT EVENTO) AS EVENTOS
    FROM INDICADORES_CORAN..TBL_EVENTOS_FECHADOS WITH(NOLOCK)
    WHERE ANO = YEAR(GETDATE())-1 AND MES = MONTH(GETDATE()) AND FLAG_BASELINE = 1 AND UF <> '-'
    GROUP BY DAY(DATA_ENCERRAMENTO), UF
)A 

--================================================================================================================================

SELECT
ANO,
MES,
DIA,
A.UF,
EVENTOS,
SUM(EVENTOS) OVER (PARTITION BY UF ORDER BY DIA ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS EVENTOS_ACUMULADO,
A.TIPO_PAGAMENTO
FROM (
    SELECT
    ANO,
    MES,
    DAY(DATA_ENCERRAMENTO) AS DIA,
    TA.UF,
    CASE WHEN SIT.UF IS NULL OR SIT.SITE IS NULL THEN 'DEMANDA' ELSE 'FIXO' END TIPO_PAGAMENTO,
    COUNT(DISTINCT EVENTO) AS EVENTOS
    FROM INDICADORES_CORAN..TBL_EVENTOS_FECHADOS TA WITH(NOLOCK)
    LEFT JOIN INDICADORES_CORAN..AUX_EXCLUSAO_SITES SIT WITH(NOLOCK)
    ON  TA.UF COLLATE Latin1_General_CI_AI = SIT.UF COLLATE Latin1_General_CI_AI
    AND TA.SITE COLLATE Latin1_General_CI_AI = SIT.SITE COLLATE Latin1_General_CI_AI
    WHERE ANO IN (2021,2022) AND MES IN (1,2,3,4,5,6,7,8,9,10,11,12) AND FLAG_BASELINE = 1 AND TA.UF <> '-'
    GROUP BY DAY(DATA_ENCERRAMENTO), TA.UF, ANO, MES,SIT.SITE,SIT.UF
)A ORDER BY A.UF, MES, DIA