SELECT
    COUNT(*),
    TB_FECHADOS.TIPO_TA 
FROM
    [INDICADORES_CORAN].[dbo].[TBL_EVENTOS_FECHADOS] AS TB_FECHADOS WITH(NOLOCK)
    LEFT JOIN [GENESIS].[dbo].[WFM_TBF_OS_PAGAMENTO] AS TB_PG WITH(NOLOCK) ON TB_FECHADOS.EVENTO = TB_PG.EVENTO
    LEFT JOIN GENESIS..WFM_TBA_OS_TIPO_PAGAMENTO TIPO_PGT WITH(NOLOCK) ON TB_PG.ID_OS_TIPO_PAGAMENTO = TIPO_PGT.ID_OS_TIPO_PAGAMENTO
    LEFT JOIN GENESIS..WFM_TBF_OS_SITE SITE WITH(NOLOCK) ON TB_PG.ID_OS_SITE = SITE.ID_OS_SITE
 
  WHERE ANO = 2024
        AND MES in (1,2)
        -- AND FLAG_BASELINE = 1
        -- AND PRE_BAIXA = 1 -- SIM
        AND TB_PG.ID_OS_TIPO_PAGAMENTO = 1 -- SOB DEMANDA
        -- AND NIVEL_ATENDIMENTO IN (1)  -- SEM ATUACAO
        AND EVENTO_RAIZ IS NULL
  GROUP BY TB_FECHADOS.TIPO_TA

--   64959
-- ==============================================================================================================================
SELECT
    TB_PG.EMPRESA,
    SITE.REGIONAL,
    SITE.MUNICIPIO,
    TB_PG.EVENTO,
    OS.DATA_CRIACAO,
    TB_PG.DATA_ENCERRAMENTO,
    TB_PG.NIVEL_ATENDIMENTO,
    TB_PG.ACEITE,
    TB_PG.ACEITE_NOME,
    TB_PG.TECNICO_NO_SITE,
    TB_PG.TECNICO_NO_SITE_NOME,
    TB_PG.ENCAMINHADO_TECNICO_NOME,
    TB_PG.PRE_BAIXA,
    TB_PG.PRE_BAIXA_NOME,
    SCIENCE.MUNICIPIO
FROM
    GENESIS..WFM_TBF_OS_PAGAMENTO AS TB_PG WITH(NOLOCK)
    LEFT JOIN GENESIS..WFM_TBF_OS OS ON TB_PG.NUM_OS = OS.NUM_OS
    -- INNER JOIN INDICADORES_CORAN..TBL_EVENTOS_FECHADOS AS TB_FECHADOS WITH(NOLOCK) ON TB_PG.EVENTO = TB_FECHADOS.EVENTO
    -- INNER JOIN AVALIACAO_CAMPO..TAS_FORA AS TAS_FORA WITH(NOLOCK) ON TAS_FORA.EVENTO = TB_PG.EVENTO
    -- LEFT JOIN GENESIS..WFM_TBA_OS_TIPO_PAGAMENTO TIPO_PGT WITH(NOLOCK) ON TB_PG.ID_OS_TIPO_PAGAMENTO = TIPO_PGT.ID_OS_TIPO_PAGAMENTO
    LEFT JOIN GENESIS..WFM_TBS_IMPORT_SCIENCE SCIENCE ON TB_PG.UF_EVENTO = SCIENCE.UF AND TB_PG.SITE_EVENTO = SCIENCE.SITE
    LEFT JOIN GENESIS..WFM_TBF_OS_SITE SITE WITH(NOLOCK) ON TB_PG.ID_OS_SITE = SITE.ID_OS_SITE
WHERE YEAR(TB_PG.PERIODO) = 2024
      AND MONTH(TB_PG.PERIODO) IN (1,2)
      -- AND PRE_BAIXA = 1 -- SIM
      AND TB_PG.ID_OS_TIPO_PAGAMENTO = 1 -- SOB DEMANDA
      AND NIVEL_ATENDIMENTO IN (1,2,3)  -- SEM ATUACAO
      AND TB_PG.EVENTO = 311696570
        -- -- AND EVENTO_RAIZ IS NULL
-- GROUP BY SITE.REGIONAL
-- ==================================================================================================================================        

-- SELECT TOP 10 * FROM GENESIS..WFM_TBF_OS_PAGAMENTO
-- SELECT TOP 10 * FROM INDICADORES_CORAN..TBL_EVENTOS_FECHADOS
-- SELECT TOP 10 * FROM GENESIS..WFM_TBA_OS_TIPO_PAGAMENTO
-- SELECT TOP 10 * FROM GENESIS..WFM_TBF_OS_SITE SITE WITH(NOLOCK)
-- SELECT TOP 10 * FROM GENESIS..WFM_TBF_OS

--   CASE WHEN PGT.NIVEL_ATENDIMENTO = 1 THEN 'Sem Atuação'
--     -- WHEN PGT.NIVEL_ATENDIMENTO = 2 THEN 'Com Atuação'
--     -- WHEN PGT.NIVEL_ATENDIMENTO = 3 THEN 'Energia Alternativa'

-- ======================================================================================================================================

-- 64.959 ---CAPITAIS---> 19.666 ---> 12.354

WITH EVENTOS AS (
SELECT
    TB_PG.EMPRESA,
    SITE.REGIONAL,
    SITE.UF,
    SITE.MUNICIPIO,
    TB_PG.SITE_EVENTO AS SITE,
    TB_PG.EVENTO,
    OS.DATA_CRIACAO,
    TB_PG.DATA_ENCERRAMENTO,
    TB_PG.NIVEL_ATENDIMENTO
FROM
    GENESIS..WFM_TBF_OS_PAGAMENTO AS TB_PG WITH(NOLOCK)
    LEFT JOIN GENESIS..WFM_TBF_OS OS WITH(NOLOCK) ON TB_PG.NUM_OS = OS.NUM_OS
    LEFT JOIN GENESIS..WFM_TBF_OS_SITE SITE WITH(NOLOCK) ON TB_PG.ID_OS_SITE = SITE.ID_OS_SITE
WHERE 
    YEAR(TB_PG.PERIODO) = 2024
    AND MONTH(TB_PG.PERIODO) IN (1,2)
    AND TB_PG.ID_OS_TIPO_PAGAMENTO = 1 -- SOB DEMANDA
    AND NIVEL_ATENDIMENTO IN (1,2,3)  -- SEM ATUACAO
    AND SITE.UF+'_'+SITE.MUNICIPIO IN ('AC_RIO BRANCO','AL_MACEIÓ','AP_MACAPÁ','AM_MANAUS','BA_SALVADOR','CE_FORTALEZA','DF_BRASÍLIA',
    'ES_VITÓRIA','GO_GOIÂNIA','MA_SÃO LUÍS','MT_CUIABÁ','MS_CAMPO GRANDE','MG_BELO HORIZONTE','PA_BELÉM','PB_JOÃO PESSOA','PR_CURITIBA',
    'PE_RECIFE','PI_TERESINA','RJ_RIO DE JANEIRO','RN_NATAL','RS_PORTO ALEGRE','RO_PORTO VELHO','RR_BOA VISTA','SC_FLORIANÓPOLIS',
    'SP_SÃO PAULO','SE_ARACAJU','TO_PALMAS'
    )
),
DISP_DIARIO_MUN AS (
SELECT
*
FROM 
    INDICADORES_CORAN..TBF_CELLDOWNTIME_DIARIO_MUNICIPIO CDT_DIARIO_MUN WITH(NOLOCK)
WHERE 
     UF+'_'+MUNICIPIO IN ('AC_RIO BRANCO','AL_MACEIÓ','AP_MACAPÁ','AM_MANAUS','BA_SALVADOR','CE_FORTALEZA','DF_BRASÍLIA',
    'ES_VITÓRIA','GO_GOIÂNIA','MA_SÃO LUÍS','MT_CUIABÁ','MS_CAMPO GRANDE','MG_BELO HORIZONTE','PA_BELÉM','PB_JOÃO PESSOA',
    'PR_CURITIBA','PE_RECIFE','PI_TERESINA','RJ_RIO DE JANEIRO','RN_NATAL','RS_PORTO ALEGRE','RO_PORTO VELHO','RR_BOA VISTA',
    'SC_FLORIANÓPOLIS','SP_SÃO PAULO','SE_ARACAJU','TO_PALMAS'
    )
),
DISP_DIARIO_SITE AS (
SELECT
*
FROM 
    INDICADORES_CORAN..TBF_CELLDOWNTIME_DIARIO_SITE DISP_DIARIO_SITE WITH(NOLOCK)
WHERE 
     UF+'_'+MUNICIPIO IN ('AC_RIO BRANCO','AL_MACEIÓ','AP_MACAPÁ','AM_MANAUS','BA_SALVADOR','CE_FORTALEZA','DF_BRASÍLIA',
    'ES_VITÓRIA','GO_GOIÂNIA','MA_SÃO LUÍS','MT_CUIABÁ','MS_CAMPO GRANDE','MG_BELO HORIZONTE','PA_BELÉM','PB_JOÃO PESSOA',
    'PR_CURITIBA','PE_RECIFE','PI_TERESINA','RJ_RIO DE JANEIRO','RN_NATAL','RS_PORTO ALEGRE','RO_PORTO VELHO','RR_BOA VISTA',
    'SC_FLORIANÓPOLIS','SP_SÃO PAULO','SE_ARACAJU','TO_PALMAS'
    )
    
)

SELECT
    EVENTOS.*,
    DISP_DIARIO_MUN.ANO,
    DISP_DIARIO_MUN.MES,
    DISP_DIARIO_MUN.DIA,
    DISP_DIARIO_MUN.DISPONIBILIDADE_GERAL AS DISP_DIARIA_MUN,
    DISP_DIARIO_SITE.DISPONIBILIDADE_GERAL AS DISP_DIARIA_SITE,
    DATEPART(DAY,DATA_CRIACAO) AS DIA,
    CASE WHEN DATEPART(HOUR, DATA_CRIACAO) IN (6,7,8,9) THEN '6-9'
         WHEN DATEPART(HOUR, DATA_CRIACAO) IN (10,12,13) THEN '10-13'
         WHEN DATEPART(HOUR, DATA_CRIACAO) IN (14,15,16,17,18) THEN '14-18'
        ELSE 'OUTRO'
    END HORA
FROM 
    EVENTOS WITH(NOLOCK)
    LEFT JOIN DISP_DIARIO_MUN WITH(NOLOCK) ON EVENTOS.UF = DISP_DIARIO_MUN.UF AND EVENTOS.MUNICIPIO = DISP_DIARIO_MUN.MUNICIPIO
    LEFT JOIN DISP_DIARIO_SITE WITH(NOLOCK) ON EVENTOS.UF = DISP_DIARIO_SITE.UF AND EVENTOS.SITE = DISP_DIARIO_SITE.SITE
WHERE 
    DISP_DIARIO_SITE.ANO = 2024 
    AND DISP_DIARIO_SITE.MES =  DATEPART(MONTH,DATA_CRIACAO) 
    AND DISP_DIARIO_SITE.DIA = DATEPART(DAY,DATA_CRIACAO)



-- ========================================
-- EVOLUÇÃO DA PLANTA DE ERBS DAS CAPITAIS
-- ========================================
SELECT
2023 AS ANO,
DATEPART(MONTH, DATA_REFERENCIA) AS MES,
UF,
MUNICIPIO,
COUNT(DISTINCT ERB) AS QTDE_ERBS
FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES_HIST_2023 WITH(NOLOCK)
WHERE UF + '_' + MUNICIPIO IN ('RJ_RIO DE JANEIRO')
    -- ('AC_RIO BRANCO','AL_MACEIÓ','AP_MACAPÁ','AM_MANAUS','BA_SALVADOR','CE_FORTALEZA','DF_BRASÍLIA',
    -- 'ES_VITÓRIA','GO_GOIÂNIA','MA_SÃO LUÍS','MT_CUIABÁ','MS_CAMPO GRANDE','MG_BELO HORIZONTE','PA_BELÉM','PB_JOÃO PESSOA',
    -- 'PR_CURITIBA','PE_RECIFE','PI_TERESINA','RJ_RIO DE JANEIRO','RN_NATAL','RS_PORTO ALEGRE','RO_PORTO VELHO','RR_BOA VISTA',
    -- 'SC_FLORIANÓPOLIS','SP_SÃO PAULO','SE_ARACAJU','TO_PALMAS')
    AND DATEPART(YEAR,DATA_REFERENCIA) = 2023 --AND DATEPART(MONTH,DATA_REFERENCIA) = 5 AND DATEPART(DAY, DATA_REFERENCIA) = 31
    AND TECNOLOGIA <> 'GSM'
GROUP BY UF, MUNICIPIO, DATEPART(MONTH, DATA_REFERENCIA)
UNION ALL
SELECT
2024 AS ANO,
DATEPART(MONTH, DATA_REFERENCIA) AS MES,
UF,
MUNICIPIO,
COUNT(DISTINCT ERB) AS QTDE_ERBS
FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES_HIST_2023 WITH(NOLOCK)
WHERE UF + '_' + MUNICIPIO IN ('RJ_RIO DE JANEIRO')
    -- ('AC_RIO BRANCO','AL_MACEIÓ','AP_MACAPÁ','AM_MANAUS','BA_SALVADOR','CE_FORTALEZA','DF_BRASÍLIA',
    -- 'ES_VITÓRIA','GO_GOIÂNIA','MA_SÃO LUÍS','MT_CUIABÁ','MS_CAMPO GRANDE','MG_BELO HORIZONTE','PA_BELÉM','PB_JOÃO PESSOA',
    -- 'PR_CURITIBA','PE_RECIFE','PI_TERESINA','RJ_RIO DE JANEIRO','RN_NATAL','RS_PORTO ALEGRE','RO_PORTO VELHO','RR_BOA VISTA',
    -- 'SC_FLORIANÓPOLIS','SP_SÃO PAULO','SE_ARACAJU','TO_PALMAS')
    AND DATEPART(YEAR,DATA_REFERENCIA) = 2024 AND DATEPART(MONTH,DATA_REFERENCIA) IN (1,2) --AND DATEPART(DAY, DATA_REFERENCIA) = 31
    AND TECNOLOGIA <> 'GSM'
GROUP BY UF, MUNICIPIO, DATEPART(MONTH, DATA_REFERENCIA)
UNION ALL
SELECT
2024 AS ANO,
DATEPART(MONTH, DATA_REFERENCIA) AS MES,
UF,
MUNICIPIO,
COUNT(DISTINCT ERB) AS QTDE_ERBS
FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES WITH(NOLOCK)
WHERE UF + '_' + MUNICIPIO IN ('RJ_RIO DE JANEIRO')
    -- ('AC_RIO BRANCO','AL_MACEIÓ','AP_MACAPÁ','AM_MANAUS','BA_SALVADOR','CE_FORTALEZA','DF_BRASÍLIA',
    -- 'ES_VITÓRIA','GO_GOIÂNIA','MA_SÃO LUÍS','MT_CUIABÁ','MS_CAMPO GRANDE','MG_BELO HORIZONTE','PA_BELÉM','PB_JOÃO PESSOA',
    -- 'PR_CURITIBA','PE_RECIFE','PI_TERESINA','RJ_RIO DE JANEIRO','RN_NATAL','RS_PORTO ALEGRE','RO_PORTO VELHO','RR_BOA VISTA',
    -- 'SC_FLORIANÓPOLIS','SP_SÃO PAULO','SE_ARACAJU','TO_PALMAS')
    AND DATEPART(YEAR,DATA_REFERENCIA) = 2024 AND DATEPART(MONTH,DATA_REFERENCIA) IN (4,5,6) --AND DATEPART(DAY, DATA_REFERENCIA) = 31
    AND TECNOLOGIA <> 'GSM'
GROUP BY UF, MUNICIPIO, DATEPART(MONTH, DATA_REFERENCIA)
ORDER BY MUNICIPIO, ANO, MES


-- =======================
-- MARÇO 2024
-- ======================
SELECT
    2024 AS ANO,
    DATEPART(MONTH, DATA_REFERENCIA) AS MES,
    UF,
    MUNICIPIO,
    COUNT(DISTINCT ERB) AS QTDE_ERBS
FROM 
    (SELECT * FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES_HIST_2023 WITH(NOLOCK)
        UNION ALL
        SELECT * FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES WITH(NOLOCK)
        WHERE DATEPART(YEAR,DATA_REFERENCIA) = 2024 AND DATEPART(MONTH,DATA_REFERENCIA) = 3) A
WHERE UF + '_' + MUNICIPIO IN ('AC_RIO BRANCO','AL_MACEIÓ','AP_MACAPÁ','AM_MANAUS','BA_SALVADOR','CE_FORTALEZA','DF_BRASÍLIA',
    'ES_VITÓRIA','GO_GOIÂNIA','MA_SÃO LUÍS','MT_CUIABÁ','MS_CAMPO GRANDE','MG_BELO HORIZONTE','PA_BELÉM','PB_JOÃO PESSOA',
    'PR_CURITIBA','PE_RECIFE','PI_TERESINA','RJ_RIO DE JANEIRO','RN_NATAL','RS_PORTO ALEGRE','RO_PORTO VELHO','RR_BOA VISTA',
    'SC_FLORIANÓPOLIS','SP_SÃO PAULO','SE_ARACAJU','TO_PALMAS')
    AND DATEPART(YEAR,DATA_REFERENCIA) = 2024 AND DATEPART(MONTH,DATA_REFERENCIA) = 3 --AND DATEPART(DAY, DATA_REFERENCIA) = 31
    AND TECNOLOGIA <> 'GSM'
GROUP BY UF, MUNICIPIO, DATEPART(MONTH, DATA_REFERENCIA)
ORDER BY MUNICIPIO, ANO, MES

-- =======================================================================
-- EVOLUÇÃO DA PLANTA DE ERBS DAS CAPITAIS QUE APRESENTARAM CELLDOWNTIME
-- ======================================================================

SELECT
2023 AS ANO,
DATEPART(MONTH, DATA_REFERENCIA) AS MES,
UF,
MUNICIPIO,
COUNT(DISTINCT ERB) AS QTDE_ERBS_CDT
FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES_HIST_2023 WITH(NOLOCK)
WHERE UF + '_' + MUNICIPIO IN ('AC_RIO BRANCO','AL_MACEIÓ','AP_MACAPÁ','AM_MANAUS','BA_SALVADOR','CE_FORTALEZA','DF_BRASÍLIA',
    'ES_VITÓRIA','GO_GOIÂNIA','MA_SÃO LUÍS','MT_CUIABÁ','MS_CAMPO GRANDE','MG_BELO HORIZONTE','PA_BELÉM','PB_JOÃO PESSOA',
    'PR_CURITIBA','PE_RECIFE','PI_TERESINA','RJ_RIO DE JANEIRO','RN_NATAL','RS_PORTO ALEGRE','RO_PORTO VELHO','RR_BOA VISTA',
    'SC_FLORIANÓPOLIS','SP_SÃO PAULO','SE_ARACAJU','TO_PALMAS')
    AND DATEPART(YEAR,DATA_REFERENCIA) = 2023 --AND DATEPART(MONTH,DATA_REFERENCIA) = 5 AND DATEPART(DAY, DATA_REFERENCIA) = 31
    AND TECNOLOGIA <> 'GSM'
    AND TEMPO_CONTADOR_HMM > 0
GROUP BY UF, MUNICIPIO, DATEPART(MONTH, DATA_REFERENCIA)
UNION ALL
SELECT
2024 AS ANO,
DATEPART(MONTH, DATA_REFERENCIA) AS MES,
UF,
MUNICIPIO,
COUNT(DISTINCT ERB) AS QTDE_ERBS_CDT
FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES_HIST_2023 WITH(NOLOCK)
WHERE UF + '_' + MUNICIPIO IN ('AC_RIO BRANCO','AL_MACEIÓ','AP_MACAPÁ','AM_MANAUS','BA_SALVADOR','CE_FORTALEZA','DF_BRASÍLIA',
    'ES_VITÓRIA','GO_GOIÂNIA','MA_SÃO LUÍS','MT_CUIABÁ','MS_CAMPO GRANDE','MG_BELO HORIZONTE','PA_BELÉM','PB_JOÃO PESSOA',
    'PR_CURITIBA','PE_RECIFE','PI_TERESINA','RJ_RIO DE JANEIRO','RN_NATAL','RS_PORTO ALEGRE','RO_PORTO VELHO','RR_BOA VISTA',
    'SC_FLORIANÓPOLIS','SP_SÃO PAULO','SE_ARACAJU','TO_PALMAS')
    AND DATEPART(YEAR,DATA_REFERENCIA) = 2024 AND DATEPART(MONTH,DATA_REFERENCIA) IN (1,2) --AND DATEPART(DAY, DATA_REFERENCIA) = 31
    AND TECNOLOGIA <> 'GSM'
    AND TEMPO_CONTADOR_HMM > 0
GROUP BY UF, MUNICIPIO, DATEPART(MONTH, DATA_REFERENCIA)
UNION ALL
SELECT
2024 AS ANO,
DATEPART(MONTH, DATA_REFERENCIA) AS MES,
UF,
MUNICIPIO,
COUNT(DISTINCT ERB) AS QTDE_ERBS_CDT
FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES WITH(NOLOCK)
WHERE UF + '_' + MUNICIPIO IN ('AC_RIO BRANCO','AL_MACEIÓ','AP_MACAPÁ','AM_MANAUS','BA_SALVADOR','CE_FORTALEZA','DF_BRASÍLIA',
    'ES_VITÓRIA','GO_GOIÂNIA','MA_SÃO LUÍS','MT_CUIABÁ','MS_CAMPO GRANDE','MG_BELO HORIZONTE','PA_BELÉM','PB_JOÃO PESSOA',
    'PR_CURITIBA','PE_RECIFE','PI_TERESINA','RJ_RIO DE JANEIRO','RN_NATAL','RS_PORTO ALEGRE','RO_PORTO VELHO','RR_BOA VISTA',
    'SC_FLORIANÓPOLIS','SP_SÃO PAULO','SE_ARACAJU','TO_PALMAS')
    AND DATEPART(YEAR,DATA_REFERENCIA) = 2024 AND DATEPART(MONTH,DATA_REFERENCIA) IN (4,5,6) --AND DATEPART(DAY, DATA_REFERENCIA) = 31
    AND TECNOLOGIA <> 'GSM'
    AND TEMPO_CONTADOR_HMM > 0
GROUP BY UF, MUNICIPIO, DATEPART(MONTH, DATA_REFERENCIA)
ORDER BY MUNICIPIO, ANO, MES

-- =======================
-- MARÇO 2024 COM CDT
-- ======================
SELECT
    2024 AS ANO,
    DATEPART(MONTH, DATA_REFERENCIA) AS MES,
    UF,
    MUNICIPIO,
    COUNT(DISTINCT ERB) AS QTDE_ERBS_CDT
FROM 
    (SELECT * FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES_HIST_2023 WITH(NOLOCK)
    UNION ALL
    SELECT * FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES WITH(NOLOCK)
        WHERE DATEPART(YEAR,DATA_REFERENCIA) = 2024 AND DATEPART(MONTH,DATA_REFERENCIA) = 3) A
WHERE UF + '_' + MUNICIPIO IN ('AC_RIO BRANCO','AL_MACEIÓ','AP_MACAPÁ','AM_MANAUS','BA_SALVADOR','CE_FORTALEZA','DF_BRASÍLIA',
    'ES_VITÓRIA','GO_GOIÂNIA','MA_SÃO LUÍS','MT_CUIABÁ','MS_CAMPO GRANDE','MG_BELO HORIZONTE','PA_BELÉM','PB_JOÃO PESSOA',
    'PR_CURITIBA','PE_RECIFE','PI_TERESINA','RJ_RIO DE JANEIRO','RN_NATAL','RS_PORTO ALEGRE','RO_PORTO VELHO','RR_BOA VISTA',
    'SC_FLORIANÓPOLIS','SP_SÃO PAULO','SE_ARACAJU','TO_PALMAS')
    AND DATEPART(YEAR,DATA_REFERENCIA) = 2024 AND DATEPART(MONTH,DATA_REFERENCIA) = 3 --AND DATEPART(DAY, DATA_REFERENCIA) = 31
    AND TECNOLOGIA <> 'GSM'
    AND TEMPO_CONTADOR_HMM > 0
GROUP BY UF, MUNICIPIO, DATEPART(MONTH, DATA_REFERENCIA)
ORDER BY MUNICIPIO, ANO, MES


-- =================================
-- DISP MENSAL
-- =================================
SELECT
A.ANO,
A.MES,
A.MUNICIPIO,
A.DISPONIBILIDADE_GERAL AS DIP_GERAL,
DISPONIBILIDADE_3G AS DISP_3G,
DISPONIBILIDADE_4G AS DISP_4G,
DISPONIBILIDADE_5G AS DISP_5G,
DISPONIBILIDADE_4G_5G AS DISP_4G_5G
FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_MENSAL_MUNICIPIO_HMM A WITH(NOLOCK)
WHERE A.UF + '_' + A.MUNICIPIO IN ('AC_RIO BRANCO','AL_MACEIÓ','AP_MACAPÁ','AM_MANAUS','BA_SALVADOR','CE_FORTALEZA','DF_BRASÍLIA',
    'ES_VITÓRIA','GO_GOIÂNIA','MA_SÃO LUÍS','MT_CUIABÁ','MS_CAMPO GRANDE','MG_BELO HORIZONTE','PA_BELÉM','PB_JOÃO PESSOA',
    'PR_CURITIBA','PE_RECIFE','PI_TERESINA','RJ_RIO DE JANEIRO','RN_NATAL','RS_PORTO ALEGRE','RO_PORTO VELHO','RR_BOA VISTA',
    'SC_FLORIANÓPOLIS','SP_SÃO PAULO','SE_ARACAJU','TO_PALMAS')
    AND A.ANO IN (2023,2024) --AND A.MES IN (1,2,3,4,5)
ORDER BY MUNICIPIO, ANO, MES




-- SELECT SUM(PLANTA_3G)  PLANTA_4G) FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_MENSAL_MUNICIPIO_20230323
-- WHERE UF + '_' + MUNICIPIO IN ('AC_RIO BRANCO') AND ANO = 2023 AND MES = 1


SELECT * FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_MENSAL_SITE_HMM


-- ======================
-- SETORES
-- ======================
SELECT
ANO, MES, UF, MUNICIPIO, COUNT(*) AS QTDE_SETORES,
SUM(TEMPO_CDT) AS TEMPO
FROM (
    SELECT 
        DATEPART(YEAR,DATA_REFERENCIA) AS ANO,
        DATEPART(MONTH,DATA_REFERENCIA) AS MES,
        UF,
        MUNICIPIO,
        TEMPO_CONTADOR_HMM AS TEMPO_CDT  
    FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES_HIST_2023 WITH(NOLOCK)
    WHERE DATEPART(YEAR,DATA_REFERENCIA) = 2023 AND TECNOLOGIA <> 'GSM' AND TEMPO_CONTADOR_HMM > 0
    -- AND UF + '_' + MUNICIPIO IN ('AC_RIO BRANCO')
    AND UF + '_' + MUNICIPIO IN ('AC_RIO BRANCO','AL_MACEIÓ','AP_MACAPÁ','AM_MANAUS','BA_SALVADOR','CE_FORTALEZA','DF_BRASÍLIA',
    'ES_VITÓRIA','GO_GOIÂNIA','MA_SÃO LUÍS','MT_CUIABÁ','MS_CAMPO GRANDE','MG_BELO HORIZONTE','PA_BELÉM','PB_JOÃO PESSOA',
    'PR_CURITIBA','PE_RECIFE','PI_TERESINA','RJ_RIO DE JANEIRO','RN_NATAL','RS_PORTO ALEGRE','RO_PORTO VELHO','RR_BOA VISTA',
    'SC_FLORIANÓPOLIS','SP_SÃO PAULO','SE_ARACAJU','TO_PALMAS')
) A
GROUP BY ANO, MES, UF, MUNICIPIO
UNION ALL
SELECT
ANO, MES, UF, MUNICIPIO, COUNT(*) AS QTDE_SETORES,
SUM(TEMPO_CDT) AS TEMPO
FROM (
    SELECT 
        DATEPART(YEAR,DATA_REFERENCIA) AS ANO,
        DATEPART(MONTH,DATA_REFERENCIA) AS MES,
        UF,
        MUNICIPIO,
        TEMPO_CONTADOR_HMM AS TEMPO_CDT
    FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES_HIST_2023 WITH(NOLOCK)
    WHERE DATEPART(YEAR,DATA_REFERENCIA) = 2024 AND DATEPART(MONTH,DATA_REFERENCIA) IN (1,2,3) AND TECNOLOGIA <> 'GSM' AND TEMPO_CONTADOR_HMM > 0
    -- AND UF + '_' + MUNICIPIO IN ('AC_RIO BRANCO')
    AND UF + '_' + MUNICIPIO IN ('AC_RIO BRANCO','AL_MACEIÓ','AP_MACAPÁ','AM_MANAUS','BA_SALVADOR','CE_FORTALEZA','DF_BRASÍLIA',
    'ES_VITÓRIA','GO_GOIÂNIA','MA_SÃO LUÍS','MT_CUIABÁ','MS_CAMPO GRANDE','MG_BELO HORIZONTE','PA_BELÉM','PB_JOÃO PESSOA',
    'PR_CURITIBA','PE_RECIFE','PI_TERESINA','RJ_RIO DE JANEIRO','RN_NATAL','RS_PORTO ALEGRE','RO_PORTO VELHO','RR_BOA VISTA',
    'SC_FLORIANÓPOLIS','SP_SÃO PAULO','SE_ARACAJU','TO_PALMAS')
) A
GROUP BY ANO, MES, UF, MUNICIPIO
UNION ALL
SELECT
ANO, MES, UF, MUNICIPIO, COUNT(*) AS QTDE_SETORES,
SUM(TEMPO_CDT) AS TEMPO
FROM (
    SELECT 
        DATEPART(YEAR,DATA_REFERENCIA) AS ANO,
        DATEPART(MONTH,DATA_REFERENCIA) AS MES,
        UF,
        MUNICIPIO,
        TEMPO_CONTADOR_HMM AS TEMPO_CDT
    FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES WITH(NOLOCK)
    WHERE DATEPART(YEAR,DATA_REFERENCIA) = 2024 AND DATEPART(MONTH,DATA_REFERENCIA) IN (5,6) AND TECNOLOGIA <> 'GSM' AND TEMPO_CONTADOR_HMM > 0
    -- AND UF + '_' + MUNICIPIO IN ('AC_RIO BRANCO')
    AND UF + '_' + MUNICIPIO IN ('AC_RIO BRANCO','AL_MACEIÓ','AP_MACAPÁ','AM_MANAUS','BA_SALVADOR','CE_FORTALEZA','DF_BRASÍLIA',
    'ES_VITÓRIA','GO_GOIÂNIA','MA_SÃO LUÍS','MT_CUIABÁ','MS_CAMPO GRANDE','MG_BELO HORIZONTE','PA_BELÉM','PB_JOÃO PESSOA',
    'PR_CURITIBA','PE_RECIFE','PI_TERESINA','RJ_RIO DE JANEIRO','RN_NATAL','RS_PORTO ALEGRE','RO_PORTO VELHO','RR_BOA VISTA',
    'SC_FLORIANÓPOLIS','SP_SÃO PAULO','SE_ARACAJU','TO_PALMAS')
) A
GROUP BY ANO, MES, UF, MUNICIPIO
UNION ALL
SELECT
ANO, MES, UF, MUNICIPIO, COUNT(*) AS QTDE_SETORES,
SUM(TEMPO_CDT) AS TEMPO
FROM (
SELECT 
        DATEPART(YEAR,DATA_REFERENCIA) AS ANO,
        DATEPART(MONTH,DATA_REFERENCIA) AS MES,
        UF,
        MUNICIPIO,
        TEMPO_CONTADOR_HMM AS TEMPO_CDT
    FROM (
            SELECT * FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES_HIST_2023 WITH(NOLOCK)
            WHERE DATEPART(YEAR,DATA_REFERENCIA) = 2024 AND DATEPART(MONTH,DATA_REFERENCIA) = 4
            UNION ALL
            SELECT * FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES WITH(NOLOCK)
            WHERE DATEPART(YEAR,DATA_REFERENCIA) = 2024 AND DATEPART(MONTH,DATA_REFERENCIA) = 4
    ) A
WHERE TECNOLOGIA <> 'GSM' AND TEMPO_CONTADOR_HMM > 0
-- AND UF + '_' + MUNICIPIO IN ('AC_RIO BRANCO')
AND UF + '_' + MUNICIPIO IN ('AC_RIO BRANCO','AL_MACEIÓ','AP_MACAPÁ','AM_MANAUS','BA_SALVADOR','CE_FORTALEZA','DF_BRASÍLIA',
'ES_VITÓRIA','GO_GOIÂNIA','MA_SÃO LUÍS','MT_CUIABÁ','MS_CAMPO GRANDE','MG_BELO HORIZONTE','PA_BELÉM','PB_JOÃO PESSOA',
'PR_CURITIBA','PE_RECIFE','PI_TERESINA','RJ_RIO DE JANEIRO','RN_NATAL','RS_PORTO ALEGRE','RO_PORTO VELHO','RR_BOA VISTA',
'SC_FLORIANÓPOLIS','SP_SÃO PAULO','SE_ARACAJU','TO_PALMAS')
) B
GROUP BY ANO, MES, UF, MUNICIPIO
ORDER BY ANO, MES, UF, MUNICIPIO






SELECT MIN(DATA_REFERENCIA), MAX(DATA_REFERENCIA) FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES_HIST_2023
SELECT MIN(DATA_REFERENCIA), MAX(DATA_REFERENCIA) FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES


-- ===========================================
-- EVOLUÇÃO DA PLANTA DE SITES DAS CAPITAIS
-- ===========================================
SELECT
2023 AS ANO,
DATEPART(MONTH, DATA_REFERENCIA) AS MES,
UF,
MUNICIPIO,
COUNT(DISTINCT SITE) AS QTDE_SITES
FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES_HIST_2023 WITH(NOLOCK)
WHERE UF + '_' + MUNICIPIO IN ('AC_RIO BRANCO','AL_MACEIÓ','AP_MACAPÁ','AM_MANAUS','BA_SALVADOR','CE_FORTALEZA','DF_BRASÍLIA',
    'ES_VITÓRIA','GO_GOIÂNIA','MA_SÃO LUÍS','MT_CUIABÁ','MS_CAMPO GRANDE','MG_BELO HORIZONTE','PA_BELÉM','PB_JOÃO PESSOA',
    'PR_CURITIBA','PE_RECIFE','PI_TERESINA','RJ_RIO DE JANEIRO','RN_NATAL','RS_PORTO ALEGRE','RO_PORTO VELHO','RR_BOA VISTA',
    'SC_FLORIANÓPOLIS','SP_SÃO PAULO','SE_ARACAJU','TO_PALMAS')
    AND DATEPART(YEAR,DATA_REFERENCIA) = 2023 AND DATEPART(MONTH,DATA_REFERENCIA) = 6
    AND TECNOLOGIA <> 'GSM'
GROUP BY UF, MUNICIPIO, DATEPART(MONTH, DATA_REFERENCIA)
UNION ALL
SELECT
2024 AS ANO,
DATEPART(MONTH, DATA_REFERENCIA) AS MES,
UF,
MUNICIPIO,
COUNT(DISTINCT SITE) AS QTDE_SITES
FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES WITH(NOLOCK)
WHERE UF + '_' + MUNICIPIO IN ('AC_RIO BRANCO','AL_MACEIÓ','AP_MACAPÁ','AM_MANAUS','BA_SALVADOR','CE_FORTALEZA','DF_BRASÍLIA',
    'ES_VITÓRIA','GO_GOIÂNIA','MA_SÃO LUÍS','MT_CUIABÁ','MS_CAMPO GRANDE','MG_BELO HORIZONTE','PA_BELÉM','PB_JOÃO PESSOA',
    'PR_CURITIBA','PE_RECIFE','PI_TERESINA','RJ_RIO DE JANEIRO','RN_NATAL','RS_PORTO ALEGRE','RO_PORTO VELHO','RR_BOA VISTA',
    'SC_FLORIANÓPOLIS','SP_SÃO PAULO','SE_ARACAJU','TO_PALMAS')
    AND DATEPART(YEAR,DATA_REFERENCIA) = 2024 AND DATEPART(MONTH,DATA_REFERENCIA) = 6
    AND TECNOLOGIA <> 'GSM'
GROUP BY UF, MUNICIPIO, DATEPART(MONTH, DATA_REFERENCIA)

-- ==========================================
-- SITES E CDT
-- ==========================================
SELECT
ANO, MES, UF, MUNICIPIO, COUNT(DISTINCT SITE) AS QTDE_SITES_CDT,
SUM(TEMPO_CDT) AS TEMPO
FROM (
    SELECT 
        DATEPART(YEAR,DATA_REFERENCIA) AS ANO,
        DATEPART(MONTH,DATA_REFERENCIA) AS MES,
        UF,
        MUNICIPIO,
        SITE,
        TEMPO_CONTADOR_HMM AS TEMPO_CDT  
    FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES_HIST_2023 WITH(NOLOCK)
    WHERE DATEPART(YEAR,DATA_REFERENCIA) = 2023 AND DATEPART(MONTH,DATA_REFERENCIA) = 6 AND TECNOLOGIA <> 'GSM' AND TEMPO_CONTADOR_HMM > 0
    -- AND UF + '_' + MUNICIPIO IN ('AC_RIO BRANCO')
    AND UF + '_' + MUNICIPIO IN ('AC_RIO BRANCO','AL_MACEIÓ','AP_MACAPÁ','AM_MANAUS','BA_SALVADOR','CE_FORTALEZA','DF_BRASÍLIA',
    'ES_VITÓRIA','GO_GOIÂNIA','MA_SÃO LUÍS','MT_CUIABÁ','MS_CAMPO GRANDE','MG_BELO HORIZONTE','PA_BELÉM','PB_JOÃO PESSOA',
    'PR_CURITIBA','PE_RECIFE','PI_TERESINA','RJ_RIO DE JANEIRO','RN_NATAL','RS_PORTO ALEGRE','RO_PORTO VELHO','RR_BOA VISTA',
    'SC_FLORIANÓPOLIS','SP_SÃO PAULO','SE_ARACAJU','TO_PALMAS')
) A
GROUP BY ANO, MES, UF, MUNICIPIO
UNION ALL
SELECT
ANO, MES, UF, MUNICIPIO, COUNT(DISTINCT SITE) AS QTDE_SITES_CDT,
SUM(TEMPO_CDT) AS TEMPO
FROM (
    SELECT 
        DATEPART(YEAR,DATA_REFERENCIA) AS ANO,
        DATEPART(MONTH,DATA_REFERENCIA) AS MES,
        UF,
        MUNICIPIO,
        SITE,
        TEMPO_CONTADOR_HMM AS TEMPO_CDT
    FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES WITH(NOLOCK)
    WHERE DATEPART(YEAR,DATA_REFERENCIA) = 2024 AND DATEPART(MONTH,DATA_REFERENCIA) = 6 AND TECNOLOGIA <> 'GSM' AND TEMPO_CONTADOR_HMM > 0
    -- AND UF + '_' + MUNICIPIO IN ('AC_RIO BRANCO')
    AND UF + '_' + MUNICIPIO IN ('AC_RIO BRANCO','AL_MACEIÓ','AP_MACAPÁ','AM_MANAUS','BA_SALVADOR','CE_FORTALEZA','DF_BRASÍLIA',
    'ES_VITÓRIA','GO_GOIÂNIA','MA_SÃO LUÍS','MT_CUIABÁ','MS_CAMPO GRANDE','MG_BELO HORIZONTE','PA_BELÉM','PB_JOÃO PESSOA',
    'PR_CURITIBA','PE_RECIFE','PI_TERESINA','RJ_RIO DE JANEIRO','RN_NATAL','RS_PORTO ALEGRE','RO_PORTO VELHO','RR_BOA VISTA',
    'SC_FLORIANÓPOLIS','SP_SÃO PAULO','SE_ARACAJU','TO_PALMAS')
) A
GROUP BY ANO, MES, UF, MUNICIPIO





-- ================================================================================================================================
-- CALCULO DA DISPONIBILIDADE 4G_5G PARA 2023
-- ================================================================================================================================

/* MUNICIPIO */


DROP TABLE #TEMP_RESULTADOS 
SELECT
        DISP.DATA_REFERENCIA,
        YEAR(DISP.DATA_REFERENCIA) AS ANO,
        MONTH(DISP.DATA_REFERENCIA) AS MES,
        CASE WHEN REGIONAL = 'BA/SE/NE' THEN 'NE' WHEN REGIONAL = 'MG/RJ/ES' THEN 'SUD' ELSE REGIONAL END REGIONAL,
        UF,
        CN,
        MUNICIPIO,
        SITE,
        ERB,
        SETOR,
        TECNOLOGIA,
        MAX(TEMPO_CONTADOR_HMM) AS TEMPO_CONTADOR,
        MAX(COLETAS_HMM) AS COLETAS
	INTO #TEMP_RESULTADOS
	FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES DISP WITH(NOLOCK)
	LEFT JOIN (SELECT DISTINCT UF AS UF_B, SIGLA_SITE AS SITE_B FROM SISTEMA_MAESTRO..TBA_PLANTA_MOVEL WITH(NOLOCK)) B ON DISP.UF = B.UF_B AND DISP.SITE = B.SITE_B
	WHERE YEAR(DISP.DATA_REFERENCIA) = 2023 AND MONTH(DISP.DATA_REFERENCIA) = 1
    AND UF + '_' + MUNICIPIO IN ('AC_RIO BRANCO')
    -- AND UF + '_' + MUNICIPIO IN ('AC_RIO BRANCO','AL_MACEIÓ','AP_MACAPÁ','AM_MANAUS','BA_SALVADOR','CE_FORTALEZA','DF_BRASÍLIA',
    -- 'ES_VITÓRIA','GO_GOIÂNIA','MA_SÃO LUÍS','MT_CUIABÁ','MS_CAMPO GRANDE','MG_BELO HORIZONTE','PA_BELÉM','PB_JOÃO PESSOA',
    -- 'PR_CURITIBA','PE_RECIFE','PI_TERESINA','RJ_RIO DE JANEIRO','RN_NATAL','RS_PORTO ALEGRE','RO_PORTO VELHO','RR_BOA VISTA',
    -- 'SC_FLORIANÓPOLIS','SP_SÃO PAULO','SE_ARACAJU','TO_PALMAS')
	GROUP BY DISP.DATA_REFERENCIA, REGIONAL, UF, CN, MUNICIPIO, SITE, ERB, SETOR, TECNOLOGIA

	SELECT
	ANO,
	MES,
	CASE WHEN REGIONAL = 'BA/SE/NE' THEN 'NE' WHEN REGIONAL = 'MG/RJ/ES' THEN 'SUD' ELSE REGIONAL END REGIONAL,
	UF,
	MUNICIPIO,
	PLANTA_GERAL,
	MINUTOS_GERAL,
	CASE WHEN PLANTA_GERAL = 0 THEN NULL WHEN COLETAS_GERAL = 0 THEN NULL WHEN COLETAS_GERAL > 0 THEN ROUND((1-(MINUTOS_GERAL/(CAST(PLANTA_GERAL AS float)*DENOMINADOR_GERAL)))*100, 2) END DISPONIBILIDADE_GERAL,
	NULL AS NOTA_IND11,
	NULL AS FLG_REINCIDENCIA,
	--DISP_4G_5G
	PLANTA_4G_5G,
	MINUTOS_4G_5G,
	CASE WHEN PLANTA_4G_5G = 0 THEN NULL WHEN COLETAS_4G_5G = 0 THEN NULL WHEN COLETAS_4G_5G > 0 THEN ROUND((1-(MINUTOS_4G_5G/(CAST(PLANTA_4G_5G AS float)*DENOMINADOR_4G_5G)))*100, 2) END DISPONIBILIDADE_4G_5G
	FROM (
		SELECT
		*,
		(CAST(COLETAS_GERAL AS float)/PLANTA_GERAL*60) AS DENOMINADOR_GERAL,
		(CAST(COLETAS_4G_5G AS float)/PLANTA_4G_5G*60) AS DENOMINADOR_4G_5G
		FROM (
			SELECT
			ANO,
			MES,
			REGIONAL,
			UF,
			MUNICIPIO,
			COUNT(DISTINCT CASE WHEN TECNOLOGIA <> 'GSM' THEN CONCAT(DISP.UF, DISP.ERB, DISP.SETOR) END) PLANTA_GERAL,
			SUM(CASE WHEN TEMPO_CONTADOR >= 0 AND TECNOLOGIA <> 'GSM' THEN TEMPO_CONTADOR ELSE 0 END) MINUTOS_GERAL,
			SUM(CASE WHEN TECNOLOGIA <> 'GSM' THEN COLETAS ELSE 0 END) COLETAS_GERAL,
			--4G+5G
			COUNT(DISTINCT CASE WHEN TECNOLOGIA IN ('LTE','5G') THEN CONCAT(DISP.UF, DISP.ERB, DISP.SETOR) END) PLANTA_4G_5G,
			SUM(CASE WHEN TECNOLOGIA IN ('LTE','5G') AND TEMPO_CONTADOR >= 0 THEN TEMPO_CONTADOR ELSE 0 END) MINUTOS_4G_5G,   
			SUM(CASE WHEN TECNOLOGIA IN ('LTE','5G') THEN COLETAS ELSE 0 END) COLETAS_4G_5G
			FROM #TEMP_RESULTADOS DISP
			GROUP BY ANO, MES, REGIONAL, UF, MUNICIPIO
		)GERAL
	)FINAL
