USE SISTEMA_MAESTRO
DECLARE @COLUNAS_DINAMICAS AS NVARCHAR(MAX), @QUERY AS NVARCHAR(MAX)
DECLARE @DATA_INICIAL DATE = GETDATE()-15
DECLARE @DATA_FINAL DATE = GETDATE()-1
SET @COLUNAS_DINAMICAS = 
STUFF((
	SELECT ',' + quotename(DATA) FROM( 	
		select distinct (CONVERT(varchar,DATA_REFERENCIA,103)) AS DATA
        from TBF_DISPONIBILIDADE_SETORES WHERE DATA_REFERENCIA BETWEEN @DATA_INICIAL AND @DATA_FINAL)A ORDER BY CONVERT(DATE,A.DATA) 
	for xml path('')),1,1,'')

print @COLUNAS_DINAMICAS

SET @QUERY = '
SELECT
	 P.UF
	,P.MUNICIPIO
	,P.CN
	,P.SITE
	,P.TECNOLOGIA
	,P.ERB
	,P.SETOR
	,'+CONCAT('[',CONVERT(VARCHAR,GETDATE()-15,103),']')+' AS DIA01
	,'+CONCAT('[',CONVERT(VARCHAR,GETDATE()-14,103),']')+' AS DIA02
	,'+CONCAT('[',CONVERT(VARCHAR,GETDATE()-13,103),']')+' AS DIA03
	,'+CONCAT('[',CONVERT(VARCHAR,GETDATE()-12,103),']')+' AS DIA04
	,'+CONCAT('[',CONVERT(VARCHAR,GETDATE()-11,103),']')+' AS DIA05
	,'+CONCAT('[',CONVERT(VARCHAR,GETDATE()-10,103),']')+' AS DIA06
	,'+CONCAT('[',CONVERT(VARCHAR,GETDATE()-9,103),']')+' AS DIA07
	,'+CONCAT('[',CONVERT(VARCHAR,GETDATE()-8,103),']')+' AS DIA08
	,'+CONCAT('[',CONVERT(VARCHAR,GETDATE()-7,103),']')+' AS DIA09
	,'+CONCAT('[',CONVERT(VARCHAR,GETDATE()-6,103),']')+' AS DIA10
	,'+CONCAT('[',CONVERT(VARCHAR,GETDATE()-5,103),']')+' AS DIA11
	,'+CONCAT('[',CONVERT(VARCHAR,GETDATE()-4,103),']')+' AS DIA12
	,'+CONCAT('[',CONVERT(VARCHAR,GETDATE()-3,103),']')+' AS DIA13
	,'+CONCAT('[',CONVERT(VARCHAR,GETDATE()-2,103),']')+' AS DIA14
	,'+CONCAT('[',CONVERT(VARCHAR,GETDATE()-1,103),']')+' AS DIA15
FROM (
SELECT DISTINCT convert(VARCHAR,DATA_REFERENCIA,103) AS DATA,cell.UF,cell.MUNICIPIO,cell.CN,SITE,cell.TECNOLOGIA,ERB,cell.SETOR,ROUND(TEMPO_CONTADOR,2) as CELL_DOWNTIME
FROM TBF_DISPONIBILIDADE_SETORES cell
INNER JOIN TBA_PLANTA_MOVEL planta ON (cell.ERB = planta.SIGLA_ERB_LOGICA AND cell.SETOR = planta.SETOR_LOGICO AND cell.UF = planta.UF)
WHERE cell.UF = ''SP'' AND (cell.TECNOLOGIA = ''GSM'' OR cell.TECNOLOGIA = ''WCDMA'' OR cell.TECNOLOGIA = ''LTE'') AND 
DATA_REFERENCIA >= ' + CONVERT(VARCHAR,@DATA_INICIAL,103) + ') A
PIVOT (SUM(A.CELL_DOWNTIME) FOR A.DATA IN (' + @COLUNAS_DINAMICAS + ')) P ORDER BY CN,MUNICIPIO,SITE,TECNOLOGIA,ERB,SETOR'

print @QUERY

execute(@QUERY)

