--======================================================================================================
--SETORES COM COLETA INCOMPLETA
--======================================================================================================
--QUALIDADE
SELECT 
 (COUNT(1)/24.0)*100.0 AS QUALIDADE,
  UF,
  SIGLA_ERB,
  SETOR
 FROM SISTEMA_MAESTRO..TBL_COLETA_METRICAS_LTE_BRUTO WITH(NOLOCK)
   GROUP BY UF, SIGLA_ERB, SETOR
   HAVING (COUNT(1)/24.0)*100.0 < 100.0000000
   ORDER BY QUALIDADE

--QUANTIDADE
  SELECT 
  UF,
  SIGLA_ERB,
  SETOR,
  COUNT(1) AS QTDE_COLETAS
  FROM SISTEMA_MAESTRO..TBL_COLETA_METRICAS_LTE_BRUTO WITH(NOLOCK)
  GROUP BY UF, SIGLA_ERB, SETOR
  HAVING COUNT(1) < 24
  ORDER BY QTDE_COLETAS

--=====================================================================================================
--SETORES ATIVOS QUE NÃO CONSTAM NA COLETA ALTAIA
--=====================================================================================================
SELECT 
	P.UF
	,P.SIGLA_ERB_LOGICA
	,P.SETOR_LOGICO
	--,COUNT(M.UF+M.SIGLA_ERB+M.SETOR)
FROM (
	SELECT DISTINCT P.UF,P.SIGLA_ERB_LOGICA,P.SETOR_LOGICO    
	FROM SISTEMA_MAESTRO..TBA_PLANTA_MOVEL P
	WHERE OPERADORA_RANSHARING = 'VIVO' AND TECNOLOGIA = 'LTE' AND SIGLA_ERB_LOGICA NOT LIKE '5%'
	) P
LEFT JOIN SISTEMA_MAESTRO..TBL_COLETA_METRICAS_LTE_BRUTO M ON P.UF = M.UF AND 
P.SIGLA_ERB_LOGICA = M.SIGLA_ERB AND P.SETOR_LOGICO = M.SETOR
GROUP BY P.UF,P.SETOR_LOGICO,P.SIGLA_ERB_LOGICA 
HAVING COUNT(M.UF+M.SIGLA_ERB+M.SETOR) = 0
ORDER BY UF, SIGLA_ERB_LOGICA,SETOR_LOGICO

--===============================================================================
WITH TBL_COLETAS_REALIZADAS_WCDMA AS
   (
   SELECT
	UF,
	COUNT(1) AS COLETAS_REALIZADAS
	FROM SISTEMA_MAESTRO..TBL_COLETA_METRICAS_WCDMA_BRUTO WITH(NOLOCK)
	GROUP BY UF
	),

TBL_COLETAS_ESPERADAS_WCDMA AS 
   (
SELECT 
    UF,
	COUNT(QTDE_COLETAS) * 24 AS COLETAS_ESPERADAS
	FROM (
		SELECT 
		UF, 
		SIGLA_ERB, 
		SETOR, 
		COUNT(1) AS QTDE_COLETAS 
		FROM SISTEMA_MAESTRO..TBL_COLETA_METRICAS_WCDMA_BRUTO WITH(NOLOCK)
	GROUP BY UF, SIGLA_ERB, SETOR) A 
	GROUP BY UF
	),
TBL_COLETAS_REALIZADAS_LTE AS
   (
   SELECT
	UF,
	COUNT(1) AS COLETAS_REALIZADAS
	FROM SISTEMA_MAESTRO..TBL_COLETA_METRICAS_LTE_BRUTO WITH(NOLOCK)
	GROUP BY UF
	),

TBL_COLETAS_ESPERADAS_LTE AS 
   (
SELECT 
    UF,
	COUNT(QTDE_COLETAS) * 24 AS COLETAS_ESPERADAS
	FROM (
		SELECT 
		UF, 
		SIGLA_ERB, 
		SETOR, 
		COUNT(1) AS QTDE_COLETAS 
		FROM SISTEMA_MAESTRO..TBL_COLETA_METRICAS_LTE_BRUTO WITH(NOLOCK)
	GROUP BY UF, SIGLA_ERB, SETOR) A 
	GROUP BY UF
	),
TBL_COLETAS_REALIZADAS_GSM AS
   (
   SELECT
	UF,
	COUNT(1) AS COLETAS_REALIZADAS
	FROM SISTEMA_MAESTRO..TBL_COLETA_METRICAS_GSM_BRUTO WITH(NOLOCK)
	GROUP BY UF
	),

TBL_COLETAS_ESPERADAS_GSM AS 
   (
SELECT 
    UF,
	COUNT(QTDE_COLETAS) * 24 AS COLETAS_ESPERADAS
	FROM (
		SELECT 
		UF, 
		SIGLA_ERB, 
		SETOR, 
		COUNT(1) AS QTDE_COLETAS 
		FROM SISTEMA_MAESTRO..TBL_COLETA_METRICAS_GSM_BRUTO WITH(NOLOCK)
	GROUP BY UF, SIGLA_ERB, SETOR) A 
	GROUP BY UF
	)


SELECT
'WCDMA' AS TECNOLOGIA,
TBL_COLETAS_REALIZADAS_WCDMA.UF,
COLETAS_REALIZADAS,
COLETAS_ESPERADAS,
(CONVERT(FLOAT,COLETAS_REALIZADAS)/CONVERT(FLOAT,COLETAS_ESPERADAS)*100) AS QUALIDADE
FROM TBL_COLETAS_REALIZADAS_WCDMA
LEFT JOIN TBL_COLETAS_ESPERADAS_WCDMA ON TBL_COLETAS_REALIZADAS_WCDMA.UF = TBL_COLETAS_ESPERADAS_WCDMA.UF
--ORDER BY UF

UNION ALL

SELECT
'LTE' AS TECNOLOGIA,
TBL_COLETAS_REALIZADAS_LTE.UF,
COLETAS_REALIZADAS,
COLETAS_ESPERADAS,
(CONVERT(FLOAT,COLETAS_REALIZADAS)/CONVERT(FLOAT,COLETAS_ESPERADAS)*100) AS QUALIDADE
FROM TBL_COLETAS_REALIZADAS_LTE
LEFT JOIN TBL_COLETAS_ESPERADAS_LTE ON TBL_COLETAS_REALIZADAS_LTE.UF = TBL_COLETAS_ESPERADAS_LTE.UF
--ORDER BY UF

UNION ALL

SELECT
'GSM' AS TECNOLOGIA,
TBL_COLETAS_REALIZADAS_GSM.UF,
COLETAS_REALIZADAS,
COLETAS_ESPERADAS,
(CONVERT(FLOAT,COLETAS_REALIZADAS)/CONVERT(FLOAT,COLETAS_ESPERADAS)*100) AS QUALIDADE
FROM TBL_COLETAS_REALIZADAS_GSM
LEFT JOIN TBL_COLETAS_ESPERADAS_GSM ON TBL_COLETAS_REALIZADAS_GSM.UF = TBL_COLETAS_ESPERADAS_GSM.UF
--ORDER BY UF


--M6349761