
/*SELECT
*
FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_MENSAL_SITE
WHERE ((ANO = 2022 AND MES IN (11,12)) OR (ANO = 2023 AND MES IN (1,2,3))) AND UF = 'GO' AND DISPONIBILIDADE_GERAL IS NOT NULL
ORDER BY ANO, MES, SITE */

--========================================================================================================
--SETORES_CELLDOWNTIME
--==============================================================================================================
SELECT
*
FROM (
	SELECT
	DATA_REFERENCIA,
	COUNT(1) AS COLETAS,
	COUNT(CASE WHEN TEMPO_CONTADOR > 0 THEN SITE END) AS SETORES_CELLDOWNTIME
	FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES_BKP_03032023 WITH(NOLOCK)
	WHERE DATA_REFERENCIA BETWEEN '2022-03-01 00:00:00.000' AND '2022-03-31 00:00:00.000' AND TEMPO_CONTADOR <> -1 AND TECNOLOGIA = 'WCDMA' AND UF = 'PE' --AND MUNICIPIO = 'RECIFE'
	GROUP BY DATA_REFERENCIA
	--ORDER BY DATA_REFERENCIA

	UNION ALL

	SELECT
	DATA_REFERENCIA,
	COUNT(1) AS COLETAS,
	COUNT(CASE WHEN TEMPO_CONTADOR > 0 THEN SITE END) AS SETORES_CELLDOWNTIME
	FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES WITH (NOLOCK)
	WHERE DATA_REFERENCIA BETWEEN '2023-03-01 00:00:00.000' AND '2023-03-31 00:00:00.000' AND TEMPO_CONTADOR <> -1 AND TECNOLOGIA = 'WCDMA' AND UF = 'PE' --AND MUNICIPIO = 'RECIFE'
	GROUP BY DATA_REFERENCIA
	) A
ORDER BY DATA_REFERENCIA

--===========================================================================================================
--PLANTA (SETORES)
--============================================================================================================
SELECT
DATA_REFERENCIA,
SUM(PLANTA_3G) AS PLANTA_WCDMA,
SUM(PLANTA_4G) AS PLANTA_LTE
FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_DIARIO_SITE_20230310
WHERE UF = 'PE' AND DATA_REFERENCIA BETWEEN '2022-03-01' AND '2022-03-31' AND MUNICIPIO = 'RECIFE'
GROUP BY DATA_REFERENCIA--, PLANTA_3G,PLANTA_4G
--ORDER BY DATA_REFERENCIA

UNION ALL

SELECT
DATA_REFERENCIA,
SUM(PLANTA_3G) AS PLANTA_WCDMA,
SUM(PLANTA_4G) AS PLANTA_LTE
FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_DIARIO_SITE
WHERE UF = 'PE' AND DATA_REFERENCIA BETWEEN '2023-03-01' AND '2023-03-31' AND MUNICIPIO = 'RECIFE'
GROUP BY DATA_REFERENCIA--, PLANTA_3G,PLANTA_4G
ORDER BY DATA_REFERENCIA


SELECT
ANO,
MES,
SUM(PLANTA_3G) AS PLANTA_WCDMA,
SUM(PLANTA_4G) AS PLANTA_LTE
FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_MENSAL_SITE_20230323
WHERE ANO = 2022 AND MES = 3 AND UF = 'PE' --AND MUNICIPIO = 'RECIFE'
GROUP BY ANO, MES
--ORDER BY DATA_REFERENCIA


SELECT
	DATA_REFERENCIA,
	COUNT(1) AS COLETAS,
	COUNT(CASE WHEN TEMPO_CONTADOR > 0 THEN SITE END) AS SETORES_CELLDOWNTIME
	FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES_BKP_03032023 WITH(NOLOCK)
	WHERE DATA_REFERENCIA BETWEEN '2022-03-01 00:00:00.000' AND '2022-03-31 00:00:00.000' AND TEMPO_CONTADOR <> -1 AND TECNOLOGIA = 'WCDMA' AND UF = 'PE' --AND MUNICIPIO = 'RECIFE'
	GROUP BY DATA_REFERENCIA

--=======================================================================================================================
--FAIXAS DE TEMPO CELLDOWNTIME
--========================================================================================================================
SELECT
*
FROM (
	SELECT
	--DATA_REFERENCIA,
	COUNT(CASE WHEN TEMPO_CONTADOR <= 30 THEN 'Até 30min' END) AS 'Até 30min' ,
	COUNT(CASE WHEN TEMPO_CONTADOR > 30 AND TEMPO_CONTADOR <= 180 THEN	'Entre 0,5h e 3h' END ) AS 'Entre 0,5h e 3h',
	COUNT(CASE WHEN TEMPO_CONTADOR > 180 AND TEMPO_CONTADOR <= 600 THEN 'Entre 3h e 10h' END) AS 'Entre 3h e 10h',
	COUNT(CASE WHEN TEMPO_CONTADOR > 600 THEN 'Maior 10h' END) AS 'Maior 10h'
	--COUNT(1) AS TOTAL_SETORES
	FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES_BKP_03032023 WITH(NOLOCK)
	WHERE DATA_REFERENCIA BETWEEN '2022-03-01 00:00:00.000' AND '2022-03-31 00:00:00.000' AND TEMPO_CONTADOR <> -1 AND TECNOLOGIA = 'WCDMA' AND UF = 'PE' --AND MUNICIPIO = 'RECIFE'
	GROUP BY DATA_REFERENCIA
	ORDER BY DATA_REFERENCIA

	UNION ALL

	SELECT
	--DATA_REFERENCIA,
	COUNT(CASE WHEN TEMPO_CONTADOR <= 30 THEN 'Até 30min' END) AS 'Até 30min' ,
	COUNT(CASE WHEN TEMPO_CONTADOR > 30 AND TEMPO_CONTADOR <= 180 THEN	'Entre 0,5h e 3h' END ) AS 'Entre 0,5h e 3h',
	COUNT(CASE WHEN TEMPO_CONTADOR > 180 AND TEMPO_CONTADOR <= 600 THEN 'Entre 3h e 10h' END) AS 'Entre 3h e 10h',
	COUNT(CASE WHEN TEMPO_CONTADOR > 600 THEN 'Maior 10h' END) AS 'Maior 10h'
	--COUNT(1) AS TOTAL_SETORES
	FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES WITH(NOLOCK)
	WHERE DATA_REFERENCIA BETWEEN '2023-03-01 00:00:00.000' AND '2023-03-31 00:00:00.000' AND TEMPO_CONTADOR <> -1 AND TECNOLOGIA = 'WCDMA' AND UF = 'PE' --AND MUNICIPIO = 'RECIFE'
	GROUP BY DATA_REFERENCIA
	ORDER BY DATA_REFERENCIA
	) A
ORDER BY DATA_REFERENCIA


SELECT
SUM(TEMPO_CONTADOR) AS MINUTOS_CELLDOWNTIME
FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES_BKP_03032023 WITH(NOLOCK)
WHERE DATA_REFERENCIA BETWEEN '2022-03-01 00:00:00.000' AND '2022-03-31 00:00:00.000' 
AND TEMPO_CONTADOR <> -1 
AND TECNOLOGIA = 'WCDMA' 
AND UF = 'PE' --AND MUNICIPIO = 'RECIFE'
AND TEMPO_CONTADOR <= 30


