SELECT
GETDATE() AS DATA_REFERENCIA,
BACKLOG,
ISNULL([VIVO],0) AS 'NE'
FROM(
					SELECT
						GETDATE() AS DATA_REFERENCIA,
						REGIONAL,
						BACKLOG,
						COUNT(*) AS TOTAL
						FROM INDICADORES_CORAN..ANALITICO_BACKLOG
						WHERE UF IN ('AL','CE','PB','PE','PI','RN')
						GROUP BY REGIONAL, BACKLOG

					UNION ALL

					SELECT
						GETDATE() AS DATA_REFERENCIA,
						REGIONAL,
						BACKLOG,
						COUNT(*) AS TOTAL
						FROM INDICADORES_CORAN..ANALITICO_BACKLOG
						WHERE UF IN ('RJ','ES')
						GROUP BY REGIONAL, BACKLOG

					UNION ALL

					SELECT
						GETDATE() AS DATA_REFERENCIA,
						REGIONAL,
						BACKLOG,
						COUNT(*) AS TOTAL
						FROM INDICADORES_CORAN..ANALITICO_BACKLOG
						WHERE UF IN ('PR','SC','RS')
						GROUP BY REGIONAL, BACKLOG

					UNION ALL

					SELECT
						GETDATE() AS DATA_REFERENCIA,
						REGIONAL,
						BACKLOG,
						COUNT(*) AS TOTAL
						FROM INDICADORES_CORAN..ANALITICO_BACKLOG
						WHERE UF IN ('SP')
						GROUP BY REGIONAL, BACKLOG
	
						
					)A
PIVOT (
	MAX(TOTAL) FOR REGIONAL IN ([NE])
)P

--===============================================================================================
SELECT * FROM (
			SELECT
									GETDATE() AS DATA_REFERENCIA,
									REGIONAL,
									GERENCIA,
									BACKLOG,
									COUNT(*) AS TOTAL
									FROM INDICADORES_CORAN..ANALITICO_BACKLOG
									WHERE UF IN ('AL','CE','PB','PE','PI','RN')
									GROUP BY REGIONAL, GERENCIA, BACKLOG

								UNION ALL

								SELECT
									GETDATE() AS DATA_REFERENCIA,
									REGIONAL,
									GERENCIA,
									BACKLOG,
									COUNT(*) AS TOTAL
									FROM INDICADORES_CORAN..ANALITICO_BACKLOG
									WHERE UF IN ('RJ','ES')
									GROUP BY REGIONAL, GERENCIA, BACKLOG

								UNION ALL

								SELECT
									GETDATE() AS DATA_REFERENCIA,
									REGIONAL,
									GERENCIA,
									BACKLOG,
									COUNT(*) AS TOTAL
									FROM INDICADORES_CORAN..ANALITICO_BACKLOG
									WHERE UF IN ('PR','SC','RS')
									GROUP BY REGIONAL, GERENCIA, BACKLOG

								UNION ALL

								SELECT
									GETDATE() AS DATA_REFERENCIA,
									REGIONAL,
									GERENCIA,
									BACKLOG,
									COUNT(*) AS TOTAL
									FROM INDICADORES_CORAN..ANALITICO_BACKLOG
									WHERE UF IN ('SP')
									GROUP BY REGIONAL, GERENCIA, BACKLOG

		) A

WHERE BACKLOG = 'BACKLOG CAMPO - 1 DIA'


SELECT
		
		REGIONAL,
		GERENCIA,
		BACKLOG,
		COUNT(*) AS TOTAL
		FROM INDICADORES_CORAN..ANALITICO_BACKLOG
		WHERE UF IN ('AL','CE','PB','PE','PI','RN') AND BACKLOG = 'BACKLOG CAMPO - 1 DIA'
		GROUP BY REGIONAL,GERENCIA, BACKLOG


SELECT
GERENCIA,
COUNT(*) AS TOTAL
FROM INDICADORES_CORAN..ANALITICO_BACKLOG
WHERE BACKLOG = 'BACKLOG CAMPO - 1 DIA' AND GERENCIA = 'RJ/ES'
GROUP BY GERENCIA

SELECT * FROM ANALITICO_BACKLOG

--=================================================================================

SELECT 
	GETDATE() AS DATA_REFERENCIA,
	BACKLOG,
	REGIONAL,
	GERENCIA,
	COUNT(*) AS TOTAL
  FROM INDICADORES_CORAN..ANALITICO_BACKLOG
  WHERE BACKLOG = 'BACKLOG CAMPO - 1 DIA' AND (UF IN ('AL','CE','PB','PE','PI','RN','RJ','ES','PR','SC','RS') OR GERENCIA IN ('SPA','SPB'))
  GROUP BY BACKLOG,GERENCIA,REGIONAL
  ORDER BY BACKLOG,GERENCIA