
-- DEEP DIVE REDE EXTERNA
SELECT
A.*,
CASE WHEN B.TEMPO >= A.TEMPO THEN 1 ELSE 0 END FLG_PIORA,
CASE WHEN A.DISP_SITE_DIA < 99 AND EV.FLG_EVENTO IS NULL THEN 0 ELSE 1 END FLG_EVENTO
FROM INDICADORES_CORAN.dbo.TBL_CELLDOWNTIME_RANKING_MENSAL_SITES_HMM A WITH(NOLOCK)
--INNER JOIN (SELECT A.* FROM SISTEMA_MAESTRO..AUX_SEMANAS A INNER JOIN (SELECT MAX(DATA_REFERENCIA)-1 AS DTMAX FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES)DTMAX ON A.DATA_REFERENCIA = DTMAX.DTMAX)D ON A.ANO = D.ANO AND A.MES = D.MES
LEFT JOIN INDICADORES_CORAN.dbo.TBL_CELLDOWNTIME_RANKING_MENSAL_SITES_HMM B WITH(NOLOCK) ON A.UF = B.UF AND A.SITE = B.SITE AND B.MES = A.MES - 1
LEFT JOIN (SELECT DISTINCT UF, SITE, 1 AS FLG_EVENTO FROM P1_REAL_TIME..TBT_IMP_ATIVOS_CAMPO_COMPLETA WITH (NOLOCK)) EV ON A.UF = EV.UF AND A.SITE = EV.SITE
WHERE A.ANO = YEAR(GETDATE()) AND A.MES in (MONTH(GETDATE())-1,MONTH(GETDATE()))


-- DEEP DIVE - ATUALIZADO COM HISTORICO DO ANTIGO AGAIN

SELECT DISTINCT
    A.DATA_REFERENCIA,
    A.ANO,
    A.MES, 
    DATEPART(DAY, A.DATA_REFERENCIA) AS DIA,
    A.UF + '_'+ A.SITE AS CHAVE,
    CASE WHEN A.UF = 'SP' THEN F.NOME_REGIONAL
        WHEN A.UF = 'SPC' THEN 'SPC'
        WHEN A.UF = 'SPI' THEN 'SPI'
        WHEN A.UF IN ('BA', 'SE', 'AL', 'RN', 'PB', 'CE', 'PI', 'PE') THEN 'NE' 
        WHEN A.UF = 'MG' THEN 'MG'
        WHEN A.UF IN ('RJ', 'ES') THEN 'RJ/ES'
        WHEN A.UF IN ('PR', 'SC', 'RS') THEN 'SUL'
        WHEN A.UF IN ('AM', 'PA', 'MA', 'AP', 'RR') THEN 'NO'
        WHEN A.UF IN ('AC', 'MS', 'MT', 'RO', 'DF', 'GO', 'TO') THEN 'CO'
    END REGIONAL,
    CASE WHEN A.UF IN ('SPC','SPI') THEN 'SP' ELSE A.UF END AS UF,
    A.MUNICIPIO,
    A.SITE,
    A.T_D1 AS CDT_DIA_SITE,
    A.CAUSA_RAIZ,
    E.CLASS_FALHA,
    C.LAT,
    C.LONG,
    D.CLASSIFICACAO   
FROM INDICADORES_CORAN..TBF_PRIORIZACAO_SITES_OFENSORES A WITH(NOLOCK)
-- INNER JOIN (SELECT DATA_REFERENCIA, DATEPART(YEAR,DATA_REFERENCIA) AS ANO, DATEPART(MONTH, DATA_REFERENCIA) AS MES, UF, SITE, SUM(CASE WHEN TEMPO_CONTADOR_HMM >= 0 AND TECNOLOGIA <> 'GSM' THEN TEMPO_CONTADOR_HMM END) AS MINUTOS_GERAL FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES WITH(NOLOCK) GROUP BY DATA_REFERENCIA, UF, SITE
-- ) B ON A.UF = B.UF AND A.SITE = B.SITE AND A.ANO = B.ANO AND B.DATA_REFERENCIA = DATEADD(DAY,-1,A.DATA_REFERENCIA)
LEFT JOIN (SELECT DISTINCT UF, SIGLA_SITE, LAT, LONG FROM SISTEMA_MAESTRO..TBA_PLANTA_MOVEL WITH(NOLOCK)) C ON CASE WHEN A.UF IN ('SPC','SPI') THEN 'SP' ELSE A.UF END = C.UF AND A.SITE = C.SIGLA_SITE
LEFT JOIN SISTEMA_MAESTRO..AUX_CLASSIFICACAO_MUNICIPIOS D WITH(NOLOCK) ON CASE WHEN A.UF IN ('SPC','SPI') THEN 'SP' ELSE A.UF END = D.UF AND A.MUNICIPIO = D.MUNICIPIO
LEFT JOIN INDICADORES_CORAN..TBF_PRIORIZACAO_SITES_OFENSORES_CAUSAS E WITH(NOLOCK) ON A.CAUSA_RAIZ = E.FALHA_ACAO
LEFT JOIN INDICADORES_CORAN..TBA_DIVISAO_MUNICIPIOS_SP_FIXA F WITH(NOLOCK) ON A.MUNICIPIO = F.MUNICIPIO AND A.UF = 'SP'
WHERE CAUSA_RAIZ IS NOT NULL AND E.CLASS_FALHA IS NOT NULL AND CAUSA_RAIZ <> 'FALHA_ACAO' AND MES <> 4
-- ORDER BY ANO, MES, DIA

UNION ALL

SELECT * FROM INDICADORES_CORAN..TBF_PRIORIZACAO_SITES_OFENSORES_BI_HIST

-- ANTIGA 
-- DEEP DIVE
SELECT
    B.DATA_REFERENCIA,
    B.ANO,
    B.MES, 
    DATEPART(DAY, B.DATA_REFERENCIA) AS DIA,
    A.UF + '_'+ A.SITE AS CHAVE,
    	CASE WHEN A.UF = 'SP' THEN F.NOME_REGIONAL
		WHEN A.UF = 'SPC' THEN 'SPC'
		WHEN A.UF = 'SPI' THEN 'SPI'
		WHEN A.UF IN ('BA', 'SE', 'AL', 'RN', 'PB', 'CE', 'PI', 'PE') THEN 'NE' 
		WHEN A.UF = 'MG' THEN 'MG'
		WHEN A.UF IN ('RJ', 'ES') THEN 'RJ/ES'
		WHEN A.UF IN ('PR', 'SC', 'RS') THEN 'SUL'
		WHEN A.UF IN ('AM', 'PA', 'MA', 'AP', 'RR') THEN 'NO'
		WHEN A.UF IN ('AC', 'MS', 'MT', 'RO', 'DF', 'GO', 'TO') THEN 'CO'
	END REGIONAL,
    A.UF,
    A.MUNICIPIO,
    A.SITE,
    B.MINUTOS_GERAL AS CDT_DIA_SITE,
    A.CAUSA_RAIZ,
    E.CLASS_FALHA,
    C.LAT,
    C.LONG,
    D.CLASSIFICACAO   
FROM INDICADORES_CORAN..TBF_PRIORIZACAO_SITES_OFENSORES A WITH(NOLOCK)
INNER JOIN INDICADORES_CORAN..TBF_CELLDOWNTIME_DIARIO_SITE_HMM B WITH(NOLOCK) ON A.UF = B.UF AND A.SITE = B.SITE AND A.ANO = B.ANO AND B.DATA_REFERENCIA = DATEADD(DAY,-1,A.DATA_REFERENCIA)
LEFT JOIN (SELECT DISTINCT UF, SIGLA_SITE, LAT, LONG FROM SISTEMA_MAESTRO..TBA_PLANTA_MOVEL WITH(NOLOCK)) C ON A.UF = C.UF AND A.SITE = C.SIGLA_SITE
LEFT JOIN SISTEMA_MAESTRO..AUX_CLASSIFICACAO_MUNICIPIOS D WITH(NOLOCK) ON A.UF = D.UF AND A.MUNICIPIO = D.MUNICIPIO
LEFT JOIN INDICADORES_CORAN..TBF_PRIORIZACAO_SITES_OFENSORES_CAUSAS E WITH(NOLOCK) ON A.CAUSA_RAIZ = E.FALHA_ACAO
LEFT JOIN INDICADORES_CORAN..TBA_DIVISAO_MUNICIPIOS_SP_FIXA F WITH(NOLOCK) ON A.MUNICIPIO = F.MUNICIPIO AND A.UF = 'SP'
ORDER BY ANO, MES, DIA
















-- SELECT DISTINCT * FROM INDICADORES_CORAN..TBF_PRIORIZACAO_SITES_OFENSORES WHERE CLASS_FALHA IS NULL AND CAUSA_RAIZ IS NOT NULL AND CAUSA_RAIZ <> 'FALHA_ACAO'





SELECT * FROM INDICADORES_CORAN..TBF_PRIORIZACAO_SITES_OFENSORES WHERE MES = 5 AND CAUSA_RAIZ IS NOT NULL
SELECT TOP 10 * FROM INDICADORES_CORAN..TBF_PRIORIZACAO_SITES_OFENSORES WHERE CAUSA_RAIZ IS NOT NULL AND MES = 5


SELECT DATA_REFERENCIA, DATEPART(YEAR,DATA_REFERENCIA) AS ANO, DATEPART(MONTH, DATA_REFERENCIA) AS MES, UF, SITE, SUM(CASE WHEN TEMPO_CONTADOR_HMM >= 0 AND TECNOLOGIA <> 'GSM' THEN TEMPO_CONTADOR_HMM END) AS MINUTOS_GERAL FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES WITH(NOLOCK) GROUP BY DATA_REFERENCIA, UF, SITE



SELECT TOP 10 
    A.DATA_REFERENCIA,
    A.ANO,
    A.MES,
    A.DIA,
    A.CHAVE,
    A.REGIONAL,
    A.UF,
    A.MUNICIPIO,
    A.SITE,
    B.MINUTOS_GERAL AS CDT_DIA_SITE,
    CAUSA_RAIZ,
    CLASS_FALHA,
    C.LAT,
    C.LONG,
    D.CLASSIFICACAO
FROM INDICADORES_CORAN..TBF_PRIORIZACAO_SITES_OFENSORES_TEMP A WITH(NOLOCK)
LEFT JOIN (SELECT DATA_REFERENCIA, UF, SITE, SUM(CASE WHEN TEMPO_CONTADOR_HMM >= 0 AND TECNOLOGIA <> 'GSM' THEN TEMPO_CONTADOR_HMM END) AS MINUTOS_GERAL FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES WITH(NOLOCK) GROUP BY DATA_REFERENCIA, UF, SITE
) B ON A.UF = B.UF AND A.SITE = B.SITE AND A.DATA_REFERENCIA = B.DATA_REFERENCIA
LEFT JOIN SISTEMA_MAESTRO..TBA_PLANTA_MOVEL C WITH(NOLOCK) ON A.UF = C.UF AND A.SITE = B.SITE 
LEFT JOIN SISTEMA_MAESTRO..AUX_CLASSIFICACAO_MUNICIPIOS D WITH(NOLOCK) ON A.UF = D.UF AND A.MUNICIPIO = D.MUNICIPIO

SELECT * FROM INDICADORES_CORAN..TBF_PRIORIZACAO_SITES_OFENSORES WITH(NOLOCK) WHERE CAUSA_RAIZ IS NOT NULL AND DATA_REFERENCIA = '2024-10-04' AND UF = 'PR' AND SITE = 'CN3'
SELECT * FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_DIARIO_SITE_HMM WHERE DATA_REFERENCIA = '2024-10-03' AND UF = 'PR' AND SITE = 'CN3'
SELECT * FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_DIARIO_SITE_HMM WHERE DATA_REFERENCIA = '2024-10-04' AND UF = 'PR' AND SITE = 'CN3'

-- =========================================================
WITH CDT AS (
SELECT
    DATA_REFERENCIA,
    UF,
    SITE,
    MINUTOS_GERAL
FROM (
    SELECT DATA_REFERENCIA, UF, SITE, SUM(CASE WHEN TEMPO_CONTADOR_HMM >= 0 AND TECNOLOGIA <> 'GSM' THEN TEMPO_CONTADOR_HMM END) AS MINUTOS_GERAL
    FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES WITH(NOLOCK)
    GROUP BY DATA_REFERENCIA, UF, SITE
    UNION ALL
    SELECT DATA_REFERENCIA, UF, SITE, SUM(CASE WHEN TEMPO_CONTADOR_HMM >= 0 AND TECNOLOGIA <> 'GSM' THEN TEMPO_CONTADOR_HMM END) AS MINUTOS_GERAL
    FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES_HIST_2023 WITH(NOLOCK)
    GROUP BY DATA_REFERENCIA, UF, SITE
) A

),

PLANTA AS (

SELECT UF, SIGLA_SITE, LAT, LONG FROM SISTEMA_MAESTRO..TBA_PLANTA_MOVEL WITH(NOLOCK) GROUP BY UF, SIGLA_SITE, LAT, LONG  

)

SELECT
    A.DATA_REFERENCIA,
    A.ANO,
    A.MES,
    A.DIA,
    A.CHAVE,
    A.REGIONAL,
    A.UF,
    A.MUNICIPIO,
    A.SITE,
    B.MINUTOS_GERAL AS CDT_DIA_SITE,
    CAUSA_RAIZ,
    CLASS_FALHA,
    C.LAT,
    C.LONG,
    D.CLASSIFICACAO
FROM INDICADORES_CORAN..TBF_PRIORIZACAO_SITES_OFENSORES_TEMP A WITH(NOLOCK)
INNER JOIN CDT B ON A.UF = B.UF AND A.SITE = B.SITE AND A.DATA_REFERENCIA = B.DATA_REFERENCIA
LEFT JOIN PLANTA C ON A.UF = C.UF AND A.SITE = C.SIGLA_SITE
LEFT JOIN SISTEMA_MAESTRO..AUX_CLASSIFICACAO_MUNICIPIOS D WITH(NOLOCK) ON A.UF = D.UF AND A.MUNICIPIO = D.MUNICIPIO
-- WHERE A.UF = 'PA' AND A.SITE = 'HLN'






-- ===============================================================================================================================
SELECT *
FROM [INDICADORES_CORAN].[dbo].[TBF_PRIORIZACAO_SITES_OFENSORES_BKP]
WHERE ANO = 2024 AND MES IN (5,6)AND CAUSA_RAIZ IS NOT NULL



SELECT DATEPART(MONTH,DATA_REFERENCIA) AS MES, COUNT(*), 'BKP' AS TBL
FROM [INDICADORES_CORAN].[dbo].[TBF_PRIORIZACAO_SITES_OFENSORES_BKP]
WHERE CAUSA_RAIZ IS NOT NULL
GROUP BY DATEPART(MONTH,DATA_REFERENCIA)
--ORDER BY MES
UNION ALL
SELECT DATEPART(MONTH,DATA_REFERENCIA) AS MES, COUNT(*), 'MAIN' AS TBL
FROM [INDICADORES_CORAN].[dbo].[TBF_PRIORIZACAO_SITES_OFENSORES]
WHERE CAUSA_RAIZ IS NOT NULL
GROUP BY DATEPART(MONTH,DATA_REFERENCIA)
ORDER BY MES, TBL

-- ========================================
-- SELECT DISTINCT DATA_REFERENCIA, COUNT(*), 'BKP' AS TBL
-- FROM [INDICADORES_CORAN].[dbo].[TBF_PRIORIZACAO_SITES_OFENSORES_BKP]
-- WHERE CAUSA_RAIZ IS NOT NULL AND ANO = 2024 AND MES = 6
-- GROUP BY DATA_REFERENCIA
-- UNION ALL

SELECT DISTINCT DATA_REFERENCIA, COUNT(*), 'MAIN' AS TBL
FROM INDICADORES_CORAN..TBF_PRIORIZACAO_SITES_OFENSORES WITH(NOLOCK)
WHERE CAUSA_RAIZ IS NOT NULL AND ANO = 2024 AND MES = 5
GROUP BY DATA_REFERENCIA
UNION ALL
SELECT DISTINCT CAST(DATA_REFERENCIA AS DATE) AS DATA_REFERENCIA, COUNT(*), 'HIST' AS TBL
FROM [INDICADORES_CORAN].[dbo].[TBF_PRIORIZACAO_SITES_OFENSORES_BI_HIST]
WHERE CAUSA_RAIZ IS NOT NULL AND ANO = 2024 AND MES = 3
GROUP BY DATA_REFERENCIA

ORDER BY DATA_REFERENCIA, TBL


SELECT TOP 10 * FROM INDICADORES_CORAN..TBF_PRIORIZACAO_SITES_OFENSORES WHERE UF = 'RJ' AND SITE = 'DSM' AND MES = 10
SELECT * FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_DIARIO_SITE_HMM  WHERE UF = 'RJ' AND SITE = 'DSM' AND MES = 10 AND ANO = 2024
SELECT * FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_MENSAL_SITE_HMM  WHERE UF = 'RJ' AND SITE = 'DSM' AND MES = 10 AND ANO = 2024

SELECT * FROM INDICADORES_CORAN..TBF_PRIORIZACAO_SITES_OFENSORES_BI_HIST  -- ATÉ 03/2024
WHERE DATA_REFERENCIA <= '2024-03-31'
