-- DEEP DIVE
DECLARE @DATA_INICIAL DATE = GETDATE()-3 --240;
DECLARE @DATA_FINAL   DATE = GETDATE()-1;

WITH DISP_MUN AS
(		
		SELECT
				DISP.DATA_REFERENCIA,
				CASE WHEN REGIONAL = 'MG/RJ/ES' THEN 'SUD'
					 WHEN REGIONAL = 'BA/SE/NE' THEN 'NE'
					 ELSE REGIONAL
				END REGIONAL,
				DISP.UF,
				DISP.MUNICIPIO,
				SUM(TEMPO_CONTADOR_HMM) AS MINUTOS_MUNICIPIO,
				SUM(COLETAS_HMM)*60 AS MINUTOS_MAX_MUNICIPIO
				-- ROUND((1-(CAST(SUM(TEMPO_CONTADOR_HMM) AS FLOAT)/CAST(nullif(SUM(COLETAS_HMM)*60,0) AS FLOAT)))*100,2) AS DISP_DIARIA_MUNICIPIO
		FROM 
				SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES DISP WITH(NOLOCK)
				-- (SELECT * FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES WITH(NOLOCK) WHERE DATA_REFERENCIA BETWEEN @DATA_INICIAL AND @DATA_FINAL UNION ALL SELECT * FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES_HIST_2023 WITH(NOLOCK) WHERE DATA_REFERENCIA BETWEEN @DATA_INICIAL AND @DATA_FINAL) DISP
				INNER JOIN INDICADORES_CORAN..TBF_PRIORIZACAO_SITES_OFENSORES PRIO WITH(NOLOCK) ON DISP.UF = PRIO.UF AND DISP.MUNICIPIO = PRIO.MUNICIPIO
		WHERE	
				TECNOLOGIA <> 'GSM'
				AND TEMPO_CONTADOR_HMM >= 0
				-- AND DISP.DATA_REFERENCIA BETWEEN @DATA_INICIAL AND @DATA_FINAL
		GROUP BY 
				DISP.DATA_REFERENCIA,
				REGIONAL,
				DISP.UF,
				DISP.MUNICIPIO
),
DISP_SITE AS
(
SELECT
		REGIONAL,
		DISP.UF,
		DISP.MUNICIPIO,
		DISP.SITE,
		TEMPO_CONTADOR_HMM AS MINUTOS_SITE
FROM 
		(SELECT * FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES WITH(NOLOCK) UNION ALL SELECT * FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES_HIST_2023 WITH(NOLOCK)) DISP
		INNER JOIN INDICADORES_CORAN..TBF_PRIORIZACAO_SITES_OFENSORES PRIO WITH(NOLOCK) ON DISP.UF = PRIO.UF AND DISP.SITE = PRIO.SITE
WHERE 
		TECNOLOGIA <> 'GSM'
		AND TEMPO_CONTADOR_HMM >= 0
		AND DISP.DATA_REFERENCIA BETWEEN @DATA_INICIAL AND @DATA_FINAL
GROUP BY
		REGIONAL,
		DISP.UF,
		DISP.MUNICIPIO,
		DISP.SITE,
		TEMPO_CONTADOR_HMM
),
DISP AS (
SELECT
	ROW_NUMBER() OVER (PARTITION BY DATA_REFERENCIA,UF, MUNICIPIO ORDER BY DATA_REFERENCIA) AS NL,
	DATEPART(YEAR,DATA_REFERENCIA) AS ANO,
	DATEPART(MONTH,DATA_REFERENCIA) AS MES,
	DATEPART(DAY,DATA_REFERENCIA) AS DIA,
	A.*,
	ROUND((1-(CAST(SUM(A.MINUTOS_MUNICIPIO - A.MINUTOS_A_EXCLUIR) AS FLOAT)/CAST(nullif(A.MINUTOS_MAX_MUNICIPIO,0) AS FLOAT)))*100,2) AS DISP_DIARIA_PREVISTA_MUNICIPIO
FROM
(
		SELECT				
				DISP_MUN.DATA_REFERENCIA,
				DISP_MUN.REGIONAL,
				DISP_MUN.UF,
				DISP_MUN.MUNICIPIO,
				DISP_SITE.SITE,
				DISP_MUN.MINUTOS_MUNICIPIO,
				DISP_MUN.MINUTOS_MAX_MUNICIPIO,
				-- DISP_MUN.DISP_DIARIA_MUNICIPIO,
				SUM(DISP_SITE.MINUTOS_SITE)	AS MINUTOS_A_EXCLUIR
		FROM
				DISP_MUN WITH(NOLOCK)
				INNER JOIN DISP_SITE ON DISP_SITE.UF = DISP_MUN.UF AND DISP_SITE.MUNICIPIO = DISP_MUN.MUNICIPIO
		WHERE
				DISP_MUN.UF IN ('AM','AP','BA','CE','DF','ES','GO','MA','MG','MS','MT','PA','PB','PE','PI','PR','RJ','RN','RO','RR','RS','SC','SE','SP','TO')
		GROUP BY 
				DISP_MUN.DATA_REFERENCIA,
				DISP_MUN.REGIONAL,
				DISP_MUN.UF,
				DISP_MUN.MUNICIPIO,
				DISP_SITE.SITE,
				DISP_MUN.MINUTOS_MUNICIPIO,
				DISP_MUN.MINUTOS_MAX_MUNICIPIO
				-- DISP_MUN.DISP_DIARIA_MUNICIPIO
) A
GROUP BY
		A.DATA_REFERENCIA,
		A.REGIONAL,
		A.UF,
		A.MUNICIPIO,
		A.SITE,
		A.MINUTOS_MUNICIPIO,
		A.MINUTOS_MAX_MUNICIPIO,
		A.MINUTOS_A_EXCLUIR
		-- A.DISP_DIARIA_MUNICIPIO
)

-- QUERY PRINCIPAL
SELECT DISTINCT
	A.DATA_REFERENCIA,
	A.ANO,
	A.MES,
	DATEPART(DAY,A.DATA_REFERENCIA) AS DIA,
	CASE WHEN A.UF = 'SP' THEN DIVISAO.NOME_REGIONAL
		WHEN A.UF IN ('BA', 'SE', 'AL', 'RN', 'PB', 'CE', 'PI', 'PE') THEN 'NE' 
		WHEN A.UF = 'MG' THEN 'MG'
		WHEN A.UF IN ('RJ', 'ES') THEN 'RJ/ES'
		WHEN A.UF IN ('PR', 'SC', 'RS') THEN 'SUL'
		WHEN A.UF IN ('AM', 'PA', 'MA', 'AP', 'RR') THEN 'NO'
		WHEN A.UF IN ('AC', 'MS', 'MT', 'RO', 'DF', 'GO', 'TO') THEN 'CO'
	END REGIONAL,
	A.UF,
	A.MUNICIPIO,
	CLASS_MUN.CLASSIFICACAO,
	DISP.MINUTOS_MUNICIPIO,
	DISP.MINUTOS_MAX_MUNICIPIO,
	-- B.DISPONIBILIDADE_GERAL AS DIARIO,
	A.SITE,
	A.CAUSA_RAIZ AS FALHA_ACAO,
	CAUSAS.CLASS_FALHA AS CLASS_CAUSA_RAIZ,
	A.DT_PREVISTA AS PREVISAO
FROM INDICADORES_CORAN..TBF_PRIORIZACAO_SITES_OFENSORES A WITH(NOLOCK)
LEFT JOIN DISP ON A.UF = DISP.UF AND A.MUNICIPIO = DISP.MUNICIPIO AND CONVERT(DATE, A.DATA_REFERENCIA, 103) = DISP.DATA_REFERENCIA
LEFT JOIN INDICADORES_CORAN..TBA_DIVISAO_MUNICIPIOS_SP_FIXA DIVISAO WITH(NOLOCK) ON A.MUNICIPIO = DIVISAO.MUNICIPIO AND A.UF = 'SP'
LEFT JOIN SISTEMA_MAESTRO..AUX_CLASSIFICACAO_MUNICIPIOS CLASS_MUN WITH(NOLOCK) ON CLASS_MUN.UF = A.UF AND CLASS_MUN.MUNICIPIO = A.MUNICIPIO
LEFT JOIN INDICADORES_CORAN..TBF_PRIORIZACAO_SITES_OFENSORES_CAUSAS CAUSAS WITH(NOLOCK) ON A.CAUSA_RAIZ = CAUSAS.FALHA_ACAO
LEFT JOIN SISTEMA_MAESTRO..TBA_PLANTA_MOVEL PLANTA WITH(NOLOCK) ON A.UF = PLANTA.UF AND A.SITE = PLANTA.SIGLA_SITE
WHERE TA_REFERENCIA IS NOT NULL
ORDER BY UF, SITE, DATA_REFERENCIA


-- ============================================================================================================================================

SELECT top 100 * FROM INDICADORES_CORAN..TBF_PRIORIZACAO_SITES_OFENSORES WHERE CAUSA_RAIZ IS NOT NULL ORDER BY DATA_REFERENCIA
SELECT * FROM (SELECT DATA_REFERENCIA, UF, MUNICIPIO, DISPONIBILIDADE_GERAL FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_DIARIO_MUNICIPIO_HMM UNION ALL SELECT DATA_REFERENCIA, UF, MUNICIPIO, DISPONIBILIDADE_GERAL FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_DIARIO_MUNICIPIO_20230310
) B WHERE MUNICIPIO = 'CONTAGEM'  ORDER BY DATA_REFERENCIA DATA_REFERENCIA = '2024-05-07'

SELECT * FROM 

(SELECT * FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES UNION ALL SELECT * FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES_HIST_2023) A

WHERE UF = 'AC' AND MUNICIPIO = 'CRUZEIRO DO SUL' ORDER BY DATA_REFERENCIA -- AND DATA_REFERENCIA = '2024-04-10 00:00:00.000' 




/*
SELECT
        FALHAS.COD_FALHA,
        FALHAS.FALHA_ACAO,
        CLASS_FALHAS.CLASS_FALHA
FROM PROJETO_AGAIN..TBA_FALHAS FALHAS
LEFT JOIN PROJETO_AGAIN..TBA_CLASSIFICACAO_FALHAS CLASS_FALHAS ON CLASS_FALHAS.COD_CLASS_FALHA =  FALHAS.COD_CLASS_FALHA
*/




-- DEEP DIVE
SELECT DISTINCT
	A.*,
	DATEPART(DAY,A.DATA_REFERENCIA) AS DIA,
	CASE WHEN A.UF = 'SP' THEN DIVISAO.NOME_REGIONAL
		WHEN A.UF = 'SPC' THEN 'SPC'
		WHEN A.UF = 'SPI' THEN 'SPI'
		WHEN A.UF IN ('BA', 'SE', 'AL', 'RN', 'PB', 'CE', 'PI', 'PE') THEN 'NE' 
		WHEN A.UF = 'MG' THEN 'MG'
		WHEN A.UF IN ('RJ', 'ES') THEN 'RJ/ES'
		WHEN A.UF IN ('PR', 'SC', 'RS') THEN 'SUL'
		WHEN A.UF IN ('AM', 'PA', 'MA', 'AP', 'RR') THEN 'NO'
		WHEN A.UF IN ('AC', 'MS', 'MT', 'RO', 'DF', 'GO', 'TO') THEN 'CO'
	END REGIONAL,
	CLASS_MUN.CLASSIFICACAO,
	CAUSAS.CLASS_FALHA AS CLASS_CAUSA_RAIZ,
	PLANTA.LAT,
	PLANTA.LONG
FROM INDICADORES_CORAN..TBF_PRIORIZACAO_SITES_OFENSORES A WITH(NOLOCK)
LEFT JOIN INDICADORES_CORAN..TBA_DIVISAO_MUNICIPIOS_SP_FIXA DIVISAO WITH(NOLOCK) ON A.MUNICIPIO = DIVISAO.MUNICIPIO AND A.UF = 'SP'
LEFT JOIN SISTEMA_MAESTRO..AUX_CLASSIFICACAO_MUNICIPIOS CLASS_MUN WITH(NOLOCK) ON CLASS_MUN.UF = A.UF AND CLASS_MUN.MUNICIPIO = A.MUNICIPIO
LEFT JOIN INDICADORES_CORAN..TBF_PRIORIZACAO_SITES_OFENSORES_CAUSAS CAUSAS WITH(NOLOCK) ON A.CAUSA_RAIZ = CAUSAS.FALHA_ACAO
LEFT JOIN SISTEMA_MAESTRO..TBA_PLANTA_MOVEL PLANTA WITH(NOLOCK) ON A.UF = PLANTA.UF AND A.SITE = PLANTA.SIGLA_SITE
WHERE TA_REFERENCIA IS NOT NULL
ORDER BY UF, SITE, DATA_REFERENCIA

SELECT * FROM INDICADORES_CORAN..TBA_DIVISAO_MUNICIPIOS_SP_FIXA





