--=============================================================================================================================================
--DISPONIBILIDADE DIARIA ESPERADA DO MUNICIPIO POR SITE
--PROJETO_AGAIN..TBL_DISPONIBILIDADE_DIARIA
--=============================================================================================================================================
DECLARE @DATA_INICIAL DATE = GETDATE()-7;
DECLARE @DATA_FINAL   DATE = GETDATE()-1;

WITH DISP_MUN AS
(		
		SELECT TOP 10
				DATA_REFERENCIA,
				CASE WHEN REGIONAL = 'MG/RJ/ES' THEN 'SUD'
					 WHEN REGIONAL = 'BA/SE/NE' THEN 'NE'
					 ELSE REGIONAL
					 END REGIONAL,
				UF,
				MUNICIPIO,
				SUM(TEMPO_CONTADOR_HMM) AS MINUTOS_MUNICIPIO,
				SUM(COLETAS_HMM)*60 AS MINUTOS_MAX_MUNICIPIO,
				ROUND((1-(CAST(SUM(TEMPO_CONTADOR_HMM) AS FLOAT)/CAST(nullif(SUM(COLETAS_HMM)*60,0) AS FLOAT)))*100,2) AS DISP_DIARIA_MUNICIPIO
		FROM 
				SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES WITH(NOLOCK)
		WHERE	
				TECNOLOGIA <> 'GSM'
				AND TEMPO_CONTADOR_HMM >= 0
				AND DATA_REFERENCIA BETWEEN @DATA_INICIAL AND @DATA_FINAL
				AND MUNICIPIO = 'CONTAGEM'
		GROUP BY 
				DATA_REFERENCIA,
				REGIONAL,
				UF,
				MUNICIPIO
		ORDER BY DATA_REFERENCIA
),

DISP_SITE AS

(
SELECT
		REGIONAL,
		UF,
		MUNICIPIO,
		SITE,
		TEMPO_CONTADOR_HMM AS MINUTOS_SITE
FROM 
		SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES DISP WITH(NOLOCK)
		
WHERE 
		TECNOLOGIA <> 'GSM'
		AND TEMPO_CONTADOR_HMM >= 0
		AND DATA_REFERENCIA BETWEEN @DATA_INICIAL AND @DATA_FINAL

GROUP BY
		REGIONAL,
		UF,
		MUNICIPIO,
		SITE,
		TEMPO_CONTADOR_HMM
)


--QUERY PRINCIPAL
SELECT
ROW_NUMBER() OVER (PARTITION BY DATA_REFERENCIA,UF, MUNICIPIO ORDER BY DATA_REFERENCIA) AS NL,
DATEPART(YEAR,DATA_REFERENCIA) AS ANO,
DATEPART(MONTH,DATA_REFERENCIA) AS MES,
DATEPART(DAY,DATA_REFERENCIA) AS DIA,
A.*,
ROUND((1-(CAST(SUM(A.MINUTOS_MUNICIPIO - A.MINUTOS_A_EXCLUIR) AS FLOAT)/CAST(nullif(A.MINUTOS_MAX_MUNICIPIO,0) AS FLOAT)))*100,2) AS DISP_DIARIA_PREVISTA_MUNICIPIO
FROM
(
		SELECT				
				DISP_MUN.DATA_REFERENCIA,
				CLASS_MUN.CLASSIFICACAO,
				DISP_MUN.REGIONAL,
				DISP_MUN.UF,
				DISP_MUN.MUNICIPIO,
				DISP_SITE.SITE,
				DISP_MUN.MINUTOS_MUNICIPIO,
				DISP_MUN.MINUTOS_MAX_MUNICIPIO,
				DISP_MUN.DISP_DIARIA_MUNICIPIO,
				SUM(DISP_SITE.MINUTOS_SITE)	AS MINUTOS_A_EXCLUIR
		FROM
				DISP_MUN WITH(NOLOCK)
				INNER JOIN DISP_SITE ON DISP_SITE.UF = DISP_MUN.UF AND DISP_SITE.MUNICIPIO = DISP_MUN.MUNICIPIO
				LEFT JOIN SISTEMA_MAESTRO..AUX_CLASSIFICACAO_MUNICIPIOS CLASS_MUN ON CLASS_MUN.UF = DISP_MUN.UF AND CLASS_MUN.MUNICIPIO = DISP_MUN.MUNICIPIO
		WHERE
				DISP_MUN.UF IN ('AM','AP','BA','CE','DF','ES','GO','MA','MG','MS','MT','PA','PB','PE','PI','PR','RJ','RN','RO','RR','RS','SC','SE','SP','TO')
		GROUP BY 
				DISP_MUN.DATA_REFERENCIA,
				DISP_MUN.REGIONAL,
				DISP_MUN.UF,
				DISP_MUN.MUNICIPIO,
				DISP_SITE.SITE,
				DISP_MUN.MINUTOS_MUNICIPIO,
				DISP_MUN.MINUTOS_MAX_MUNICIPIO,
				DISP_MUN.DISP_DIARIA_MUNICIPIO,
				CLASS_MUN.CLASSIFICACAO
) A
GROUP BY
		A.DATA_REFERENCIA,
		A.REGIONAL,
		A.UF,
		A.MUNICIPIO,
		A.SITE,
		A.MINUTOS_MUNICIPIO,
		A.MINUTOS_MAX_MUNICIPIO,
		A.MINUTOS_A_EXCLUIR,
		A.DISP_DIARIA_MUNICIPIO,
		A.CLASSIFICACAO
-- LEFT JOIN PROJETO_AGAIN..TBL_DISPONIBILIDADE_DIARIA DISP ON REUNIAO.UF = DISP.UF AND REUNIAO.SITES_OFENSORES = DISP.SITE AND DISP.DATA_REFERENCIA = (SELECT FORMAT(DATEADD(DAY,-1,REUNIAO.DATA_REUNIAO),'dd/MM/yyyy'))



--==================================================================================================================================
--PROJETO_AGAIN..TBL_CONSOLIDADA
--==================================================================================================================================
SELECT
        DATEPART(YEAR,DISP.DATA_REFERENCIA) AS ANO,
		DATEPART(MONTH,DISP.DATA_REFERENCIA) AS MES,
		DATEPART(DAY,DISP.DATA_REFERENCIA) AS DIA,
		DATEPART(YEAR,REUNIAO.DATA_REUNIAO) AS ANO_DT_REUNIAO,
		DATEPART(MONTH,REUNIAO.DATA_REUNIAO) AS MES_DT_REUNIAO,
		DATEPART(DAY,REUNIAO.DATA_REUNIAO) AS DIA_DT_REUNIAO,
		REUNIAO.DATA_REUNIAO,
        DISP.DATA_REFERENCIA,
		REUNIÃO.FALHA_ACAO,
		CASE WHEN REUNIAO.UF = 'SP' THEN DIVISAO.NOME_REGIONAL
		ELSE DISP.REGIONAL
		END AS REGIONAL,
		REUNIAO.UF,
		DISP.CLASSIFICACAO,
		DISP.MUNICIPIO,
		DISP.MINUTOS_MUNICIPIO,
		DISP.MINUTOS_MAX_MUNICIPIO,
		DISP.SITE,
		COORD.LAT,
		COORD.LONG,
		SUM(DISP.MINUTOS_A_EXCLUIR) AS MINUTOS_A_EXCLUIR,
		DISP.DISP_DIARIA_MUNICIPIO,
		ROUND((1-(CAST(DISP.MINUTOS_MUNICIPIO - SUM(DISP.MINUTOS_A_EXCLUIR) AS FLOAT)/CAST(DISP.MINUTOS_MAX_MUNICIPIO AS FLOAT)))*100,2) AS DISP_DIARIA_PREVISTA_MUNICIPIO,
        CLASS_FALHAS.CLASS_FALHA,
        REGIONAL.UF_NOME
FROM 
        PROJETO_AGAIN..TBL_MATERIAL_REUNIAO_BRUTO REUNIAO
        LEFT JOIN PROJETO_AGAIN..TBL_DISPONIBILIDADE_DIARIA DISP ON REUNIAO.UF = DISP.UF AND REUNIAO.SITES_OFENSORES = DISP.SITE AND DISP.DATA_REFERENCIA = (SELECT FORMAT(DATEADD(DAY,-1,REUNIAO.DATA_REUNIAO),'dd/MM/yyyy'))
        INNER JOIN PROJETO_AGAIN..TBA_FALHAS FALHAS ON REUNIAO.FALHA_ACAO = FALHAS.FALHA_ACAO
        INNER JOIN PROJETO_AGAIN..TBA_CLASSIFICACAO_FALHAS CLASS_FALHAS ON FALHAS.COD_CLASS_FALHA = CLASS_FALHAS.COD_CLASS_FALHA
        LEFT JOIN PROJETO_AGAIN..AUX_REGIONAL_UF REGIONAL ON REUNIAO.UF = REGIONAL.UF
		LEFT JOIN PROJETO_AGAIN..AUX_DIVISAO_MUNICIPIOS_SP_FIXA DIVISAO ON REUNIAO.UF = 'SP' AND REUNIAO.MUNICIPIO = DIVISAO.MUNICIPIO
		LEFT JOIN PROJETO_AGAIN..AUX_COORDENADAS_SITES COORD ON REUNIAO.UF = COORD.UF AND REUNIAO.SITES_OFENSORES = COORD.SIGLA_SITE
GROUP BY
        DISP.MUNICIPIO,DISP.DATA_REFERENCIA,DISP.MINUTOS_MUNICIPIO,DISP.MINUTOS_MAX_MUNICIPIO,DISP.DISP_DIARIA_MUNICIPIO,DISP.SITE,REUNIAO.DATA_REUNIAO,DISP.REGIONAL,REUNIAO.UF,REUNIAO.FALHA_ACAO,DISP.CLASSIFICACAO,FALHAS.FALHA_ACAO,CLASS_FALHAS.CLASS_FALHA,UF_NOME,DIVISAO.NOME_REGIONAL,LAT, LONG
ORDER BY 
        MES, DIA


--==================================================================================================================================
--DEEP_DIVE..TBL_CONSOLIDADA_NOVA
--==================================================================================================================================
SELECT
        DATEPART(YEAR,PRIORIZACAO.DATA_REFERENCIA) AS ANO,
		DATEPART(MONTH,PRIORIZACAO.DATA_REFERENCIA) AS MES,
		DATEPART(DAY,PRIORIZACAO.DATA_REFERENCIA) AS DIA,
		'' AS ANO_DT_REUNIAO,
		'' AS MES_DT_REUNIAO,
		'' AS DIA_DT_REUNIAO,
		PRIORIZACAO.DATA_REFERENCIA,
        DISP.DATA_REFERENCIA,
		PRIORIZACAO.CAUSA_RAIZ,
		CASE WHEN PRIORIZACAO.UF = 'SP' THEN DIVISAO.NOME_REGIONAL
		ELSE DISP.REGIONAL
		END AS REGIONAL,
		PRIORIZACAO.UF,
		DISP.CLASSIFICACAO,
		DISP.MUNICIPIO,
		DISP.MINUTOS_MUNICIPIO,
		DISP.MINUTOS_MAX_MUNICIPIO,
		DISP.SITE,
		PRIORIZACAO.LAT,
		PRIORIZACAO.LONG,
		SUM(DISP.MINUTOS_A_EXCLUIR) AS MINUTOS_A_EXCLUIR,
		DISP.DISP_DIARIA_MUNICIPIO,
		ROUND((1-(CAST(DISP.MINUTOS_MUNICIPIO - SUM(DISP.MINUTOS_A_EXCLUIR) AS FLOAT)/CAST(DISP.MINUTOS_MAX_MUNICIPIO AS FLOAT)))*100,2) AS DISP_DIARIA_PREVISTA_MUNICIPIO,
        PRIORIZACAO.CLASS_CAUSA_RAIZ,
        REGIONAL.UF_NOME
FROM 
        DEEP_DIVE..TBL_PRIORIZACAO PRIORIZACAO
        INNER JOIN DEEP_DIVE..TBL_DISPONIBILIDADE_DIARIA DISP ON PRIORIZACAO.UF = DISP.UF AND PRIORIZACAO.SITE = DISP.SITE AND DISP.DATA_REFERENCIA = (SELECT FORMAT(DATEADD(DAY,-1,PRIORIZACAO.DATA_REFERENCIA),'dd/MM/yyyy'))
        LEFT JOIN DEEP_DIVE..AUX_REGIONAL_UF REGIONAL ON PRIORIZACAO.UF = REGIONAL.UF
		LEFT JOIN DEEP_DIVE..AUX_DIVISAO_MUNICIPIOS_SP_FIXA DIVISAO ON PRIORIZACAO.UF = 'SP' AND PRIORIZACAO.MUNICIPIO = DIVISAO.MUNICIPIO
WHERE PRIORIZACAO.UF = 'MG' AND PRIORIZACAO.SITE = 'UIU'
GROUP BY
        DISP.MUNICIPIO,DISP.DATA_REFERENCIA,DISP.MINUTOS_MUNICIPIO,DISP.MINUTOS_MAX_MUNICIPIO,DISP.DISP_DIARIA_MUNICIPIO,DISP.SITE,PRIORIZACAO.DATA_REFERENCIA,DISP.REGIONAL,PRIORIZACAO.UF,PRIORIZACAO.CAUSA_RAIZ,DISP.CLASSIFICACAO,PRIORIZACAO.CLASS_CAUSA_RAIZ,UF_NOME,DIVISAO.NOME_REGIONAL,PRIORIZACAO.LAT, PRIORIZACAO.LONG
ORDER BY 
        MES, DIA


SELECT * FROM DEEP_DIVE..TBL_PRIORIZACAO



-- DEEP DIVE
SELECT
    B.DATA_REFERENCIA,
    B.ANO,
    B.MES, 
    DATEPART(DAY, B.DATA_REFERENCIA) AS DIA,
    A.UF + '_'+ A.SITE AS CHAVE,
    	CASE WHEN A.UF = 'SP' THEN F.NOME_REGIONAL
		WHEN A.UF = 'SPC' THEN 'SPC'
		WHEN A.UF = 'SPI' THEN 'SPI'
		WHEN A.UF IN ('BA', 'SE', 'AL', 'RN', 'PB', 'CE', 'PI', 'PE') THEN 'NE' 
		WHEN A.UF = 'MG' THEN 'MG'
		WHEN A.UF IN ('RJ', 'ES') THEN 'RJ/ES'
		WHEN A.UF IN ('PR', 'SC', 'RS') THEN 'SUL'
		WHEN A.UF IN ('AM', 'PA', 'MA', 'AP', 'RR') THEN 'NO'
		WHEN A.UF IN ('AC', 'MS', 'MT', 'RO', 'DF', 'GO', 'TO') THEN 'CO'
	END REGIONAL,
    A.UF,
    A.MUNICIPIO,
    A.SITE,
    B.MINUTOS_GERAL AS CDT_DIA_SITE,
    A.CAUSA_RAIZ,
    E.CLASS_FALHA,
    C.LAT,
    C.LONG,
    D.CLASSIFICACAO   
FROM INDICADORES_CORAN..TBF_PRIORIZACAO_SITES_OFENSORES A WITH(NOLOCK)
INNER JOIN INDICADORES_CORAN..TBF_CELLDOWNTIME_DIARIO_SITE_HMM B WITH(NOLOCK) ON A.UF = B.UF AND A.SITE = B.SITE AND A.ANO = B.ANO AND B.DATA_REFERENCIA = DATEADD(DAY,-1,A.DATA_REFERENCIA)
LEFT JOIN (SELECT DISTINCT UF, SIGLA_SITE, LAT, LONG FROM SISTEMA_MAESTRO..TBA_PLANTA_MOVEL WITH(NOLOCK)) C ON A.UF = C.UF AND A.SITE = C.SIGLA_SITE
LEFT JOIN SISTEMA_MAESTRO..AUX_CLASSIFICACAO_MUNICIPIOS D WITH(NOLOCK) ON A.UF = D.UF AND A.MUNICIPIO = D.MUNICIPIO
LEFT JOIN INDICADORES_CORAN..TBF_PRIORIZACAO_SITES_OFENSORES_CAUSAS E WITH(NOLOCK) ON A.CAUSA_RAIZ = E.FALHA_ACAO
LEFT JOIN INDICADORES_CORAN..TBA_DIVISAO_MUNICIPIOS_SP_FIXA F WITH(NOLOCK) ON A.MUNICIPIO = F.MUNICIPIO AND A.UF = 'SP'
WHERE CLASS_FALHA = 'Rompimento' AND B.MES = 7
ORDER BY ANO, MES, DIA


