WITH CTE_RECURSIVO (TQA_CODIGO,TQA_RAIZ,NIVEL,CAMINHO) AS
(
SELECT
TA.TQA_CODIGO,
TA.TQA_RAIZ,
1 AS NIVEL,
CAST('\' + CAST(TQA_CODIGO AS VARCHAR) + '\' AS VARCHAR(MAX)) AS CAMINHO
FROM FABIO..TESTE_DERIVADOS TA
WHERE TA.TQA_RAIZ IS NULL AND TA.TQA_CODIGO in (307696326)

UNION ALL

SELECT
A.TQA_CODIGO,
A.TQA_RAIZ,
B.NIVEL + 1 AS NIVEL,
CAST(B.CAMINHO + CAST(A.TQA_CODIGO AS VARCHAR) + '\' AS VARCHAR(MAX))
FROM FABIO..TESTE_DERIVADOS A
INNER JOIN CTE_RECURSIVO B ON A.TQA_RAIZ = B.TQA_CODIGO
)

SELECT
CAMINHO,
REPLICATE(' | ', A.NIVEL) + CAST(B.TQA_CODIGO AS VARCHAR) AS TA
FROM CTE_RECURSIVO A
INNER JOIN FABIO..TESTE_DERIVADOS B ON A.TQA_CODIGO = B.TQA_CODIGO
ORDER BY CAMINHO




SELECT
NIVEL,
CAMINHO
FROM CTE_RECURSIVO
order by NIVEL, CAMINHO