-- ===============================================================
-- DISP DIARIA SP POR CN
-- ===============================================================
DECLARE @ANO INT = (SELECT CASE WHEN YEAR(GETDATE()) = YEAR(GETDATE()-1) THEN YEAR(GETDATE()) ELSE YEAR(GETDATE()-1) END) 
DECLARE @MES INT = (SELECT CASE WHEN MONTH(GETDATE()) = MONTH(GETDATE()-1) THEN MONTH(GETDATE()) ELSE MONTH(GETDATE()-1) END) 

SELECT
    ANO,
    MES,
    DIA, 
	UF,
    CN,
    ROUND(((1-(SUM(CASE WHEN TECNOLOGIA = 'WCDMA' AND TEMPO_CONTADOR_HMM >= 0 THEN TEMPO_CONTADOR_HMM END)/(SUM(CASE WHEN TECNOLOGIA = 'WCDMA' THEN COLETAS_HMM END)*60)))*100),2) AS DISP_3G,
    ROUND(((1-(SUM(CASE WHEN TECNOLOGIA = 'LTE' AND TEMPO_CONTADOR_HMM >= 0 THEN TEMPO_CONTADOR_HMM END)/(SUM(CASE WHEN TECNOLOGIA = 'LTE' THEN COLETAS_HMM END)*60)))*100),2) AS DISP_4G,
    ROUND(((1-(SUM(CASE WHEN TECNOLOGIA = '5G' AND TEMPO_CONTADOR_HMM >= 0 THEN TEMPO_CONTADOR_HMM END)/(SUM(CASE WHEN TECNOLOGIA = '5G' THEN COLETAS_HMM END)*60)))*100),2) AS DISP_5G,
    ROUND(((1-(SUM(CASE WHEN TECNOLOGIA <> 'GSM' AND TEMPO_CONTADOR_HMM >= 0 THEN TEMPO_CONTADOR_HMM END)/(SUM(CASE WHEN TECNOLOGIA <> 'GSM' THEN COLETAS_HMM END)*60)))*100),2) AS DISP_GERAL,
    ROUND(((1-(SUM(CASE WHEN TECNOLOGIA IN ('LTE','5G') AND TEMPO_CONTADOR_HMM >= 0 THEN TEMPO_CONTADOR_HMM END)/(SUM(CASE WHEN TECNOLOGIA IN ('LTE','5G') THEN COLETAS_HMM END)*60)))*100),2) AS DISP_4G_5G
FROM (
    SELECT
        YEAR(DATA_REFERENCIA) AS ANO,
        MONTH(DATA_REFERENCIA) AS MES,
        CAST(DAY(DATA_REFERENCIA) AS INT) AS DIA,
        A.TECNOLOGIA,
        A.UF,
        B.CN,
        CAST(TEMPO_CONTADOR_HMM AS FLOAT) AS TEMPO_CONTADOR_HMM,
        CAST(COLETAS_HMM AS FLOAT) AS COLETAS_HMM
    FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES A WITH(NOLOCK)
    LEFT JOIN (SELECT DISTINCT UF, CN, SIGLA_SITE FROM SISTEMA_MAESTRO..TBA_PLANTA_MOVEL WITH(NOLOCK)) B ON A.UF = B.UF AND A.SITE = B.SIGLA_SITE AND A.CN = B.CN
    WHERE YEAR(DATA_REFERENCIA) = @ANO AND MONTH(DATA_REFERENCIA) = @MES AND A.UF = 'SP' AND B.CN IN (16)
) C
GROUP BY ANO, MES, DIA, UF, CN
ORDER BY ANO, MES, DIA DESC, CN


-- ===============================================================
-- DISP MENSAL SP POR CN
-- ===============================================================
DECLARE @ANO INT = (SELECT CASE WHEN YEAR(GETDATE()) = YEAR(GETDATE()-1) THEN YEAR(GETDATE()) ELSE YEAR(GETDATE()-1) END) 
DECLARE @MES INT = (SELECT CASE WHEN MONTH(GETDATE()) = MONTH(GETDATE()-1) THEN MONTH(GETDATE()) ELSE MONTH(GETDATE()-1) END) 

SELECT
    ANO,
    MES, 
	UF,
    CN,
    -- COUNT(DISTINCT SITE) AS QTDE_SITES, 
    ROUND(((1-(SUM(CASE WHEN TECNOLOGIA = 'WCDMA' AND TEMPO_CONTADOR_HMM >= 0 THEN TEMPO_CONTADOR_HMM END)/(SUM(CASE WHEN TECNOLOGIA = 'WCDMA' THEN COLETAS_HMM END)*60)))*100),2) AS DISP_3G,
    ROUND(((1-(SUM(CASE WHEN TECNOLOGIA = 'LTE' AND TEMPO_CONTADOR_HMM >= 0 THEN TEMPO_CONTADOR_HMM END)/(SUM(CASE WHEN TECNOLOGIA = 'LTE' THEN COLETAS_HMM END)*60)))*100),2) AS DISP_4G,
    ROUND(((1-(SUM(CASE WHEN TECNOLOGIA = '5G' AND TEMPO_CONTADOR_HMM >= 0 THEN TEMPO_CONTADOR_HMM END)/(SUM(CASE WHEN TECNOLOGIA = '5G' THEN COLETAS_HMM END)*60)))*100),2) AS DISP_5G,
    ROUND(((1-(SUM(CASE WHEN TECNOLOGIA <> 'GSM' AND TEMPO_CONTADOR_HMM >= 0 THEN TEMPO_CONTADOR_HMM END)/(SUM(CASE WHEN TECNOLOGIA <> 'GSM' THEN COLETAS_HMM END)*60)))*100),2) AS DISP_GERAL,
    ROUND(((1-(SUM(CASE WHEN TECNOLOGIA IN ('LTE','5G') AND TEMPO_CONTADOR_HMM >= 0 THEN TEMPO_CONTADOR_HMM END)/(SUM(CASE WHEN TECNOLOGIA IN ('LTE','5G') THEN COLETAS_HMM END)*60)))*100),2) AS DISP_4G_5G
    
FROM (
    SELECT
        YEAR(DATA_REFERENCIA) AS ANO,
        MONTH(DATA_REFERENCIA) AS MES,
        A.TECNOLOGIA,
        A.UF,
        B.CN,
        CAST(TEMPO_CONTADOR_HMM AS FLOAT) AS TEMPO_CONTADOR_HMM,
        CAST(COLETAS_HMM AS FLOAT) AS COLETAS_HMM
        -- A.SITE
    FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES A WITH(NOLOCK)
    LEFT JOIN (SELECT DISTINCT UF, CN, SIGLA_SITE FROM SISTEMA_MAESTRO..TBA_PLANTA_MOVEL WITH(NOLOCK)) B ON A.UF = B.UF AND A.SITE = B.SIGLA_SITE AND A.CN = B.CN
    WHERE YEAR(DATA_REFERENCIA) = @ANO AND MONTH(DATA_REFERENCIA) = @MES AND A.UF = 'SP' AND B.CN IN (16,17)
) C
GROUP BY ANO, MES, UF, CN
ORDER BY ANO, MES, CN

-- ===============================================================
-- DISP DIARIA SP POR CN - QUERY PARA EMAIL
-- ===============================================================
DECLARE @ANO INT = (SELECT CASE WHEN YEAR(GETDATE()) = YEAR(GETDATE()-1) THEN YEAR(GETDATE()) ELSE YEAR(GETDATE()-1) END) 
DECLARE @MES INT = (SELECT CASE WHEN MONTH(GETDATE()) = MONTH(GETDATE()-1) THEN MONTH(GETDATE()) ELSE MONTH(GETDATE()-1) END) 

SELECT
CONCAT('<tr><td>', ANO, '</td>') AS ANO,
CONCAT('<td>', MES, '</td>') AS MES,
CONCAT('<td style="font-weight: bold; background-color: #ced6db">', DIA, '</td>') AS DIA,
CONCAT('<td>', UF, '</td>') AS UF,
CONCAT('<td style="font-weight: bold; background-color: #ced6db">', CN, '</td>') AS CN,
CONCAT('<td style="color: ', CASE WHEN DISP_3G < 99 THEN 'red;; background-color: #e1e1e1">' ELSE 'green;; background-color: #e1e1e1">' END, DISP_3G, '%</td>')  AS DISP_3G,
CONCAT('<td style="color: ', CASE WHEN DISP_4G < 99 THEN 'red;; background-color: #e1e1e1">' ELSE 'green;; background-color: #e1e1e1">' END, DISP_4G, '%</td>')  AS DISP_4G,
CONCAT('<td style="color: ', CASE WHEN DISP_5G < 99 THEN 'red;; background-color: #e1e1e1">' ELSE 'green;; background-color: #e1e1e1">' END, DISP_5G, '%</td>')  AS DISP_5G,
CONCAT('<td style="color: ', CASE WHEN DISP_GERAL < 99 THEN 'red;; background-color: #e1e1e1">' ELSE 'green;; background-color: #e1e1e1">' END, DISP_GERAL, '%</td>')  AS DISP_GERAL,
CONCAT('<td style="color: ', CASE WHEN DISP_4G_5G < 99 THEN 'red;; background-color: #e1e1e1">' ELSE 'green;; background-color: #e1e1e1">' END, DISP_4G_5G, '%</td>')  AS DISP_4G_5G
FROM (

    SELECT
        ANO,
        MES,
        DIA,
        UF,
        CN,
        ROUND(((1-(SUM(CASE WHEN TECNOLOGIA = 'WCDMA' AND TEMPO_CONTADOR_HMM >= 0 THEN TEMPO_CONTADOR_HMM END)/(SUM(CASE WHEN TECNOLOGIA = 'WCDMA' THEN COLETAS_HMM END)*60)))*100),2) AS DISP_3G,
        ROUND(((1-(SUM(CASE WHEN TECNOLOGIA = 'LTE' AND TEMPO_CONTADOR_HMM >= 0 THEN TEMPO_CONTADOR_HMM END)/(SUM(CASE WHEN TECNOLOGIA = 'LTE' THEN COLETAS_HMM END)*60)))*100),2) AS DISP_4G,
        ROUND(((1-(SUM(CASE WHEN TECNOLOGIA = '5G' AND TEMPO_CONTADOR_HMM >= 0 THEN TEMPO_CONTADOR_HMM END)/(SUM(CASE WHEN TECNOLOGIA = '5G' THEN COLETAS_HMM END)*60)))*100),2) AS DISP_5G,
        ROUND(((1-(SUM(CASE WHEN TECNOLOGIA <> 'GSM' AND TEMPO_CONTADOR_HMM >= 0 THEN TEMPO_CONTADOR_HMM END)/(SUM(CASE WHEN TECNOLOGIA <> 'GSM' THEN COLETAS_HMM END)*60)))*100),2) AS DISP_GERAL,
        ROUND(((1-(SUM(CASE WHEN TECNOLOGIA IN ('LTE','5G') AND TEMPO_CONTADOR_HMM >= 0 THEN TEMPO_CONTADOR_HMM END)/(SUM(CASE WHEN TECNOLOGIA IN ('LTE','5G') THEN COLETAS_HMM END)*60)))*100),2) AS DISP_4G_5G,
        ROW_NUMBER() OVER (ORDER BY DIA) AS NL
    FROM (
        SELECT
            YEAR(DATA_REFERENCIA) AS ANO,
            MONTH(DATA_REFERENCIA) AS MES,
            CAST(DAY(DATA_REFERENCIA) AS INT) AS DIA,
            A.TECNOLOGIA,
            A.UF,
            B.CN,
            CAST(TEMPO_CONTADOR_HMM AS FLOAT) AS TEMPO_CONTADOR_HMM,
            CAST(COLETAS_HMM AS FLOAT) AS COLETAS_HMM
        FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES A WITH(NOLOCK)
        LEFT JOIN (SELECT DISTINCT UF, CN, SIGLA_SITE FROM SISTEMA_MAESTRO.dbo.TBA_PLANTA_MOVEL WITH(NOLOCK)) B ON A.UF = B.UF AND A.SITE = B.SIGLA_SITE AND A.CN = B.CN
        WHERE YEAR(DATA_REFERENCIA) = 2024 AND MONTH(DATA_REFERENCIA) = 6 AND A.UF = 'SP' AND B.CN IN (16,17)
    ) C
    GROUP BY ANO, MES, DIA, UF, CN
) D
ORDER BY ANO, MES, NL DESC, CN


-- ===============================================================
-- DISP MENSAL SP POR CN - QUERY PARA EMAIL
-- ===============================================================
DECLARE @ANO INT = (SELECT CASE WHEN YEAR(GETDATE()) = YEAR(GETDATE()-1) THEN YEAR(GETDATE()) ELSE YEAR(GETDATE()-1) END) 
DECLARE @MES INT = (SELECT CASE WHEN MONTH(GETDATE()) = MONTH(GETDATE()-1) THEN MONTH(GETDATE()) ELSE MONTH(GETDATE()-1) END) 

SELECT
        CONCAT('<tr><td>', ANO, '</td>') AS ANO,
        CONCAT('<td>', MES, '</td>') AS MES, 
        CONCAT('<td>', UF, '</td>') AS UF,
        CONCAT('<td style="font-weight: bold; background-color: #ced6db">', CN, '</td>') AS CN,
        CONCAT('<td style="color: ', CASE WHEN DISP_3G < 99 THEN 'red;; background-color: #e1e1e1">' ELSE 'green;; background-color: #e1e1e1">' END, DISP_3G, '%</td>')  AS DISP_3G,
        CONCAT('<td style="color: ', CASE WHEN DISP_4G < 99 THEN 'red;; background-color: #e1e1e1">' ELSE 'green;; background-color: #e1e1e1">' END, DISP_4G, '%</td>')  AS DISP_4G,
        CONCAT('<td style="color: ', CASE WHEN DISP_5G < 99 THEN 'red;; background-color: #e1e1e1">' ELSE 'green;; background-color: #e1e1e1">' END, DISP_5G, '%</td>')  AS DISP_5G,
        CONCAT('<td style="color: ', CASE WHEN DISP_GERAL < 99 THEN 'red;; background-color: #e1e1e1">' ELSE 'green;; background-color: #e1e1e1">' END, DISP_GERAL, '%</td>')  AS DISP_GERAL,
        CONCAT('<td style="color: ', CASE WHEN DISP_4G_5G < 99 THEN 'red;; background-color: #e1e1e1">' ELSE 'green;; background-color: #e1e1e1">' END, DISP_4G_5G, '%</td>')  AS DISP_4G_5G
FROM (

    SELECT
        ANO,
        MES, 
        UF,
        CN,
        -- COUNT(DISTINCT SITE) AS QTDE_SITES, 
        ROUND(((1-(SUM(CASE WHEN TECNOLOGIA = 'WCDMA' AND TEMPO_CONTADOR_HMM >= 0 THEN TEMPO_CONTADOR_HMM END)/(SUM(CASE WHEN TECNOLOGIA = 'WCDMA' THEN COLETAS_HMM END)*60)))*100),2) AS DISP_3G,
        ROUND(((1-(SUM(CASE WHEN TECNOLOGIA = 'LTE' AND TEMPO_CONTADOR_HMM >= 0 THEN TEMPO_CONTADOR_HMM END)/(SUM(CASE WHEN TECNOLOGIA = 'LTE' THEN COLETAS_HMM END)*60)))*100),2) AS DISP_4G,
        ROUND(((1-(SUM(CASE WHEN TECNOLOGIA = '5G' AND TEMPO_CONTADOR_HMM >= 0 THEN TEMPO_CONTADOR_HMM END)/(SUM(CASE WHEN TECNOLOGIA = '5G' THEN COLETAS_HMM END)*60)))*100),2) AS DISP_5G,
        ROUND(((1-(SUM(CASE WHEN TECNOLOGIA <> 'GSM' AND TEMPO_CONTADOR_HMM >= 0 THEN TEMPO_CONTADOR_HMM END)/(SUM(CASE WHEN TECNOLOGIA <> 'GSM' THEN COLETAS_HMM END)*60)))*100),2) AS DISP_GERAL,
        ROUND(((1-(SUM(CASE WHEN TECNOLOGIA IN ('LTE','5G') AND TEMPO_CONTADOR_HMM >= 0 THEN TEMPO_CONTADOR_HMM END)/(SUM(CASE WHEN TECNOLOGIA IN ('LTE','5G') THEN COLETAS_HMM END)*60)))*100),2) AS DISP_4G_5G
        
    FROM (
        SELECT
            YEAR(DATA_REFERENCIA) AS ANO,
            MONTH(DATA_REFERENCIA) AS MES,
            A.TECNOLOGIA,
            A.UF,
            B.CN,
            CAST(TEMPO_CONTADOR_HMM AS FLOAT) AS TEMPO_CONTADOR_HMM,
            CAST(COLETAS_HMM AS FLOAT) AS COLETAS_HMM
            -- A.SITE
        FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES A WITH(NOLOCK)
        LEFT JOIN (SELECT DISTINCT UF, CN, SIGLA_SITE FROM SISTEMA_MAESTRO.dbo.TBA_PLANTA_MOVEL WITH(NOLOCK)) B ON A.UF = B.UF AND A.SITE = B.SIGLA_SITE AND A.CN = B.CN
        WHERE YEAR(DATA_REFERENCIA) = @ANO AND MONTH(DATA_REFERENCIA) = @MES AND A.UF = 'SP' AND B.CN IN (16)
    ) C
    GROUP BY ANO, MES, UF, CN
) D
ORDER BY ANO, MES, CN

