-- *************************************************
-- CAPITAIS - ESTUDO QUEDA NA DISPONIBILIDADE
-- *************************************************

-- ===================================
-- DISPONIBILIDADE
-- ===================================
SELECT
*
FROM (
    SELECT
        ANO,
        MES,
        A.UF,
        A.MUNICIPIO,
        PLANTA_GERAL AS PLANTA,
        AVG(PLANTA_GERAL) OVER (PARTITION BY A.UF, A.MUNICIPIO ORDER BY ANO, MES ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS MM_PLANTA,
        -- MINUTOS_GERAL AS TEMPO,
        -- AVG(MINUTOS_GERAL) OVER (PARTITION BY A.UF, A.MUNICIPIO ORDER BY ANO, MES ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS MM_TEMPO,
        DISPONIBILIDADE_GERAL AS DISP,
        ROUND(AVG(DISPONIBILIDADE_GERAL) OVER (PARTITION BY A.UF, A.MUNICIPIO ORDER BY ANO, MES ROWS BETWEEN 2 PRECEDING AND CURRENT ROW),2) AS MM_DISP,
        PLANTA_3G AS PLANTA_3G,
        AVG(PLANTA_3G) OVER (PARTITION BY A.UF, A.MUNICIPIO ORDER BY ANO, MES ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS MM_PLANTA_3G,
        DISPONIBILIDADE_3G AS DISP_3G,
        ROUND(AVG(DISPONIBILIDADE_3G) OVER (PARTITION BY A.UF, A.MUNICIPIO ORDER BY ANO, MES ROWS BETWEEN 2 PRECEDING AND CURRENT ROW),2) AS MM_DISP_3G,
        PLANTA_4G AS PLANTA_4G,
        AVG(PLANTA_4G) OVER (PARTITION BY A.UF, A.MUNICIPIO ORDER BY ANO, MES ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS MM_PLANTA_4G,
        DISPONIBILIDADE_4G AS DISP_4G,
        ROUND(AVG(DISPONIBILIDADE_4G) OVER (PARTITION BY A.UF, A.MUNICIPIO ORDER BY ANO, MES ROWS BETWEEN 2 PRECEDING AND CURRENT ROW),2) AS MM_DISP_4G,
        PLANTA_5G AS PLANTA_5G,
        AVG(PLANTA_5G) OVER (PARTITION BY A.UF, A.MUNICIPIO ORDER BY ANO, MES ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS MM_PLANTA_5G,
        DISPONIBILIDADE_5G AS DISP_5G,
        ROUND(AVG(DISPONIBILIDADE_4G) OVER (PARTITION BY A.UF, A.MUNICIPIO ORDER BY ANO, MES ROWS BETWEEN 2 PRECEDING AND CURRENT ROW),2) AS MM_DISP_5G,
        CASE WHEN B.MUNICIPIO IS NOT NULL THEN 1 ELSE 0 END FLG_CAPITAL,
        CASE WHEN ANO = 2024 AND MES = 6 THEN 1 ELSE 0 END FLG_EXP
    FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_MENSAL_MUNICIPIO_HMM A
    LEFT JOIN INDICADORES_CORAN..TBA_CAPITAIS B ON A.UF = B.UF AND A.MUNICIPIO = B.MUNICIPIO
    WHERE ANO IN (2023,2024) AND A.DISPONIBILIDADE_GERAL IS NOT NULL
    -- ORDER BY A.UF, A.MUNICIPIO, ANO, MES
) C WHERE FLG_CAPITAL = 1
ORDER BY UF, MUNICIPIO, ANO, MES
-- =================================================
-- EVENTOS
-- =================================================
SELECT
    A.PERIODO,
    A.ANO,
    A.MES,
    B.INDICADOR,
    C.PLANTA,
    A.EVENTO,
    A.REGIONAL,
    A.UF,
    A.MUNICIPIO,
    A.SITE,
    A.TIPO_TA,
    A.TIPO_ALARME,
    A.DATA_CRIACAO,
    A.DATA_ENCERRAMENTO,
    D.TIPO_PAGAMENTO
FROM AVALIACAO_CAMPO..TAS_FORA A WITH(NOLOCK)
LEFT JOIN AVALIACAO_CAMPO..INDICADOR B WITH(NOLOCK) ON A.ID_INDICADOR = B.ID
LEFT JOIN AVALIACAO_CAMPO..PLANTA C WITH(NOLOCK) ON A.ID_PLANTA = C.ID
LEFT JOIN AVALIACAO_CAMPO..TBA_TIPO_PAGAMENTO D WITH(NOLOCK) ON A.ID_TIPO_PAGAMENTO = D.ID_TIPO_PAGAMENTO
INNER JOIN INDICADORES_CORAN..TBA_CAPITAIS E ON A.MUNICIPIO COLLATE Latin1_General_CI_AI = E.MUNICIPIO COLLATE Latin1_General_CI_AI
WHERE ANO IN (2024) AND A.ID_TIPO_PAGAMENTO = 1
ORDER BY ANO, MES
-- *********************************************************************

SELECT
    A.PERIODO,
    A.ANO,
    A.MES,
    A.MUNICIPIO,
    COUNT(*) AS QTDE_EVENTOS
FROM AVALIACAO_CAMPO..TAS_FORA A WITH(NOLOCK)
LEFT JOIN AVALIACAO_CAMPO..INDICADOR B WITH(NOLOCK) ON A.ID_INDICADOR = B.ID
LEFT JOIN AVALIACAO_CAMPO..PLANTA C WITH(NOLOCK) ON A.ID_PLANTA = C.ID
LEFT JOIN AVALIACAO_CAMPO..TBA_TIPO_PAGAMENTO D WITH(NOLOCK) ON A.ID_TIPO_PAGAMENTO = D.ID_TIPO_PAGAMENTO
INNER JOIN INDICADORES_CORAN..TBA_CAPITAIS E WITH(NOLOCK) ON A.MUNICIPIO COLLATE Latin1_General_CI_AI = E.MUNICIPIO COLLATE Latin1_General_CI_AI
WHERE ANO IN (2023,2024) AND A.ID_TIPO_PAGAMENTO = 1
GROUP BY A.PERIODO, A.ANO, A.MES, A.MUNICIPIO
ORDER BY ANO, MES, MUNICIPIO


SELECT
*
FROM (
    SELECT
    ANO,
    MES,
    A.UF,
    A.MUNICIPIO,
    PLANTA_GERAL AS PLANTA,
    AVG(PLANTA_GERAL) OVER (PARTITION BY A.UF, A.MUNICIPIO ORDER BY ANO, MES ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS MM_PLANTA,
    -- MINUTOS_GERAL AS TEMPO,
    -- AVG(MINUTOS_GERAL) OVER (PARTITION BY A.UF, A.MUNICIPIO ORDER BY ANO, MES ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS MM_TEMPO,
    DISPONIBILIDADE_GERAL AS DISP,
    ROUND(AVG(DISPONIBILIDADE_GERAL) OVER (PARTITION BY A.UF, A.MUNICIPIO ORDER BY ANO, MES ROWS BETWEEN 2 PRECEDING AND CURRENT ROW),2) AS MM_DISP,
    DISPONIBILIDADE_3G AS DISP_3G,
    ROUND(AVG(DISPONIBILIDADE_3G) OVER (PARTITION BY A.UF, A.MUNICIPIO ORDER BY ANO, MES ROWS BETWEEN 2 PRECEDING AND CURRENT ROW),2) AS MM_DISP_3G,
    DISPONIBILIDADE_4G AS DISP_4G,
    ROUND(AVG(DISPONIBILIDADE_4G) OVER (PARTITION BY A.UF, A.MUNICIPIO ORDER BY ANO, MES ROWS BETWEEN 2 PRECEDING AND CURRENT ROW),2) AS MM_DISP_4G,
    CASE WHEN B.MUNICIPIO IS NOT NULL THEN 1 ELSE 0 END FLG_CAPITAL,
    CASE WHEN ANO = 2024 AND MES = 6 THEN 1 ELSE 0 END FLG_EXP
FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_MENSAL_MUNICIPIO_HMM A
LEFT JOIN INDICADORES_CORAN..TBA_CAPITAIS B ON A.UF = B.UF AND A.MUNICIPIO = B.MUNICIPIO
WHERE YEAR(A.DATA_REFERENCIA) IN (2023,2024) AND A.DISPONIBILIDADE_GERAL IS NOT NULL
-- ORDER BY A.UF, A.MUNICIPIO, ANO, MES
) B
WHERE FLG_CAPITAL = 1 AND ANO = 2024 AND FLG_EXP = 0

-- ==================================================================================

WITH TEMP AS (
SELECT
C.*,
CASE WHEN MUNICIPIO = 'RIO BRANCO' AND ANO = 2024 AND MES = 2 THEN 1
WHEN MUNICIPIO = 'MACEIÓ' AND ANO = 2024 AND MES = 1 THEN 1
WHEN MUNICIPIO = 'MANAUS' AND ANO = 2023 AND MES = 12 THEN 1
WHEN MUNICIPIO = 'MACAPÁ' AND ANO = 2024 AND MES = 3 THEN 1
WHEN MUNICIPIO = 'SALVADOR' AND ANO = 2023 AND MES = 12 THEN 1
WHEN MUNICIPIO = 'FORTALEZA' AND ANO = 2023 AND MES = 12 THEN 1
WHEN MUNICIPIO = 'BRASÍLIA' AND ANO = 2023 AND MES = 12 THEN 1
WHEN MUNICIPIO = 'VITÓRIA' AND ANO = 2023 AND MES = 12 THEN 1
WHEN MUNICIPIO = 'GOIÂNIA' AND ANO = 2023 AND MES = 12 THEN 1
WHEN MUNICIPIO = 'SÃO LUÍS' AND ANO = 2023 AND MES = 12 THEN 1
WHEN MUNICIPIO = 'BELO HORIZONTE' AND ANO = 2023 AND MES = 12 THEN 1
WHEN MUNICIPIO = 'CAMPO GRANDE' AND ANO = 2023 AND MES = 12 THEN 1
WHEN MUNICIPIO = 'CUIABÁ' AND ANO = 2023 AND MES = 12 THEN 1
WHEN MUNICIPIO = 'BELÉM' AND ANO = 2023 AND MES = 12 THEN 1
WHEN MUNICIPIO = 'JOÃO PESSOA' AND ANO = 2023 AND MES = 12 THEN 1
WHEN MUNICIPIO = 'RECIFE' AND ANO = 2023 AND MES = 12 THEN 1
WHEN MUNICIPIO = 'TERESINA' AND ANO = 2023 AND MES = 12 THEN 1
WHEN MUNICIPIO = 'CURITIBA' AND ANO = 2023 AND MES = 12 THEN 1
WHEN MUNICIPIO = 'RIO DE JANEIRO' AND ANO = 2023 AND MES = 12 THEN 1
WHEN MUNICIPIO = 'NATAL' AND ANO = 2023 AND MES = 12 THEN 1
WHEN MUNICIPIO = 'PORTO VELHO' AND ANO = 2024 AND MES = 3 THEN 1
WHEN MUNICIPIO = 'BOA VISTA' AND ANO = 2024 AND MES = 3 THEN 1
WHEN MUNICIPIO = 'PORTO ALEGRE' AND ANO = 2023 AND MES = 12 THEN 1
WHEN MUNICIPIO = 'FLORIANÓPOLIS' AND ANO = 2023 AND MES = 12 THEN 1
WHEN MUNICIPIO = 'ARACAJU' AND ANO = 2024 AND MES = 1 THEN 1
WHEN MUNICIPIO = 'SÃO PAULO' AND ANO = 2023 AND MES = 12 THEN 1
WHEN MUNICIPIO = 'PALMAS' AND ANO = 2023 AND MES = 12 THEN 1
ELSE 0
END FLG_ESTRUTURANTES
FROM (
    SELECT
        ANO,
        MES,
        A.UF,
        A.MUNICIPIO,
        PLANTA_GERAL AS PLANTA,
        AVG(PLANTA_GERAL) OVER (PARTITION BY A.UF, A.MUNICIPIO ORDER BY ANO, MES ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS MM_PLANTA,
        -- MINUTOS_GERAL AS TEMPO,
        -- AVG(MINUTOS_GERAL) OVER (PARTITION BY A.UF, A.MUNICIPIO ORDER BY ANO, MES ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS MM_TEMPO,
        DISPONIBILIDADE_GERAL AS DISP,
        -- ROUND(AVG(DISPONIBILIDADE_GERAL) OVER (PARTITION BY A.UF, A.MUNICIPIO ORDER BY ANO, MES ROWS BETWEEN 2 PRECEDING AND CURRENT ROW),2) AS MM_DISP,
        -- PLANTA_3G AS PLANTA_3G,
        -- AVG(PLANTA_3G) OVER (PARTITION BY A.UF, A.MUNICIPIO ORDER BY ANO, MES ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS MM_PLANTA_3G,
        -- DISPONIBILIDADE_3G AS DISP_3G,
        -- ROUND(AVG(DISPONIBILIDADE_3G) OVER (PARTITION BY A.UF, A.MUNICIPIO ORDER BY ANO, MES ROWS BETWEEN 2 PRECEDING AND CURRENT ROW),2) AS MM_DISP_3G,
        -- PLANTA_4G AS PLANTA_4G,
        -- AVG(PLANTA_4G) OVER (PARTITION BY A.UF, A.MUNICIPIO ORDER BY ANO, MES ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS MM_PLANTA_4G,
        -- DISPONIBILIDADE_4G AS DISP_4G,
        -- ROUND(AVG(DISPONIBILIDADE_4G) OVER (PARTITION BY A.UF, A.MUNICIPIO ORDER BY ANO, MES ROWS BETWEEN 2 PRECEDING AND CURRENT ROW),2) AS MM_DISP_4G,
        -- PLANTA_5G AS PLANTA_5G,
        -- AVG(PLANTA_5G) OVER (PARTITION BY A.UF, A.MUNICIPIO ORDER BY ANO, MES ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS MM_PLANTA_5G,
        -- DISPONIBILIDADE_5G AS DISP_5G,
        -- ROUND(AVG(DISPONIBILIDADE_4G) OVER (PARTITION BY A.UF, A.MUNICIPIO ORDER BY ANO, MES ROWS BETWEEN 2 PRECEDING AND CURRENT ROW),2) AS MM_DISP_5G,
        CASE WHEN B.MUNICIPIO IS NOT NULL THEN 1 ELSE 0 END FLG_CAPITAL,
        CASE WHEN ANO = 2024 AND MES = 6 THEN 1 ELSE 0 END FLG_EXP
    FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_MENSAL_MUNICIPIO_HMM A
    LEFT JOIN INDICADORES_CORAN..TBA_CAPITAIS B ON A.UF = B.UF AND A.MUNICIPIO = B.MUNICIPIO
    WHERE ANO IN (2023,2024) AND A.DISPONIBILIDADE_GERAL IS NOT NULL
    -- ORDER BY A.UF, A.MUNICIPIO, ANO, MES
) C WHERE FLG_CAPITAL = 1 -- AND MUNICIPIO IN ('SALVADOR','SÃO PAULO')
-- ORDER BY UF, MUNICIPIO, ANO, MES
)
SELECT
*
FROM (
SELECT
TEMP.*,
CASE WHEN FLG_ESTRUTURANTES = 1 THEN ROUND(AVG(DISP) OVER (PARTITION BY UF, MUNICIPIO ORDER BY ANO, MES ROWS BETWEEN 3 PRECEDING AND 1 PRECEDING),2) END AS ANTES,
CASE WHEN FLG_ESTRUTURANTES = 1 THEN ROUND(AVG(DISP) OVER (PARTITION BY UF, MUNICIPIO ORDER BY ANO, MES ROWS BETWEEN 1 FOLLOWING AND 3 FOLLOWING),2) END AS DEPOIS
FROM TEMP
) A
WHERE ANTES IS NOT NULL

