SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VW_DISP_MENSAL_PROGRESSIVA_TOP50_HMM] AS 
--DISPONIBILIDADE MENSAL PROGRESSIVA - MUNICIPIOS TOP50

WITH DATAS AS (
SELECT 
    MAX(DATA_REFERENCIA) AS DT_MAX, 
    YEAR(MAX(DATA_REFERENCIA)) AS ANO, 
    MONTH(MAX(DATA_REFERENCIA)) AS MES 
FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES WITH(NOLOCK)

),

DISP AS (
SELECT      
        YEAR(DATA_REFERENCIA) AS ANO,
        MONTH(DATA_REFERENCIA) AS MES,
        DAY(DATA_REFERENCIA) AS DIA,
        CASE WHEN A.UF = 'SP' THEN B.NOME_REGIONAL
            WHEN A.UF IN ('BA', 'SE', 'AL', 'RN', 'PB', 'CE', 'PI', 'PE') THEN 'NE' 
            WHEN A.UF = 'MG' THEN 'MG'
            WHEN A.UF IN ('RJ', 'ES') THEN 'RJ/ES'
            WHEN A.UF IN ('PR', 'SC', 'RS') THEN 'SUL'
            WHEN A.UF IN ('AM', 'PA', 'MA', 'AP', 'RR') THEN 'NO'
            WHEN A.UF IN ('AC', 'MS', 'MT', 'RO', 'DF', 'GO', 'TO') THEN 'CO'
        END REGIONAL,
        A.UF,
        A.MUNICIPIO,
        SITE,
        ERB,
        SETOR,
        TECNOLOGIA,
        COLETAS_HMM,
        TEMPO_CONTADOR_HMM
FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES A WITH(NOLOCK)
INNER JOIN DATAS ON YEAR(A.DATA_REFERENCIA) = DATAS.ANO AND MONTH(A.DATA_REFERENCIA) = DATAS.MES
LEFT JOIN INDICADORES_CORAN..TBA_DIVISAO_MUNICIPIOS_SP_FIXA B ON A.MUNICIPIO = B.MUNICIPIO AND A.UF = 'SP'
INNER JOIN INDICADORES_CORAN..TBA_CLASSIFICACAO_MUNICIPIOS C ON A.UF = C.UF AND A.MUNICIPIO = C.MUNICIPIO AND C.CLASSIFICACAO = 'TOP 50'
)

SELECT
'3G+4G+5G' AS TECNOLOGIA,
DATEFROMPARTS(ANO, MES, DIA) AS DATA_REFERENCIA,
ANO,
MES,
DIA,
UF+'_' + MUNICIPIO AS UF_MUNICIPIO,
REGIONAL,
UF,
MUNICIPIO,
ROUND((1-(TEMPO_ACUM / NULLIF((CAST(PLANTA_ACUM AS FLOAT) * DENOMINADOR),0))) * 100, 2) AS DISPONIBILIDADE,
LAG(ROUND((1-(TEMPO_ACUM / NULLIF((CAST(PLANTA_ACUM AS FLOAT) * DENOMINADOR),0))) * 100, 2)) OVER (PARTITION BY UF, MUNICIPIO ORDER BY MES, DIA) AS DISP_ANTERIOR
FROM (
    SELECT
    *,
    COLETAS_ACUM / CAST(PLANTA_ACUM AS FLOAT) * 60 AS DENOMINADOR
    FROM (
        SELECT
        *,
        MAX(PLANTA) OVER (PARTITION BY ANO, MES, UF, MUNICIPIO ORDER BY DIA ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS PLANTA_ACUM,
        SUM(COLETAS) OVER (PARTITION BY ANO, MES, UF, MUNICIPIO ORDER BY DIA ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS COLETAS_ACUM,
        SUM(TEMPO) OVER (PARTITION BY ANO, MES, UF, MUNICIPIO ORDER BY DIA ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS TEMPO_ACUM
        FROM (
            SELECT
            ANO,
            MES,
            DIA,
            REGIONAL,
            UF,
            MUNICIPIO,
            COUNT(DISTINCT CONCAT(UF, SITE, ERB, SETOR)) AS PLANTA,
            ISNULL(SUM(COLETAS_HMM), 0) AS COLETAS,
            SUM(CASE WHEN TEMPO_CONTADOR_HMM >= 0 THEN TEMPO_CONTADOR_HMM ELSE 0 END) TEMPO
            FROM DISP WITH(NOLOCK)
            WHERE TECNOLOGIA <> 'GSM'
            GROUP BY ANO, MES, DIA, REGIONAL, UF, MUNICIPIO
        )A
    )B
)C 

UNION ALL

SELECT
'2G' AS TECNOLOGIA,
DATEFROMPARTS(ANO, MES, DIA) AS DATA_REFERENCIA,
ANO,
MES,
DIA,
REGIONAL+'_'+UF+'_'+MUNICIPIO AS 'REGIONAL/UF/MUNICIPIO',
REGIONAL,
UF,
MUNICIPIO,
ROUND((1-(TEMPO_ACUM / NULLIF((CAST(PLANTA_ACUM AS FLOAT) * DENOMINADOR),0))) * 100, 2) AS DISPONIBILIDADE,
LAG(ROUND((1-(TEMPO_ACUM / NULLIF((CAST(PLANTA_ACUM AS FLOAT) * DENOMINADOR),0))) * 100, 2)) OVER (PARTITION BY UF, MUNICIPIO ORDER BY MES, DIA) AS DISP_ANTERIOR
FROM (
    SELECT
    *,
    COLETAS_ACUM / CAST(PLANTA_ACUM AS FLOAT) * 60 AS DENOMINADOR
    FROM (
        SELECT
        *,
        MAX(PLANTA) OVER (PARTITION BY ANO, MES, UF, MUNICIPIO ORDER BY DIA ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS PLANTA_ACUM,
        SUM(COLETAS) OVER (PARTITION BY ANO, MES, UF, MUNICIPIO ORDER BY DIA ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS COLETAS_ACUM,
        SUM(TEMPO) OVER (PARTITION BY ANO, MES, UF, MUNICIPIO ORDER BY DIA ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS TEMPO_ACUM
        FROM (
            SELECT
            ANO,
            MES,
            DIA,
            REGIONAL,
            UF,
            MUNICIPIO,
            COUNT(DISTINCT CONCAT(UF, SITE, ERB, SETOR)) AS PLANTA,
            ISNULL(SUM(COLETAS_HMM), 0) AS COLETAS,
            SUM(CASE WHEN TEMPO_CONTADOR_HMM >= 0 THEN TEMPO_CONTADOR_HMM ELSE 0 END) TEMPO
            FROM DISP WITH(NOLOCK)
            WHERE TECNOLOGIA = 'GSM'
            GROUP BY ANO, MES, DIA, REGIONAL, UF, MUNICIPIO
        )A
    )B
)C 

UNION ALL

SELECT
'3G' AS TECNOLOGIA,
DATEFROMPARTS(ANO, MES, DIA) AS DATA_REFERENCIA,
ANO,
MES,
DIA,
REGIONAL+'_'+UF+'_'+MUNICIPIO AS 'REGIONAL/UF/MUNICIPIO',
REGIONAL,
UF,
MUNICIPIO,
ROUND((1-(TEMPO_ACUM / NULLIF((CAST(PLANTA_ACUM AS FLOAT) * DENOMINADOR),0))) * 100, 2) AS DISPONIBILIDADE,
LAG(ROUND((1-(TEMPO_ACUM / NULLIF((CAST(PLANTA_ACUM AS FLOAT) * DENOMINADOR),0))) * 100, 2)) OVER (PARTITION BY UF, MUNICIPIO ORDER BY MES, DIA) AS DISP_ANTERIOR
FROM (
    SELECT
    *,
    COLETAS_ACUM / CAST(PLANTA_ACUM AS FLOAT) * 60 AS DENOMINADOR
    FROM (
        SELECT
        *,
        MAX(PLANTA) OVER (PARTITION BY ANO, MES, UF, MUNICIPIO ORDER BY DIA ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS PLANTA_ACUM,
        SUM(COLETAS) OVER (PARTITION BY ANO, MES, UF, MUNICIPIO ORDER BY DIA ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS COLETAS_ACUM,
        SUM(TEMPO) OVER (PARTITION BY ANO, MES, UF, MUNICIPIO ORDER BY DIA ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS TEMPO_ACUM
        FROM (
            SELECT
            ANO,
            MES,
            DIA,
            REGIONAL,
            UF,
            MUNICIPIO,
            COUNT(DISTINCT CONCAT(UF, SITE, ERB, SETOR)) AS PLANTA,
            ISNULL(SUM(COLETAS_HMM), 0) AS COLETAS,
            SUM(CASE WHEN TEMPO_CONTADOR_HMM >= 0 THEN TEMPO_CONTADOR_HMM ELSE 0 END) TEMPO
            FROM DISP WITH(NOLOCK)
            WHERE TECNOLOGIA = 'WCDMA'
            GROUP BY ANO, MES, DIA, REGIONAL, UF, MUNICIPIO
        )A
    )B
)C 

UNION ALL

SELECT
'4G' AS TECNOLOGIA,
DATEFROMPARTS(ANO, MES, DIA) AS DATA_REFERENCIA,
ANO,
MES,
DIA,
REGIONAL+'_'+UF+'_'+MUNICIPIO AS 'REGIONAL/UF/MUNICIPIO',
REGIONAL,
UF,
MUNICIPIO,
ROUND((1-(TEMPO_ACUM / NULLIF((CAST(PLANTA_ACUM AS FLOAT) * DENOMINADOR),0))) * 100, 2) AS DISPONIBILIDADE,
LAG(ROUND((1-(TEMPO_ACUM / NULLIF((CAST(PLANTA_ACUM AS FLOAT) * DENOMINADOR),0))) * 100, 2)) OVER (PARTITION BY UF, MUNICIPIO ORDER BY MES, DIA) AS DISP_ANTERIOR
FROM (
    SELECT
    *,
    COLETAS_ACUM / CAST(PLANTA_ACUM AS FLOAT) * 60 AS DENOMINADOR
    FROM (
        SELECT
        *,
        MAX(PLANTA) OVER (PARTITION BY ANO, MES, UF, MUNICIPIO ORDER BY DIA ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS PLANTA_ACUM,
        SUM(COLETAS) OVER (PARTITION BY ANO, MES, UF, MUNICIPIO ORDER BY DIA ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS COLETAS_ACUM,
        SUM(TEMPO) OVER (PARTITION BY ANO, MES, UF, MUNICIPIO ORDER BY DIA ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS TEMPO_ACUM
        FROM (
            SELECT
            ANO,
            MES,
            DIA,
            REGIONAL,
            UF,
            MUNICIPIO,
            COUNT(DISTINCT CONCAT(UF, SITE, ERB, SETOR)) AS PLANTA,
            ISNULL(SUM(COLETAS_HMM), 0) AS COLETAS,
            SUM(CASE WHEN TEMPO_CONTADOR_HMM >= 0 THEN TEMPO_CONTADOR_HMM ELSE 0 END) TEMPO
            FROM DISP WITH(NOLOCK)
            WHERE TECNOLOGIA = 'LTE'
            GROUP BY ANO, MES, DIA, REGIONAL, UF, MUNICIPIO
        )A
    )B
)C 

UNION ALL

SELECT
'5G' AS TECNOLOGIA,
DATEFROMPARTS(ANO, MES, DIA) AS DATA_REFERENCIA,
ANO,
MES,
DIA,
REGIONAL+'_'+UF+'_'+MUNICIPIO AS 'REGIONAL/UF/MUNICIPIO',
REGIONAL,
UF,
MUNICIPIO,
ROUND((1-(TEMPO_ACUM / NULLIF((CAST(PLANTA_ACUM AS FLOAT) * DENOMINADOR),0))) * 100, 2) AS DISPONIBILIDADE,
LAG(ROUND((1-(TEMPO_ACUM / NULLIF((CAST(PLANTA_ACUM AS FLOAT) * DENOMINADOR),0))) * 100, 2)) OVER (PARTITION BY UF, MUNICIPIO ORDER BY MES, DIA) AS DISP_ANTERIOR
FROM (
    SELECT
    *,
    COLETAS_ACUM / CAST(PLANTA_ACUM AS FLOAT) * 60 AS DENOMINADOR
    FROM (
        SELECT
        *,
        MAX(PLANTA) OVER (PARTITION BY ANO, MES, UF, MUNICIPIO ORDER BY DIA ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS PLANTA_ACUM,
        SUM(COLETAS) OVER (PARTITION BY ANO, MES, UF, MUNICIPIO ORDER BY DIA ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS COLETAS_ACUM,
        SUM(TEMPO) OVER (PARTITION BY ANO, MES, UF, MUNICIPIO ORDER BY DIA ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS TEMPO_ACUM
        FROM (
            SELECT
            ANO,
            MES,
            DIA,
            REGIONAL,
            UF,
            MUNICIPIO,
            COUNT(DISTINCT CONCAT(UF, SITE, ERB, SETOR)) AS PLANTA,
            ISNULL(SUM(COLETAS_HMM), 0) AS COLETAS,
            SUM(CASE WHEN TEMPO_CONTADOR_HMM >= 0 THEN TEMPO_CONTADOR_HMM ELSE 0 END) TEMPO
            FROM DISP WITH(NOLOCK)
            WHERE TECNOLOGIA = '5G'
            GROUP BY ANO, MES, DIA, REGIONAL, UF, MUNICIPIO
        )A
    )B
)C 

UNION ALL

SELECT
'4G+5G' AS TECNOLOGIA,
DATEFROMPARTS(ANO, MES, DIA) AS DATA_REFERENCIA,
ANO,
MES,
DIA,
REGIONAL+'_'+UF+'_'+MUNICIPIO AS 'REGIONAL/UF/MUNICIPIO',
REGIONAL,
UF,
MUNICIPIO,
ROUND((1-(TEMPO_ACUM / NULLIF((CAST(PLANTA_ACUM AS FLOAT) * DENOMINADOR),0))) * 100, 2) AS DISPONIBILIDADE,
LAG(ROUND((1-(TEMPO_ACUM / NULLIF((CAST(PLANTA_ACUM AS FLOAT) * DENOMINADOR),0))) * 100, 2)) OVER (PARTITION BY UF, MUNICIPIO ORDER BY MES, DIA) AS DISP_ANTERIOR
FROM (
    SELECT
    *,
    COLETAS_ACUM / CAST(PLANTA_ACUM AS FLOAT) * 60 AS DENOMINADOR
    FROM (
        SELECT
        *,
        MAX(PLANTA) OVER (PARTITION BY ANO, MES, UF, MUNICIPIO ORDER BY DIA ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS PLANTA_ACUM,
        SUM(COLETAS) OVER (PARTITION BY ANO, MES, UF, MUNICIPIO ORDER BY DIA ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS COLETAS_ACUM,
        SUM(TEMPO) OVER (PARTITION BY ANO, MES, UF, MUNICIPIO ORDER BY DIA ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS TEMPO_ACUM
        FROM (
            SELECT
            ANO,
            MES,
            DIA,
            REGIONAL,
            UF,
            MUNICIPIO,
            COUNT(DISTINCT CONCAT(UF, SITE, ERB, SETOR)) AS PLANTA,
            ISNULL(SUM(COLETAS_HMM), 0) AS COLETAS,
            SUM(CASE WHEN TEMPO_CONTADOR_HMM >= 0 THEN TEMPO_CONTADOR_HMM ELSE 0 END) TEMPO
            FROM DISP WITH(NOLOCK)
            WHERE TECNOLOGIA IN ('LTE','5G')
            GROUP BY ANO, MES, DIA, REGIONAL, UF, MUNICIPIO
        )A
    )B
)C 
GO





