DECLARE @ANO INT = (SELECT CASE WHEN YEAR(GETDATE()) = YEAR(GETDATE()-1) THEN YEAR(GETDATE()) ELSE YEAR(GETDATE()-1) END) 
DECLARE @MES INT = (SELECT CASE WHEN MONTH(GETDATE()) = MONTH(GETDATE()-1) THEN MONTH(GETDATE()) ELSE MONTH(GETDATE()-1) END);

WITH IRT AS (

	SELECT
	DATA_REFERENCIA,	
	DIA,
	UF,
	MUNICIPIO,
	ROUND(PLANTA_AFETADA / CAST(PLANTA AS float) * 100, 2) AS IRT,
	TMA
	FROM (
		SELECT
		DATA_REFERENCIA,
		FORMAT(DATA_REFERENCIA, 'dd/MM/yyyy') AS DIA,
		UF,
		MUNICIPIO,
		COUNT(DISTINCT CONCAT(UF, SITE, ERB, SETOR)) AS PLANTA,
		COUNT(DISTINCT CASE WHEN TEMPO_CONTADOR_HMM > 0 THEN CONCAT(UF, SITE, ERB, SETOR) END) AS PLANTA_AFETADA,
		AVG(CASE WHEN TEMPO_CONTADOR_HMM > 0 THEN TEMPO_CONTADOR_HMM END) AS TMA
		FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES
		WHERE YEAR(DATA_REFERENCIA) = 2024 AND MONTH(DATA_REFERENCIA) = 6 AND TECNOLOGIA <> 'GSM'
		GROUP BY DATA_REFERENCIA, UF, MUNICIPIO
	)A
), IRR AS(

	SELECT
	DATA_REFERENCIA,
	UF,
	MUNICIPIO,
	COUNT(DISTINCT SITE) AS SITES,
	SUM(FLG_REINCIDENTE) AS REINCIDENTES,
	ROUND(SUM(FLG_REINCIDENTE) / NULLIF(CAST(COUNT(DISTINCT SITE) AS FLOAT), 0) * 100, 2) AS IRR,
	ROUND(SUM(FLG_PIORA_REINCIDENTE) / NULLIF(CAST(SUM(FLG_REINCIDENTE) AS FLOAT), 0) * 100, 2) AS IRR_P
	FROM (
		SELECT
		DATA_REFERENCIA,
		UF,
		MUNICIPIO,
		SITE,
		MINUTOS_GERAL AS TEMPO,
		DISPONIBILIDADE_GERAL AS DISP_SITE,
		LAG(MINUTOS_GERAL, 1, NULL) OVER (PARTITION BY UF, MUNICIPIO, SITE ORDER BY DATA_REFERENCIA) AS TEMPO_OLD,
		LAG(DISPONIBILIDADE_GERAL, 1, NULL) OVER (PARTITION BY UF, MUNICIPIO, SITE ORDER BY DATA_REFERENCIA) AS DISP_SITE_OLD,
		CASE WHEN LAG(MINUTOS_GERAL, 1, NULL) OVER (PARTITION BY UF, MUNICIPIO, SITE ORDER BY DATA_REFERENCIA) > 0 THEN 1 ELSE 0 END FLG_REINCIDENTE,
		CASE WHEN LAG(MINUTOS_GERAL, 1, NULL) OVER (PARTITION BY UF, MUNICIPIO, SITE ORDER BY DATA_REFERENCIA) > MINUTOS_GERAL THEN 1 ELSE 0 END FLG_PIORA_REINCIDENTE
		FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_DIARIO_SITE_HMM
		WHERE YEAR(DATA_REFERENCIA) = 2024 AND MONTH(DATA_REFERENCIA) = 6
	)A GROUP BY DATA_REFERENCIA, UF, MUNICIPIO

), DISP_DIA AS (

	SELECT * FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_DIARIO_MUNICIPIO_HMM WHERE YEAR(DATA_REFERENCIA) = 2024 AND MONTH(DATA_REFERENCIA) = 6

), DISP_PROGR AS (

	SELECT
	*,
	ROUND((1-(TEMPO_ACUM / (CAST(PLANTA_ACUM AS float) * DENOMINADOR))) * 100, 2) AS DISP_PROGRESSIVA
	FROM (
		SELECT
		*,
		COLETAS_ACUM / CAST(PLANTA_ACUM AS float) * 60 AS DENOMINADOR
		FROM (
			SELECT
			*,
			MAX(PLANTA) OVER (PARTITION BY UF, MUNICIPIO ORDER BY DATA_REFERENCIA ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS PLANTA_ACUM,
			SUM(COLETAS) OVER (PARTITION BY UF, MUNICIPIO ORDER BY DATA_REFERENCIA ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS COLETAS_ACUM,
			SUM(TEMPO) OVER (PARTITION BY UF, MUNICIPIO ORDER BY DATA_REFERENCIA ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS TEMPO_ACUM
			FROM (
				SELECT
				DATA_REFERENCIA,
				UF,
				MUNICIPIO,
				COUNT(DISTINCT CONCAT(UF, SITE, ERB, SETOR)) AS PLANTA,
				ISNULL(SUM(COLETAS_HMM), 0) AS COLETAS,
				SUM(CASE WHEN TEMPO_CONTADOR_HMM >= 0 THEN TEMPO_CONTADOR_HMM ELSE 0 END) TEMPO
				FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES
				WHERE YEAR(DATA_REFERENCIA) = 2024 AND MONTH(DATA_REFERENCIA) = 6 AND TECNOLOGIA <> 'GSM'
				GROUP BY DATA_REFERENCIA, UF, MUNICIPIO
			)A
		)B
	)C

), PIOR_SITE AS (

	SELECT
	*
	FROM (
		SELECT
		DATA_REFERENCIA,
		UF,
		MUNICIPIO,
		SITE,
		MINUTOS_GERAL,
		ROW_NUMBER() OVER (PARTITION BY DATA_REFERENCIA, UF, MUNICIPIO ORDER BY MINUTOS_GERAL DESC) AS RANK_SITE
		FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_DIARIO_SITE_HMM
		WHERE YEAR(DATA_REFERENCIA) = 2024 AND MONTH(DATA_REFERENCIA) = 6 AND MINUTOS_GERAL > 0
	)A WHERE RANK_SITE = 1

), SHARE_DIA AS (

	SELECT
	*,
	ROUND(TEMPO_DIA / NULLIF(CAST(TEMPO_MUNICIPIO_DIA AS float), 0) * 100, 2) AS SHARE_TEMPO_DIA
	FROM (
		SELECT
		DATA_REFERENCIA,
		UF,
		MUNICIPIO,
		MINUTOS_GERAL AS TEMPO_DIA,
		SUM(MINUTOS_GERAL) OVER (PARTITION BY UF, MUNICIPIO ORDER BY DATA_REFERENCIA ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS TEMPO_MUNICIPIO_DIA
		FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_DIARIO_MUNICIPIO_HMM
		WHERE YEAR(DATA_REFERENCIA) = 2024 AND MONTH(DATA_REFERENCIA) = 6
	)A

)

SELECT
CONCAT('<tr><td style="font-weight: bold; background-color: #ced6db">', IRT.DIA,  '</td>') AS DIA,
CONCAT('<td>', IRT.UF, '</td>') AS UF,
CONCAT('<td>', IRT.MUNICIPIO, '</td>') AS MUNICIPIO,
CONCAT('<td>', IRT.IRT, '</td>') AS IRT,
CONCAT('<td>', IRR.IRR, '</td>') AS IRR,
CONCAT('<td>', IRR.IRR_P, '</td>') AS IRR_P,
CONCAT('<td>', IRT.TMA, '</td>') AS TMA,
CONCAT('<td style="color: ', CASE WHEN DISP_DIA.DISPONIBILIDADE_GERAL < 99 THEN 'red;; background-color: #e1e1e1">' ELSE 'green;; background-color: #e1e1e1">' END, DISP_DIA.DISPONIBILIDADE_GERAL, '%</td>')  AS DISP_DIA,
CONCAT('<td style="color: ', CASE WHEN DISP_PROGR.DISP_PROGRESSIVA < 99 THEN 'red;; background-color: #e1e1e1">' ELSE 'green;; background-color: #e1e1e1">' END, DISP_PROGR.DISP_PROGRESSIVA, '%</td>') AS DISP_PROGRESSIVA,
CONCAT('<td>', FORMAT(SHARE_DIA.TEMPO_DIA,'#,0', 'pt-BR'), '</td>') AS TEMPO_DIA,
CONCAT('<td>', SHARE_DIA.SHARE_TEMPO_DIA, '</td>') AS SHARE_TEMPO_DIA,
CONCAT('<td>', PIOR_SITE.SITE, '</td>') AS PIOR_SITE
FROM IRT
INNER JOIN IRR ON IRT.DATA_REFERENCIA = IRR.DATA_REFERENCIA AND IRT.UF = IRR.UF AND IRT.MUNICIPIO = IRR.MUNICIPIO
INNER JOIN DISP_DIA ON IRT.UF = DISP_DIA.UF AND IRT.MUNICIPIO = DISP_DIA.MUNICIPIO AND IRT.DATA_REFERENCIA = DISP_DIA.DATA_REFERENCIA
INNER JOIN DISP_PROGR ON IRT.UF = DISP_PROGR.UF AND IRT.MUNICIPIO = DISP_PROGR.MUNICIPIO AND IRT.DATA_REFERENCIA = DISP_PROGR.DATA_REFERENCIA
INNER JOIN PIOR_SITE ON IRT.UF = PIOR_SITE.UF AND IRT.MUNICIPIO = PIOR_SITE.MUNICIPIO AND IRT.DATA_REFERENCIA = PIOR_SITE.DATA_REFERENCIA
INNER JOIN SHARE_DIA ON IRT.UF = SHARE_DIA.UF AND IRT.MUNICIPIO = SHARE_DIA.MUNICIPIO AND IRT.DATA_REFERENCIA = SHARE_DIA.DATA_REFERENCIA
WHERE IRT.UF = 'MG' AND IRT.MUNICIPIO = 'BELO HORIZONTE'
ORDER BY DIA



