-- ========================
-- MENSAL
-- ========================
DECLARE @ANO_ATUAL INT = (SELECT CASE WHEN YEAR(GETDATE()) = YEAR(GETDATE()-1) THEN YEAR(GETDATE()) ELSE YEAR(GETDATE()-1) END) 
DECLARE @MES_ATUAL INT = (SELECT CASE WHEN MONTH(GETDATE()) = MONTH(GETDATE()-1) THEN MONTH(GETDATE()) ELSE MONTH(GETDATE()-1) END)

SELECT
    'VIVO' AS REGIONAL,
    ANO,
    MES,
    DISPONIBILIDADE_GERAL AS DISP_GERAL,
    DISPONIBILIDADE_3G AS DISP_3G,
    DISPONIBILIDADE_4G AS DISP_4G,
    DISPONIBILIDADE_5G AS DISP_5G,
    DISPONIBILIDADE_3G_4G AS DISP_3G_4G,
    DISPONIBILIDADE_4G_5G AS DISP_4G_5G
FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_MENSAL_VIVO_HMM
WHERE ANO = @ANO_ATUAL AND MES = @MES_ATUAL

UNION ALL

SELECT
    CASE WHEN UF = 'CAPITAL'  THEN 'SPC' ELSE 'SPI' END REGIONAL,
    ANO,
    MES,
    DISPONIBILIDADE_GERAL AS DISP_GERAL,
    DISPONIBILIDADE_3G AS DISP_3G,
    DISPONIBILIDADE_4G AS DISP_4G,
    DISPONIBILIDADE_5G AS DISP_5G,
    DISPONIBILIDADE_3G_4G AS DISP_3G_4G,
    DISPONIBILIDADE_4G_5G AS DISP_4G_5G
FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_MENSAL_UF_HMM
WHERE REGIONAL = 'SP' AND UF <> 'SP' AND ANO = @ANO_ATUAL AND MES = @MES_ATUAL

UNION ALL

SELECT
    REGIONAL,
    ANO,
    MES,
    DISPONIBILIDADE_GERAL AS DISP_GERAL,
    DISPONIBILIDADE_3G AS DISP_3G,
    DISPONIBILIDADE_4G AS DISP_4G,
    DISPONIBILIDADE_5G AS DISP_5G,
    DISPONIBILIDADE_3G_4G AS DISP_3G_4G,
    DISPONIBILIDADE_4G_5G AS DISP_4G_5G
FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_MENSAL_REGIONAL_HMM
WHERE ANO = @ANO_ATUAL AND MES = @MES_ATUAL


-- ========================
-- SEMANAL
-- ========================
DECLARE @ANO_ATUAL INT = (SELECT CASE WHEN YEAR(GETDATE()) = YEAR(GETDATE()-1) THEN YEAR(GETDATE()) ELSE YEAR(GETDATE()-1) END) 
DECLARE @SEMANA_ATUAL INT = (SELECT CASE WHEN DATEPART(WEEK,GETDATE()) = DATEPART(WEEK,GETDATE()-1) THEN DATEPART(WEEK,GETDATE()) ELSE DATEPART(WEEK,GETDATE()-1) END)

SELECT
    'VIVO' AS REGIONAL,
    ANO,
    SEMANA,
    DISPONIBILIDADE_GERAL AS DISP_GERAL,
    DISPONIBILIDADE_3G AS DISP_3G,
    DISPONIBILIDADE_4G AS DISP_4G,
    DISPONIBILIDADE_5G AS DISP_5G,
    DISPONIBILIDADE_3G_4G AS DISP_3G_4G,
    DISPONIBILIDADE_4G_5G AS DISP_4G_5G
FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_SEMANAL_VIVO_HMM
WHERE ANO = @ANO_ATUAL AND SEMANA = @SEMANA_ATUAL

UNION ALL

SELECT
    CASE WHEN UF = 'CAPITAL'  THEN 'SPC' ELSE 'SPI' END REGIONAL,
    ANO,
    SEMANA,
    DISPONIBILIDADE_GERAL AS DISP_GERAL,
    DISPONIBILIDADE_3G AS DISP_3G,
    DISPONIBILIDADE_4G AS DISP_4G,
    DISPONIBILIDADE_5G AS DISP_5G,
    DISPONIBILIDADE_3G_4G AS DISP_3G_4G,
    DISPONIBILIDADE_4G_5G AS DISP_4G_5G
FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_SEMANAL_UF_HMM
WHERE REGIONAL = 'SP' AND UF <> 'SP' AND @ANO_ATUAL = 2024 AND SEMANA = @SEMANA_ATUAL

UNION ALL

SELECT
    REGIONAL,
    ANO,
    SEMANA,
    DISPONIBILIDADE_GERAL AS DISP_GERAL,
    DISPONIBILIDADE_3G AS DISP_3G,
    DISPONIBILIDADE_4G AS DISP_4G,
    DISPONIBILIDADE_5G AS DISP_5G,
    DISPONIBILIDADE_3G_4G AS DISP_3G_4G,
    DISPONIBILIDADE_4G_5G AS DISP_4G_5G
FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_SEMANAL_REGIONAL_HMM
WHERE @ANO_ATUAL = 2024 AND SEMANA = @SEMANA_ATUAL


-- ========================
-- D-1
-- ========================
DECLARE @ANO_ATUAL INT = (SELECT CASE WHEN YEAR(GETDATE()) = YEAR(GETDATE()-1) THEN YEAR(GETDATE()) ELSE YEAR(GETDATE()-1) END)
DECLARE @MES_ATUAL INT = (SELECT CASE WHEN MONTH(GETDATE()) = MONTH(GETDATE()-1) THEN MONTH(GETDATE()) ELSE MONTH(GETDATE()-1) END)
DECLARE @D_MENOS_1 INT = DATEPART(DAY,GETDATE()-1)

SELECT
    'VIVO' AS REGIONAL,
    ANO,
    MES,
    DIA,
    DISPONIBILIDADE_GERAL AS DISP_GERAL,
    DISPONIBILIDADE_3G AS DISP_3G,
    DISPONIBILIDADE_4G AS DISP_4G,
    DISPONIBILIDADE_5G AS DISP_5G,
    DISPONIBILIDADE_3G_4G AS DISP_3G_4G,
    DISPONIBILIDADE_4G_5G AS DISP_4G_5G
FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_DIARIO_VIVO_HMM A
WHERE ANO = @ANO_ATUAL AND MES = @MES_ATUAL AND DIA = @D_MENOS_1

UNION ALL

SELECT
    CASE WHEN UF = 'CAPITAL'  THEN 'SPC' ELSE 'SPI' END REGIONAL,
    ANO,
    MES,
    DIA,
    DISPONIBILIDADE_GERAL AS DISP_GERAL,
    DISPONIBILIDADE_3G AS DISP_3G,
    DISPONIBILIDADE_4G AS DISP_4G,
    DISPONIBILIDADE_5G AS DISP_5G,
    DISPONIBILIDADE_3G_4G AS DISP_3G_4G,
    DISPONIBILIDADE_4G_5G AS DISP_4G_5G
FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_DIARIO_UF_HMM A
WHERE REGIONAL = 'SP' AND UF <> 'SP' AND ANO = @ANO_ATUAL AND MES = @MES_ATUAL AND DIA = @D_MENOS_1

UNION ALL

SELECT
    REGIONAL,
    ANO,
    MES,
    DIA,
    DISPONIBILIDADE_GERAL AS DISP_GERAL,
    DISPONIBILIDADE_3G AS DISP_3G,
    DISPONIBILIDADE_4G AS DISP_4G,
    DISPONIBILIDADE_5G AS DISP_5G,
    DISPONIBILIDADE_3G_4G AS DISP_3G_4G,
    DISPONIBILIDADE_4G_5G AS DISP_4G_5G
FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_DIARIO_REGIONAL_HMM
WHERE @ANO_ATUAL = 2024 AND MES = @MES_ATUAL AND DIA = @D_MENOS_1 AND REGIONAL <> 'SP'








