-- ===============================================================
-- DISP MENSAL SUL POR GESTAO
-- ===============================================================
DECLARE @ANO INT = (SELECT CASE WHEN YEAR(GETDATE()) = YEAR(GETDATE()-1) THEN YEAR(GETDATE()) ELSE YEAR(GETDATE()-1) END) 
DECLARE @MES INT = (SELECT CASE WHEN MONTH(GETDATE()) = MONTH(GETDATE()-1) THEN MONTH(GETDATE()) ELSE MONTH(GETDATE()-1) END) 

SELECT
    ANO,
    MES, 
    C.GESTAO AS CM,
    ROUND(((1-(SUM(CASE WHEN TECNOLOGIA = 'WCDMA' AND TEMPO_CONTADOR_HMM >= 0 THEN TEMPO_CONTADOR_HMM END)/(SUM(CASE WHEN TECNOLOGIA = 'WCDMA' THEN COLETAS_HMM END)*60)))*100),2) AS DISP_3G,
    ROUND(((1-(SUM(CASE WHEN TECNOLOGIA = 'LTE' AND TEMPO_CONTADOR_HMM >= 0 THEN TEMPO_CONTADOR_HMM END)/(SUM(CASE WHEN TECNOLOGIA = 'LTE' THEN COLETAS_HMM END)*60)))*100),2) AS DISP_4G,
    ROUND(((1-(SUM(CASE WHEN TECNOLOGIA = '5G' AND TEMPO_CONTADOR_HMM >= 0 THEN TEMPO_CONTADOR_HMM END)/(SUM(CASE WHEN TECNOLOGIA = '5G' THEN COLETAS_HMM END)*60)))*100),2) AS DISP_5G,
    ROUND(((1-(SUM(CASE WHEN TECNOLOGIA <> 'GSM' AND TEMPO_CONTADOR_HMM >= 0 THEN TEMPO_CONTADOR_HMM END)/(SUM(CASE WHEN TECNOLOGIA <> 'GSM' THEN COLETAS_HMM END)*60)))*100),2) AS DISP_GERAL,
    ROUND(((1-(SUM(CASE WHEN TECNOLOGIA IN ('LTE','5G') AND TEMPO_CONTADOR_HMM >= 0 THEN TEMPO_CONTADOR_HMM END)/(SUM(CASE WHEN TECNOLOGIA IN ('LTE','5G') THEN COLETAS_HMM END)*60)))*100),2) AS DISP_4G_5G
FROM (
    SELECT
        YEAR(DATA_REFERENCIA) AS ANO,
        MONTH(DATA_REFERENCIA) AS MES,
        TECNOLOGIA,
        A.UF,
        B.GESTAO,
        CAST(TEMPO_CONTADOR_HMM AS FLOAT) AS TEMPO_CONTADOR_HMM,
        CAST(COLETAS_HMM AS FLOAT) AS COLETAS_HMM
    FROM (SELECT * FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES WITH(NOLOCK) UNION ALL SELECT * FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES_HIST_2023 WITH(NOLOCK)) A
    INNER JOIN INDICADORES_CORAN..TBA_DIVISAO_MUNICIPIOS_SUL B WITH(NOLOCK) ON A.UF = B.UF AND A.MUNICIPIO = B.MUNICIPIO
    WHERE YEAR(DATA_REFERENCIA) = 2024 AND MONTH(DATA_REFERENCIA) = 4 AND A.UF IN ('PR','SC','RS')
) C
GROUP BY ANO, MES, C.GESTAO


-- E-MAIL

DECLARE @ANO INT = (SELECT CASE WHEN YEAR(GETDATE()) = YEAR(GETDATE()-1) THEN YEAR(GETDATE()) ELSE YEAR(GETDATE()-1) END) 
DECLARE @MES INT = (SELECT CASE WHEN MONTH(GETDATE()) = MONTH(GETDATE()-1) THEN MONTH(GETDATE()) ELSE MONTH(GETDATE()-1) END) 

SELECT
    CONCAT('<tr><td>', ANO, '</td>') AS ANO,
    CONCAT('<td>', MES, '</td>') AS MES, 
    CONCAT('<td>', UF, '</td>') AS UF,
    CONCAT('<td style="font-weight: bold; background-color: #ced6db">', CM, '</td>') AS CM,
    CONCAT('<td style="color: ', CASE WHEN DISP_3G < 99 THEN 'red;; background-color: #e1e1e1">' ELSE 'green;; background-color: #e1e1e1">' END, DISP_3G, '%</td>') AS DISP_3G,
    CONCAT('<td style="color: ', CASE WHEN DISP_4G < 99 THEN 'red;; background-color: #e1e1e1">' ELSE 'green;; background-color: #e1e1e1">' END, DISP_4G, '%</td>') AS DISP_4G,
    CONCAT('<td style="color: ', CASE WHEN DISP_5G < 99 THEN 'red;; background-color: #e1e1e1">' ELSE 'green;; background-color: #e1e1e1">' END, DISP_5G, '%</td>') AS DISP_5G,
    CONCAT('<td style="color: ', CASE WHEN DISP_GERAL < 99 THEN 'red;; background-color: #e1e1e1">' ELSE 'green;; background-color: #e1e1e1">' END, DISP_GERAL, '%</td>') AS DISP_GERAL,
    CONCAT('<td style="color: ', CASE WHEN DISP_4G_5G < 99 THEN 'red;; background-color: #e1e1e1">' ELSE 'green;; background-color: #e1e1e1">' END, DISP_4G_5G, '%</td>') AS DISP_4G_5G
FROM (
    SELECT
    ANO,
    MES,
    UF, 
    C.GESTAO AS CM,
    ROUND(((1-(SUM(CASE WHEN TECNOLOGIA = 'WCDMA' AND TEMPO_CONTADOR_HMM >= 0 THEN TEMPO_CONTADOR_HMM END)/(SUM(CASE WHEN TECNOLOGIA = 'WCDMA' THEN COLETAS_HMM END)*60)))*100),2) AS DISP_3G,
    ROUND(((1-(SUM(CASE WHEN TECNOLOGIA = 'LTE' AND TEMPO_CONTADOR_HMM >= 0 THEN TEMPO_CONTADOR_HMM END)/(SUM(CASE WHEN TECNOLOGIA = 'LTE' THEN COLETAS_HMM END)*60)))*100),2) AS DISP_4G,
    ROUND(((1-(SUM(CASE WHEN TECNOLOGIA = '5G' AND TEMPO_CONTADOR_HMM >= 0 THEN TEMPO_CONTADOR_HMM END)/(SUM(CASE WHEN TECNOLOGIA = '5G' THEN COLETAS_HMM END)*60)))*100),2) AS DISP_5G,
    ROUND(((1-(SUM(CASE WHEN TECNOLOGIA <> 'GSM' AND TEMPO_CONTADOR_HMM >= 0 THEN TEMPO_CONTADOR_HMM END)/(SUM(CASE WHEN TECNOLOGIA <> 'GSM' THEN COLETAS_HMM END)*60)))*100),2) AS DISP_GERAL,
    ROUND(((1-(SUM(CASE WHEN TECNOLOGIA IN ('LTE','5G') AND TEMPO_CONTADOR_HMM >= 0 THEN TEMPO_CONTADOR_HMM END)/(SUM(CASE WHEN TECNOLOGIA IN ('LTE','5G') THEN COLETAS_HMM END)*60)))*100),2) AS DISP_4G_5G
FROM (
    SELECT
        YEAR(DATA_REFERENCIA) AS ANO,
        MONTH(DATA_REFERENCIA) AS MES,
        TECNOLOGIA,
        A.UF,
        B.GESTAO,
        CAST(TEMPO_CONTADOR_HMM AS FLOAT) AS TEMPO_CONTADOR_HMM,
        CAST(COLETAS_HMM AS FLOAT) AS COLETAS_HMM
    FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES A WITH(NOLOCK)
    INNER JOIN INDICADORES_CORAN..TBA_DIVISAO_MUNICIPIOS_SUL B WITH(NOLOCK) ON A.UF = B.UF AND A.MUNICIPIO = B.MUNICIPIO
    WHERE YEAR(DATA_REFERENCIA) = @ANO AND MONTH(DATA_REFERENCIA) = @MES AND A.UF IN ('PR','SC','RS')
) C
GROUP BY ANO, MES, UF, C.GESTAO

) D


-- ===============================================================
-- DISP MENSAL SUL POR CN
-- ===============================================================
DECLARE @ANO INT = (SELECT CASE WHEN YEAR(GETDATE()) = YEAR(GETDATE()-1) THEN YEAR(GETDATE()) ELSE YEAR(GETDATE()-1) END) 
DECLARE @MES INT = (SELECT CASE WHEN MONTH(GETDATE()) = MONTH(GETDATE()-1) THEN MONTH(GETDATE()) ELSE MONTH(GETDATE()-1) END) 

SELECT
*
FROM (
SELECT
    ANO,
    MES, 
	UF,
    CN,
    ROUND(((1-(SUM(CASE WHEN TECNOLOGIA = 'WCDMA' AND TEMPO_CONTADOR_HMM >= 0 THEN TEMPO_CONTADOR_HMM END)/(SUM(CASE WHEN TECNOLOGIA = 'WCDMA' THEN COLETAS_HMM END)*60)))*100),2) AS DISP_3G,
    ROUND(((1-(SUM(CASE WHEN TECNOLOGIA = 'LTE' AND TEMPO_CONTADOR_HMM >= 0 THEN TEMPO_CONTADOR_HMM END)/(SUM(CASE WHEN TECNOLOGIA = 'LTE' THEN COLETAS_HMM END)*60)))*100),2) AS DISP_4G,
    ROUND(((1-(SUM(CASE WHEN TECNOLOGIA = '5G' AND TEMPO_CONTADOR_HMM >= 0 THEN TEMPO_CONTADOR_HMM END)/(SUM(CASE WHEN TECNOLOGIA = '5G' THEN COLETAS_HMM END)*60)))*100),2) AS DISP_5G,
    ROUND(((1-(SUM(CASE WHEN TECNOLOGIA <> 'GSM' AND TEMPO_CONTADOR_HMM >= 0 THEN TEMPO_CONTADOR_HMM END)/(SUM(CASE WHEN TECNOLOGIA <> 'GSM' THEN COLETAS_HMM END)*60)))*100),2) AS DISP_GERAL,
    ROUND(((1-(SUM(CASE WHEN TECNOLOGIA IN ('LTE','5G') AND TEMPO_CONTADOR_HMM >= 0 THEN TEMPO_CONTADOR_HMM END)/(SUM(CASE WHEN TECNOLOGIA IN ('LTE','5G') THEN COLETAS_HMM END)*60)))*100),2) AS DISP_4G_5G
    
FROM (
    SELECT
        YEAR(DATA_REFERENCIA) AS ANO,
        MONTH(DATA_REFERENCIA) AS MES,
        A.TECNOLOGIA,
        A.UF,
        B.CN,
        CAST(TEMPO_CONTADOR_HMM AS FLOAT) AS TEMPO_CONTADOR_HMM,
        CAST(COLETAS_HMM AS FLOAT) AS COLETAS_HMM
    FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES A WITH(NOLOCK)
    INNER JOIN SISTEMA_MAESTRO..TBA_PLANTA_MOVEL B WITH(NOLOCK) ON A.UF = B.UF AND A.SITE = B.SIGLA_SITE AND A.CN = B.CN
    WHERE YEAR(DATA_REFERENCIA) = @ANO AND MONTH(DATA_REFERENCIA) = @MES AND A.UF IN ('PR','SC','RS')
) C
GROUP BY ANO, MES, UF, CN
) D
WHERE DISP_3G IS NOT NULL AND DISP_4G IS NOT NULL AND DISP_5G IS NOT NULL AND DISP_GERAL IS NOT NULL AND DISP_4G_5G IS NOT NULL





DECLARE @ANO INT = (SELECT CASE WHEN YEAR(GETDATE()) = YEAR(GETDATE()-1) THEN YEAR(GETDATE()) ELSE YEAR(GETDATE()-1) END) 
DECLARE @MES INT = (SELECT CASE WHEN MONTH(GETDATE()) = MONTH(GETDATE()-1) THEN MONTH(GETDATE()) ELSE MONTH(GETDATE()-1) END) 

SELECT
*
FROM (
SELECT
ANO, MES, REGIONAL, UF, CN, DISPONIBILIDADE_2G AS DISP_2G, DISPONIBILIDADE_3G AS DISP_3G, DISPONIBILIDADE_4G AS DISP_4G, DISPONIBILIDADE_GERAL AS DISP_GERAL, DISPONIBILIDADE_5G AS DISP_5G, DISPONIBILIDADE_4G_5G AS DISP_4G_5G
FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_MENSAL_CN_HMM A
WHERE YEAR(DATA_REFERENCIA) = @ANO AND MONTH(DATA_REFERENCIA) = @MES AND A.UF IN ('PR','SC','RS')
) B
WHERE DISP_GERAL IS NOT NULL

-- =======================
-- SEMANAL POR CN
-- ==========================
DECLARE @ANO INT = (SELECT CASE WHEN YEAR(GETDATE()) = YEAR(GETDATE()-1) THEN YEAR(GETDATE()) ELSE YEAR(GETDATE()-1) END) 
DECLARE @MES INT = (SELECT CASE WHEN MONTH(GETDATE()) = MONTH(GETDATE()-1) THEN MONTH(GETDATE()) ELSE MONTH(GETDATE()-1) END)
DECLARE @SEMANA INT = (SELECT CASE WHEN DATEPART(WEEK,GETDATE()) = DATEPART(WEEK,GETDATE()-1) THEN DATEPART(WEEK,GETDATE()) ELSE DATEPART(WEEK,GETDATE()-1) END)

SELECT
*
FROM (
SELECT
ANO, SEMANA, REGIONAL, UF, CN, DISPONIBILIDADE_2G AS DISP_2G, DISPONIBILIDADE_3G AS DISP_3G, DISPONIBILIDADE_4G AS DISP_4G, DISPONIBILIDADE_GERAL AS DISP_GERAL, DISPONIBILIDADE_5G AS DISP_5G, DISPONIBILIDADE_4G_5G AS DISP_4G_5G
FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_SEMANAL_CN_HMM A
WHERE ANO = 2024 -- AND SEMANA = @SEMANA AND A.UF IN ('PR','SC','RS')
) B
WHERE DISP_GERAL IS NOT NULL