--====================================================================================================================
-- DISPONIBILIDADE DIARIA POR UF
--====================================================================================================================
SELECT ANO, 
	   MES, 
	   DIA, 
	   UF,
	   DISPONIBILIDADE_GERAL AS DISP_GERAL,
	   99.00 AS META_DISP
FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_DIARIO_UF_HMM
WHERE DATA_REFERENCIA >= FORMAT(GETDATE()-7, 'yyyy-MM-dd') 
AND DATA_REFERENCIA <= FORMAT(GETDATE()-1, 'yyyy-MM-dd')
AND UF IN ('AL','CE','PB','PE','PI','RN','PR','SC','RS','RJ','ES','CAPITAL') 
ORDER BY MES, DIA, UF

--====================================================================================================================
--DISPONIBILIDADE SEMANAL POR UF
--====================================================================================================================
DECLARE @SEMANA_INICIAL INT = (DATEPART(WEEK,GETDATE()-1)-3)
DECLARE @SEMANA_FINAL INT = DATEPART(WEEK,GETDATE()-1)
DECLARE @ANO INT = DATEPART(YEAR,GETDATE())

SELECT 
				   ANO,
				   SEMANA,
				   REGIONAL,
				   UF,
				   DISPONIBILIDADE_GERAL AS DISP_GERAL,
				   CAST(((SELECT DISPONIBILIDADE_GERAL FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_SEMANAL_UF_HMM WHERE ANO = @ANO AND SEMANA = @SEMANA_FINAL AND UF = 'AL') - (SELECT DISPONIBILIDADE_GERAL FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_SEMANAL_UF_HMM WHERE ANO = @ANO AND SEMANA = @SEMANA_INICIAL AND UF = 'AL')) AS NUMERIC(10,2)) AS EVOLUCAO
			FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_SEMANAL_UF_HMM
			WHERE UF = 'AL' AND ANO = @ANO AND SEMANA >=@SEMANA_INICIAL AND SEMANA<=@SEMANA_FINAL

UNION ALL

SELECT 
				   ANO,
				   SEMANA,
				   REGIONAL,
				   UF,
				   DISPONIBILIDADE_GERAL AS DISP_GERAL,
				   CAST(((SELECT DISPONIBILIDADE_GERAL FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_SEMANAL_UF_HMM WHERE ANO = @ANO AND SEMANA = @SEMANA_FINAL AND UF = 'CE') - (SELECT DISPONIBILIDADE_GERAL FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_SEMANAL_UF_HMM WHERE ANO = @ANO AND SEMANA = @SEMANA_INICIAL AND UF = 'CE')) AS NUMERIC(10,2)) AS EVOLUCAO
			FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_SEMANAL_UF_HMM
			WHERE UF = 'CE' AND ANO = @ANO AND SEMANA >=@SEMANA_INICIAL AND SEMANA<=@SEMANA_FINAL

UNION ALL

SELECT 
				   ANO,
				   SEMANA,
				   REGIONAL,
				   UF,
				   DISPONIBILIDADE_GERAL AS DISP_GERAL,
				   CAST(((SELECT DISPONIBILIDADE_GERAL FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_SEMANAL_UF_HMM WHERE ANO = @ANO AND SEMANA = @SEMANA_FINAL AND UF = 'PA') - (SELECT DISPONIBILIDADE_GERAL FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_SEMANAL_UF_HMM WHERE ANO = @ANO AND SEMANA = @SEMANA_INICIAL AND UF = 'PA')) AS NUMERIC(10,2)) AS EVOLUCAO
			FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_SEMANAL_UF_HMM
			WHERE UF = 'PA' AND ANO = @ANO AND SEMANA >=@SEMANA_INICIAL AND SEMANA<=@SEMANA_FINAL

UNION ALL

SELECT 
				   ANO,
				   SEMANA,
				   REGIONAL,
				   UF,
				   DISPONIBILIDADE_GERAL AS DISP_GERAL,
				   CAST(((SELECT DISPONIBILIDADE_GERAL FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_SEMANAL_UF_HMM WHERE ANO = @ANO AND SEMANA = @SEMANA_FINAL AND UF = 'PB') - (SELECT DISPONIBILIDADE_GERAL FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_SEMANAL_UF_HMM WHERE ANO = @ANO AND SEMANA = @SEMANA_INICIAL AND UF = 'PB')) AS NUMERIC(10,2)) AS EVOLUCAO
			FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_SEMANAL_UF_HMM
			WHERE UF = 'PB' AND ANO = @ANO AND SEMANA >=@SEMANA_INICIAL AND SEMANA<=@SEMANA_FINAL

UNION ALL

SELECT 
				   ANO,
				   SEMANA,
				   REGIONAL,
				   UF,
				   DISPONIBILIDADE_GERAL AS DISP_GERAL,
				   CAST(((SELECT DISPONIBILIDADE_GERAL FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_SEMANAL_UF_HMM WHERE ANO = @ANO AND SEMANA = @SEMANA_FINAL AND UF = 'PE') - (SELECT DISPONIBILIDADE_GERAL FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_SEMANAL_UF_HMM WHERE ANO = @ANO AND SEMANA = @SEMANA_INICIAL AND UF = 'PE')) AS NUMERIC(10,2)) AS EVOLUCAO
			FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_SEMANAL_UF_HMM
			WHERE UF = 'PE' AND ANO = @ANO AND SEMANA >=@SEMANA_INICIAL AND SEMANA<=@SEMANA_FINAL

UNION ALL

SELECT 
				   ANO,
				   SEMANA,
				   REGIONAL,
				   UF,
				   DISPONIBILIDADE_GERAL AS DISP_GERAL,
				   CAST(((SELECT DISPONIBILIDADE_GERAL FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_SEMANAL_UF_HMM WHERE ANO = @ANO AND SEMANA = @SEMANA_FINAL AND UF = 'PI') - (SELECT DISPONIBILIDADE_GERAL FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_SEMANAL_UF_HMM WHERE ANO = @ANO AND SEMANA = @SEMANA_INICIAL AND UF = 'PI')) AS NUMERIC(10,2)) AS EVOLUCAO
			FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_SEMANAL_UF_HMM
			WHERE UF = 'PI' AND ANO = @ANO AND SEMANA >=@SEMANA_INICIAL AND SEMANA<=@SEMANA_FINAL

UNION ALL

SELECT 
				   ANO,
				   SEMANA,
				   REGIONAL,
				   UF,
				   DISPONIBILIDADE_GERAL AS DISP_GERAL,
				   CAST(((SELECT DISPONIBILIDADE_GERAL FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_SEMANAL_UF_HMM WHERE ANO = @ANO AND SEMANA = @SEMANA_FINAL AND UF = 'RN') - (SELECT DISPONIBILIDADE_GERAL FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_SEMANAL_UF_HMM WHERE ANO = @ANO AND SEMANA = @SEMANA_INICIAL AND UF = 'RN')) AS NUMERIC(10,2)) AS EVOLUCAO
			FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_SEMANAL_UF_HMM
			WHERE UF = 'RN' AND ANO = @ANO AND SEMANA >=@SEMANA_INICIAL AND SEMANA<=@SEMANA_FINAL

UNION ALL

SELECT 
				   ANO,
				   SEMANA,
				   REGIONAL,
				   UF,
				   DISPONIBILIDADE_GERAL AS DISP_GERAL,
				   CAST(((SELECT DISPONIBILIDADE_GERAL FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_SEMANAL_UF_HMM WHERE ANO = @ANO AND SEMANA = @SEMANA_FINAL AND UF = 'PR') - (SELECT DISPONIBILIDADE_GERAL FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_SEMANAL_UF_HMM WHERE ANO = @ANO AND SEMANA = @SEMANA_INICIAL AND UF = 'PR')) AS NUMERIC(10,2)) AS EVOLUCAO
			FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_SEMANAL_UF_HMM
			WHERE UF = 'PR' AND ANO = @ANO AND SEMANA >=@SEMANA_INICIAL AND SEMANA<=@SEMANA_FINAL

UNION ALL

SELECT 
				   ANO,
				   SEMANA,
				   REGIONAL,
				   UF,
				   DISPONIBILIDADE_GERAL AS DISP_GERAL,
				   CAST(((SELECT DISPONIBILIDADE_GERAL FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_SEMANAL_UF_HMM WHERE ANO = @ANO AND SEMANA = @SEMANA_FINAL AND UF = 'SC') - (SELECT DISPONIBILIDADE_GERAL FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_SEMANAL_UF_HMM WHERE ANO = @ANO AND SEMANA = @SEMANA_INICIAL AND UF = 'SC')) AS NUMERIC(10,2)) AS EVOLUCAO
			FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_SEMANAL_UF_HMM
			WHERE UF = 'SC' AND ANO = @ANO AND SEMANA >=@SEMANA_INICIAL AND SEMANA<=@SEMANA_FINAL

UNION ALL

SELECT 
				   ANO,
				   SEMANA,
				   REGIONAL,
				   UF,
				   DISPONIBILIDADE_GERAL AS DISP_GERAL,
				   CAST(((SELECT DISPONIBILIDADE_GERAL FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_SEMANAL_UF_HMM WHERE ANO = @ANO AND SEMANA = @SEMANA_FINAL AND UF = 'RS') - (SELECT DISPONIBILIDADE_GERAL FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_SEMANAL_UF_HMM WHERE ANO = @ANO AND SEMANA = @SEMANA_INICIAL AND UF = 'RS')) AS NUMERIC(10,2)) AS EVOLUCAO
			FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_SEMANAL_UF_HMM
			WHERE UF = 'RS' AND ANO = @ANO AND SEMANA >=@SEMANA_INICIAL AND SEMANA<=@SEMANA_FINAL

UNION ALL

SELECT 
				   ANO,
				   SEMANA,
				   REGIONAL,
				   UF,
				   DISPONIBILIDADE_GERAL AS DISP_GERAL,
				   CAST(((SELECT DISPONIBILIDADE_GERAL FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_SEMANAL_UF_HMM WHERE ANO = @ANO AND SEMANA = @SEMANA_FINAL AND UF = 'RJ') - (SELECT DISPONIBILIDADE_GERAL FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_SEMANAL_UF_HMM WHERE ANO = @ANO AND SEMANA = @SEMANA_INICIAL AND UF = 'RJ')) AS NUMERIC(10,2)) AS EVOLUCAO
			FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_SEMANAL_UF_HMM
			WHERE UF = 'RJ' AND ANO = @ANO AND SEMANA >=@SEMANA_INICIAL AND SEMANA<=@SEMANA_FINAL

UNION ALL

SELECT 
				   ANO,
				   SEMANA,
				   REGIONAL,
				   UF,
				   DISPONIBILIDADE_GERAL AS DISP_GERAL,
				   CAST(((SELECT DISPONIBILIDADE_GERAL FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_SEMANAL_UF_HMM WHERE ANO = @ANO AND SEMANA = @SEMANA_FINAL AND UF = 'ES') - (SELECT DISPONIBILIDADE_GERAL FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_SEMANAL_UF_HMM WHERE ANO = @ANO AND SEMANA = @SEMANA_INICIAL AND UF = 'ES')) AS NUMERIC(10,2)) AS EVOLUCAO
			FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_SEMANAL_UF_HMM
			WHERE UF = 'ES' AND ANO = @ANO AND SEMANA >=@SEMANA_INICIAL AND SEMANA<=@SEMANA_FINAL

UNION ALL

SELECT 
				   ANO,
				   SEMANA,
				   REGIONAL,
				   UF,
				   DISPONIBILIDADE_GERAL AS DISP_GERAL,
				   CAST(((SELECT DISPONIBILIDADE_GERAL FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_SEMANAL_UF_HMM WHERE ANO = @ANO AND SEMANA = @SEMANA_FINAL AND UF = 'CAPITAL') - (SELECT DISPONIBILIDADE_GERAL FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_SEMANAL_UF_HMM WHERE ANO = @ANO AND SEMANA = @SEMANA_INICIAL AND UF = 'CAPITAL')) AS NUMERIC(10,2)) AS EVOLUCAO
			FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_SEMANAL_UF_HMM
			WHERE UF = 'CAPITAL' AND ANO = @ANO AND SEMANA >=@SEMANA_INICIAL AND SEMANA<=@SEMANA_FINAL

--========================================================================================================================
--DISPONIBILIDADE SEMANA POR REGIONAL
--========================================================================================================================
DECLARE @SEMANA_INICIAL INT = (DATEPART(WEEK,GETDATE()-1)-3)
DECLARE @SEMANA_FINAL INT = DATEPART(WEEK,GETDATE()-1)
DECLARE @ANO INT = DATEPART(YEAR,GETDATE())
SELECT
	   ANO,
	   SEMANA,
	   REGIONAL,
	   DISPONIBILIDADE_GERAL AS DISP_GERAL
FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_SEMANAL_REGIONAL_HMM
WHERE ANO = @ANO AND REGIONAL IN ('NE','SUL','SP','SUD') AND SEMANA >=@SEMANA_INICIAL AND SEMANA<=@SEMANA_FINAL
ORDER BY ANO, SEMANA, REGIONAL

--================================================================================================================================================================================================================================
--================================================================================================================================================================================================================================
