--DISPONIBILIDADE MENSAL
DECLARE @MES_ATUAL INT = DATEPART(MONTH,GETDATE())
DECLARE @DATA_INICIAL DATE = GETDATE()-11;
DECLARE @DATA_FINAL   DATE = GETDATE()-1;

SELECT
ANO,
MES,
REGIONAL,
UF,
MUNICIPIO,
SUM(MINUTOS_MUNICIPIO) AS MINUTOS,
SUM(MINUTOS_MAX_MUNICIPIO) AS MINUTOS_MAX_MUNICIPIO,
ROUND((1-(CAST(SUM(MINUTOS_MUNICIPIO) AS FLOAT)/CAST(SUM(MINUTOS_MAX_MUNICIPIO) AS FLOAT)))*100,2) AS DISP_MENSAL_MUNICIPIO
FROM
(
		SELECT
				DATEPART(YEAR,DATA_REFERENCIA) AS ANO,
				DATEPART(MONTH,DATA_REFERENCIA) AS MES,
				DATEPART(DAY,DATA_REFERENCIA) AS DIA,
				CASE WHEN REGIONAL = 'MG/RJ/ES' THEN 'SUD'
					 WHEN REGIONAL = 'BA/SE/NE' THEN 'NE'
				ELSE REGIONAL
				END REGIONAL,
				UF,
				MUNICIPIO,
				SUM(TEMPO_CONTADOR_HMM) AS MINUTOS_MUNICIPIO,
				SUM(COLETAS_HMM)*60 AS MINUTOS_MAX_MUNICIPIO
				--ROUND((1-(CAST(SUM(TEMPO_CONTADOR_HMM) AS FLOAT)/CAST(SUM(COLETAS_HMM)*60 AS FLOAT)))*100,2) AS DISP_DIARIA_MUNICIPIO
		FROM 
				SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES
		WHERE 
				TECNOLOGIA <> 'GSM'
				AND TEMPO_CONTADOR_HMM >= 0
				--AND DATA_REFERENCIA BETWEEN @DATA_INICIAL AND @DATA_FINAL
				AND UF = 'SE' AND MUNICIPIO = 'ARACAJU'
		GROUP BY 
				DATA_REFERENCIA,
				REGIONAL,
				UF,
				MUNICIPIO
) A
WHERE MES = DATEPART(MONTH,GETDATE()) AND ANO = DATEPART(YEAR,GETDATE())
GROUP BY
		ANO,
		MES,
		REGIONAL,
		UF,
		MUNICIPIO