SELECT
	ANO,
	MES,
	REGIONAL,
	UF,
	MUNICIPIO,
	SITE,
	TEMPO,
	ROUND((1-(TEMPO_PONDERADO / NULLIF((CAST(PLANTA_TOTAL AS float) * DENOMINADOR), 0))) * 100, 2) AS DISPONIBILIDADE_UF
FROM(
		SELECT
		*,
		TEMPO_TOTAL - TEMPO_ACUM AS TEMPO_PONDERADO,
		COLETAS_TOTAL / PLANTA_TOTAL * 60 AS DENOMINADOR
	FROM (
		SELECT
			*,
			SUM(TEMPO) OVER (PARTITION BY ANO, MES, REGIONAL ORDER BY TEMPO DESC ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS TEMPO_ACUM,
			SUM(TEMPO) OVER (PARTITION BY ANO, MES, REGIONAL ORDER BY TEMPO DESC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS TEMPO_TOTAL,
			SUM(PLANTA) OVER (PARTITION BY ANO, MES, REGIONAL ORDER BY SITE ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS PLANTA_TOTAL,
			SUM(COLETAS) OVER (PARTITION BY ANO, MES, REGIONAL ORDER BY SITE ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS COLETAS_TOTAL
		FROM (
				SELECT
					YEAR(DATA_REFERENCIA) AS ANO,
					MONTH(DATA_REFERENCIA) AS MES,
					REGIONAL,
					UF,
					A.MUNICIPIO,
					SITE,
					COUNT(DISTINCT CONCAT(UF, ERB, SETOR)) AS PLANTA,
					ISNULL(SUM(COLETAS_HMM), 0) AS COLETAS,
					SUM(CASE WHEN TEMPO_CONTADOR_HMM >= 0 THEN TEMPO_CONTADOR_HMM ELSE 0 END) TEMPO
				FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES A
				--INNER JOIN INDICADORES_CORAN..TBA_DIVISAO_MUNICIPIOS_SP_FIXA B ON A.MUNICIPIO = B.MUNICIPIO
				WHERE DATA_REFERENCIA >= '2023-10-01' AND DATA_REFERENCIA < '2023-10-31' AND A.UF = 'RJ' AND TECNOLOGIA <> 'GSM' --AND B.GESTAO = 'INTERIOR'
				GROUP BY YEAR(DATA_REFERENCIA), MONTH(DATA_REFERENCIA), REGIONAL, UF, A.MUNICIPIO, SITE
		)A1
	)A
)B ORDER BY REGIONAL, TEMPO DESC
