DELETE FROM INDICADORES_CORAN.dbo.TBF_CELLDOWNTIME_MENSAL_BAIRROS_HMM WHERE ANO = 2024 AND MES = 10;

WITH PLANTA AS (

	SELECT UF, SIGLA_SITE, BAIRRO, AVG(LAT) AS LAT, AVG(LONG) AS LNG FROM SISTEMA_MAESTRO..TBA_PLANTA_MOVEL GROUP BY UF, SIGLA_SITE, BAIRRO

), SITES_BAIRRO AS (

	SELECT UF, MUNICIPIO, BAIRRO, COUNT(DISTINCT SIGLA_SITE) AS SITES FROM SISTEMA_MAESTRO..TBA_PLANTA_MOVEL GROUP BY UF, MUNICIPIO, BAIRRO

), DISP AS (

	SELECT
	*,
	ROUND((1-(TEMPO / NULLIF((CAST(SETORES AS float) * DENOMINADOR), 0))) * 100, 2) AS DISPONIBILIDADE
	FROM (
		SELECT
		*,
		COLETAS / CAST(SETORES AS float) * 60 AS DENOMINADOR
		FROM (
			SELECT
			A.UF,
			MUNICIPIO,
			P.BAIRRO,
			TECNOLOGIA,
			COUNT(DISTINCT CONCAT(ERB, SETOR)) AS SETORES,
			SUM(COLETAS_HMM) AS COLETAS,
			SUM(CASE WHEN TEMPO_CONTADOR_HMM >= 0 THEN TEMPO_CONTADOR_HMM END) TEMPO
			FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES A with (nolock)
			INNER JOIN PLANTA P ON A.UF = P.UF AND A.SITE = P.SIGLA_SITE
			WHERE DATA_REFERENCIA >= '2024-10-01' AND DATA_REFERENCIA < '2024-11-01'
			GROUP BY A.UF, MUNICIPIO, P.BAIRRO, TECNOLOGIA
			UNION ALL
			SELECT
			A.UF,
			MUNICIPIO,
			P.BAIRRO,
			TECNOLOGIA,
			COUNT(DISTINCT CONCAT(ERB, SETOR)) AS SETORES,
			SUM(COLETAS_HMM) AS COLETAS,
			SUM(CASE WHEN TEMPO_CONTADOR_HMM >= 0 THEN TEMPO_CONTADOR_HMM END) TEMPO
			FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES_HIST_2023 A with (nolock)
			INNER JOIN PLANTA P ON A.UF = P.UF AND A.SITE = P.SIGLA_SITE
			WHERE DATA_REFERENCIA >= '2024-10-01' AND DATA_REFERENCIA < '2024-11-01'
			GROUP BY A.UF, MUNICIPIO, P.BAIRRO, TECNOLOGIA
		)A
	)B

), DISP_GERAL AS (

	SELECT
	*,
	ROUND((1-(TEMPO / NULLIF((CAST(SETORES AS float) * DENOMINADOR), 0))) * 100, 2) AS DISPONIBILIDADE
	FROM (
		SELECT
		*,
		COLETAS / CAST(SETORES AS float) * 60 AS DENOMINADOR
		FROM (
			SELECT
			A.UF,
			MUNICIPIO,
			P.BAIRRO,
			'GERAL' AS TECNOLOGIA,
			COUNT(DISTINCT CONCAT(ERB, SETOR)) AS SETORES,
			SUM(COLETAS_HMM) AS COLETAS,
			SUM(CASE WHEN TEMPO_CONTADOR_HMM >= 0 THEN TEMPO_CONTADOR_HMM END) TEMPO
			FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES A with (nolock)
			INNER JOIN PLANTA P ON A.UF = P.UF AND A.SITE = P.SIGLA_SITE
			WHERE DATA_REFERENCIA >= '2024-10-01' AND DATA_REFERENCIA < '2024-11-01' AND TECNOLOGIA <> 'GSM'
			GROUP BY A.UF, MUNICIPIO, P.BAIRRO
		)A
	)B

), DISP_4G5G AS (

	SELECT
	*,
	ROUND((1-(TEMPO / NULLIF((CAST(SETORES AS float) * DENOMINADOR), 0))) * 100, 2) AS DISPONIBILIDADE
	FROM (
		SELECT
		*,
		COLETAS / CAST(SETORES AS float) * 60 AS DENOMINADOR
		FROM (
			SELECT
			A.UF,
			MUNICIPIO,
			P.BAIRRO,
			'4G_5G' AS TECNOLOGIA,
			COUNT(DISTINCT CONCAT(ERB, SETOR)) AS SETORES,
			SUM(COLETAS_HMM) AS COLETAS,
			SUM(CASE WHEN TEMPO_CONTADOR_HMM >= 0 THEN TEMPO_CONTADOR_HMM END) TEMPO
			FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES A with (nolock)
			INNER JOIN PLANTA P ON A.UF = P.UF AND A.SITE = P.SIGLA_SITE
			WHERE DATA_REFERENCIA >= '2024-10-01' AND DATA_REFERENCIA < '2024-11-01' AND TECNOLOGIA IN('LTE', '5G')
			GROUP BY A.UF, MUNICIPIO, P.BAIRRO
		)A
	)B

)


INSERT INTO INDICADORES_CORAN.dbo.TBF_CELLDOWNTIME_MENSAL_BAIRROS_HMM
SELECT
2024 AS ANO,
10 AS MES,
A.UF,
A.MUNICIPIO,
A.BAIRRO,
MAX(SITES_BAIRRO.SITES) AS SITES,
MAX(DISP_2G) AS DISP_2G,
MAX(DISP_3G) AS DISP_3G,
MAX(DISP_4G) AS DISP_4G,
MAX(DISP_5G) AS DISP_5G,
MAX(DISP_4G_5G) AS DISP_4G_5G,
MAX(DISP_GERAL) AS DISP_GERAL
FROM (
	SELECT
	DISP_GERAL.UF,
	DISP_GERAL.MUNICIPIO,
	DISP_GERAL.BAIRRO,
	CASE WHEN DISP.TECNOLOGIA = 'GSM' THEN DISP.DISPONIBILIDADE END DISP_2G,
	CASE WHEN DISP.TECNOLOGIA = 'WCDMA' THEN DISP.DISPONIBILIDADE END DISP_3G,
	CASE WHEN DISP.TECNOLOGIA = 'LTE' THEN DISP.DISPONIBILIDADE END DISP_4G,
	CASE WHEN DISP.TECNOLOGIA = '5G' THEN DISP.DISPONIBILIDADE END DISP_5G,
	CASE WHEN DISP_4G5G.TECNOLOGIA = '4G_5G' THEN DISP_4G5G.DISPONIBILIDADE END DISP_4G_5G,
	CASE WHEN DISP_GERAL.TECNOLOGIA = 'GERAL' THEN DISP_GERAL.DISPONIBILIDADE END DISP_GERAL
	FROM DISP_GERAL
	INNER JOIN DISP ON DISP.UF = DISP_GERAL.UF AND DISP.MUNICIPIO = DISP_GERAL.MUNICIPIO AND DISP.BAIRRO = DISP_GERAL.BAIRRO
	LEFT JOIN DISP_4G5G ON DISP.UF = DISP_4G5G.UF AND DISP.MUNICIPIO = DISP_4G5G.MUNICIPIO AND DISP.BAIRRO = DISP_4G5G.BAIRRO
	WHERE DISP_GERAL.DISPONIBILIDADE IS NOT NULL AND DISP_GERAL.BAIRRO IS NOT NULL AND DISP_GERAL.BAIRRO <> '-'
)A LEFT JOIN SITES_BAIRRO ON A.UF = SITES_BAIRRO.UF AND A.MUNICIPIO = SITES_BAIRRO.MUNICIPIO AND A.BAIRRO = SITES_BAIRRO.BAIRRO GROUP BY A.UF, A.MUNICIPIO, A.BAIRRO

