-- DISP (SPI) ABILITY E TEL
WITH GERAL AS (
 
	SELECT
	'GERAL' AS TECNOLOGIA,
	DATA_REFERENCIA,
	EMPRESA,
	ROUND((1-(CAST(TEMPO AS FLOAT) / NULLIF((CAST(PLANTA AS float) * DENOMINADOR), 0))) * 100, 2) AS DISPONIBILIDADE
	FROM (
		SELECT
		*,
		COLETAS / CAST(PLANTA AS float) * 60 AS DENOMINADOR
		FROM (
			SELECT
			DATA_REFERENCIA,
			B.EMPRESA,
			COUNT(DISTINCT CONCAT(ERB, SETOR)) AS PLANTA,
			SUM(CASE WHEN TEMPO_CONTADOR_HMM >= 0 THEN TEMPO_CONTADOR_HMM END) AS TEMPO,
			SUM(COLETAS_HMM) AS COLETAS
			FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES A WITH(NOLOCK)
			INNER JOIN SISTEMA_MAESTRO..AUX_REGIONAIS_EMPRESAS B ON A.UF = B.UF AND A.MUNICIPIO = B.MUNICIPIO
			WHERE A.UF = 'SP' AND B.REGIONAL = 'SPI' AND DATA_REFERENCIA >= GETDATE()-32 AND A.TECNOLOGIA <> 'GSM'
			GROUP BY DATA_REFERENCIA, B.EMPRESA
		)A
	)B
 
), GSM AS (
 
	SELECT
	'2G' AS TECNOLOGIA,
	DATA_REFERENCIA,
	EMPRESA,
	ROUND((1-(CAST(TEMPO AS FLOAT) / NULLIF((CAST(PLANTA AS float) * DENOMINADOR), 0))) * 100, 2) AS DISPONIBILIDADE
	FROM (
		SELECT
		*,
		COLETAS / CAST(PLANTA AS float) * 60 AS DENOMINADOR
		FROM (
			SELECT
			DATA_REFERENCIA,
			B.EMPRESA,
			COUNT(DISTINCT CONCAT(ERB, SETOR)) AS PLANTA,
			SUM(CASE WHEN TEMPO_CONTADOR_HMM >= 0 THEN TEMPO_CONTADOR_HMM END) AS TEMPO,
			SUM(COLETAS_HMM) AS COLETAS
			FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES A WITH(NOLOCK)
			INNER JOIN SISTEMA_MAESTRO..AUX_REGIONAIS_EMPRESAS B ON A.UF = B.UF AND A.MUNICIPIO = B.MUNICIPIO
			WHERE A.UF = 'SP' AND B.REGIONAL = 'SPI' AND DATA_REFERENCIA >= GETDATE()-32 AND A.TECNOLOGIA = 'GSM'
			GROUP BY DATA_REFERENCIA, B.EMPRESA
		)A
	)B
 
), WCDMA AS (
 
	SELECT
	'3G' AS TECNOLOGIA,
	DATA_REFERENCIA,
	EMPRESA,
	ROUND((1-(CAST(TEMPO AS FLOAT) / NULLIF((CAST(PLANTA AS float) * DENOMINADOR), 0))) * 100, 2) AS DISPONIBILIDADE
	FROM (
		SELECT
		*,
		COLETAS / CAST(PLANTA AS float) * 60 AS DENOMINADOR
		FROM (
			SELECT
			DATA_REFERENCIA,
			B.EMPRESA,
			COUNT(DISTINCT CONCAT(ERB, SETOR)) AS PLANTA,
			SUM(CASE WHEN TEMPO_CONTADOR_HMM >= 0 THEN TEMPO_CONTADOR_HMM END) AS TEMPO,
			SUM(COLETAS_HMM) AS COLETAS
			FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES A WITH(NOLOCK)
			INNER JOIN SISTEMA_MAESTRO..AUX_REGIONAIS_EMPRESAS B ON A.UF = B.UF AND A.MUNICIPIO = B.MUNICIPIO
			WHERE A.UF = 'SP' AND B.REGIONAL = 'SPI' AND DATA_REFERENCIA >= GETDATE()-32 AND A.TECNOLOGIA = 'WCDMA'
			GROUP BY DATA_REFERENCIA, B.EMPRESA
		)A
	)B
 
), LTE AS (
 
	SELECT
	'4G' AS TECNOLOGIA,
	DATA_REFERENCIA,
	EMPRESA,
	ROUND((1-(CAST(TEMPO AS FLOAT) / NULLIF((CAST(PLANTA AS float) * DENOMINADOR), 0))) * 100, 2) AS DISPONIBILIDADE
	FROM (
		SELECT
		*,
		COLETAS / CAST(PLANTA AS float) * 60 AS DENOMINADOR
		FROM (
			SELECT
			DATA_REFERENCIA,
			B.EMPRESA,
			COUNT(DISTINCT CONCAT(ERB, SETOR)) AS PLANTA,
			SUM(CASE WHEN TEMPO_CONTADOR_HMM >= 0 THEN TEMPO_CONTADOR_HMM END) AS TEMPO,
			SUM(COLETAS_HMM) AS COLETAS
			FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES A WITH(NOLOCK)
			INNER JOIN SISTEMA_MAESTRO..AUX_REGIONAIS_EMPRESAS B ON A.UF = B.UF AND A.MUNICIPIO = B.MUNICIPIO
			WHERE A.UF = 'SP' AND B.REGIONAL = 'SPI' AND DATA_REFERENCIA >= GETDATE()-32 AND A.TECNOLOGIA = 'LTE'
			GROUP BY DATA_REFERENCIA, B.EMPRESA
		)A
	)B
 
), NR AS (
 
	SELECT
	'5G' AS TECNOLOGIA,
	DATA_REFERENCIA,
	EMPRESA,
	ROUND((1-(CAST(TEMPO AS FLOAT) / NULLIF((CAST(PLANTA AS float) * DENOMINADOR), 0))) * 100, 2) AS DISPONIBILIDADE
	FROM (
		SELECT
		*,
		COLETAS / CAST(PLANTA AS float) * 60 AS DENOMINADOR
		FROM (
			SELECT
			DATA_REFERENCIA,
			B.EMPRESA,
			COUNT(DISTINCT CONCAT(ERB, SETOR)) AS PLANTA,
			SUM(CASE WHEN TEMPO_CONTADOR_HMM >= 0 THEN TEMPO_CONTADOR_HMM END) AS TEMPO,
			SUM(COLETAS_HMM) AS COLETAS
			FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES A WITH(NOLOCK)
			INNER JOIN SISTEMA_MAESTRO..AUX_REGIONAIS_EMPRESAS B ON A.UF = B.UF AND A.MUNICIPIO = B.MUNICIPIO
			WHERE A.UF = 'SP' AND B.REGIONAL = 'SPI' AND DATA_REFERENCIA >= GETDATE()-32 AND A.TECNOLOGIA = '5G'
			GROUP BY DATA_REFERENCIA, B.EMPRESA
		)A
	)B
 
), LTE_NR AS (
 
	SELECT
	'4G_5G' AS TECNOLOGIA,
	DATA_REFERENCIA,
	EMPRESA,
	ROUND((1-(CAST(TEMPO AS FLOAT) / NULLIF((CAST(PLANTA AS float) * DENOMINADOR), 0))) * 100, 2) AS DISPONIBILIDADE
	FROM (
		SELECT
		*,
		COLETAS / CAST(PLANTA AS float) * 60 AS DENOMINADOR
		FROM (
			SELECT
			DATA_REFERENCIA,
			B.EMPRESA,
			COUNT(DISTINCT CONCAT(ERB, SETOR)) AS PLANTA,
			SUM(CASE WHEN TEMPO_CONTADOR_HMM >= 0 THEN TEMPO_CONTADOR_HMM END) AS TEMPO,
			SUM(COLETAS_HMM) AS COLETAS
			FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES A WITH(NOLOCK)
			INNER JOIN SISTEMA_MAESTRO..AUX_REGIONAIS_EMPRESAS B ON A.UF = B.UF AND A.MUNICIPIO = B.MUNICIPIO
			WHERE A.UF = 'SP' AND B.REGIONAL = 'SPI' AND DATA_REFERENCIA >= GETDATE()-32 AND A.TECNOLOGIA IN('LTE', '5G')
			GROUP BY DATA_REFERENCIA, B.EMPRESA
		)A
	)B
 
)
 
 
SELECT
GERAL.DATA_REFERENCIA,
GERAL.EMPRESA,
GERAL.DISPONIBILIDADE AS DISP_GERAL,
GSM.DISPONIBILIDADE AS DISP_2G,
WCDMA.DISPONIBILIDADE AS DISP_3G,
LTE.DISPONIBILIDADE AS DISP_4G,
NR.DISPONIBILIDADE AS DISP_5G,
LTE_NR.DISPONIBILIDADE AS DISP_4G_5G
FROM GERAL
LEFT JOIN GSM ON GERAL.DATA_REFERENCIA = GSM.DATA_REFERENCIA AND GERAL.EMPRESA = GSM.EMPRESA
LEFT JOIN WCDMA ON GERAL.DATA_REFERENCIA = WCDMA.DATA_REFERENCIA AND GERAL.EMPRESA = WCDMA.EMPRESA
LEFT JOIN LTE ON GERAL.DATA_REFERENCIA = LTE.DATA_REFERENCIA AND GERAL.EMPRESA = LTE.EMPRESA
LEFT JOIN NR ON GERAL.DATA_REFERENCIA = NR.DATA_REFERENCIA AND GERAL.EMPRESA = NR.EMPRESA
LEFT JOIN LTE_NR ON GERAL.DATA_REFERENCIA = LTE_NR.DATA_REFERENCIA AND GERAL.EMPRESA = LTE_NR.EMPRESA
ORDER BY GERAL.EMPRESA, GERAL.DATA_REFERENCIA
 
-- DISP ABILITY (JAI e OCO)
WITH GERAL AS (
SELECT
	'GERAL' AS TECNOLOGIA,
	DATA_REFERENCIA,
	REGIAO,
	ROUND((1-(CAST(TEMPO AS FLOAT) / NULLIF((CAST(PLANTA AS float) * DENOMINADOR), 0))) * 100, 2) AS DISPONIBILIDADE
	FROM (
		SELECT
		*,
		COLETAS / CAST(PLANTA AS float) * 60 AS DENOMINADOR
		FROM (
            SELECT
            DATA_REFERENCIA,
            REGIAO,
            SUM(COLETAS) AS COLETAS,
            SUM(TEMPO) AS TEMPO,
            SUM(PLANTA) AS PLANTA
            FROM
            (
                SELECT
                DATA_REFERENCIA,
                CASE WHEN A.MUNICIPIO IN ('ATIBAIA','BOM JESUS DOS PERDÕES','BRAGANÇA PAULISTA','CABREÚVA','CAIEIRAS','CAJAMAR','CAMPO LIMPO PAULISTA','FRANCISCO MORATO','FRANCO DA ROCHA','ITATIBA','ITU','ITUPEVA','JARINU','JOANÓPOLIS','JUNDIAÍ','MAIRIPORÃ','MORUNGABA','NAZARÉ PAULISTA',
                'PEDRA BELA','PINHALZINHO','PIRACAIA','SALTO','TUIUTI','VARGEM','VÁRZEA PAULISTA') THEN 'OCO' ELSE 'JAI' END AS REGIAO,
                COUNT(DISTINCT CONCAT(ERB, SETOR)) AS PLANTA,
                SUM(CASE WHEN TEMPO_CONTADOR_HMM >= 0 THEN TEMPO_CONTADOR_HMM END) AS TEMPO,
                SUM(COLETAS_HMM) AS COLETAS
                FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES A WITH(NOLOCK)
                INNER JOIN SISTEMA_MAESTRO..AUX_REGIONAIS_EMPRESAS B ON A.UF = B.UF AND A.MUNICIPIO = B.MUNICIPIO
                WHERE A.UF = 'SP'  AND  DATA_REFERENCIA >= GETDATE()-32 AND A.TECNOLOGIA <> 'GSM' AND B.REGIONAL = 'SPI' AND B.EMPRESA = 'ABILITY'
                GROUP BY DATA_REFERENCIA, A.MUNICIPIO
            ) Z GROUP BY DATA_REFERENCIA, REGIAO
		)A
	)B
),
GSM AS (
	SELECT
	'2G' AS TECNOLOGIA,
	DATA_REFERENCIA,
	REGIAO,
	ROUND((1-(CAST(TEMPO AS FLOAT) / NULLIF((CAST(PLANTA AS float) * DENOMINADOR), 0))) * 100, 2) AS DISPONIBILIDADE
	FROM (
		SELECT
		*,
		COLETAS / CAST(PLANTA AS float) * 60 AS DENOMINADOR
		FROM (
            SELECT
            DATA_REFERENCIA,
            REGIAO,
            SUM(COLETAS) AS COLETAS,
            SUM(TEMPO) AS TEMPO,
            SUM(PLANTA) AS PLANTA
            FROM (
                SELECT
                DATA_REFERENCIA,
                CASE WHEN A.MUNICIPIO IN ('ATIBAIA','BOM JESUS DOS PERDÕES','BRAGANÇA PAULISTA','CABREÚVA','CAIEIRAS','CAJAMAR','CAMPO LIMPO PAULISTA','FRANCISCO MORATO','FRANCO DA ROCHA','ITATIBA','ITU','ITUPEVA','JARINU','JOANÓPOLIS','JUNDIAÍ','MAIRIPORÃ','MORUNGABA','NAZARÉ PAULISTA',
                'PEDRA BELA','PINHALZINHO','PIRACAIA','SALTO','TUIUTI','VARGEM','VÁRZEA PAULISTA') THEN 'OCO' ELSE 'JAI' END AS REGIAO,
                COUNT(DISTINCT CONCAT(ERB, SETOR)) AS PLANTA,
                SUM(CASE WHEN TEMPO_CONTADOR_HMM >= 0 THEN TEMPO_CONTADOR_HMM END) AS TEMPO,
                SUM(COLETAS_HMM) AS COLETAS
                FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES A WITH(NOLOCK)
                INNER JOIN SISTEMA_MAESTRO..AUX_REGIONAIS_EMPRESAS B ON A.UF = B.UF AND A.MUNICIPIO = B.MUNICIPIO
                WHERE A.UF = 'SP' AND B.REGIONAL = 'SPI' AND DATA_REFERENCIA >= GETDATE()-32 AND A.TECNOLOGIA = 'GSM' AND B.EMPRESA = 'ABILITY'
                GROUP BY DATA_REFERENCIA, A.MUNICIPIO
            ) Z GROUP BY DATA_REFERENCIA, REGIAO
		)A
	)B
),
WCDMA AS (
	SELECT
	'3G' AS TECNOLOGIA,
	DATA_REFERENCIA,
	REGIAO,
	ROUND((1-(CAST(TEMPO AS FLOAT) / NULLIF((CAST(PLANTA AS float) * DENOMINADOR), 0))) * 100, 2) AS DISPONIBILIDADE
	FROM (
		SELECT
		*,
		COLETAS / CAST(PLANTA AS float) * 60 AS DENOMINADOR
		FROM (
		    SELECT
            DATA_REFERENCIA,
            REGIAO,
            SUM(COLETAS) AS COLETAS,
            SUM(TEMPO) AS TEMPO,
            SUM(PLANTA) AS PLANTA
            FROM (
                SELECT
			    DATA_REFERENCIA,
                CASE WHEN A.MUNICIPIO IN ('ATIBAIA','BOM JESUS DOS PERDÕES','BRAGANÇA PAULISTA','CABREÚVA','CAIEIRAS','CAJAMAR','CAMPO LIMPO PAULISTA','FRANCISCO MORATO','FRANCO DA ROCHA','ITATIBA','ITU','ITUPEVA','JARINU','JOANÓPOLIS','JUNDIAÍ','MAIRIPORÃ','MORUNGABA','NAZARÉ PAULISTA',
                'PEDRA BELA','PINHALZINHO','PIRACAIA','SALTO','TUIUTI','VARGEM','VÁRZEA PAULISTA') THEN 'OCO' ELSE 'JAI' END AS REGIAO,
                COUNT(DISTINCT CONCAT(ERB, SETOR)) AS PLANTA,
                SUM(CASE WHEN TEMPO_CONTADOR_HMM >= 0 THEN TEMPO_CONTADOR_HMM END) AS TEMPO,
                SUM(COLETAS_HMM) AS COLETAS
                FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES A WITH(NOLOCK)
                INNER JOIN SISTEMA_MAESTRO..AUX_REGIONAIS_EMPRESAS B ON A.UF = B.UF AND A.MUNICIPIO = B.MUNICIPIO
                WHERE A.UF = 'SP' AND B.REGIONAL = 'SPI' AND DATA_REFERENCIA >= GETDATE()-32 AND A.TECNOLOGIA = 'WCDMA' AND B.EMPRESA = 'ABILITY'
                GROUP BY DATA_REFERENCIA, A.MUNICIPIO
            ) Z GROUP BY DATA_REFERENCIA, REGIAO
		)A
	)B

),
LTE AS (
	SELECT
	'4G' AS TECNOLOGIA,
	DATA_REFERENCIA,
	REGIAO,
	ROUND((1-(CAST(TEMPO AS FLOAT) / NULLIF((CAST(PLANTA AS float) * DENOMINADOR), 0))) * 100, 2) AS DISPONIBILIDADE
	FROM (
		SELECT
		*,
		COLETAS / CAST(PLANTA AS float) * 60 AS DENOMINADOR
		FROM (
            SELECT
            DATA_REFERENCIA,
            REGIAO,
            SUM(COLETAS) AS COLETAS,
            SUM(TEMPO) AS TEMPO,
            SUM(PLANTA) AS PLANTA
            FROM (
                SELECT
			    DATA_REFERENCIA,
                CASE WHEN A.MUNICIPIO IN ('ATIBAIA','BOM JESUS DOS PERDÕES','BRAGANÇA PAULISTA','CABREÚVA','CAIEIRAS','CAJAMAR','CAMPO LIMPO PAULISTA','FRANCISCO MORATO','FRANCO DA ROCHA','ITATIBA','ITU','ITUPEVA','JARINU','JOANÓPOLIS','JUNDIAÍ','MAIRIPORÃ','MORUNGABA','NAZARÉ PAULISTA',
                'PEDRA BELA','PINHALZINHO','PIRACAIA','SALTO','TUIUTI','VARGEM','VÁRZEA PAULISTA') THEN 'OCO' ELSE 'JAI' END AS REGIAO,
                COUNT(DISTINCT CONCAT(ERB, SETOR)) AS PLANTA,
                SUM(CASE WHEN TEMPO_CONTADOR_HMM >= 0 THEN TEMPO_CONTADOR_HMM END) AS TEMPO,
                SUM(COLETAS_HMM) AS COLETAS
                FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES A WITH(NOLOCK)
                INNER JOIN SISTEMA_MAESTRO..AUX_REGIONAIS_EMPRESAS B ON A.UF = B.UF AND A.MUNICIPIO = B.MUNICIPIO
                WHERE A.UF = 'SP' AND B.REGIONAL = 'SPI' AND DATA_REFERENCIA >= GETDATE()-32 AND A.TECNOLOGIA = 'LTE' AND B.EMPRESA = 'ABILITY'
                GROUP BY DATA_REFERENCIA, A.MUNICIPIO
            ) Z GROUP BY DATA_REFERENCIA, REGIAO
		)A
	)B
),
NR AS (

	SELECT
	'5G' AS TECNOLOGIA,
	DATA_REFERENCIA,
	REGIAO,
	ROUND((1-(CAST(TEMPO AS FLOAT) / NULLIF((CAST(PLANTA AS float) * DENOMINADOR), 0))) * 100, 2) AS DISPONIBILIDADE
	FROM (
		SELECT
		*,
		COLETAS / CAST(PLANTA AS float) * 60 AS DENOMINADOR
		FROM (
            SELECT
            DATA_REFERENCIA,
            REGIAO,
            SUM(COLETAS) AS COLETAS,
            SUM(TEMPO) AS TEMPO,
            SUM(PLANTA) AS PLANTA
            FROM (
                SELECT
			    DATA_REFERENCIA,
                CASE WHEN A.MUNICIPIO IN ('ATIBAIA','BOM JESUS DOS PERDÕES','BRAGANÇA PAULISTA','CABREÚVA','CAIEIRAS','CAJAMAR','CAMPO LIMPO PAULISTA','FRANCISCO MORATO','FRANCO DA ROCHA','ITATIBA','ITU','ITUPEVA','JARINU','JOANÓPOLIS','JUNDIAÍ','MAIRIPORÃ','MORUNGABA','NAZARÉ PAULISTA',
                'PEDRA BELA','PINHALZINHO','PIRACAIA','SALTO','TUIUTI','VARGEM','VÁRZEA PAULISTA') THEN 'OCO' ELSE 'JAI' END AS REGIAO,
                COUNT(DISTINCT CONCAT(ERB, SETOR)) AS PLANTA,
                SUM(CASE WHEN TEMPO_CONTADOR_HMM >= 0 THEN TEMPO_CONTADOR_HMM END) AS TEMPO,
                SUM(COLETAS_HMM) AS COLETAS
                FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES A WITH(NOLOCK)
                INNER JOIN SISTEMA_MAESTRO..AUX_REGIONAIS_EMPRESAS B ON A.UF = B.UF AND A.MUNICIPIO = B.MUNICIPIO
                WHERE A.UF = 'SP' AND B.REGIONAL = 'SPI' AND DATA_REFERENCIA >= GETDATE()-32 AND A.TECNOLOGIA = '5G' AND EMPRESA = 'ABILITY'
                GROUP BY DATA_REFERENCIA, A.MUNICIPIO
            ) Z GROUP BY DATA_REFERENCIA, REGIAO
		)A
	)B
),
LTE_NR AS (

	SELECT
	'4G_5G' AS TECNOLOGIA,
	DATA_REFERENCIA,
	REGIAO,
	ROUND((1-(CAST(TEMPO AS FLOAT) / NULLIF((CAST(PLANTA AS float) * DENOMINADOR), 0))) * 100, 2) AS DISPONIBILIDADE
	FROM (
		SELECT
		*,
		COLETAS / CAST(PLANTA AS float) * 60 AS DENOMINADOR
		FROM (
            SELECT
            DATA_REFERENCIA,
            REGIAO,
            SUM(COLETAS) AS COLETAS,
            SUM(TEMPO) AS TEMPO,
            SUM(PLANTA) AS PLANTA
            FROM (
                SELECT
			    DATA_REFERENCIA,
                CASE WHEN A.MUNICIPIO IN ('ATIBAIA','BOM JESUS DOS PERDÕES','BRAGANÇA PAULISTA','CABREÚVA','CAIEIRAS','CAJAMAR','CAMPO LIMPO PAULISTA','FRANCISCO MORATO','FRANCO DA ROCHA','ITATIBA','ITU','ITUPEVA','JARINU','JOANÓPOLIS','JUNDIAÍ','MAIRIPORÃ','MORUNGABA','NAZARÉ PAULISTA',
                'PEDRA BELA','PINHALZINHO','PIRACAIA','SALTO','TUIUTI','VARGEM','VÁRZEA PAULISTA') THEN 'OCO' ELSE 'JAI' END AS REGIAO,
                COUNT(DISTINCT CONCAT(ERB, SETOR)) AS PLANTA,
                SUM(CASE WHEN TEMPO_CONTADOR_HMM >= 0 THEN TEMPO_CONTADOR_HMM END) AS TEMPO,
                SUM(COLETAS_HMM) AS COLETAS
                FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES A WITH(NOLOCK)
                INNER JOIN SISTEMA_MAESTRO..AUX_REGIONAIS_EMPRESAS B ON A.UF = B.UF AND A.MUNICIPIO = B.MUNICIPIO
                WHERE A.UF = 'SP' AND B.REGIONAL = 'SPI' AND DATA_REFERENCIA >= GETDATE()-32 AND A.TECNOLOGIA IN('LTE', '5G') AND EMPRESA = 'ABILITY'
                GROUP BY DATA_REFERENCIA, A.MUNICIPIO
            ) Z GROUP BY DATA_REFERENCIA, REGIAO
		)A
	)B
)


SELECT
GERAL.DATA_REFERENCIA,
GERAL.REGIAO,
GERAL.DISPONIBILIDADE AS DISP_GERAL,
GSM.DISPONIBILIDADE AS DISP_2G,
WCDMA.DISPONIBILIDADE AS DISP_3G,
LTE.DISPONIBILIDADE AS DISP_4G,
NR.DISPONIBILIDADE AS DISP_5G,
LTE_NR.DISPONIBILIDADE AS DISP_4G_5G
FROM GERAL
LEFT JOIN GSM ON GERAL.DATA_REFERENCIA = GSM.DATA_REFERENCIA AND GERAL.REGIAO = GSM.REGIAO
LEFT JOIN WCDMA ON GERAL.DATA_REFERENCIA = WCDMA.DATA_REFERENCIA AND GERAL.REGIAO = WCDMA.REGIAO
LEFT JOIN LTE ON GERAL.DATA_REFERENCIA = LTE.DATA_REFERENCIA AND GERAL.REGIAO = LTE.REGIAO
LEFT JOIN NR ON GERAL.DATA_REFERENCIA = NR.DATA_REFERENCIA AND GERAL.REGIAO = NR.REGIAO
LEFT JOIN LTE_NR ON GERAL.DATA_REFERENCIA = LTE_NR.DATA_REFERENCIA AND GERAL.REGIAO = LTE_NR.REGIAO
ORDER BY GERAL.REGIAO, GERAL.DATA_REFERENCIA