    -- SELECT MIN(DATA_REFERENCIA), MAX(DATA_REFERENCIA) FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES_HIST_2023
    -- SELECT MIN(DATA_REFERENCIA), MAX(DATA_REFERENCIA) FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES
    -- DROP TABLE #TEMP_RESULTADOS_SPI
    SELECT
        DISP.DATA_REFERENCIA,
        YEAR(DISP.DATA_REFERENCIA) AS ANO,
        MONTH(DISP.DATA_REFERENCIA) AS MES,
        ISNULL(REGIAO_SP.GESTAO, 'CAPITAL') AS REGIONAL,
        UF,
        CN,
        DISP.MUNICIPIO,
        SITE,
        ERB,
        SETOR,
        TECNOLOGIA,
        EMPRESA,
        MAX(TEMPO_CONTADOR_HMM) AS TEMPO_CONTADOR,
        MAX(COLETAS_HMM) AS COLETAS
	INTO #TEMP_RESULTADOS_SPI
	FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES DISP WITH(NOLOCK)
	LEFT JOIN INDICADORES_CORAN.dbo.TBA_DIVISAO_MUNICIPIOS_SP_FIXA REGIAO_SP WITH(NOLOCK) ON DISP.MUNICIPIO = REGIAO_SP.MUNICIPIO
	LEFT JOIN (SELECT DISTINCT UF AS UF_B, SIGLA_SITE AS SITE_B, EMPRESA FROM SISTEMA_MAESTRO..TBA_PLANTA_MOVEL WITH(NOLOCK) WHERE UF = 'SP') B ON DISP.UF = B.UF_B AND DISP.SITE = B.SITE_B
	WHERE YEAR(DISP.DATA_REFERENCIA) = 2024 AND UF = 'SP' AND REGIAO_SP.NOME_REGIONAL = 'SPI' AND EMPRESA = 'ABILITY' --AND MONTH(DISP.DATA_REFERENCIA) = 10
	GROUP BY DISP.DATA_REFERENCIA, REGIONAL, UF, CN, DISP.MUNICIPIO, SITE, ERB, SETOR, TECNOLOGIA, REGIAO_SP.GESTAO, EMPRESA


/* ALIADAS SPI */
	SELECT
	ANO,
	MES,
	CONCAT(EMPRESA, ' SPI') AS EMPRESA,
	PLANTA_2G,
	MINUTOS_2G,
	COLETAS_GSM,
	CASE WHEN PLANTA_2G = 0 THEN NULL WHEN COLETAS_GSM = 0 THEN NULL WHEN COLETAS_GSM > 0 THEN ROUND((1-(MINUTOS_2G/(CAST(PLANTA_2G AS float)*DENOMINADOR_2G)))*100, 2) END DISPONIBILIDADE_2G,
	PLANTA_3G,
	MINUTOS_3G,
	COLETAS_WCDMA,
	CASE WHEN PLANTA_3G = 0 THEN NULL WHEN COLETAS_WCDMA = 0 THEN NULL WHEN COLETAS_WCDMA > 0 THEN ROUND((1-(MINUTOS_3G/(CAST(PLANTA_3G AS float)*DENOMINADOR_3G)))*100, 2) END DISPONIBILIDADE_3G,
	PLANTA_4G,
	MINUTOS_4G,
	COLETAS_LTE,
	CASE WHEN PLANTA_4G = 0 THEN NULL WHEN COLETAS_LTE = 0 THEN NULL WHEN COLETAS_LTE > 0 THEN ROUND((1-(MINUTOS_4G/(CAST(PLANTA_4G AS float)*DENOMINADOR_4G)))*100, 2) END DISPONIBILIDADE_4G,
	PLANTA_GERAL,
	MINUTOS_GERAL,
	COLETAS_GERAL,
	CASE WHEN PLANTA_GERAL = 0 THEN NULL WHEN COLETAS_GERAL = 0 THEN NULL WHEN COLETAS_GERAL > 0 THEN ROUND((1-(MINUTOS_GERAL/(CAST(PLANTA_GERAL AS float)*DENOMINADOR_GERAL)))*100, 2) END DISPONIBILIDADE_GERAL,
	PLANTA_5G,
	MINUTOS_5G,
	COLETAS_5G,
	CASE WHEN PLANTA_5G = 0 THEN NULL WHEN COLETAS_5G = 0 THEN NULL WHEN COLETAS_5G > 0 THEN ROUND((1-(MINUTOS_5G/(CAST(PLANTA_5G AS float)*DENOMINADOR_5G)))*100, 2) END DISPONIBILIDADE_5G,
	--DISP_4G_5G
	PLANTA_4G_5G,
	MINUTOS_4G_5G,
	COLETAS_4G_5G,
	CASE WHEN PLANTA_4G_5G = 0 THEN NULL WHEN COLETAS_4G_5G = 0 THEN NULL WHEN COLETAS_4G_5G > 0 THEN ROUND((1-(MINUTOS_4G_5G/(CAST(PLANTA_4G_5G AS float)*DENOMINADOR_4G_5G)))*100, 2) END DISPONIBILIDADE_4G_5G

	
	FROM (
		SELECT
		*,
		(CAST(COLETAS_GSM AS float)/PLANTA_2G*60) AS DENOMINADOR_2G,
		(CAST(COLETAS_WCDMA AS float)/PLANTA_3G*60) AS DENOMINADOR_3G,
		(CAST(COLETAS_LTE AS float)/PLANTA_4G*60) AS DENOMINADOR_4G,
		(CAST(COLETAS_GERAL AS float)/PLANTA_GERAL*60) AS DENOMINADOR_GERAL,
		(CAST(COLETAS_5G AS float)/PLANTA_5G*60) AS DENOMINADOR_5G,
		(CAST(COLETAS_3G_4G AS float)/PLANTA_3G_4G*60) AS DENOMINADOR_3G_4G,
		(CAST(COLETAS_3G_5G AS float)/PLANTA_3G_5G*60) AS DENOMINADOR_3G_5G,
		(CAST(COLETAS_4G_5G AS float)/PLANTA_4G_5G*60) AS DENOMINADOR_4G_5G
		FROM (
			SELECT
			ANO,
			MES,
			EMPRESA,
			COUNT(DISTINCT CASE WHEN TECNOLOGIA = 'GSM' THEN CONCAT(DISP.UF, DISP.ERB, DISP.SETOR) END) PLANTA_2G,
			SUM(CASE WHEN TECNOLOGIA = 'GSM' AND TEMPO_CONTADOR >= 0 THEN TEMPO_CONTADOR ELSE 0 END) MINUTOS_2G,   
			COUNT(DISTINCT CASE WHEN TECNOLOGIA = 'WCDMA' THEN CONCAT(DISP.UF, DISP.ERB, DISP.SETOR) END) PLANTA_3G,
			SUM(CASE WHEN TECNOLOGIA = 'WCDMA' AND TEMPO_CONTADOR >= 0 THEN TEMPO_CONTADOR ELSE 0 END) MINUTOS_3G,
			COUNT(DISTINCT CASE WHEN TECNOLOGIA = 'LTE' THEN CONCAT(DISP.UF, DISP.ERB, DISP.SETOR) END) PLANTA_4G,
			SUM(CASE WHEN TECNOLOGIA = 'LTE' AND TEMPO_CONTADOR >= 0 THEN TEMPO_CONTADOR ELSE 0 END) MINUTOS_4G,
			--COUNT(DISTINCT CONCAT(DISP.UF, DISP.ERB, DISP.SETOR)) PLANTA_GERAL,
			COUNT(DISTINCT CASE WHEN TECNOLOGIA <> 'GSM' THEN CONCAT(DISP.UF, DISP.ERB, DISP.SETOR) END) PLANTA_GERAL,
			--SUM(CASE WHEN TEMPO_CONTADOR >= 0 THEN TEMPO_CONTADOR ELSE 0 END) MINUTOS_GERAL,
			SUM(CASE WHEN TEMPO_CONTADOR >= 0 AND TECNOLOGIA <> 'GSM' THEN TEMPO_CONTADOR ELSE 0 END) MINUTOS_GERAL,
			SUM(CASE WHEN TECNOLOGIA = 'GSM' THEN COLETAS ELSE 0 END) COLETAS_GSM,
			SUM(CASE WHEN TECNOLOGIA = 'WCDMA' THEN COLETAS ELSE 0 END) COLETAS_WCDMA,
			SUM(CASE WHEN TECNOLOGIA = 'LTE' THEN COLETAS ELSE 0 END) COLETAS_LTE,
			--SUM(COLETAS) COLETAS_GERAL,
			SUM(CASE WHEN TECNOLOGIA <> 'GSM' THEN COLETAS ELSE 0 END) COLETAS_GERAL,
			COUNT(DISTINCT CASE WHEN TECNOLOGIA = '5G' THEN CONCAT(DISP.UF, DISP.ERB, DISP.SETOR) END) PLANTA_5G,
			SUM(CASE WHEN TECNOLOGIA = '5G' AND TEMPO_CONTADOR >= 0 THEN TEMPO_CONTADOR ELSE 0 END) MINUTOS_5G,   
			SUM(CASE WHEN TECNOLOGIA = '5G' THEN COLETAS ELSE 0 END) COLETAS_5G,
			--3G+4G
			COUNT(DISTINCT CASE WHEN TECNOLOGIA IN ('WCDMA','LTE') THEN CONCAT(DISP.UF, DISP.ERB, DISP.SETOR) END) PLANTA_3G_4G,
			SUM(CASE WHEN TECNOLOGIA IN ('WCDMA','LTE') AND TEMPO_CONTADOR >= 0 THEN TEMPO_CONTADOR ELSE 0 END) MINUTOS_3G_4G,   
			SUM(CASE WHEN TECNOLOGIA IN ('WCDMA','LTE') THEN COLETAS ELSE 0 END) COLETAS_3G_4G,
			--3G+5G
			COUNT(DISTINCT CASE WHEN TECNOLOGIA IN ('WCDMA','5G') THEN CONCAT(DISP.UF, DISP.ERB, DISP.SETOR) END) PLANTA_3G_5G,
			SUM(CASE WHEN TECNOLOGIA IN ('WCDMA','5G') AND TEMPO_CONTADOR >= 0 THEN TEMPO_CONTADOR ELSE 0 END) MINUTOS_3G_5G,   
			SUM(CASE WHEN TECNOLOGIA IN ('WCDMA','5G') THEN COLETAS ELSE 0 END) COLETAS_3G_5G,
			--4G+5G
			COUNT(DISTINCT CASE WHEN TECNOLOGIA IN ('LTE','5G') THEN CONCAT(DISP.UF, DISP.ERB, DISP.SETOR) END) PLANTA_4G_5G,
			SUM(CASE WHEN TECNOLOGIA IN ('LTE','5G') AND TEMPO_CONTADOR >= 0 THEN TEMPO_CONTADOR ELSE 0 END) MINUTOS_4G_5G,   
			SUM(CASE WHEN TECNOLOGIA IN ('LTE','5G') THEN COLETAS ELSE 0 END) COLETAS_4G_5G

			FROM #TEMP_RESULTADOS_SPI DISP
			WHERE EMPRESA IS NOT NULL
			GROUP BY ANO, MES, EMPRESA
		)GERAL
	)FINAL


