WITH MENSAL AS (

SELECT DISPONIBILIDADE_GERAL FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_MENSAL_UF_HMM WHERE ANO = ${ANO} AND MES = ${MES} AND UF = 'INTERIOR'

), SEMANAL AS (

SELECT DISPONIBILIDADE_GERAL FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_SEMANAL_UF_HMM WHERE ANO = ${ANO} AND SEMANA = ${SEMANA} AND UF = 'INTERIOR'

), DIARIO AS (

SELECT DISPONIBILIDADE_GERAL FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_DIARIO_UF_HMM WHERE ANO = ${ANO} AND MES = ${MES} AND DIA = ${DIA} AND UF = 'INTERIOR'

), ESTATISTICA AS (

	SELECT
	AVG(PLANTA) AS AVG_PLANTA,
	SUM(PLANTA) AS SUM_PLANTA,
	AVG(COLETAS) AS AVG_COLETAS,
	SUM(COLETAS) AS SUM_COLETAS,
	AVG(TEMPO) AS AVG_TEMPO,
	SUM(TEMPO) AS SUM_TEMPO
	FROM (
		SELECT
		DATA_REFERENCIA,
		COUNT(DISTINCT CONCAT(SITE, ERB, SETOR)) AS PLANTA,
		ISNULL(SUM(COLETAS_HMM), 0) AS COLETAS,
		SUM(CASE WHEN TEMPO_CONTADOR_HMM >= 0 THEN TEMPO_CONTADOR_HMM ELSE 0 END) TEMPO
		FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES A WITH (NOLOCK)
		INNER JOIN INDICADORES_CORAN..TBA_DIVISAO_MUNICIPIOS_SP_FIXA B WITH (NOLOCK) ON A.MUNICIPIO = B.MUNICIPIO
		WHERE TECNOLOGIA <> 'GSM' AND A.UF = 'SP' AND B.GESTAO = 'INTERIOR' AND YEAR(DATA_REFERENCIA) = ${ANO} AND MONTH(DATA_REFERENCIA) = ${MES}
		GROUP BY DATA_REFERENCIA
	)A

), DIAS_RESTANTE AS (

		SELECT
		COUNT(*) AS DIAS_RESTANTE
		FROM SISTEMA_MAESTRO..AUX_SEMANAS A LEFT JOIN (
			SELECT DISTINCT
			DATA_REFERENCIA,
			'CDT' AS TIPO
			FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_DIARIO_UF_HMM A WITH(NOLOCK)
			WHERE ANO = ${ANO} AND MES = ${MES} AND UF = 'INTERIOR'
		)B ON A.DATA_REFERENCIA = B.DATA_REFERENCIA WHERE A.ANO = ${ANO} AND A.MES = ${MES} AND B.TIPO IS NULL

), PROJECOES AS (

	SELECT
	CONSUMO,
	ROUND((1-(SALDO_DIARIO_FORECAST / CAST((AVG_PLANTA * DENOMINADOR_FORECAST) AS float))) * 100, 2) AS FORECAST_DISPONIBILIDADE,
	ROUND((1-(SUM_TEMPO / CAST((SUM_PROJECAO_PLANTA * DENOMINADOR_PROJECAO) AS float))) * 100, 2) AS PROJECAO_DISPONIBILIDADE
	FROM (
		SELECT
		ROUND(SUM_TEMPO / CAST((((A.SUM_COLETAS * 60) + (A.AVG_COLETAS * 60 * NULLIF(B.DIAS_RESTANTE, 0))) / 100) AS float) * 100, 2) AS CONSUMO,
		((A.SUM_COLETAS * 60) + (A.AVG_COLETAS * 60 * NULLIF(B.DIAS_RESTANTE, 0))) AS SALDO_TOTAL,
		((((A.SUM_COLETAS * 60) + (A.AVG_COLETAS * 60 * NULLIF(B.DIAS_RESTANTE, 0))) / 100) - A.SUM_TEMPO) / NULLIF(B.DIAS_RESTANTE, 0) AS SALDO_DIARIO_FORECAST,
		(SUM_COLETAS + (AVG_COLETAS * 60 * NULLIF(B.DIAS_RESTANTE, 0))) / CAST(((SUM_PLANTA + (AVG_PLANTA * 60 * NULLIF(B.DIAS_RESTANTE, 0)))) AS float) * 60 AS DENOMINADOR_PROJECAO,
		AVG_COLETAS / CAST(AVG_PLANTA AS float) * 60 AS DENOMINADOR_FORECAST,
		AVG_PLANTA,
		SUM_PLANTA + (AVG_PLANTA * NULLIF(B.DIAS_RESTANTE, 0)) AS SUM_PROJECAO_PLANTA,
		SUM_TEMPO
		FROM ESTATISTICA A
		INNER JOIN DIAS_RESTANTE B ON 1 = 1
	)A

)


SELECT
'${DATA_REFERENCIA}' AS DATA_REFERENCIA,
${ANO} AS ANO,
${MES} AS MES,
${SEMANA} AS SEMANA,
${DIA} AS DIA,
'REGIONAL' AS TIPO,
'SPI' AS NOME,
A.DISPONIBILIDADE_GERAL AS MENSAL,
B.DISPONIBILIDADE_GERAL AS SEMANAL,
C.DISPONIBILIDADE_GERAL AS DIARIO,
100 AS SHARE_PLANTA,
100 AS SHARE_TEMPO,
D.CONSUMO,
D.PROJECAO_DISPONIBILIDADE,
D.FORECAST_DISPONIBILIDADE
FROM MENSAL A
INNER JOIN SEMANAL B ON 1 = 1
INNER JOIN DIARIO C ON 1 = 1
INNER JOIN PROJECOES D ON 1 = 1





--==========================================================================================================================================================================
--REGIONAL NO
--==========================================================================================================================================================================

WITH MENSAL AS (

SELECT DISPONIBILIDADE_GERAL FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_MENSAL_REGIONAL_HMM WHERE ANO = ${ANO} AND MES = ${MES} AND REGIONAL = 'NO'

), SEMANAL AS (

SELECT DISPONIBILIDADE_GERAL FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_SEMANAL_REGIONAL_HMM WHERE ANO = ${ANO} AND SEMANA = ${SEMANA} AND REGIONAL = 'NO'

), DIARIO AS (

SELECT DISPONIBILIDADE_GERAL FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_DIARIO_REGIONAL_HMM WHERE ANO = ${ANO} AND MES = ${MES} AND DIA = ${DIA} AND REGIONAL = 'NO'

), ESTATISTICA AS (

	SELECT
	AVG(PLANTA) AS AVG_PLANTA,
	SUM(PLANTA) AS SUM_PLANTA,
	AVG(COLETAS) AS AVG_COLETAS,
	SUM(COLETAS) AS SUM_COLETAS,
	AVG(TEMPO) AS AVG_TEMPO,
	SUM(TEMPO) AS SUM_TEMPO
	FROM (
		SELECT
		DATA_REFERENCIA,
		COUNT(DISTINCT CONCAT(SITE, ERB, SETOR)) AS PLANTA,
		ISNULL(SUM(COLETAS_HMM), 0) AS COLETAS,
		SUM(CASE WHEN TEMPO_CONTADOR_HMM >= 0 THEN TEMPO_CONTADOR_HMM ELSE 0 END) TEMPO
		FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES A WITH (NOLOCK)
		WHERE TECNOLOGIA <> 'GSM' AND REGIONAL = 'NO' AND YEAR(DATA_REFERENCIA) = ${ANO} AND MONTH(DATA_REFERENCIA) = ${MES}
		GROUP BY DATA_REFERENCIA
	)A

), DIAS_RESTANTE AS (

		SELECT
		COUNT(*) AS DIAS_RESTANTE
		FROM SISTEMA_MAESTRO..AUX_SEMANAS A LEFT JOIN (
			SELECT DISTINCT
			DATA_REFERENCIA,
			'CDT' AS TIPO
			FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_DIARIO_UF_HMM A WITH(NOLOCK)
			WHERE ANO = ${ANO} AND MES = ${MES} AND REGIONAL = 'NO'
		)B ON A.DATA_REFERENCIA = B.DATA_REFERENCIA WHERE A.ANO = ${ANO} AND A.MES = ${MES} AND B.TIPO IS NULL

), PROJECOES AS (

	SELECT
	CONSUMO,
	ROUND((1-(SALDO_DIARIO_FORECAST / CAST((AVG_PLANTA * DENOMINADOR_FORECAST) AS float))) * 100, 2) AS FORECAST_DISPONIBILIDADE,
	ROUND((1-(SUM_TEMPO / CAST((SUM_PROJECAO_PLANTA * DENOMINADOR_PROJECAO) AS float))) * 100, 2) AS PROJECAO_DISPONIBILIDADE
	FROM (
		SELECT
		ROUND(SUM_TEMPO / CAST((((A.SUM_COLETAS * 60) + (A.AVG_COLETAS * 60 * NULLIF(B.DIAS_RESTANTE, 0))) / 100) AS float) * 100, 2) AS CONSUMO,
		((A.SUM_COLETAS * 60) + (A.AVG_COLETAS * 60 * NULLIF(B.DIAS_RESTANTE, 0))) AS SALDO_TOTAL,
		((((A.SUM_COLETAS * 60) + (A.AVG_COLETAS * 60 * NULLIF(B.DIAS_RESTANTE, 0))) / 100) - A.SUM_TEMPO) / NULLIF(B.DIAS_RESTANTE, 0) AS SALDO_DIARIO_FORECAST,
		(SUM_COLETAS + (AVG_COLETAS * 60 * NULLIF(B.DIAS_RESTANTE, 0))) / CAST(((SUM_PLANTA + (AVG_PLANTA * 60 * NULLIF(B.DIAS_RESTANTE, 0)))) AS float) * 60 AS DENOMINADOR_PROJECAO,
		AVG_COLETAS / CAST(AVG_PLANTA AS float) * 60 AS DENOMINADOR_FORECAST,
		AVG_PLANTA,
		SUM_PLANTA + (AVG_PLANTA * NULLIF(B.DIAS_RESTANTE, 0)) AS SUM_PROJECAO_PLANTA,
		SUM_TEMPO
		FROM ESTATISTICA A
		INNER JOIN DIAS_RESTANTE B ON 1 = 1
	)A

)


SELECT
${DATA_REFERENCIA} AS DATA_REFERENCIA,
${ANO} AS ANO,
${MES} AS MES,
${SEMANA} AS SEMANA,
${DIA} AS DIA,
'REGIONAL' AS TIPO,
'NO' AS NOME,
A.DISPONIBILIDADE_GERAL AS MENSAL,
B.DISPONIBILIDADE_GERAL AS SEMANAL,
C.DISPONIBILIDADE_GERAL AS DIARIO,
100 AS SHARE_PLANTA,
100 AS SHARE_TEMPO,
D.CONSUMO,
D.PROJECAO_DISPONIBILIDADE,
D.FORECAST_DISPONIBILIDADE
FROM MENSAL A
INNER JOIN SEMANAL B ON 1 = 1
INNER JOIN DIARIO C ON 1 = 1
INNER JOIN PROJECOES D ON 1 = 1

--=====================================================================================================================================
--REGIONAL NO
--=====================================================================================================================================
WITH MENSAL AS (

SELECT DISPONIBILIDADE_GERAL FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_MENSAL_REGIONAL_HMM WHERE ANO = 2024 AND MES = 1 AND REGIONAL = 'NO'

), SEMANAL AS (

SELECT DISPONIBILIDADE_GERAL FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_SEMANAL_REGIONAL_HMM WHERE ANO = 2024 AND SEMANA = 2 AND REGIONAL = 'NO'

), DIARIO AS (

SELECT DISPONIBILIDADE_GERAL FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_DIARIO_REGIONAL_HMM WHERE ANO = 2024 AND MES = 1 AND DIA = 9 AND REGIONAL = 'NO' --AND UF IN ('PA','AM','AP','RR','MA')

), ESTATISTICA AS (

	SELECT
	AVG(PLANTA) AS AVG_PLANTA,
	SUM(PLANTA) AS SUM_PLANTA,
	AVG(COLETAS) AS AVG_COLETAS,
	SUM(COLETAS) AS SUM_COLETAS,
	AVG(TEMPO) AS AVG_TEMPO,
	SUM(TEMPO) AS SUM_TEMPO
	FROM (
		SELECT
		DATA_REFERENCIA,
		COUNT(DISTINCT CONCAT(SITE, ERB, SETOR)) AS PLANTA,
		ISNULL(SUM(COLETAS_HMM), 0) AS COLETAS,
		SUM(CASE WHEN TEMPO_CONTADOR_HMM >= 0 THEN TEMPO_CONTADOR_HMM ELSE 0 END) TEMPO
		FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES A WITH (NOLOCK)
		WHERE TECNOLOGIA <> 'GSM' AND REGIONAL = 'NO' AND YEAR(DATA_REFERENCIA) = 2024 AND MONTH(DATA_REFERENCIA) = 1
		GROUP BY DATA_REFERENCIA
	)A

), DIAS_RESTANTE AS (

		SELECT
		COUNT(*) AS DIAS_RESTANTE
		FROM SISTEMA_MAESTRO..AUX_SEMANAS A LEFT JOIN (
			SELECT DISTINCT
			DATA_REFERENCIA,
			'CDT' AS TIPO
			FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_DIARIO_UF_HMM A WITH(NOLOCK)
			WHERE ANO = 2024 AND MES = 1 AND REGIONAL = 'NO'
		)B ON A.DATA_REFERENCIA = B.DATA_REFERENCIA WHERE A.ANO = 2024 AND A.MES = 1 AND B.TIPO IS NULL

), PROJECOES AS (

	SELECT
	CONSUMO,
	ROUND((1-(SALDO_DIARIO_FORECAST / CAST((AVG_PLANTA * DENOMINADOR_FORECAST) AS float))) * 100, 2) AS FORECAST_DISPONIBILIDADE,
	ROUND((1-(SUM_TEMPO / CAST((SUM_PROJECAO_PLANTA * DENOMINADOR_PROJECAO) AS float))) * 100, 2) AS PROJECAO_DISPONIBILIDADE
	FROM (
		SELECT
		ROUND(SUM_TEMPO / CAST((((A.SUM_COLETAS * 60) + (A.AVG_COLETAS * 60 * NULLIF(B.DIAS_RESTANTE, 0))) / 100) AS float) * 100, 2) AS CONSUMO,
		((A.SUM_COLETAS * 60) + (A.AVG_COLETAS * 60 * NULLIF(B.DIAS_RESTANTE, 0))) AS SALDO_TOTAL,
		((((A.SUM_COLETAS * 60) + (A.AVG_COLETAS * 60 * NULLIF(B.DIAS_RESTANTE, 0))) / 100) - A.SUM_TEMPO) / NULLIF(B.DIAS_RESTANTE, 0) AS SALDO_DIARIO_FORECAST,
		(SUM_COLETAS + (AVG_COLETAS * 60 * NULLIF(B.DIAS_RESTANTE, 0))) / CAST(((SUM_PLANTA + (AVG_PLANTA * 60 * NULLIF(B.DIAS_RESTANTE, 0)))) AS float) * 60 AS DENOMINADOR_PROJECAO,
		AVG_COLETAS / CAST(AVG_PLANTA AS float) * 60 AS DENOMINADOR_FORECAST,
		AVG_PLANTA,
		SUM_PLANTA + (AVG_PLANTA * NULLIF(B.DIAS_RESTANTE, 0)) AS SUM_PROJECAO_PLANTA,
		SUM_TEMPO
		FROM ESTATISTICA A
		INNER JOIN DIAS_RESTANTE B ON 1 = 1
	)A

)


SELECT
'09/01/2024' AS DATA_REFERENCIA,
2024 AS ANO,
1 AS MES,
2 AS SEMANA,
9 AS DIA,
'REGIONAL' AS TIPO,
'NO' AS NOME,
A.DISPONIBILIDADE_GERAL AS MENSAL,
B.DISPONIBILIDADE_GERAL AS SEMANAL,
C.DISPONIBILIDADE_GERAL AS DIARIO,
100 AS SHARE_PLANTA,
100 AS SHARE_TEMPO,
D.CONSUMO,
D.PROJECAO_DISPONIBILIDADE,
D.FORECAST_DISPONIBILIDADE
FROM MENSAL A
INNER JOIN SEMANAL B ON 1 = 1
INNER JOIN DIARIO C ON 1 = 1
INNER JOIN PROJECOES D ON 1 = 1




