-- =======================================================
-- ESTRUTURANTES MG - CALCULO DA DISPONIBILIDADE
-- =======================================================

-- 7 dias antes da data de migracao
SELECT
    '7_DIAS_ANTES' AS TEMPO,
    A.UF,
    A.REGIONAL,
    A.SITE,
    B.DT_MIGRACAO,
    STATUS_ATIVACAO,
    EQUIPAMENTO,
    ID_METRO,
    HOSTNAME,
    LOCALIDADE,
    STATUS_ESTRUTURANTE,
    STATUS_SUBGRUPO,
    [HL4-PREDECESSOR],
    [HL5D-PREDECESSOR],
    EPS,
    ROUND(((1-(SUM(CASE WHEN TECNOLOGIA = 'LTE' AND TEMPO_CONTADOR_HMM >= 0 THEN CAST(TEMPO_CONTADOR_HMM AS FLOAT) END)/(SUM(CASE WHEN TECNOLOGIA = 'LTE' THEN CAST(COLETAS_HMM AS FLOAT) END)*60)))*100),2) AS DISP_4G
FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES A WITH(NOLOCK)
LEFT JOIN QUALIDADE..TBL_ESTRUTURANTES_MG_BI B WITH(NOLOCK) ON A.UF COLLATE Latin1_General_CI_AI = 'MG' AND A.UF+A.SITE COLLATE Latin1_General_CI_AI = B.SITE COLLATE Latin1_General_CI_AI
WHERE A.DATA_REFERENCIA <= CONVERT(DATETIME,DT_MIGRACAO,103) AND A.DATA_REFERENCIA >= CONVERT(DATETIME,DT_MIGRACAO,103)-7 AND UF = 'MG' 
GROUP BY REGIONAL, UF, A.SITE, DT_MIGRACAO,STATUS_ATIVACAO,EQUIPAMENTO,ID_METRO,HOSTNAME,LOCALIDADE,STATUS_ESTRUTURANTE,STATUS_SUBGRUPO,[HL4-PREDECESSOR],[HL5D-PREDECESSOR],EPS

UNION ALL

-- 7 dias depois da data de migracao
SELECT
    '7_DIAS_DEPOIS' AS TEMPO,
    A.UF,
    A.REGIONAL,
    A.SITE,
    B.DT_MIGRACAO,
    STATUS_ATIVACAO,
    EQUIPAMENTO,
    ID_METRO,
    HOSTNAME,
    LOCALIDADE,
    STATUS_ESTRUTURANTE,
    STATUS_SUBGRUPO,
    [HL4-PREDECESSOR],
    [HL5D-PREDECESSOR],
    EPS,
    ROUND(((1-(SUM(CASE WHEN TECNOLOGIA = 'LTE' AND TEMPO_CONTADOR_HMM >= 0 THEN CAST(TEMPO_CONTADOR_HMM AS FLOAT) END)/(SUM(CASE WHEN TECNOLOGIA = 'LTE' THEN CAST(COLETAS_HMM AS FLOAT) END)*60)))*100),2) AS DISP_4G
FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES A WITH(NOLOCK)
LEFT JOIN QUALIDADE..TBL_ESTRUTURANTES_MG_BI B WITH(NOLOCK) ON A.UF COLLATE Latin1_General_CI_AI = 'MG' AND A.UF+A.SITE COLLATE Latin1_General_CI_AI = B.SITE COLLATE Latin1_General_CI_AI
WHERE A.DATA_REFERENCIA >= CONVERT(DATETIME,DT_MIGRACAO,103) AND A.DATA_REFERENCIA <= CONVERT(DATETIME,DT_MIGRACAO,103)+7 AND UF = 'MG' 
GROUP BY REGIONAL, UF, A.SITE, DT_MIGRACAO,STATUS_ATIVACAO,EQUIPAMENTO,ID_METRO,HOSTNAME,LOCALIDADE,STATUS_ESTRUTURANTE,STATUS_SUBGRUPO,[HL4-PREDECESSOR],[HL5D-PREDECESSOR],EPS

UNION ALL

-- 15 dias antes da data de migracao
SELECT
    '15_DIAS_ANTES' AS TEMPO,
    A.UF,
    A.REGIONAL,
    A.SITE,
    B.DT_MIGRACAO,
    STATUS_ATIVACAO,
    EQUIPAMENTO,
    ID_METRO,
    HOSTNAME,
    LOCALIDADE,
    STATUS_ESTRUTURANTE,
    STATUS_SUBGRUPO,
    [HL4-PREDECESSOR],
    [HL5D-PREDECESSOR],
    EPS,
    ROUND(((1-(SUM(CASE WHEN TECNOLOGIA = 'LTE' AND TEMPO_CONTADOR_HMM >= 0 THEN CAST(TEMPO_CONTADOR_HMM AS FLOAT) END)/(SUM(CASE WHEN TECNOLOGIA = 'LTE' THEN CAST(COLETAS_HMM AS FLOAT) END)*60)))*100),2) AS DISP_4G
FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES A WITH(NOLOCK)
LEFT JOIN QUALIDADE..TBL_ESTRUTURANTES_MG_BI B WITH(NOLOCK) ON A.UF COLLATE Latin1_General_CI_AI = 'MG' AND A.UF+A.SITE COLLATE Latin1_General_CI_AI = B.SITE COLLATE Latin1_General_CI_AI
WHERE A.DATA_REFERENCIA <= CONVERT(DATETIME,DT_MIGRACAO,103) AND A.DATA_REFERENCIA >= CONVERT(DATETIME,DT_MIGRACAO,103)-15 AND UF = 'MG' 
GROUP BY REGIONAL, UF, A.SITE, DT_MIGRACAO,STATUS_ATIVACAO,EQUIPAMENTO,ID_METRO,HOSTNAME,LOCALIDADE,STATUS_ESTRUTURANTE,STATUS_SUBGRUPO,[HL4-PREDECESSOR],[HL5D-PREDECESSOR],EPS

UNION ALL

-- 15 dias depois da data de migracao
SELECT
    '15_DIAS_DEPOIS' AS TEMPO,
    A.UF,
    A.REGIONAL,
    A.SITE,
    B.DT_MIGRACAO,
    STATUS_ATIVACAO,
    EQUIPAMENTO,
    ID_METRO,
    HOSTNAME,
    LOCALIDADE,
    STATUS_ESTRUTURANTE,
    STATUS_SUBGRUPO,
    [HL4-PREDECESSOR],
    [HL5D-PREDECESSOR],
    EPS,
    ROUND(((1-(SUM(CASE WHEN TECNOLOGIA = 'LTE' AND TEMPO_CONTADOR_HMM >= 0 THEN CAST(TEMPO_CONTADOR_HMM AS FLOAT) END)/(SUM(CASE WHEN TECNOLOGIA = 'LTE' THEN CAST(COLETAS_HMM AS FLOAT) END)*60)))*100),2) AS DISP_4G
FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES A WITH(NOLOCK)
LEFT JOIN QUALIDADE..TBL_ESTRUTURANTES_MG_BI B WITH(NOLOCK) ON A.UF COLLATE Latin1_General_CI_AI = 'MG' AND A.UF+A.SITE COLLATE Latin1_General_CI_AI = B.SITE COLLATE Latin1_General_CI_AI
WHERE A.DATA_REFERENCIA >= CONVERT(DATETIME,DT_MIGRACAO,103) AND A.DATA_REFERENCIA <= CONVERT(DATETIME,DT_MIGRACAO,103)+15 AND UF = 'MG'
GROUP BY REGIONAL, UF, A.SITE, DT_MIGRACAO,STATUS_ATIVACAO,EQUIPAMENTO,ID_METRO,HOSTNAME,LOCALIDADE,STATUS_ESTRUTURANTE,STATUS_SUBGRUPO,[HL4-PREDECESSOR],[HL5D-PREDECESSOR],EPS

UNION ALL

-- 30 dias antes da data de migracao
SELECT
    '30_DIAS_ANTES' AS TEMPO,
    A.UF,
    A.REGIONAL,
    A.SITE,
    B.DT_MIGRACAO,
    STATUS_ATIVACAO,
    EQUIPAMENTO,
    ID_METRO,
    HOSTNAME,
    LOCALIDADE,
    STATUS_ESTRUTURANTE,
    STATUS_SUBGRUPO,
    [HL4-PREDECESSOR],
    [HL5D-PREDECESSOR],
    EPS,
    ROUND(((1-(SUM(CASE WHEN TECNOLOGIA = 'LTE' AND TEMPO_CONTADOR_HMM >= 0 THEN CAST(TEMPO_CONTADOR_HMM AS FLOAT) END)/(SUM(CASE WHEN TECNOLOGIA = 'LTE' THEN CAST(COLETAS_HMM AS FLOAT) END)*60)))*100),2) AS DISP_4G
FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES A WITH(NOLOCK)
LEFT JOIN QUALIDADE..TBL_ESTRUTURANTES_MG_BI B WITH(NOLOCK) ON A.UF COLLATE Latin1_General_CI_AI = 'MG' AND A.UF+A.SITE COLLATE Latin1_General_CI_AI = B.SITE COLLATE Latin1_General_CI_AI
WHERE A.DATA_REFERENCIA <= CONVERT(DATETIME,DT_MIGRACAO,103) AND A.DATA_REFERENCIA >= CONVERT(DATETIME,DT_MIGRACAO,103)-30 AND UF = 'MG'
GROUP BY REGIONAL, UF, A.SITE, DT_MIGRACAO,STATUS_ATIVACAO,EQUIPAMENTO,ID_METRO,HOSTNAME,LOCALIDADE,STATUS_ESTRUTURANTE,STATUS_SUBGRUPO,[HL4-PREDECESSOR],[HL5D-PREDECESSOR],EPS

UNION ALL

-- 30 dias depois da data de migracao
SELECT
    '30_DIAS_DEPOIS' AS TEMPO,
    A.UF,
    A.REGIONAL,
    A.SITE,
    B.DT_MIGRACAO,
    STATUS_ATIVACAO,
    EQUIPAMENTO,
    ID_METRO,
    HOSTNAME,
    LOCALIDADE,
    STATUS_ESTRUTURANTE,
    STATUS_SUBGRUPO,
    [HL4-PREDECESSOR],
    [HL5D-PREDECESSOR],
    EPS,
    ROUND(((1-(SUM(CASE WHEN TECNOLOGIA = 'LTE' AND TEMPO_CONTADOR_HMM >= 0 THEN CAST(TEMPO_CONTADOR_HMM AS FLOAT) END)/(SUM(CASE WHEN TECNOLOGIA = 'LTE' THEN CAST(COLETAS_HMM AS FLOAT) END)*60)))*100),2) AS DISP_4G
FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES A WITH(NOLOCK)
LEFT JOIN QUALIDADE..TBL_ESTRUTURANTES_MG_BI B WITH(NOLOCK) ON A.UF COLLATE Latin1_General_CI_AI = 'MG' AND A.UF+A.SITE COLLATE Latin1_General_CI_AI = B.SITE COLLATE Latin1_General_CI_AI
WHERE A.DATA_REFERENCIA >= CONVERT(DATETIME,DT_MIGRACAO,103) AND A.DATA_REFERENCIA <= CONVERT(DATETIME,DT_MIGRACAO,103)+30 AND UF = 'MG'
GROUP BY REGIONAL, UF, A.SITE, DT_MIGRACAO,STATUS_ATIVACAO,EQUIPAMENTO,ID_METRO,HOSTNAME,LOCALIDADE,STATUS_ESTRUTURANTE,STATUS_SUBGRUPO,[HL4-PREDECESSOR],[HL5D-PREDECESSOR],EPS

UNION ALL

-- 45 dias antes da data de migracao
SELECT
    '45_DIAS_ANTES' AS TEMPO,
    A.UF,
    A.REGIONAL,
    A.SITE,
    B.DT_MIGRACAO,
    STATUS_ATIVACAO,
    EQUIPAMENTO,
    ID_METRO,
    HOSTNAME,
    LOCALIDADE,
    STATUS_ESTRUTURANTE,
    STATUS_SUBGRUPO,
    [HL4-PREDECESSOR],
    [HL5D-PREDECESSOR],
    EPS,
    ROUND(((1-(SUM(CASE WHEN TECNOLOGIA = 'LTE' AND TEMPO_CONTADOR_HMM >= 0 THEN CAST(TEMPO_CONTADOR_HMM AS FLOAT) END)/(SUM(CASE WHEN TECNOLOGIA = 'LTE' THEN CAST(COLETAS_HMM AS FLOAT) END)*60)))*100),2) AS DISP_4G
FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES A WITH(NOLOCK)
LEFT JOIN QUALIDADE..TBL_ESTRUTURANTES_MG_BI B WITH(NOLOCK) ON A.UF COLLATE Latin1_General_CI_AI = 'MG' AND A.UF+A.SITE COLLATE Latin1_General_CI_AI = B.SITE COLLATE Latin1_General_CI_AI
WHERE A.DATA_REFERENCIA <= CONVERT(DATETIME,DT_MIGRACAO,103) AND A.DATA_REFERENCIA >= CONVERT(DATETIME,DT_MIGRACAO,103)-45 AND UF = 'MG' 
GROUP BY REGIONAL, UF, A.SITE, DT_MIGRACAO,STATUS_ATIVACAO,EQUIPAMENTO,ID_METRO,HOSTNAME,LOCALIDADE,STATUS_ESTRUTURANTE,STATUS_SUBGRUPO,[HL4-PREDECESSOR],[HL5D-PREDECESSOR],EPS

UNION ALL

-- 45 dias depois da data de migracao
SELECT
    '45_DIAS_DEPOIS' AS TEMPO,
    A.UF,
    A.REGIONAL,
    A.SITE,
    B.DT_MIGRACAO,
    STATUS_ATIVACAO,
    EQUIPAMENTO,
    ID_METRO,
    HOSTNAME,
    LOCALIDADE,
    STATUS_ESTRUTURANTE,
    STATUS_SUBGRUPO,
    [HL4-PREDECESSOR],
    [HL5D-PREDECESSOR],
    EPS,
    ROUND(((1-(SUM(CASE WHEN TECNOLOGIA = 'LTE' AND TEMPO_CONTADOR_HMM >= 0 THEN CAST(TEMPO_CONTADOR_HMM AS FLOAT) END)/(SUM(CASE WHEN TECNOLOGIA = 'LTE' THEN CAST(COLETAS_HMM AS FLOAT) END)*60)))*100),2) AS DISP_4G
FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES A WITH(NOLOCK)
LEFT JOIN QUALIDADE..TBL_ESTRUTURANTES_MG_BI B WITH(NOLOCK) ON A.UF COLLATE Latin1_General_CI_AI = 'MG' AND A.UF+A.SITE COLLATE Latin1_General_CI_AI = B.SITE COLLATE Latin1_General_CI_AI
WHERE A.DATA_REFERENCIA >= CONVERT(DATETIME,DT_MIGRACAO,103) AND A.DATA_REFERENCIA <= CONVERT(DATETIME,DT_MIGRACAO,103)+45 AND UF = 'MG' 
GROUP BY REGIONAL, UF, A.SITE, DT_MIGRACAO,STATUS_ATIVACAO,EQUIPAMENTO,ID_METRO,HOSTNAME,LOCALIDADE,STATUS_ESTRUTURANTE,STATUS_SUBGRUPO,[HL4-PREDECESSOR],[HL5D-PREDECESSOR],EPS




CREATE VIEW VW_ESTRUTURANTES_MG_DISP AS
SELECT
    DATA_REFERENCIA,
    A.UF+A.SITE AS SITE,
    DISPONIBILIDADE_4G AS DISP_4G,
    B.DT_MIGRACAO
FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_DIARIO_SITE_HMM A
LEFT JOIN QUALIDADE..TBL_ESTRUTURANTES_MG_BI B WITH(NOLOCK) ON A.UF COLLATE Latin1_General_CI_AI = 'MG' AND A.UF+A.SITE COLLATE Latin1_General_CI_AI = B.SITE COLLATE Latin1_General_CI_AI
WHERE A.UF = 'MG'