






--DISP. MENSAL POR SITE (4G+5G)
SELECT
REGIONAL,
B.UF,
B.MUNICIPIO,
B.SITE,
'4G+5G' AS TECNOLOGIA,
SITE,
ROUND((1-(TEMPO / (CAST(PLANTA AS float) * DENOMINADOR))) * 100, 2) AS DISPONIBILIDADE
FROM (
	SELECT
	*,
	COLETAS / CAST(PLANTA AS float) * 60 AS DENOMINADOR
	FROM (
		SELECT
		A.REGIONAL,
		A.UF,
        A.MUNICIPIO,
        A.SITE,
		COUNT(DISTINCT CONCAT(UF, SITE, ERB, SETOR)) AS PLANTA,
		ISNULL(SUM(COLETAS_HMM), 0) AS COLETAS,
		SUM(CASE WHEN TEMPO_CONTADOR_HMM >= 0 THEN TEMPO_CONTADOR_HMM ELSE 0 END) TEMPO
		FROM (SELECT * FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES WITH(NOLOCK) UNION ALL SELECT * FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES_HIST_2023 WITH(NOLOCK)) A 
		WHERE DATA_REFERENCIA >= '2023-08-01' AND DATA_REFERENCIA < '2023-09-01' AND TECNOLOGIA IN ('LTE', '5G') AND COLETAS_HMM > 0
		GROUP BY A.REGIONAL, A.UF, A.SITE
	)A
)B
ORDER BY REGIONAL, UF, B.SITE

-- ============================================
SELECT 
ANO, 
MES, 
CASE WHEN A.UF = 'SP' THEN B.NOME_REGIONAL
     WHEN A.UF IN ('BA', 'SE', 'AL', 'RN', 'PB', 'CE', 'PI', 'PE') THEN 'NE' 
     WHEN A.UF = 'MG' THEN 'MG'
     WHEN A.UF IN ('RJ', 'ES') THEN 'RJ/ES'
     WHEN A.UF IN ('PR', 'SC', 'RS') THEN 'SUL'
     WHEN A.UF IN ('AM', 'PA', 'MA', 'AP', 'RR') THEN 'NO'
     WHEN A.UF IN ('AC', 'MS', 'MT', 'RO', 'DF', 'GO', 'TO') THEN 'CO'
END REGIONAL,
UF,
A.MUNICIPIO,
DISPONIBILIDADE_GERAL AS DISP_GERAL,
NOTA_IND11 
FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_MENSAL_MUNICIPIO_HMM A
LEFT JOIN INDICADORES_CORAN..TBA_DIVISAO_MUNICIPIOS_SP_FIXA B ON A.MUNICIPIO = B.MUNICIPIO AND A.UF = 'SP'
WHERE DISPONIBILIDADE_GERAL IS NOT NULL
AND ANO = (SELECT CASE WHEN YEAR(GETDATE()) = YEAR(GETDATE()-1) THEN YEAR(GETDATE()) ELSE YEAR(GETDATE()-1) END)
AND MES = (SELECT CASE WHEN MONTH(GETDATE()) = MONTH(GETDATE()-1) THEN MONTH(GETDATE()) ELSE MONTH(GETDATE()-1) END)


-- ==========================================
-- ESTUDO QUEDA DISPONIBILIDADE DAS CAPITAIS
-- ==========================================

-- EVOLUÇÃO DA PLANTA DE ERBS DAS CAPITAIS
SELECT
DATEPART(YEAR,A.DATA_REFERENCIA) AS ANO,
DATEPART(MONTH, DATA_REFERENCIA) AS MES,
A.UF,
A.MUNICIPIO,
COUNT(DISTINCT ERB) AS QTDE_ERBS
FROM (SELECT * FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES_HIST_2023 WITH(NOLOCK) UNION ALL SELECT * FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES WITH(NOLOCK)) A
INNER JOIN INDICADORES_CORAN..TBA_CLASSIFICACAO_MUNICIPIOS B ON A.UF = B.UF AND A.MUNICIPIO = B.MUNICIPIO
WHERE CLASSIFICACAO = 'TOP 50' AND DATEPART(YEAR,DATA_REFERENCIA) IN (2023,2024) --AND DATEPART(MONTH,DATA_REFERENCIA) = 5 AND DATEPART(DAY, DATA_REFERENCIA) = 31
AND TECNOLOGIA <> 'GSM'
GROUP BY A.UF, A.MUNICIPIO, DATEPART(YEAR,A.DATA_REFERENCIA), DATEPART(MONTH, DATA_REFERENCIA)
ORDER BY ANO, MES, A.UF, A.MUNICIPIO



-- SELECT DISTINCT DATEPART(YEAR,A.DATA_ATIVACAO) AS ANO, DATEPART(MONTH,A.DATA_ATIVACAO) AS MES, A.UF, B.MUNICIPIO, A.SIGLA_SITE, SUM(TEMPO_CONTADOR_HMM) AS CDT
-- FROM SISTEMA_MAESTRO..TBL_SITES_HL5 A
-- INNER JOIN SISTEMA_MAESTRO..TBA_PLANTA_MOVEL B ON A.UF = B.UF AND A.SIGLA_SITE = B.SIGLA_SITE
-- LEFT JOIN SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES C ON A.UF = C.UF AND A.SIGLA_SITE = C.SITE AND DATA_ATIVACAO = DATA_REFERENCIA
-- WHERE DATEPART(YEAR, DATA_ATIVACAO) IN (2024) AND B.MUNICIPIO = 'RECIFE' AND DATEPART(MONTH,A.DATA_ATIVACAO) = 5 AND C.TECNOLOGIA <> 'GSM'  AND TEMPO_CONTADOR_HMM >= 0 
-- GROUP BY DATEPART(YEAR,A.DATA_ATIVACAO), DATEPART(MONTH,A.DATA_ATIVACAO), A.UF, B.MUNICIPIO, A.SIGLA_SITE
-- ORDER BY B.MUNICIPIO, A.UF, A.SIGLA_SITE

SELECT SUM(TEMPO_CONTADOR_HMM) FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES WHERE UF = 'PE' AND SITE = 'APL' AND DATEPART(YEAR, DATA_REFERENCIA) = 2024 AND DATEPART(MONTH, DATA_REFERENCIA) = 5


SELECT A.DATA_ATIVACAO, A.UF, A.SIGLA_SITE, B.MUNICIPIO, B.DISPONIBILIDADE_GERAL AS DISP_GERAL, DISPONIBILIDADE_3G AS DISP_3G, DISPONIBILIDADE_4G AS DISP_4G, DISPONIBILIDADE_5G AS DISP_5G
FROM SISTEMA_MAESTRO..TBL_SITES_HL5 A
LEFT JOIN INDICADORES_CORAN..TBF_CELLDOWNTIME_MENSAL_SITE B ON A.UF = B.UF AND A.SIGLA_SITE = B.SITE AND A.DATA_ATIVACAO = B.DATA_REFERENCIA
WHERE DATEPART(YEAR, DATA_ATIVACAO) IN (2023, 2024) AND B.MUNICIPIO IN ('RECIFE')
ORDER BY B.MUNICIPIO, A.UF, A.SIGLA_SITE

-- Quantos sites são migrados no município?
SELECT A.UF, B.MUNICIPIO, COUNT(DISTINCT A.UF+A.SIGLA_SITE) AS QTDE
FROM SISTEMA_MAESTRO..TBL_SITES_HL5 A
INNER JOIN SISTEMA_MAESTRO..TBA_PLANTA_MOVEL B ON A.UF = B.UF AND A.SIGLA_SITE = B.SIGLA_SITE
WHERE DATEPART(YEAR, DATA_ATIVACAO) IN (2023, 2024)
GROUP BY A.UF, B.MUNICIPIO
ORDER BY QTDE DESC

-- Share dos migrados no município

SELECT * FROM SISTEMA_MAESTRO..TBL_SITES_HL5 WHERE DATEPART(YEAR, DATA_ATIVACAO) IN (2023, 2024)

-- ATIVACAO HL5
SELECT DATA_ATIVACAO, COUNT(DISTINCT UF+SIGLA_SITE) AS QTDE FROM SISTEMA_MAESTRO..TBL_SITES_HL5
GROUP BY DATA_ATIVACAO ORDER BY QTDE DESC

SELECT * FROM SISTEMA_MAESTRO..TBL_SITES_LEGADO



WITH PLANTA AS (

SELECT UF, MUNICIPIO, COUNT(DISTINCT UF+SIGLA_SITE) AS QTDE_SITES FROM SISTEMA_MAESTRO..TBA_PLANTA_MOVEL GROUP BY UF, MUNICIPIO

),

HL5 AS (

SELECT DISTINCT A.UF, B.MUNICIPIO, COUNT(DISTINCT A.UF+A.SIGLA_SITE) AS QTDE_MIGRADOS FROM SISTEMA_MAESTRO..TBL_SITES_HL5 A INNER JOIN SISTEMA_MAESTRO..TBA_PLANTA_MOVEL B ON A.UF = B.UF AND A.SIGLA_SITE = B.SIGLA_SITE GROUP BY A.UF, B.MUNICIPIO

)

SELECT * FROM PLANTA A
INNER JOIN HL5 B ON A.UF = B.UF AND A.SIGLA_SITE = B.SIGLA_SITE

WITH PLANTAS AS (
			SELECT
			UF,
            MUNICIPIO,
			SIGLA_SITE AS SITE,
			COUNT(DISTINCT CONCAT(UF,MUNICIPIO,SIGLA_SITE, SIGLA_ERB, SETOR)) AS PLANTA
			FROM (
				SELECT DISTINCT B.*
                FROM SISTEMA_MAESTRO..TBL_SITES_HL5 A
                INNER JOIN SISTEMA_MAESTRO..TBA_PLANTA_MOVEL B ON A.UF = B.UF AND A.SIGLA_SITE = B.SIGLA_SITE
				EXCEPT
				SELECT DISTINCT B.*
                FROM SISTEMA_MAESTRO..TBL_SITES_HL5 A
                INNER JOIN SISTEMA_MAESTRO..TBA_PLANTA_MOVEL B ON A.UF = B.UF AND A.SIGLA_SITE = B.SIGLA_SITE WHERE SIGLA_LOGICA LIKE '5%' AND TECNOLOGIA = 'LTE'
			)A1 GROUP BY UF, SIGLA_SITE, MUNICIPIO
)

SELECT
*,
ROUND(PLANTA / CAST(SUM(PLANTA) OVER (PARTITION BY UF, MUNICIPIO ORDER BY UF, MUNICIPIO ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS float) * 100, 2) AS SHARE_PLANTA
FROM PLANTAS

-- =================================================================================
SELECT DATEFROMPARTS(ANO,MES,'01') AS DATA, A.UF, A.MUNICIPIO, DISPONIBILIDADE_GERAL AS DISP_MENSAL_MUNICIPIO 
FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_MENSAL_MUNICIPIO_HMM A
INNER JOIN INDICADORES_CORAN..TBA_CLASSIFICACAO_MUNICIPIOS B ON A.UF = B.UF AND A.MUNICIPIO = B.MUNICIPIO
WHERE CLASSIFICACAO = 'TOP 50' AND A.ANO IN (2023,2024)
ORDER BY UF, MUNICIPIO, DATA
-- =================================================================================

WITH DISP AS (

SELECT DATEFROMPARTS(ANO,MES,'01') AS DATA, A.UF, A.MUNICIPIO, DISPONIBILIDADE_GERAL AS DISP_MENSAL_MUNICIPIO 
FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_MENSAL_MUNICIPIO_HMM A
INNER JOIN INDICADORES_CORAN..TBA_CLASSIFICACAO_MUNICIPIOS B ON A.UF = B.UF AND A.MUNICIPIO = B.MUNICIPIO
WHERE CLASSIFICACAO = 'TOP 50' AND A.ANO IN (2023,2024)
),

MIGRADOS AS (

SELECT DISTINCT DATA_ATIVACAO,A.UF, B.MUNICIPIO, A.SIGLA_SITE
FROM SISTEMA_MAESTRO..TBL_SITES_HL5 A
INNER JOIN SISTEMA_MAESTRO..TBA_PLANTA_MOVEL B ON A.UF = B.UF AND A.SIGLA_SITE = B.SIGLA_SITE
WHERE DATEPART(YEAR, DATA_ATIVACAO) IN (2023, 2024)
)

SELECT
*
FROM MIGRADOS A
RIGHT JOIN DISP B ON A.UF = B.UF AND A.MUNICIPIO = B.MUNICIPIO AND DATEPART(YEAR, A.DATA_ATIVACAO) = DATEPART(YEAR, B.DATA) AND DATEPART(MONTH, A.DATA_ATIVACAO) = DATEPART(MONTH, B.DATA)
ORDER BY B.UF, B.MUNICIPIO, DATA




-- ====================================================================================================================================
WITH DISP AS (

SELECT DATEFROMPARTS(ANO,MES,'01') AS DATA, A.UF, A.MUNICIPIO, DISPONIBILIDADE_GERAL AS DISP_MENSAL_GERAL_MUN, DISPONIBILIDADE_3G AS DISP_MENSAL_3G_MUN, DISPONIBILIDADE_4G AS DISP_MENSAL_4G_MUN, DISPONIBILIDADE_5G AS DISP_MENSAL_5G_MUN
FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_MENSAL_MUNICIPIO A
INNER JOIN INDICADORES_CORAN..TBA_CLASSIFICACAO_MUNICIPIOS B ON A.UF = B.UF AND A.MUNICIPIO = B.MUNICIPIO
WHERE CLASSIFICACAO = 'TOP 50' AND A.ANO IN (2023,2024)
),

MIGRADOS AS (

SELECT DATEFROMPARTS(DATEPART(YEAR,DATA_ATIVACAO),DATEPART(MONTH,DATA_ATIVACAO),'01') AS DATA, A.UF, B.MUNICIPIO, COUNT(DISTINCT A.UF+B.MUNICIPIO+A.SIGLA_SITE) AS QTDE_ATIVACOES
FROM SISTEMA_MAESTRO..TBL_SITES_HL5 A
INNER JOIN SISTEMA_MAESTRO..TBA_PLANTA_MOVEL B ON A.UF = B.UF AND A.SIGLA_SITE = B.SIGLA_SITE
WHERE DATEPART(YEAR, DATA_ATIVACAO) IN (2023, 2024)
GROUP BY DATEFROMPARTS(DATEPART(YEAR,DATA_ATIVACAO),DATEPART(MONTH,DATA_ATIVACAO),'01'), A.UF, B.MUNICIPIO
),

PLANTA AS (
SELECT
    DATEPART(YEAR,A.DATA_REFERENCIA) AS ANO,
    DATEPART(MONTH, DATA_REFERENCIA) AS MES,
    A.UF,
    A.MUNICIPIO,
    COUNT(DISTINCT ERB) AS QTDE_ERBS
FROM (SELECT * FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES_HIST_2023 WITH(NOLOCK) UNION ALL SELECT * FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES_HIST_2023 WITH(NOLOCK)) A
INNER JOIN INDICADORES_CORAN..TBA_CLASSIFICACAO_MUNICIPIOS B ON A.UF = B.UF AND A.MUNICIPIO = B.MUNICIPIO
WHERE CLASSIFICACAO = 'TOP 50' AND DATEPART(YEAR,DATA_REFERENCIA) IN (2023,2024) --AND DATEPART(DAY,DATA_REFERENCIA) = EOMONTH(A.DATA_REFERENCIA)
AND TECNOLOGIA <> 'GSM'
GROUP BY A.UF, A.MUNICIPIO, DATEPART(YEAR,A.DATA_REFERENCIA), DATEPART(MONTH, DATA_REFERENCIA)
)


SELECT
A.DATA, A.UF, A.MUNICIPIO, A.DISP_MENSAL_GERAL_MUN, A.DISP_MENSAL_3G_MUN, DISP_MENSAL_4G_MUN, DISP_MENSAL_5G_MUN, B.QTDE_ATIVACOES--, C.QTDE_ERBS
FROM DISP A
LEFT JOIN MIGRADOS B ON A.UF = B.UF AND A.MUNICIPIO = B.MUNICIPIO AND A.DATA = B.DATA
--LEFT JOIN PLANTA C ON A.UF = C.UF AND A.MUNICIPIO = C.MUNICIPIO
ORDER BY A.UF, A.MUNICIPIO, A.DATA

-- ==========================================================================================================================
-- CDT MENSAL POR SITE COM HL5

WITH CDT AS (
SELECT
    DATEFROMPARTS(DATEPART(YEAR,DATA_REFERENCIA),DATEPART(MONTH,DATA_REFERENCIA),'01') AS DATA,
    UF,
    MUNICIPIO,
    SITE,
    SUM(TEMPO_CONTADOR_HMM) AS CDT
FROM  (SELECT * FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES WITH(NOLOCK) UNION ALL SELECT * FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES_HIST_2023 WITH(NOLOCK)) A
WHERE TEMPO_CONTADOR_HMM >=0 AND TECNOLOGIA <> 'GSM' AND DATEPART(YEAR,DATA_REFERENCIA) IN (2023,2024)
GROUP BY DATEPART(YEAR,DATA_REFERENCIA), DATEPART(MONTH, DATA_REFERENCIA), UF, MUNICIPIO, SITE
),

HL5 AS (
SELECT 
    DATEFROMPARTS(DATEPART(YEAR,DATA_ATIVACAO),DATEPART(MONTH,DATA_ATIVACAO),'01') AS DATA,
    A.UF, 
    B.MUNICIPIO,
    A.SIGLA_SITE
FROM SISTEMA_MAESTRO..TBL_SITES_HL5 A
INNER JOIN (SELECT UF, MUNICIPIO, SIGLA_SITE FROM SISTEMA_MAESTRO..TBA_PLANTA_MOVEL GROUP BY UF, MUNICIPIO, SIGLA_SITE) B ON A.UF = B.UF AND A.SIGLA_SITE = B.SIGLA_SITE
WHERE DATEPART(YEAR, DATA_ATIVACAO) IN (2023, 2024)
)

SELECT
    A.DATA,
    A.UF,
    A.MUNICIPIO,
    -- B.SIGLA_SITE,
    A.CDT,
    B.DATA
FROM CDT A
LEFT JOIN HL5 B ON A.UF = B.UF AND A.MUNICIPIO = B.MUNICIPIO AND A.SITE = B.SIGLA_SITE --AND A.DATA = B.DATA
INNER JOIN INDICADORES_CORAN..TBA_CLASSIFICACAO_MUNICIPIOS C ON B.UF = C.UF AND B.MUNICIPIO = C.MUNICIPIO
WHERE C.CLASSIFICACAO = 'TOP 50' --AND SIGLA_SITE = 'ADA' AND A.UF = 'AC'
ORDER BY B.UF, B.MUNICIPIO,A.DATA



-- gráfico com minutos de cdt dos sites hl5
-- qtde de armarios instalados por municipio
-- qtde mensal de tas de hl5



SELECT 
    -- DATEFROMPARTS(DATEPART(YEAR,DATA_ATIVACAO),DATEPART(MONTH,DATA_ATIVACAO),'01') AS DATA,
    -- A.UF, 
    -- B.MUNICIPIO,
    A.UF + A.SIGLA_SITE AS CHAVE
FROM SISTEMA_MAESTRO..TBL_SITES_HL5 A
INNER JOIN (SELECT UF, MUNICIPIO, SIGLA_SITE FROM SISTEMA_MAESTRO..TBA_PLANTA_MOVEL GROUP BY UF, MUNICIPIO, SIGLA_SITE) B ON A.UF = B.UF AND A.SIGLA_SITE = B.SIGLA_SITE
INNER JOIN INDICADORES_CORAN..TBA_CLASSIFICACAO_MUNICIPIOS C ON B.UF = C.UF AND B.MUNICIPIO = C.MUNICIPIO
WHERE DATEPART(YEAR, DATA_ATIVACAO) IN (2023, 2024) AND C.CLASSIFICACAO = 'TOP 50'


-- ==============================================================================

WITH CDT_MUN AS (
-- CDT DOS MUNICIPIOS TOP 50
SELECT
    DATEFROMPARTS(DATEPART(YEAR,DATA_REFERENCIA),DATEPART(MONTH,DATA_REFERENCIA),'01') AS DATA,
    A.UF,
    A.MUNICIPIO,
    SUM(TEMPO_CONTADOR_HMM) AS CDT_MUN
FROM (SELECT DATA_REFERENCIA,UF, MUNICIPIO, SITE, TEMPO_CONTADOR_HMM, TECNOLOGIA FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES WITH(NOLOCK) UNION ALL SELECT DATA_REFERENCIA,UF, MUNICIPIO, SITE, TEMPO_CONTADOR_HMM,TECNOLOGIA FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES_HIST_2023 WITH(NOLOCK)) A
INNER JOIN INDICADORES_CORAN..TBA_CLASSIFICACAO_MUNICIPIOS B ON A.UF = B.UF AND A.MUNICIPIO = B.MUNICIPIO
WHERE TEMPO_CONTADOR_HMM >=0 AND TECNOLOGIA <> 'GSM' AND DATEPART(YEAR,DATA_REFERENCIA) IN (2023,2024) AND B.CLASSIFICACAO = 'TOP 50' --AND A.MUNICIPIO = 'RIO BRANCO'
GROUP BY DATEPART(YEAR,DATA_REFERENCIA), DATEPART(MONTH, DATA_REFERENCIA), A.UF, A.MUNICIPIO
-- ORDER BY DATA
),
CDT_SITES_HL5_POR_MUN AS (
-- CDT DOS SITES HL5 (POR MUNICIPIO)
SELECT
    DATEFROMPARTS(DATEPART(YEAR,DATA_REFERENCIA),DATEPART(MONTH,DATA_REFERENCIA),'01') AS DATA,
    A.UF,
    A.MUNICIPIO,
    SUM(TEMPO_CONTADOR_HMM) AS CDT_HL5
FROM  (SELECT DATA_REFERENCIA,UF, MUNICIPIO, SITE, TEMPO_CONTADOR_HMM, TECNOLOGIA FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES WITH(NOLOCK) UNION ALL SELECT DATA_REFERENCIA,UF, MUNICIPIO, SITE, TEMPO_CONTADOR_HMM,TECNOLOGIA FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES_HIST_2023 WITH(NOLOCK)) A
INNER JOIN INDICADORES_CORAN..TBA_CLASSIFICACAO_MUNICIPIOS B ON A.UF = B.UF AND A.MUNICIPIO = B.MUNICIPIO
INNER JOIN SISTEMA_MAESTRO..TBL_SITES_HL5 C ON A.UF = C.UF AND A.SITE = C.SIGLA_SITE AND DATEFROMPARTS(DATEPART(YEAR,A.DATA_REFERENCIA),DATEPART(MONTH,A.DATA_REFERENCIA),'01') = DATEFROMPARTS(DATEPART(YEAR,C.DATA_ATIVACAO),DATEPART(MONTH,C.DATA_ATIVACAO),'01')
WHERE TEMPO_CONTADOR_HMM >=0 AND TECNOLOGIA <> 'GSM' AND DATEPART(YEAR,DATA_REFERENCIA) IN (2023,2024) AND B.CLASSIFICACAO = 'TOP 50' --AND A.MUNICIPIO = 'RIO BRANCO'
GROUP BY DATEPART(YEAR,DATA_REFERENCIA), DATEPART(MONTH, DATA_REFERENCIA), A.UF, A.MUNICIPIO
-- ORDER BY DATA
),
CDT_SITES_HL5_POR_SITE AS (
-- CDT DOS SITES HL5 (POR SITE)
SELECT
    DATEFROMPARTS(DATEPART(YEAR,DATA_REFERENCIA),DATEPART(MONTH,DATA_REFERENCIA),'01') AS DATA,
    A.UF,
    A.MUNICIPIO,
    A.SITE,
    SUM(TEMPO_CONTADOR_HMM) AS CDT_HL5_SITE
FROM  (SELECT DATA_REFERENCIA,UF, MUNICIPIO, SITE, TEMPO_CONTADOR_HMM, TECNOLOGIA FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES WITH(NOLOCK) UNION ALL SELECT DATA_REFERENCIA,UF, MUNICIPIO, SITE, TEMPO_CONTADOR_HMM,TECNOLOGIA FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES_HIST_2023 WITH(NOLOCK)) A
INNER JOIN SISTEMA_MAESTRO..TBL_SITES_HL5 C ON A.UF = C.UF AND A.SITE = C.SIGLA_SITE AND DATEFROMPARTS(DATEPART(YEAR,A.DATA_REFERENCIA),DATEPART(MONTH,A.DATA_REFERENCIA),'01') = DATEFROMPARTS(DATEPART(YEAR,C.DATA_ATIVACAO),DATEPART(MONTH,C.DATA_ATIVACAO),'01')
INNER JOIN INDICADORES_CORAN..TBA_CLASSIFICACAO_MUNICIPIOS B ON A.UF = B.UF AND A.MUNICIPIO = B.MUNICIPIO
WHERE TEMPO_CONTADOR_HMM >=0 AND TECNOLOGIA <> 'GSM' AND DATEPART(YEAR,DATA_REFERENCIA) IN (2023,2024) AND B.CLASSIFICACAO = 'TOP 50' --AND A.MUNICIPIO = 'RIO BRANCO'
GROUP BY DATEPART(YEAR,DATA_REFERENCIA), DATEPART(MONTH, DATA_REFERENCIA), A.UF, A.MUNICIPIO, A.SITE
-- ORDER BY DATA
)

SELECT
A.DATA,
A.UF,
A.MUNICIPIO,
A.CDT_MUN,
B.CDT_HL5
FROM CDT_MUN A
INNER JOIN CDT_SITES_HL5_POR_MUN B ON A.UF = B.UF AND A.MUNICIPIO = B.MUNICIPIO AND A.DATA = B.DATA
-- INNER JOIN CDT_SITES_HL5_POR_SITE C ON A.UF = C.UF AND A.MUNICIPIO = C.MUNICIPIO AND A.DATA = C.DATA




SELECT
DATA_REFERENCIA, A.UF, A.MUNICIPIO, SITE, MINUTOS_3G, MINUTOS_4G, MINUTOS_5G, HL5.TIPO_SITE, HL5.DATA_ATIVACAO, 
CASE WHEN A.DATA_REFERENCIA >= HL5.DATA_ATIVACAO THEN 1 ELSE 0 END FLG_CDT_HL5,
CASE WHEN LEG.SIGLA_SITE IS NOT NULL THEN 1 ELSE 0 END FLG_GW
FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_MENSAL_SITE_HMM A
LEFT JOIN SISTEMA_MAESTRO..TBL_SITES_HL5 HL5 ON A.UF = HL5.UF AND A.SITE = HL5.SIGLA_SITE
LEFT JOIN SISTEMA_MAESTRO..TBL_SITES_LEGADO LEG ON A.UF = LEG.UF AND A.SITE = LEG.SIGLA_SITE
WHERE ANO >= 2023 AND MUNICIPIO IN ('CAMPO GRANDE')





