-- TBL_EVENTOS_FECHADOS x GENESIS

WITH EVENTOS AS (
SELECT
ANO,
MES,
UF,
MUNICIPIO,
A.EVENTO,
CASE WHEN TEMPO_CAMPO_TERCEIRA > 30*60 THEN 1 ELSE 0 END AS "TEMPO_CAMPO_MAIOR_30_MIN"
FROM INDICADORES_CORAN..TBL_EVENTOS_FECHADOS A WITH(NOLOCK)
WHERE TEMPO_CAMPO_TERCEIRA > 0 AND ANO = 2024 AND MES IN (7,8,9,10)
),

GENESIS AS (
SELECT
C.EVENTO,
CASE WHEN C.NIVEL_ATENDIMENTO = 1 THEN 'Sem Atuação'
WHEN C.NIVEL_ATENDIMENTO = 2 THEN 'Com Atuação'
WHEN C.NIVEL_ATENDIMENTO = 3 THEN 'Energia Alternativa'
END NIVEL_ATENDIMENTO
FROM GENESIS..WFM_TBF_OS_PAGAMENTO C WITH(NOLOCK)
LEFT JOIN GENESIS..WFM_TBA_OS_TIPO_PAGAMENTO D WITH(NOLOCK) ON C.ID_OS_TIPO_PAGAMENTO = D.ID_OS_TIPO_PAGAMENTO
-- WHERE ANO = 2024 AND MES IN (7,8,9,10)
)

SELECT
ANO,
MES,
REGIONAL,
COUNT(DISTINCT EVENTO) AS QTDE_EVENTOS,
COUNT(DISTINCT CASE WHEN NIVEL_ATENDIMENTO = 'Sem Atuação' THEN EVENTO END) AS 'SEM_ATUACAO',
COUNT(DISTINCT CASE WHEN NIVEL_ATENDIMENTO = 'Com Atuação' THEN EVENTO END) AS 'COM_ATUACAO',
COUNT(DISTINCT CASE WHEN NIVEL_ATENDIMENTO = 'Energia Alternativa' THEN EVENTO END) AS 'ENERGIA_ALTERNATIVA',
COUNT(DISTINCT CASE WHEN TEMPO_CAMPO_MAIOR_30_MIN = 1 THEN EVENTO END) AS TEMPO_CAMPO_MAIOR_30_MIN
FROM (
    SELECT
    A.ANO,
    A.MES,
    CASE WHEN A.UF = 'SP' THEN C.NOME_REGIONAL
    WHEN A.UF IN ('BA', 'SE', 'AL', 'RN', 'PB', 'CE', 'PI', 'PE') THEN 'NE' 
    WHEN A.UF IN ('MG') THEN 'MG'
    WHEN A.UF IN ('RJ', 'ES') THEN 'RJ/ES'
    WHEN A.UF IN ('PR', 'SC', 'RS') THEN 'SUL'
    WHEN A.UF IN ('AM', 'PA', 'MA', 'AP', 'RR') THEN 'NO'
    WHEN A.UF IN ('AC', 'MS', 'MT', 'RO', 'DF', 'GO', 'TO') THEN 'CO' 
    END REGIONAL,
    A.UF,
    A.EVENTO,
    B.NIVEL_ATENDIMENTO,
    A.TEMPO_CAMPO_MAIOR_30_MIN
    FROM 
    EVENTOS A
    INNER JOIN GENESIS B ON A.EVENTO = B.EVENTO
    LEFT JOIN INDICADORES_CORAN..TBA_DIVISAO_MUNICIPIOS_SP_FIXA C ON A.MUNICIPIO = C.MUNICIPIO AND A.UF = 'SP'
) Z
GROUP BY ANO, MES, REGIONAL
ORDER BY ANO, MES, REGIONAL


-- SELECT TOP 10 * FROM INDICADORES_CORAN..TBL_EVENTOS_FECHADOS where EVENTO = 317437077