-- =======================================
-- ESTUDO DISPONIBILIDADE SPI
-- =======================================
SELECT *  FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_DIARIO_CN
WHERE DATA_REFERENCIA = '2024-09-03'

--DISPONIBILIDADE MENSAL PROGRESSIVA - REGIONAL
WITH DATAS AS (
SELECT 
    MAX(DATA_REFERENCIA) AS DT_MAX, 
    YEAR(MAX(DATA_REFERENCIA)) AS ANO, 
    MONTH(MAX(DATA_REFERENCIA)) AS MES 
FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES WITH(NOLOCK)

),

DISP AS (

SELECT      
        YEAR(DATA_REFERENCIA) AS ANO,
        MONTH(DATA_REFERENCIA) AS MES,
        DAY(DATA_REFERENCIA) AS DIA,
        CASE WHEN A.UF = 'SP' THEN B.NOME_REGIONAL
            WHEN A.UF IN ('BA', 'SE', 'AL', 'RN', 'PB', 'CE', 'PI', 'PE') THEN 'NE' 
            WHEN A.UF = 'MG' THEN 'MG'
            WHEN A.UF IN ('RJ', 'ES') THEN 'RJ/ES'
            WHEN A.UF IN ('PR', 'SC', 'RS') THEN 'SUL'
            WHEN A.UF IN ('AM', 'PA', 'MA', 'AP', 'RR') THEN 'NO'
            WHEN A.UF IN ('AC', 'MS', 'MT', 'RO', 'DF', 'GO', 'TO') THEN 'CO'
        END REGIONAL,
        UF,
        SITE,
        ERB,
        SETOR,
        TECNOLOGIA,
        COLETAS_HMM,
        TEMPO_CONTADOR_HMM
FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES A WITH(NOLOCK)
INNER JOIN DATAS ON YEAR(A.DATA_REFERENCIA) = DATAS.ANO AND MONTH(A.DATA_REFERENCIA)  = DATAS.MES
LEFT JOIN INDICADORES_CORAN..TBA_DIVISAO_MUNICIPIOS_SP_FIXA B ON A.MUNICIPIO = B.MUNICIPIO AND A.UF = 'SP'
WHERE A.UF = 'SP'
)

SELECT
'3G+4G+5G' AS TECNOLOGIA,
DATEFROMPARTS(ANO, MES, DIA) AS DATA_REFERENCIA,
ANO,
MES,
DIA,
REGIONAL,
ROUND((1-(TEMPO_ACUM / (CAST(PLANTA_ACUM AS FLOAT) * DENOMINADOR))) * 100, 2) AS DISPONIBILIDADE
FROM (
    SELECT
    *,
    COLETAS_ACUM / CAST(PLANTA_ACUM AS FLOAT) * 60 AS DENOMINADOR
    FROM (
        SELECT
        *,
        MAX(PLANTA) OVER (PARTITION BY ANO, MES, REGIONAL ORDER BY DIA ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS PLANTA_ACUM,
        SUM(COLETAS) OVER (PARTITION BY ANO, MES, REGIONAL ORDER BY DIA ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS COLETAS_ACUM,
        SUM(TEMPO) OVER (PARTITION BY ANO, MES, REGIONAL ORDER BY DIA ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS TEMPO_ACUM
        FROM (
            SELECT
                ANO,
                MES,
                DIA,
                REGIONAL,
                COUNT(DISTINCT CONCAT(UF, SITE, ERB, SETOR)) AS PLANTA,
                ISNULL(SUM(COLETAS_HMM), 0) AS COLETAS,
                SUM(CASE WHEN TEMPO_CONTADOR_HMM >= 0 THEN TEMPO_CONTADOR_HMM ELSE 0 END) TEMPO
            FROM DISP A WITH(NOLOCK)
            WHERE TECNOLOGIA <> 'GSM'
            GROUP BY ANO, MES, DIA, REGIONAL
        )A
    )B
)C --ORDER BY REGIONAL, DIA

UNION ALL

SELECT
'3G' AS TECNOLOGIA,
DATEFROMPARTS(ANO, MES, DIA) AS DATA_REFERENCIA,
ANO,
MES,
DIA,
REGIONAL,
ROUND((1-(TEMPO_ACUM / (CAST(PLANTA_ACUM AS FLOAT) * DENOMINADOR))) * 100, 2) AS DISPONIBILIDADE
FROM (
    SELECT
    *,
    COLETAS_ACUM / CAST(PLANTA_ACUM AS FLOAT) * 60 AS DENOMINADOR
    FROM (
        SELECT
        *,
        MAX(PLANTA) OVER (PARTITION BY ANO, MES, REGIONAL ORDER BY DIA ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS PLANTA_ACUM,
        SUM(COLETAS) OVER (PARTITION BY ANO, MES, REGIONAL ORDER BY DIA ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS COLETAS_ACUM,
        SUM(TEMPO) OVER (PARTITION BY ANO, MES, REGIONAL ORDER BY DIA ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS TEMPO_ACUM
        FROM (
            SELECT
                ANO,
                MES,
                DIA,
                REGIONAL,
                COUNT(DISTINCT CONCAT(UF, SITE, ERB, SETOR)) AS PLANTA,
                ISNULL(SUM(COLETAS_HMM), 0) AS COLETAS,
                SUM(CASE WHEN TEMPO_CONTADOR_HMM >= 0 THEN TEMPO_CONTADOR_HMM ELSE 0 END) TEMPO
            FROM DISP A WITH(NOLOCK)
            WHERE TECNOLOGIA = 'WCDMA'
            GROUP BY ANO, MES, DIA, REGIONAL
        )A
    )B
)C --ORDER BY TECNOLOGIA, REGIONAL, DIA

UNION ALL

SELECT
'4G' AS TECNOLOGIA,
DATEFROMPARTS(ANO, MES, DIA) AS DATA_REFERENCIA,
ANO,
MES,
DIA,
REGIONAL,
ROUND((1-(TEMPO_ACUM / (CAST(PLANTA_ACUM AS FLOAT) * DENOMINADOR))) * 100, 2) AS DISPONIBILIDADE
FROM (
    SELECT
    *,
    COLETAS_ACUM / CAST(PLANTA_ACUM AS FLOAT) * 60 AS DENOMINADOR
    FROM (
        SELECT
        *,
        MAX(PLANTA) OVER (PARTITION BY ANO, MES, REGIONAL ORDER BY DIA ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS PLANTA_ACUM,
        SUM(COLETAS) OVER (PARTITION BY ANO, MES, REGIONAL ORDER BY DIA ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS COLETAS_ACUM,
        SUM(TEMPO) OVER (PARTITION BY ANO, MES, REGIONAL ORDER BY DIA ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS TEMPO_ACUM
        FROM (
            SELECT
                ANO,
                MES,
                DIA,
                REGIONAL,
                COUNT(DISTINCT CONCAT(UF, SITE, ERB, SETOR)) AS PLANTA,
                ISNULL(SUM(COLETAS_HMM), 0) AS COLETAS,
                SUM(CASE WHEN TEMPO_CONTADOR_HMM >= 0 THEN TEMPO_CONTADOR_HMM ELSE 0 END) TEMPO
            FROM DISP A WITH(NOLOCK)
            WHERE TECNOLOGIA = 'LTE'
            GROUP BY ANO, MES, DIA, REGIONAL
        )A
    )B
)C --ORDER BY TECNOLOGIA, REGIONAL, DIA

UNION ALL

SELECT
'5G' AS TECNOLOGIA,
DATEFROMPARTS(ANO, MES, DIA) AS DATA_REFERENCIA,
ANO,
MES,
DIA,
REGIONAL,
ROUND((1-(TEMPO_ACUM / (CAST(PLANTA_ACUM AS FLOAT) * DENOMINADOR))) * 100, 2) AS DISPONIBILIDADE
FROM (
    SELECT
    *,
    COLETAS_ACUM / CAST(PLANTA_ACUM AS FLOAT) * 60 AS DENOMINADOR
    FROM (
        SELECT
        *,
        MAX(PLANTA) OVER (PARTITION BY ANO, MES, REGIONAL ORDER BY DIA ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS PLANTA_ACUM,
        SUM(COLETAS) OVER (PARTITION BY ANO, MES, REGIONAL ORDER BY DIA ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS COLETAS_ACUM,
        SUM(TEMPO) OVER (PARTITION BY ANO, MES, REGIONAL ORDER BY DIA ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS TEMPO_ACUM
        FROM (
            SELECT
                ANO,
                MES,
                DIA,
                REGIONAL,
                COUNT(DISTINCT CONCAT(UF, SITE, ERB, SETOR)) AS PLANTA,
                ISNULL(SUM(COLETAS_HMM), 0) AS COLETAS,
                SUM(CASE WHEN TEMPO_CONTADOR_HMM >= 0 THEN TEMPO_CONTADOR_HMM ELSE 0 END) TEMPO
            FROM DISP A WITH(NOLOCK)
            WHERE TECNOLOGIA = '5G'
            GROUP BY ANO, MES, DIA, REGIONAL
        )A
    )B
)C 












-- CN
SELECT
    ANO,
    MES,
    DIA,
    CN,
    ROUND((1-(TEMPO_ACUM / (CAST(PLANTA_ACUM AS float) * DENOMINADOR))) * 100, 2) AS DISPONIBILIDADE
FROM (
    SELECT
    *,
    COLETAS_ACUM / CAST(PLANTA_ACUM AS float) * 60 AS DENOMINADOR
    FROM (
        SELECT
        *,
        MAX(PLANTA) OVER (PARTITION BY ANO, MES, CN ORDER BY DIA ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS PLANTA_ACUM,
        SUM(COLETAS) OVER (PARTITION BY ANO, MES, CN ORDER BY DIA ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS COLETAS_ACUM,
        SUM(TEMPO) OVER (PARTITION BY ANO, MES, CN ORDER BY DIA ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS TEMPO_ACUM
        FROM (
            SELECT
            YEAR(DATA_REFERENCIA) AS ANO,
            MONTH(DATA_REFERENCIA) AS MES,
            DAY(DATA_REFERENCIA) AS DIA,
            CN,
            COUNT(DISTINCT CONCAT(UF, SITE, ERB, SETOR)) AS PLANTA,
            ISNULL(SUM(COLETAS_HMM), 0) AS COLETAS,
            SUM(CASE WHEN TEMPO_CONTADOR_HMM >= 0 THEN TEMPO_CONTADOR_HMM ELSE 0 END) TEMPO
            FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES A WITH(NOLOCK)
            LEFT JOIN INDICADORES_CORAN.dbo.TBA_DIVISAO_MUNICIPIOS_SP_FIXA B WITH(NOLOCK) ON A.MUNICIPIO = B.MUNICIPIO
            WHERE YEAR(DATA_REFERENCIA) = 2024 AND MONTH(DATA_REFERENCIA) = 9 AND TECNOLOGIA <> 'GSM' AND UF = 'SP'
            GROUP BY YEAR(DATA_REFERENCIA), MONTH(DATA_REFERENCIA), DAY(DATA_REFERENCIA), CN
        )A
    )B
)C ORDER BY CN, DIA



-- DISPONIBILIDADE PROGRESSIVA MENSAL - CN
WITH DATAS AS (
SELECT 
    MAX(DATA_REFERENCIA) AS DT_MAX, 
    YEAR(MAX(DATA_REFERENCIA)) AS ANO, 
    MONTH(MAX(DATA_REFERENCIA)) AS MES 
FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES WITH(NOLOCK)

),

DISP AS (

SELECT      
        YEAR(DATA_REFERENCIA) AS ANO,
        MONTH(DATA_REFERENCIA) AS MES,
        DAY(DATA_REFERENCIA) AS DIA,
        CASE WHEN A.UF = 'SP' THEN B.NOME_REGIONAL
            WHEN A.UF IN ('BA', 'SE', 'AL', 'RN', 'PB', 'CE', 'PI', 'PE') THEN 'NE' 
            WHEN A.UF = 'MG' THEN 'MG'
            WHEN A.UF IN ('RJ', 'ES') THEN 'RJ/ES'
            WHEN A.UF IN ('PR', 'SC', 'RS') THEN 'SUL'
            WHEN A.UF IN ('AM', 'PA', 'MA', 'AP', 'RR') THEN 'NO'
            WHEN A.UF IN ('AC', 'MS', 'MT', 'RO', 'DF', 'GO', 'TO') THEN 'CO'
        END REGIONAL,
        UF,
        CN,
        SITE,
        ERB,
        SETOR,
        TECNOLOGIA,
        COLETAS_HMM,
        TEMPO_CONTADOR_HMM
FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES A WITH(NOLOCK)
INNER JOIN DATAS ON YEAR(A.DATA_REFERENCIA) = DATAS.ANO AND MONTH(A.DATA_REFERENCIA)  = DATAS.MES
LEFT JOIN INDICADORES_CORAN..TBA_DIVISAO_MUNICIPIOS_SP_FIXA B ON A.MUNICIPIO = B.MUNICIPIO AND A.UF = 'SP'
WHERE A.UF = 'SP'
)

SELECT
'3G+4G+5G' AS TECNOLOGIA,
DATEFROMPARTS(ANO, MES, DIA) AS DATA_REFERENCIA,
ANO,
MES,
DIA,
CN,
TEMPO,
ROUND((1-(TEMPO_ACUM / (CAST(PLANTA_ACUM AS FLOAT) * DENOMINADOR))) * 100, 2) AS DISPONIBILIDADE
FROM (
    SELECT
    *,
    COLETAS_ACUM / CAST(PLANTA_ACUM AS FLOAT) * 60 AS DENOMINADOR
    FROM (
        SELECT
        *,
        MAX(PLANTA) OVER (PARTITION BY ANO, MES, CN ORDER BY DIA ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS PLANTA_ACUM,
        SUM(COLETAS) OVER (PARTITION BY ANO, MES, CN ORDER BY DIA ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS COLETAS_ACUM,
        SUM(TEMPO) OVER (PARTITION BY ANO, MES, CN ORDER BY DIA ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS TEMPO_ACUM
        FROM (
            SELECT
                ANO,
                MES,
                DIA,
                CN,
                COUNT(DISTINCT CONCAT(UF, SITE, ERB, SETOR)) AS PLANTA,
                ISNULL(SUM(COLETAS_HMM), 0) AS COLETAS,
                SUM(CASE WHEN TEMPO_CONTADOR_HMM >= 0 THEN TEMPO_CONTADOR_HMM ELSE 0 END) TEMPO
            FROM DISP A WITH(NOLOCK)
            WHERE TECNOLOGIA <> 'GSM'
            GROUP BY ANO, MES, DIA, CN
        )A
    )B
)C

UNION ALL

SELECT
'3G' AS TECNOLOGIA,
DATEFROMPARTS(ANO, MES, DIA) AS DATA_REFERENCIA,
ANO,
MES,
DIA,
CN,
TEMPO,
ROUND((1-(TEMPO_ACUM / (CAST(PLANTA_ACUM AS FLOAT) * DENOMINADOR))) * 100, 2) AS DISPONIBILIDADE
FROM (
    SELECT
    *,
    COLETAS_ACUM / CAST(PLANTA_ACUM AS FLOAT) * 60 AS DENOMINADOR
    FROM (
        SELECT
        *,
        MAX(PLANTA) OVER (PARTITION BY ANO, MES, CN ORDER BY DIA ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS PLANTA_ACUM,
        SUM(COLETAS) OVER (PARTITION BY ANO, MES, CN ORDER BY DIA ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS COLETAS_ACUM,
        SUM(TEMPO) OVER (PARTITION BY ANO, MES, CN ORDER BY DIA ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS TEMPO_ACUM
        FROM (
            SELECT
                ANO,
                MES,
                DIA,
                CN,
                COUNT(DISTINCT CONCAT(UF, SITE, ERB, SETOR)) AS PLANTA,
                ISNULL(SUM(COLETAS_HMM), 0) AS COLETAS,
                SUM(CASE WHEN TEMPO_CONTADOR_HMM >= 0 THEN TEMPO_CONTADOR_HMM ELSE 0 END) TEMPO
            FROM DISP A WITH(NOLOCK)
            WHERE TECNOLOGIA = 'WCDMA'
            GROUP BY ANO, MES, DIA, CN
        )A
    )B
)C

UNION ALL

SELECT
'4G' AS TECNOLOGIA,
DATEFROMPARTS(ANO, MES, DIA) AS DATA_REFERENCIA,
ANO,
MES,
DIA,
CN,
TEMPO,
ROUND((1-(TEMPO_ACUM / (CAST(PLANTA_ACUM AS FLOAT) * DENOMINADOR))) * 100, 2) AS DISPONIBILIDADE
FROM (
    SELECT
    *,
    COLETAS_ACUM / CAST(PLANTA_ACUM AS FLOAT) * 60 AS DENOMINADOR
    FROM (
        SELECT
        *,
        MAX(PLANTA) OVER (PARTITION BY ANO, MES, CN ORDER BY DIA ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS PLANTA_ACUM,
        SUM(COLETAS) OVER (PARTITION BY ANO, MES, CN ORDER BY DIA ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS COLETAS_ACUM,
        SUM(TEMPO) OVER (PARTITION BY ANO, MES, CN ORDER BY DIA ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS TEMPO_ACUM
        FROM (
            SELECT
                ANO,
                MES,
                DIA,
                CN,
                COUNT(DISTINCT CONCAT(UF, SITE, ERB, SETOR)) AS PLANTA,
                ISNULL(SUM(COLETAS_HMM), 0) AS COLETAS,
                SUM(CASE WHEN TEMPO_CONTADOR_HMM >= 0 THEN TEMPO_CONTADOR_HMM ELSE 0 END) TEMPO
            FROM DISP A WITH(NOLOCK)
            WHERE TECNOLOGIA = 'LTE'
            GROUP BY ANO, MES, DIA, CN
        )A
    )B
)C

UNION ALL

SELECT
'5G' AS TECNOLOGIA,
DATEFROMPARTS(ANO, MES, DIA) AS DATA_REFERENCIA,
ANO,
MES,
DIA,
CN,
TEMPO,
ROUND((1-(TEMPO_ACUM / (CAST(PLANTA_ACUM AS FLOAT) * DENOMINADOR))) * 100, 2) AS DISPONIBILIDADE
FROM (
    SELECT
    *,
    COLETAS_ACUM / CAST(PLANTA_ACUM AS FLOAT) * 60 AS DENOMINADOR
    FROM (
        SELECT
        *,
        MAX(PLANTA) OVER (PARTITION BY ANO, MES, CN ORDER BY DIA ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS PLANTA_ACUM,
        SUM(COLETAS) OVER (PARTITION BY ANO, MES, CN ORDER BY DIA ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS COLETAS_ACUM,
        SUM(TEMPO) OVER (PARTITION BY ANO, MES, CN ORDER BY DIA ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS TEMPO_ACUM
        FROM (
            SELECT
                ANO,
                MES,
                DIA,
                CN,
                COUNT(DISTINCT CONCAT(UF, SITE, ERB, SETOR)) AS PLANTA,
                ISNULL(SUM(COLETAS_HMM), 0) AS COLETAS,
                SUM(CASE WHEN TEMPO_CONTADOR_HMM >= 0 THEN TEMPO_CONTADOR_HMM ELSE 0 END) TEMPO
            FROM DISP A WITH(NOLOCK)
            WHERE TECNOLOGIA = '5G'
            GROUP BY ANO, MES, DIA, CN
        )A
    )B
)C


-- DISPONIBILIDADE PROGRESSIVA MENSAL - MUNICIPIO
WITH DATAS AS (
SELECT 
    MAX(DATA_REFERENCIA) AS DT_MAX, 
    YEAR(MAX(DATA_REFERENCIA)) AS ANO, 
    MONTH(MAX(DATA_REFERENCIA)) AS MES 
FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES WITH(NOLOCK)

),

DISP AS (

SELECT      
        YEAR(DATA_REFERENCIA) AS ANO,
        MONTH(DATA_REFERENCIA) AS MES,
        DAY(DATA_REFERENCIA) AS DIA,
        CASE WHEN A.UF = 'SP' THEN B.NOME_REGIONAL
            WHEN A.UF IN ('BA', 'SE', 'AL', 'RN', 'PB', 'CE', 'PI', 'PE') THEN 'NE' 
            WHEN A.UF = 'MG' THEN 'MG'
            WHEN A.UF IN ('RJ', 'ES') THEN 'RJ/ES'
            WHEN A.UF IN ('PR', 'SC', 'RS') THEN 'SUL'
            WHEN A.UF IN ('AM', 'PA', 'MA', 'AP', 'RR') THEN 'NO'
            WHEN A.UF IN ('AC', 'MS', 'MT', 'RO', 'DF', 'GO', 'TO') THEN 'CO'
        END REGIONAL,
        UF,
        A.MUNICIPIO,
        CN,
        SITE,
        ERB,
        SETOR,
        TECNOLOGIA,
        COLETAS_HMM,
        TEMPO_CONTADOR_HMM
FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES A WITH(NOLOCK)
INNER JOIN DATAS ON YEAR(A.DATA_REFERENCIA) = DATAS.ANO AND MONTH(A.DATA_REFERENCIA)  = DATAS.MES
LEFT JOIN INDICADORES_CORAN..TBA_DIVISAO_MUNICIPIOS_SP_FIXA B ON A.MUNICIPIO = B.MUNICIPIO AND A.UF = 'SP'
WHERE A.UF = 'SP'
)

SELECT
'3G+4G+5G' AS TECNOLOGIA,
DATEFROMPARTS(ANO, MES, DIA) AS DATA_REFERENCIA,
ANO,
MES,
DIA,
SITE,
ROUND((1-(TEMPO_ACUM / (CAST(PLANTA_ACUM AS FLOAT) * DENOMINADOR))) * 100, 2) AS DISPONIBILIDADE
FROM (
    SELECT
    *,
    COLETAS_ACUM / CAST(PLANTA_ACUM AS FLOAT) * 60 AS DENOMINADOR
    FROM (
        SELECT
        *,
        MAX(PLANTA) OVER (PARTITION BY ANO, MES, SITE ORDER BY DIA ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS PLANTA_ACUM,
        SUM(COLETAS) OVER (PARTITION BY ANO, MES, SITE ORDER BY DIA ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS COLETAS_ACUM,
        SUM(TEMPO) OVER (PARTITION BY ANO, MES, SITE ORDER BY DIA ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS TEMPO_ACUM
        FROM (
            SELECT
                ANO,
                MES,
                DIA,
                SITE,
                COUNT(DISTINCT CONCAT(UF, SITE, ERB, SETOR)) AS PLANTA,
                ISNULL(SUM(COLETAS_HMM), 0) AS COLETAS,
                SUM(CASE WHEN TEMPO_CONTADOR_HMM >= 0 THEN TEMPO_CONTADOR_HMM ELSE 0 END) TEMPO
            FROM DISP A WITH(NOLOCK)
            WHERE TECNOLOGIA <> 'GSM'
            GROUP BY ANO, MES, DIA, SITE
        )A
    )B
)C

UNION ALL

SELECT
'3G' AS TECNOLOGIA,
DATEFROMPARTS(ANO, MES, DIA) AS DATA_REFERENCIA,
ANO,
MES,
DIA,
CN,
ROUND((1-(TEMPO_ACUM / (CAST(PLANTA_ACUM AS FLOAT) * DENOMINADOR))) * 100, 2) AS DISPONIBILIDADE
FROM (
    SELECT
    *,
    COLETAS_ACUM / CAST(PLANTA_ACUM AS FLOAT) * 60 AS DENOMINADOR
    FROM (
        SELECT
        *,
        MAX(PLANTA) OVER (PARTITION BY ANO, MES, CN ORDER BY DIA ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS PLANTA_ACUM,
        SUM(COLETAS) OVER (PARTITION BY ANO, MES, CN ORDER BY DIA ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS COLETAS_ACUM,
        SUM(TEMPO) OVER (PARTITION BY ANO, MES, CN ORDER BY DIA ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS TEMPO_ACUM
        FROM (
            SELECT
                ANO,
                MES,
                DIA,
                CN,
                COUNT(DISTINCT CONCAT(UF, SITE, ERB, SETOR)) AS PLANTA,
                ISNULL(SUM(COLETAS_HMM), 0) AS COLETAS,
                SUM(CASE WHEN TEMPO_CONTADOR_HMM >= 0 THEN TEMPO_CONTADOR_HMM ELSE 0 END) TEMPO
            FROM DISP A WITH(NOLOCK)
            WHERE TECNOLOGIA = 'WCDMA'
            GROUP BY ANO, MES, DIA, CN
        )A
    )B
)C

UNION ALL

SELECT
'4G' AS TECNOLOGIA,
DATEFROMPARTS(ANO, MES, DIA) AS DATA_REFERENCIA,
ANO,
MES,
DIA,
CN,
ROUND((1-(TEMPO_ACUM / (CAST(PLANTA_ACUM AS FLOAT) * DENOMINADOR))) * 100, 2) AS DISPONIBILIDADE
FROM (
    SELECT
    *,
    COLETAS_ACUM / CAST(PLANTA_ACUM AS FLOAT) * 60 AS DENOMINADOR
    FROM (
        SELECT
        *,
        MAX(PLANTA) OVER (PARTITION BY ANO, MES, CN ORDER BY DIA ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS PLANTA_ACUM,
        SUM(COLETAS) OVER (PARTITION BY ANO, MES, CN ORDER BY DIA ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS COLETAS_ACUM,
        SUM(TEMPO) OVER (PARTITION BY ANO, MES, CN ORDER BY DIA ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS TEMPO_ACUM
        FROM (
            SELECT
                ANO,
                MES,
                DIA,
                CN,
                COUNT(DISTINCT CONCAT(UF, SITE, ERB, SETOR)) AS PLANTA,
                ISNULL(SUM(COLETAS_HMM), 0) AS COLETAS,
                SUM(CASE WHEN TEMPO_CONTADOR_HMM >= 0 THEN TEMPO_CONTADOR_HMM ELSE 0 END) TEMPO
            FROM DISP A WITH(NOLOCK)
            WHERE TECNOLOGIA = 'LTE'
            GROUP BY ANO, MES, DIA, CN
        )A
    )B
)C

UNION ALL

SELECT
'5G' AS TECNOLOGIA,
DATEFROMPARTS(ANO, MES, DIA) AS DATA_REFERENCIA,
ANO,
MES,
DIA,
CN,
ROUND((1-(TEMPO_ACUM / (CAST(PLANTA_ACUM AS FLOAT) * DENOMINADOR))) * 100, 2) AS DISPONIBILIDADE
FROM (
    SELECT
    *,
    COLETAS_ACUM / CAST(PLANTA_ACUM AS FLOAT) * 60 AS DENOMINADOR
    FROM (
        SELECT
        *,
        MAX(PLANTA) OVER (PARTITION BY ANO, MES, CN ORDER BY DIA ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS PLANTA_ACUM,
        SUM(COLETAS) OVER (PARTITION BY ANO, MES, CN ORDER BY DIA ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS COLETAS_ACUM,
        SUM(TEMPO) OVER (PARTITION BY ANO, MES, CN ORDER BY DIA ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS TEMPO_ACUM
        FROM (
            SELECT
                ANO,
                MES,
                DIA,
                CN,
                COUNT(DISTINCT CONCAT(UF, SITE, ERB, SETOR)) AS PLANTA,
                ISNULL(SUM(COLETAS_HMM), 0) AS COLETAS,
                SUM(CASE WHEN TEMPO_CONTADOR_HMM >= 0 THEN TEMPO_CONTADOR_HMM ELSE 0 END) TEMPO
            FROM DISP A WITH(NOLOCK)
            WHERE TECNOLOGIA = '5G'
            GROUP BY ANO, MES, DIA, CN
        )A
    )B
)C


