SELECT
SUM(TEMPO_CONTADOR)
FROM TBF_DISPONIBILIDADE_SETORES 
WHERE DATA_REFERENCIA >= '2023-02-01 00:00:00.000'
AND DATA_REFERENCIA <= '2023-02-28 00:00:00.000'
AND UF = 'SC'
AND TEMPO_CONTADOR > 0
GROUP BY UF


SELECT
SITE,
SUM(TEMPO_CONTADOR) AS CELLDOWNTIME,
COUNT(SITE) AS QTDE_SETORES,
SUM(COLETAS) AS QTDE_COLETAS,
COUNT(SITE)*24*28 AS QTDE_COLETAS_ESPERADA,
AVG(COLETAS)
FROM TBF_DISPONIBILIDADE_SETORES 
WHERE DATA_REFERENCIA >= '2023-02-01 00:00:00.000'
AND DATA_REFERENCIA <= '2023-02-28 00:00:00.000'
AND UF = 'SC'
AND TEMPO_CONTADOR > 0
GROUP BY SITE
ORDER BY SITE

SELECT
AVG(COLETAS)
FROM TBF_DISPONIBILIDADE_SETORES 
WHERE DATA_REFERENCIA >= '2023-02-01 00:00:00.000'
AND DATA_REFERENCIA <= '2023-02-28 00:00:00.000'
AND UF = 'BA'
--AND TEMPO_CONTADOR > 0
AND TECNOLOGIA <> 'GSM'
GROUP BY SITE





SELECT 
*
FROM SISTEMA_MAESTRO..TBA_PLANTA_MOVEL
WHERE TECNOLOGIA = 'LTE' AND OPERADORA_RANSHARING = 'VIVO'--AND UF = 'PE' AND MUNICIPIO = 'RECIFE'
ORDER BY SIGLA_LOGICA 






SELECT DISTINCT
UF,
SIGLA_SITE,
SIGLA_ERB,
SETOR,
SIGLA_LOGICA,
SIGLA_ERB_LOGICA
FROM SISTEMA_MAESTRO..TBA_PLANTA_MOVEL
WHERE TECNOLOGIA = 'lte' AND OPERADORA_RANSHARING = 'VIVO'AND SIGLA_LOGICA LIKE '5%' AND UF = 'SP' AND MUNICIPIO = 'ARARAQUARA'
ORDER BY SIGLA_LOGICA 


SELECT
*
FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_MENSAL_UF
WHERE ANO >= 2022 
ORDER BY UF, ANO, MES