-- ===========================
-- DISP DIARIA DE FLORIANOPOLIS DESCONSIDERANDO OS MINUTOS DE ALGUNS SITES
-- ===========================
DECLARE @ANO INT = (SELECT CASE WHEN YEAR(GETDATE()) = YEAR(GETDATE()-1) THEN YEAR(GETDATE()) ELSE YEAR(GETDATE()-1) END) 
DECLARE @MES INT = (SELECT CASE WHEN MONTH(GETDATE()) = MONTH(GETDATE()-1) THEN MONTH(GETDATE()) ELSE MONTH(GETDATE()-1) END) 

DECLARE @TEMPO INT = (
SELECT SUM(TEMPO_CONTADOR_HMM) AS TEMPO_CDT FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES 
WHERE UF = 'SC' AND TEMPO_CONTADOR_HMM >=0 AND DATA_REFERENCIA = '2024-09-17'
AND SITE IN
(
'FS2','SCS','1FV','FNR','GMP','GAR','SLL','IMA','SJL','ASI','PPF','SPC','FKA','LPO','TSC','UUG','GCS','YR2','MCV','TVM','CMO','FPB','PAU','CSO','NVB','ALG','FI2','CMU','PGU','FFI','TSE','FVS',
'F2R','FT2','ZRQ','FSL','SOG','TGV','LTC','MGL','SAN','LRG','LML','IRU','GAV','ROF','SLU','LNV','PSC','FCG','TV2','SJP','FPR','FB2','SRO','GTE','1FL','FSE','FMP','BSM','FSS','FRI','1FA','SSM',
'FTB','SLB','SYP','SYP','GE2','PTP','BGI','SJS','PGD','JCH','TVO','BGV','FGR','PUL','GFE','PPS','1GR','1GR','GFE','PUL','GRH','FGR','F09','FCQ','ARC','1GR','1GR','ENC','FPL','GMP','FVM','IBQ',
'FMR','FU2','FVG','FCO','PSS','PPT','FTD','SMN','SMN','FSE','ENC','LZZ','IAR','PUL','PPI','GCP','FU2','1FS','TVR','TXV','RQO','PGD','CEH','FSL','FSB','FBO','FLP','SAM','ORL','SAM','OLS','NVT',
'FSS','F03','JUA','JCM','FDC','SSH','SF2','FES','FIO','SPO','SFO','SPO','SFO','SDI','SF2','PPA','LMO','TRE','LOM','TMP','SRS'
)
GROUP BY DATA_REFERENCIA
)
PRINT @TEMPO

SELECT
UF,
MUNICIPIO,
ROUND(((1-(SUM(CASE WHEN TECNOLOGIA <> 'GSM' AND TEMPO_CONTADOR_HMM >= 0 THEN CAST(TEMPO_CONTADOR_HMM AS FLOAT) END)/(SUM(CASE WHEN TECNOLOGIA <> 'GSM' THEN CAST(COLETAS_HMM AS FLOAT) END)*60)))*100),2) AS DISP_GERAL_ATUAL,
ROUND(((1-((SUM(CASE WHEN TECNOLOGIA <> 'GSM' AND TEMPO_CONTADOR_HMM >= 0 THEN (TEMPO_CONTADOR_HMM) END)-@TEMPO)/(SUM(CASE WHEN TECNOLOGIA <> 'GSM' THEN CAST(COLETAS_HMM AS FLOAT) END)*60)))*100),2) AS DISP_GERAL_DEPOIS
FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES A WITH(NOLOCK)
WHERE
    A.UF = 'SC' 
    AND A.MUNICIPIO = 'FLORIANÓPOLIS' 
    AND A.DATA_REFERENCIA = '2024-09-17 00:00:00.000'
GROUP BY DATA_REFERENCIA, UF, MUNICIPIO


-- ===================================
-- CÁLCULO PADRÃO DA DISPONIBILIDADE
-- ===================================
SELECT
UF,
MUNICIPIO,
DISP_3G = ROUND(((1-(SUM(CASE WHEN TECNOLOGIA = 'WCDMA' AND TEMPO_CONTADOR_HMM >= 0 THEN CAST(TEMPO_CONTADOR_HMM AS FLOAT) END)/(SUM(CASE WHEN TECNOLOGIA = 'WCDMA' THEN CAST(COLETAS_HMM AS FLOAT) END)*60)))*100),6),
DISP_4G = ROUND(((1-(SUM(CASE WHEN TECNOLOGIA = 'LTE' AND TEMPO_CONTADOR_HMM >= 0 THEN CAST(TEMPO_CONTADOR_HMM AS FLOAT) END)/(SUM(CASE WHEN TECNOLOGIA = 'LTE' THEN CAST(COLETAS_HMM AS FLOAT) END)*60)))*100),2),
DISP_5G = ROUND(((1-(SUM(CASE WHEN TECNOLOGIA = '5G' AND TEMPO_CONTADOR_HMM >= 0 THEN CAST(TEMPO_CONTADOR_HMM AS FLOAT) END)/(SUM(CASE WHEN TECNOLOGIA = '5G' THEN CAST(COLETAS_HMM AS FLOAT) END)*60)))*100),2),
DISP_GERAL = ROUND(((1-(SUM(CASE WHEN TECNOLOGIA <> 'GSM' AND TEMPO_CONTADOR_HMM >= 0 THEN CAST(TEMPO_CONTADOR_HMM AS FLOAT) END)/(SUM(CASE WHEN TECNOLOGIA <> 'GSM' THEN CAST(COLETAS_HMM AS FLOAT) END)*60)))*100),2),
DISP_4G_5G = ROUND(((1-(SUM(CASE WHEN TECNOLOGIA IN ('LTE','5G') AND TEMPO_CONTADOR_HMM >= 0 THEN CAST(TEMPO_CONTADOR_HMM AS FLOAT) END)/(SUM(CASE WHEN TECNOLOGIA IN ('LTE','5G') THEN CAST(COLETAS_HMM AS FLOAT) END)*60)))*100),2)
FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES A WITH(NOLOCK)
WHERE
    A.UF = 'SC' 
    AND A.MUNICIPIO = 'FLORIANÓPOLIS' 
    AND A.DATA_REFERENCIA = '2024-09-29 00:00:00.000'
GROUP BY DATA_REFERENCIA, UF, MUNICIPIO

