EXEC DB_GUSTAVO.[dbo].[QTDE_EVENTOS_ENTRADA_SAIDA]


SELECT 
RES.DATA_REFERENCIA,
SUM(RES.ENTROU) AS TOTAL,
SUM(RES.NOVOS) AS EVENTOS_Q_ENTRARAM,
SUM(RES.SAIU) AS EVENTOS_Q_SAIRAM
FROM
					(
					SELECT
					T.EVENTO,
					T.DATA_REFERENCIA,
					T.ENTROU,
					T.RECORRENTE,
					T.SAIU,

					CASE WHEN (T.ENTROU <> T.RECORRENTE) 
					--AND (LAG(T.EVENTO) OVER (ORDER BY T.EVENTO, T.DATA_REFERENCIA) = T.EVENTO) 
					THEN 1 ELSE 0 END NOVOS

FROM(

SELECT 
R.EVENTO,
R.DATA_REFERENCIA,
R.ENTROU,

CASE WHEN ((LAG(R.ENTROU) OVER (ORDER BY R.EVENTO, R.DATA_REFERENCIA))=1 AND R.ENTROU= 1)
AND
(LAG(R.EVENTO) OVER (ORDER BY R.EVENTO, R.DATA_REFERENCIA) = R.EVENTO)
 THEN 1 ELSE 0 END 
RECORRENTE,

CASE WHEN ((LAG(R.ENTROU) OVER (ORDER BY R.EVENTO, R.DATA_REFERENCIA))=1 AND R.ENTROU= 0) 
AND
(LAG(R.EVENTO) OVER (ORDER BY R.EVENTO, R.DATA_REFERENCIA) = R.EVENTO)
THEN 1 ELSE 0 END SAIU

FROM
(
SELECT 
Q_1.EVENTO, 
Q_1.DATA_REFERENCIA,
CASE WHEN Q_2.EVENTO IS NULL THEN 0 ELSE 1 END ENTROU

FROM
(
SELECT
DISTINCT 
EVENTOS.EVENTO, 
DATAS.DATA_REFERENCIA 
FROM TBL_ATIVOS_CAMPO EVENTOS WITH(NOLOCK)
CROSS JOIN
(SELECT DISTINCT DATA_REFERENCIA FROM TBL_ATIVOS_CAMPO WITH(NOLOCK))DATAS
WHERE EVENTOS.EVENTO 
IN(46894547,48965314,260000801)
--IN(46894547,48965314,260000801)
)Q_1
LEFT JOIN
(SELECT 
EVENTO,
DATA_REFERENCIA
FROM TBL_ATIVOS_CAMPO WITH(NOLOCK)
---WHERE EVENTO 
--IN(46894547,48965314,260000801)
---IN(46894547,48965314,260000801)
)Q_2

ON Q_1.DATA_REFERENCIA = Q_2.DATA_REFERENCIA
AND Q_1.EVENTO = Q_2.EVENTO

)R

)T
---ORDER BY 1,2
)RES

GROUP BY 
RES.DATA_REFERENCIA

ORDER BY 1
