SELECT  *
FROM SISTEMA_MAESTRO..TBL_COLETA_METRICAS_5G
WHERE UF = 'TO' AND SIGLA_ERB LIKE '5S%'-- AND SIGLA_ERB = '5SPAR1' AND SETOR = 1

EXCEPT

SELECT  *
FROM SISTEMA_MAESTRO..TBL_COLETA_METRICAS_5G
WHERE UF = 'TO' AND SIGLA_ERB LIKE '5S%' --AND SIGLA_ERB = '5SPAR1' AND SETOR = 1
       AND M2979300545 IS NULL
       AND M2970982225 IS NULL
       AND M2970983082 IS NULL
       AND M2981608151 IS NULL
       AND M2981608161 IS NULL
       AND M76996616   IS NULL
       AND M76996644   IS NULL
       AND M2971525806 IS NULL
       AND M2971525809 IS NULL
       AND M2971930195 IS NULL
       AND M2971930194 IS NULL
       AND CELLDOWNTIME_AUTOMATICO_NR IS NULL
       AND TAXA_QUEDA_SA_NR IS NULL
       AND TAXA_QUEDA_NSA_NR IS  NULL
       AND EFICIENCIA_HANDOVER_INTER_NSA_NR IS NULL
       AND EFICIENCIA_HANDOVER_INTER_SA_NR IS NULL
       AND FLAG_QUALIDADE_NOTA IS NULL
ORDER BY DATA_REFERENCIA_CONTADOR

--=============================================================
SELECT
*
FROM (
       SELECT
       UF,
       SIGLA_ERB,
       SETOR,
       COUNT(*) AS QTDE_COLETAS
       FROM SISTEMA_MAESTRO..TBL_COLETA_METRICAS_5G
       WHERE SIGLA_ERB LIKE '5S%' AND SETOR <> '-1'
       GROUP BY UF, SIGLA_ERB, SETOR
) A
WHERE QTDE_COLETAS > 24
ORDER BY QTDE_COLETAS DESC

SELECT * FROM QUALIDADE..TBL_QUALIDADE_COLETA
WHERE TECNOLOGIA = '5G' AND DATA_REFERENCIA = '08/03/2024'
