WITH MANHA AS (
    SELECT * FROM FABIO..TBL_FALHA_IMPACTO_BASE
    WHERE PERIODO = 'MANHA'
),
TARDE AS (
    SELECT * FROM FABIO..TBL_FALHA_IMPACTO_BASE
    WHERE PERIODO = 'TARDE'
),
ENTRANTES AS (
    SELECT MANHA.* FROM MANHA
    RIGHT JOIN TARDE ON MANHA.TA = TARDE.TA AND DATEPART(DAY,MANHA.DATA_REFERENCIA) = DATEPART(DAY,TARDE.DATA_REFERENCIA) AND DATEPART(MONTH,MANHA.DATA_REFERENCIA) = DATEPART(MONTH,TARDE.DATA_REFERENCIA)
),
FECHADOS AS (
    SELECT MANHA.* FROM MANHA
    LEFT JOIN TARDE ON MANHA.TA = TARDE.TA AND DATEPART(DAY,MANHA.DATA_REFERENCIA) = DATEPART(DAY,TARDE.DATA_REFERENCIA) AND DATEPART(MONTH,MANHA.DATA_REFERENCIA) = DATEPART(MONTH,TARDE.DATA_REFERENCIA)
)


SELECT
DATEPART(YEAR,DATA_REFERENCIA) AS ANO, 
DATEPART(MONTH,DATA_REFERENCIA) AS MES, 
DATEPART(DAY,DATA_REFERENCIA) AS DIA,
COUNT(*) AS QTDE
FROM ENTRANTES
WHERE DATEPART(YEAR,DATA_REFERENCIA) IS NOT NULL
GROUP BY DATA_REFERENCIA, PERIODO




SELECT 
    DATEPART(YEAR, DATA_REFERENCIA) AS ANO,
    DATEPART(MONTH, DATA_REFERENCIA) AS MES, 
    DATEPART(DAY, DATA_REFERENCIA) AS DIA, 
    PERIODO, 
    COUNT(TA) AS QTDE 
FROM FABIO..TBL_FALHA_IMPACTO_BASE
GROUP BY DATA_REFERENCIA, PERIODO
ORDER BY DATA_REFERENCIA, PERIODO
;


/*
WITH BASE AS (
SELECT 
    DATEPART(YEAR, A.DATA_REFERENCIA) AS ANO, 
    DATEPART(MONTH, A.DATA_REFERENCIA) AS MES, 
    DATEPART(DAY, A.DATA_REFERENCIA) AS DIA, 
    A.TA AS TA_MANHA,
    B.TA AS TA_TARDE
FROM FABIO..TBL_FALHA_IMPACTO_BASE A
LEFT JOIN FABIO..TBL_FALHA_IMPACTO_BASE B ON A.TA = B.TA AND A.PERIODO = 'MANHA' AND B.PERIODO = 'TARDE' 
AND DATEPART(YEAR,A.DATA_REFERENCIA) = DATEPART(YEAR,B.DATA_REFERENCIA)
AND DATEPART(MONTH,A.DATA_REFERENCIA) = DATEPART(MONTH,B.DATA_REFERENCIA)
AND DATEPART(DAY,A.DATA_REFERENCIA) = DATEPART(DAY,B.DATA_REFERENCIA)
)

SELECT COUNT(*) FROM BASE 
WHERE TA_TARDE IS NOT NULL
*/

SELECT * FROM FABIO..TBL_FALHA_IMPACTO_BASE
ORDER BY DATA_REFERENCIA, PERIODO
