

SELECT DISTINCT
    CASE
        WHEN NIVEL_ATENDIMENTO = 1 THEN 'Sem Atuação'
        WHEN NIVEL_ATENDIMENTO = 2 THEN 'Com Atuação'
        WHEN NIVEL_ATENDIMENTO = 3 THEN 'Energia Alternativa'
        ELSE 'nda'
    END AS NIVEL_ATENDIMENTO,
    ISNULL(CAST(OSP.NUM_OS AS VARCHAR),'') AS NUM_OS,
    EVENTO,
    FORMAT(DATA_ENCERRAMENTO,'dd/MM/yyyy HH:mm:ss') AS DATA_ENCERRAMENTO,
    ISNULL(CAST(PRIORIDADE AS VARCHAR),'') AS PRIORIDADE,
    UF_EVENTO,
    SIGLA_LOCALIDADE_EVENTO,
    CODIGO_LOCALIDADE_EVENTO,
    GERENCIA_EVENTO,
    SITE_EVENTO,
    OSS.LAT AS LAT_SITE,
    OSS.LONG AS LONG_SITE,
    TIPO_PLANTA_EVENTO,
    ISNULL(OSS.UF,'') UF_GENESIS,
    ISNULL(CAST(OSS.DDD AS VARCHAR),'') AS DDD_GENESIS,
    ISNULL(OSS.SIGLA_MUNICIPIO,'') AS LOCALIDADE_GENESIS,
    ISNULL(CAST(OSS.CNL AS VARCHAR),'') AS CODIGO_LOCALIDADE_GENESIS,
    ISNULL(OSS.SIGLA_SITE,'') SITE_GENESIS,
    ISNULL(OSTP.TIPO_PAGAMENTO,'') TIPO_PAGAMENTO,
    CASE WHEN ENCAMINHADO_TECNICO = 1 THEN 'Sim' ELSE 'Não' END AS ENCAMINHADO_TECNICO,
    ISNULL(ENCAMINHADO_TECNICO_NOME,'') AS ENCAMINHADO_TECNICO_NOME,
    CASE WHEN ACEITE = 1 THEN 'Sim' ELSE 'Não' END ACEITE,
    ISNULL(FORMAT(ACEITE_DATA,'dd/MM/yyyy HH:mm:ss'),'') AS ACEITE_DATA,
    ISNULL(ACEITE_NOME,'') ACEITE_NOME,
    CASE WHEN TECNICO_NO_SITE = 1 THEN 'Sim' ELSE 'Não' END AS TECNICO_NO_SITE,
    TB_CHECK_GPS.LAT AS LAT_TECNICO,
    TB_CHECK_GPS.LONG AS LONG_TECNICO,
    ISNULL(FORMAT(TECNICO_NO_SITE_DATA,'dd/MM/yyyy HH:mm:ss'),'') AS TECNICO_NO_SITE_DATA,
    ISNULL(TECNICO_NO_SITE_NOME,'') TECNICO_NO_SITE_NOME,
    CASE WHEN PRE_BAIXA = 1 THEN 'Sim' ELSE 'Não' END AS PRE_BAIXA,
    ISNULL(FORMAT(PRE_BAIXA_DATA,'dd/MM/yyyy HH:mm:ss'),'') AS PRE_BAIXA_DATA,
    ISNULL(PRE_BAIXA_NOME,'') PRE_BAIXA_NOME,
    CASE WHEN ENERGIA_ALTERNATIVA = 1 THEN 'Sim' ELSE 'Não' END AS ENERGIA_ALTERNATIVA,
    ISNULL(ENERGIA_ALTERNATIVA_NOME,'') AS ENERGIA_ALTERNATIVA_NOME,
    ISNULL(OSP.CONTRATO,'') AS CONTRATO,
    ISNULL(OSP.EMPRESA,'') AS EMPRESA,
    TB_JUST_ESTOU_SITE.ANALISE_JUST_ESTOU_NO_SITE,
    TB_JUST_ESTOU_SITE.LAT AS LAT_JUSTIFICADA,
    TB_JUST_ESTOU_SITE.LONG AS LONG_JUSTIFICADA,
    ROUND((geography::Point(ISNULL(TB_CHECK_GPS.LAT,0), ISNULL(TB_CHECK_GPS.LONG,0), 4326)).STDistance(geography::Point(ISNULL(OSS.LAT,0), ISNULL(OSS.LONG,0), 4326))/1000,2) AS DISTANCIA_TECNICO_ATE_SITE
FROM GENESIS..WFM_TBF_OS_PAGAMENTO OSP WITH(NOLOCK)
LEFT JOIN GENESIS..WFM_TBF_OS_SITE OSS WITH(NOLOCK) ON OSS.ID_OS_SITE = OSP.ID_OS_SITE
LEFT JOIN GENESIS..WFM_TBA_OS_CONTRATO_SITE OSCS WITH(NOLOCK) ON OSCS.ID_OS_SITE = OSS.ID_OS_SITE
LEFT JOIN GENESIS..WFM_TBF_OS_CONTRATO OSC WITH(NOLOCK) ON OSC.ID_OS_CONTRATO = OSCS.ID_OS_CONTRATO AND OSP.PERIODO BETWEEN OSC.DATA_INICIO AND OSC.DATA_FIM
LEFT JOIN GENESIS..WFM_TBA_OS_EMPRESA OSE WITH(NOLOCK) ON OSE.ID_OS_EMPRESA = OSC.ID_OS_EMPRESA
LEFT JOIN GENESIS..WFM_TBA_OS_TIPO_PAGAMENTO OSTP WITH(NOLOCK) ON OSP.ID_OS_TIPO_PAGAMENTO = OSTP.ID_OS_TIPO_PAGAMENTO
LEFT JOIN (
            SELECT DISTINCT ROW_NUMBER() OVER (PARTITION BY NUM_OS ORDER BY DATA DESC) AS NL, NUM_OS, 1 AS CHECK_GPS_GNS, LAT, LONG
            FROM GENESIS..WFM_TBF_OS_PROCEDIMENTO WITH(NOLOCK)
            -- WHERE ID_OS_TIPO_PROC IN (16) -- ESTOU NO SITE VIA GSP               
        ) TB_CHECK_GPS ON OSP.NUM_OS = TB_CHECK_GPS.NUM_OS
LEFT JOIN (
            SELECT DISTINCT [NUM_OS] -- distinct utilizada por causa de respostas duplicadas
                ,CASE WHEN RESPOSTA = 'Não' AND ACEITE_EVIDENCIA = 1 AND ACEITE_PAGAMENTO = 1 THEN 1 ELSE 0 END AS ANALISE_JUST_ESTOU_NO_SITE,
                LAT, 
                LONG, 
                RESPOSTA
            FROM GENESIS..WFM_TBA_ROTEIRO_OS_RESPOSTAS WITH(NOLOCK)
            WHERE ID_ROTEIRO = 1 
            AND ID_ROTEIRO_PERGUNTA = 2  --"Conseguiu registrar que "Estou no Site" ?"
        ) AS TB_JUST_ESTOU_SITE ON OSP.NUM_OS = TB_JUST_ESTOU_SITE.NUM_OS
WHERE TB_CHECK_GPS.NL = 1 AND PERIODO >= '2024-08-01' --AND OSP.NUM_OS = 1421833
-- TECNICO_NO_SITE_DATA >= DATEADD(DAY, -2, GETDATE())
-- AND TB_JUST_ESTOU_SITE.ANALISE_JUST_ESTOU_NO_SITE = 1 AND TB_JUST_ESTOU_SITE.LAT IS NOT NULL



SELECT TOP 100 *  FROM GENESIS..WFM_TBF_OS_pagamento  WITH(NOLOCK) WHERE NIVEL_ATENDIMENTO = 1 AND PERIODO >= '2024-08-01'--= 917813
SELECT * FROM GENESIS..WFM_TBA_ROTEIRO_PERGUNTA WHERE ID_ROTEIRO_PERGUNTA = 2



-- ESTOU NO SITE VIA GPS APP
    -- LEFT JOIN (
    --             SELECT DISTINCT NUM_OS, 1 AS CHECK_GPS_GNS
    --             FROM [GENESIS].[dbo].[WFM_TBF_OS_PROCEDIMENTO] WITH(NOLOCK)
    --             WHERE ID_OS_TIPO_PROC IN (16) --- ESTOU NO SITE VIA GSP
    --           ) TB_CHECK_GPS ON TB_OS.NUM_OS = TB_CHECK_GPS.NUM_OS
 
    -- ANALISE JUSTIFICATIVA ESTOU NO SITE
    -- LEFT JOIN (
    --             SELECT distinct [NUM_OS] -- distinct utilizada por causa de respostas duplucadas
    --                 ,CASE
    --                     WHEN RESPOSTA = 'Não' AND ACEITE_EVIDENCIA = 1 AND ACEITE_PAGAMENTO = 1 THEN
    --                         1 ELSE 0 END ANALISE_JUST_ESTOU_NO_SITE
    --             FROM [GENESIS].[dbo].[WFM_TBA_ROTEIRO_OS_RESPOSTAS] WITH(NOLOCK)
    --             WHERE ID_ROTEIRO = 1 AND ID_ROTEIRO_PERGUNTA = 2
    --           ) AS TB_JUST_ESTOU_SITE ON OSP.NUM_OS = TB_JUST_ESTOU_SITE.NUM_OS

    SELECT TOP 10 * FROM GENESIS..WFM_TBF_OS WITH(NOLOCK) WHERE ID_OS_ORIGEM = 1 AND NUM_OS = 1052432   