SELECT
    SITE.REGIONAL AS REGIONAL_EVENTO,
    SITE.MUNICIPIO AS MUNICIPIO_EVENTO,
    CASE WHEN PGT.NIVEL_ATENDIMENTO = 1 THEN 'Sem Atuação'
         WHEN PGT.NIVEL_ATENDIMENTO = 2 THEN 'Com Atuação'
         WHEN PGT.NIVEL_ATENDIMENTO = 3 THEN 'Energia Alternativa'
    END NIVEL_ATENDIMENTO,
    PGT.NUM_OS,
    PGT.EVENTO,
    DATA_ENCERRAMENTO,
    PRIORIDADE,
    UF_EVENTO,
    SIGLA_LOCALIDADE_EVENTO,
    PGT.CODIGO_LOCALIDADE_EVENTO,
    GERENCIA_EVENTO,
    SITE_EVENTO,
    TIPO_PLANTA_EVENTO,
    SITE.UF AS UF_GENESIS,
    SITE.DDD AS DDD_GENESIS,
    SITE.SIGLA_MUNICIPIO AS LOCALIDADE_GENESIS,
    SITE.CNL AS CODIGO_LOCALIDADE_GENESIS,
    SITE.SIGLA_SITE AS SITE_GENESIS,
    TIPO_PGT.TIPO_PAGAMENTO AS TIPO_PAGAMENTO,
    CASE WHEN ENCAMINHADO_TECNICO = 0 THEN 'Não'
         WHEN ENCAMINHADO_TECNICO = 1 THEN 'Sim'
    END ENCAMINHADO_TECNICO,
    PGT.ENCAMINHADO_TECNICO_NOME,
    CASE WHEN ACEITE = 0 THEN 'Não'
         WHEN ACEITE = 1 THEN 'Sim'
    END ACEITE,
    PGT.ACEITE_NOME,
    CASE WHEN TECNICO_NO_SITE = 0 THEN 'Não'
         WHEN TECNICO_NO_SITE = 1 THEN 'Sim'
    END TECNICO_NO_SITE,
    PGT.TECNICO_NO_SITE_NOME,
    CASE WHEN PRE_BAIXA = 0 THEN 'Não'
         WHEN PRE_BAIXA = 1 THEN 'Sim'
    END PRE_BAIXA,
    PGT.PRE_BAIXA_NOME,
    CASE WHEN ENERGIA_ALTERNATIVA = 0 THEN 'Não'
         WHEN ENERGIA_ALTERNATIVA = 1 THEN 'Sim'
    END ENERGIA_ALTERNATIVA,
    PGT.ENERGIA_ALTERNATIVA_NOME,
    PGT.CONTRATO,
    PGT.EMPRESA
FROM GENESIS..WFM_TBF_OS_PAGAMENTO PGT WITH(NOLOCK)
LEFT JOIN GENESIS..WFM_TBA_OS_TIPO_PAGAMENTO TIPO_PGT WITH(NOLOCK) ON PGT.ID_OS_TIPO_PAGAMENTO = TIPO_PGT.ID_OS_TIPO_PAGAMENTO
LEFT JOIN GENESIS..WFM_TBF_OS_SITE SITE WITH(NOLOCK) ON PGT.ID_OS_SITE = SITE.ID_OS_SITE
WHERE  PGT.EVENTO = 322817054 --and MONTH(PERIODO) = 1 AND YEAR(PERIODO) = 2024




SELECT TOP 1 * FROM GENESIS..WFM_TBF_OS WITH(NOLOCK) WHERE EVENTO = 322817054 --322817435 -- --