SELECT 
      [CLASSIFICACAO_GRUPO],
      COUNT(*)
  FROM [INDICADORES_CORAN].[dbo].[AUX_CLASSIFICACAO_GESTORES]
  GROUP BY 
      [CLASSIFICACAO_GRUPO]


SELECT CLASSIFICACAO_GRUPO, GRUPO, ID_GRUPO_SIGITM FROM INDICADORES_CORAN..AUX_CLASSIFICACAO_GESTORES
WHERE CLASSIFICACAO_GRUPO = 'CAMPO - TERCEIRA'

-- PORTAL NOC_CORAN
CORAN - PROPRIO
CORAN - TERCEIRA
NOC
-- PORTAL CAMPO
CAMPO - PROPRIO
CAMPO - TERCEIRA



SELECT STUFF (
    (SELECT CONCAT(',',ID_GRUPO_SIGITM) FROM INDICADORES_CORAN..AUX_CLASSIFICACAO_GESTORES WHERE CLASSIFICACAO_GRUPO = 'CAMPO - PROPRIO' FOR XML PATH('')),1,1,'') AS GRUPOS





