SELECT
    A.*,
    B.TIPO_BILHETE,
    C.TECNOLOGIA,
    C.EQUIPAMENTO
FROM REDE_EXTERNA..TBL_GRAFO_EVENTOS A
INNER JOIN REDE_EXTERNA..TBL_EVENTOS_ATIVOS_SIGITM B ON A.TA_REFERENCIA = B.EVENTO
INNER JOIN REDE_EXTERNA..TBL_EVENTOS_ATIVOS_SIGITM C ON A.TA_PARA = C.EVENTO
-- WHERE TA_REFERENCIA
ORDER BY TA_REFERENCIA, ID_SALTO


SELECT TOP 100 * FROM REDE_EXTERNA..TBL_EVENTOS_ATIVOS_SIGITM WHERE EVENTO_REFERENCIA = 315161423 ORDER BY EVENTO_ORIGEM DESC

-- CONSIDERAÇÕES DO PROJETO "GRAFO":
    -- qdo evento_origem = evento_referencia o ta não possui "ta mais alto"
    -- evento_referencia é o ta mais alto
    -- evento com evento_origem diferente de nulo é um evento elemento

SELECT DISTINCT
UF,
SIGLA_SITE
FROM (
SELECT A.*, CASE WHEN D.GESTAO = 'INTERIOR' THEN 'SPI' WHEN D.GESTAO = 'CAPITAL' THEN 'SPC' ELSE C.UF END UF, C.SIGLA_SITE, C.EQUIPAMENTO, C.TIPO_EQUIPAMENTO, C.TIPO_REDE FROM REDE_EXTERNA..TBL_GRAFO_EVENTOS A
INNER JOIN REDE_EXTERNA..TBL_EVENTOS_ATIVOS_SIGITM B ON A.TA_REFERENCIA = B.EVENTO
INNER JOIN REDE_EXTERNA..TBL_EVENTOS_ATIVOS_SIGITM C ON A.TA_PARA = C.EVENTO
LEFT JOIN INDICADORES_CORAN..TBA_DIVISAO_MUNICIPIOS_SP_FIXA D ON C.UF = 'SP' AND C.MUNICIPIO = D.MUNICIPIO
WHERE B.TIPO_BILHETE LIKE '%BACKBONE%' AND C.TIPO_REDE = 'ERB / Repetidor' AND A.TIPO_SALTO = 'ORIGEM'
) E



