
-- HISTORICO DOS SITES COM CDT E SEM EVENTO

WITH EVENTOS AS (
SELECT DISTINCT
    TQA_CODIGO,
    VDA_TA_STATUS,
    UF,
    SITE,
    Periodo
FROM CAMILA..TBL_EVENTOS A
INNER JOIN FABIO..fn_GerIntervalos('20240101','20240930',1,'d') B ON B.Periodo >= A.DATA AND B.Periodo <= A.DATA_2
),

DISP AS (
SELECT
*
FROM CAMILA..TBL_DISP_DIARIA_SITE
-- WHERE MINUTOS_CDT > 15
),

ANALITICO AS (
SELECT
DISP.*,
SUM(CASE WHEN TQA_CODIGO IS NOT NULL THEN 1 ELSE 0 END) AS QTDE_TA
FROM DISP
LEFT JOIN EVENTOS ON DISP.UF = EVENTOS.UF AND DISP.SITE = EVENTOS.SITE AND DISP.DATA_REFERENCIA = EVENTOS.Periodo
WHERE MINUTOS_CDT > 0
GROUP BY DATA_REFERENCIA, DISP.UF, DISP.SITE, MINUTOS_CDT
)

SELECT
-- UF,
-- SITE,
DATA_REFERENCIA,
SITE_COM_TA_CDT = SUM(CASE WHEN QTDE_TA > 0 THEN 1 ELSE 0 END),
SITE_SEM_TA_CDT = SUM(CASE WHEN QTDE_TA = 0  THEN 1 ELSE 0 END),
SITE_COM_TA_CDT_15 = SUM(CASE WHEN QTDE_TA > 0 AND MINUTOS_CDT > 15 THEN 1 ELSE 0 END),
SITE_SEM_TA_CDT_15 = SUM(CASE WHEN QTDE_TA = 0 AND MINUTOS_CDT > 15 THEN 1 ELSE 0 END),
COUNT(DISTINCT UF+SITE) AS TOTAL
FROM ANALITICO
WHERE DATA_REFERENCIA >= '20240801' AND DATA_REFERENCIA < '20240901'
GROUP BY DATA_REFERENCIA--, UF, SITE



