SELECT
ANO,
MES,
REGIONAL,
CDT.UF,
CN.CN,
CDT.MUNICIPIO,
TOP50.CLASSIFICACAO AS CLASSIFICACAO_MUNICIPIO,
DISPONIBILIDADE_2G,
DISPONIBILIDADE_3G,
DISPONIBILIDADE_4G,
DISPONIBILIDADE_GERAL,
CASE WHEN DISPONIBILIDADE_GERAL >= 99.2 THEN 'A+' 
     WHEN DISPONIBILIDADE_GERAL >= 99 THEN 'A' 
     WHEN DISPONIBILIDADE_GERAL >= 98 THEN 'B' 
     WHEN DISPONIBILIDADE_GERAL >= 96 THEN 'C' 
     WHEN DISPONIBILIDADE_GERAL >= 92 THEN 'D' 
     WHEN DISPONIBILIDADE_GERAL < 92 THEN 'E' 
END NOTA_IND11,
ISNULL(FLG_REINCIDENCIA, 0) AS FLG_REINCIDENCIA,
ISNULL(PLN.PLANOS, 0) AS PLANOS_ACAO
FROM INDICADORES_CORAN.dbo.TBF_CELLDOWNTIME_MENSAL_MUNICIPIO_HMM CDT
LEFT JOIN (SELECT * FROM SISTEMA_MAESTRO..AUX_CLASSIFICACAO_MUNICIPIOS) TOP50 ON CDT.UF = TOP50.UF AND CDT.MUNICIPIO = TOP50.MUNICIPIO
LEFT JOIN (SELECT DISTINCT UF AS UF_CN, MUNICIPIO AS MUNICIPIO_CN, CN FROM SISTEMA_MAESTRO..TBA_PLANTA_MOVEL) CN ON CDT.UF = CN.UF_CN AND CDT.MUNICIPIO = CN.MUNICIPIO_CN
LEFT JOIN (SELECT UF, MUNICIPIO, COUNT(*) AS PLANOS FROM INDICADORES_CORAN.dbo.TBC_PLANO_ACAO GROUP BY UF, MUNICIPIO) PLN ON CDT.UF = PLN.UF AND CDT.MUNICIPIO = PLN.MUNICIPIO
WHERE ANO = 2024 AND MES IN (8,9)
ORDER BY 1,2,3,4,5


