--==============================================================================================
--INFANCIA MOVEL
--==============================================================================================

SELECT
*
FROM (		
		SELECT DISTINCT
		A.UF,
		SUBSTRING(SIGLA_ERB,2,3) AS SITE,
		A.SIGLA_ERB,
		A.TECNOLOGIA,
		A.DATA_ATIVACAO,
		FORMAT(A.DATA_CRIACAO_TA,'dd/MM/yyyy') AS DATA_CRIACAO,
		DATEDIFF(DAY,A.DATA_ATIVACAO,A.DATA_CRIACAO_TA) AS DIAS
		FROM(
			SELECT DISTINCT
			PORT.CHAVE,
			PORT.UF,
			PORT.SIGLA_ERB,
			PORT.TECNOLOGIA,
			PORT.DATA_ATIVACAO,
			TAS.DATA_CRIACAO_TA
			FROM INFANCIA_MOVEL..TBL_PORTADORAS PORT
			INNER JOIN (
						SELECT DISTINCT
						CHAVE,
						MIN(DATA_CRIACAO) AS DATA_CRIACAO_TA
						FROM INFANCIA_MOVEL..TBL_TAS
						WHERE TIPO_BILHETE <> 'Aceite RF'
						GROUP BY CHAVE
						) TAS ON TAS.CHAVE = PORT.CHAVE
			)A
		INNER JOIN INFANCIA_MOVEL..TBL_TAS TAS2 ON TAS2.CHAVE = A.CHAVE
		WHERE A.DATA_CRIACAO_TA > A.DATA_ATIVACAO AND DATEDIFF(DAY,A.DATA_ATIVACAO,A.DATA_CRIACAO_TA) <> 0
		)B
INNER JOIN INFANCIA_MOVEL..TBL_DISPONIBILIDADE DISP ON DISP.UF = B.UF AND DISP.SITE = B.SITE
ORDER BY B.UF, B.SITE, SIGLA_ERB, MES, DIA

--===============================================================================================
--DATA ATIVACAO PORTADORAS
SELECT 
UF+'_'+SIGLA_ERB+'_'+TECNOLOGIA AS CHAVE,
UF,
SIGLA_ERB,
SIGLA_ERB_LOGICA,
TECNOLOGIA,
FORMAT(MAX(DT_ATIVACAO_SETOR),'dd/MM/yyyy') AS DATA_ATIVACAO
FROM SISTEMA_MAESTRO..TBA_PLANTA_MOVEL
WHERE DT_ATIVACAO_SETOR >= '2023-01-01' 
GROUP BY UF,SIGLA_ERB_LOGICA,TECNOLOGIA,SIGLA_ERB 
ORDER BY UF,SIGLA_ERB


WITH CTE AS (
		SELECT DISTINCT
			PORT.UF,
			SUBSTRING(PORT.SIGLA_ERB, 2, 3) AS SITE,
			PORT.SIGLA_ERB,
			PORT.TECNOLOGIA,
			PORT.DATA_ATIVACAO,
			MIN(TAS.DATA_CRIACAO) AS DATA_CRIACAO_TA
		FROM INFANCIA_MOVEL..TBL_PORTADORAS PORT
			INNER JOIN INFANCIA_MOVEL..TBL_TAS TAS
				ON TAS.CHAVE = PORT.CHAVE
					AND TAS.TIPO_BILHETE <> 'Aceite RF'
		GROUP BY PORT.UF, PORT.SIGLA_ERB, PORT.TECNOLOGIA, PORT.DATA_ATIVACAO
	)
SELECT
	CTE.UF,
	CTE.SITE,
	CTE.SIGLA_ERB,
	CTE.TECNOLOGIA,
	CTE.DATA_ATIVACAO,
	FORMAT(CTE.DATA_CRIACAO_TA, 'dd/MM/yyyy') AS DATA_CRIACAO,
	DATEDIFF(DAY, CTE.DATA_ATIVACAO, CTE.DATA_CRIACAO_TA) AS DIAS
FROM CTE
	INNER JOIN INFANCIA_MOVEL..TBL_DISPONIBILIDADE DISP
		ON DISP.UF = CTE.UF
			AND DISP.SITE = CTE.SITE
WHERE CTE.DATA_CRIACAO_TA > CTE.DATA_ATIVACAO
	AND DATEDIFF(DAY, CTE.DATA_ATIVACAO, CTE.DATA_CRIACAO_TA) <> 0
ORDER BY CTE.UF, CTE.SITE, CTE.SIGLA_ERB, DISP.MES, DISP.DIA



--DATA ATIVACAO PORTADORAS
SELECT
CHAVE,
MAX(DATA_ATIVACAO)
--MIN(DATA_ATIVACAO)
FROM (
	
	SELECT 
	UF+SIGLA_SITE AS CHAVE,
	UF,
	SIGLA_ERB,
	SIGLA_ERB_LOGICA,
	TECNOLOGIA,
	FORMAT(MAX(DT_ATIVACAO_SETOR),'dd/MM/yyyy') AS DATA_ATIVACAO
	FROM SISTEMA_MAESTRO..TBA_PLANTA_MOVEL
	WHERE UF = 'AM' AND SIGLA_SITE = 'DUB' AND TECNOLOGIA = 'LTE' --AND DT_ATIVACAO_SETOR >= '2023-01-01' 
	GROUP BY UF,SIGLA_ERB_LOGICA,TECNOLOGIA,SIGLA_ERB,SIGLA_SITE
	--ORDER BY UF,SIGLA_ERB

	) A
GROUP BY CHAVE

SELECT
CHAVE,
DT_MAX,
CASE WHEN DT_MAX = DT_MIN THEN 'SITE_NOVO'
ELSE 'AMPLIACAO'
END AS TIPO
FROM (
	SELECT
	UF+SIGLA_SITE AS CHAVE,
	FORMAT(MAX(DT_ATIVACAO_SETOR),'dd/MM/yyyy') AS DT_MAX,
	FORMAT(MIN(DT_ATIVACAO_SETOR),'dd/MM/yyyy') AS DT_MIN
	FROM SISTEMA_MAESTRO..TBA_PLANTA_MOVEL
	WHERE TECNOLOGIA = 'LTE' AND UF+SIGLA_SITE IN 
	('SEJRD','SEBCG','SEPCQ','SENAP','SESSI','SESTN','SECMC','SEMEC','SEDIA','SEROB','SEEMD','SEAAF','SESQC','SEJAB','SESTG','SECBG','SEBSM','SEPNB','SECAD','SEPRL','PATEN','PALBT','PABEG','PASMZ','PAAEP','PACAT','PATVB','PACRE','SCBPG','SCBGA','SCBPM','SCBIZ','SCBVL','SCBJB','SCBC3','SCBRJ','SCBSH','SC1BE','SPOMA','SPPTE','SPNSA','SPETO','SPNCL','SPJBE','SPMMX','SPJTR','SPKWI','SPLON','SPQCT','SPDBO','SPBOS','SPUNE','SPRWR','SP1LS','SPMAM','SPSGL','SPNIL','SPCMI','SPFTP','SPABE','MGCUR','MGMZA','MGFLA','MGSCI','MGCPS','MGVPC','MGAGB','MGCOR','MGPFD','MGBJL','MGIFC','MGLIN','MGCNI','MGCJH','PRKL2','PRKT4','PRKCI','PRKOF','PRK3E','PRKLM','PRK2X','PRKMS','PRK3X','PRKTG','PRKJZ','PRKOR','PR1TN','PR1TS','PRKUB','PRKES','PRK0Q','PRK3K','PRKJ2','PRK1I','PRK22','PRK0O','PRKTB','CEOHP','CEPFT','CETZM','CEKPF','CELUC','CECYJ','CEPSF','CEOGD','CECFD','CEXMM','CEJBA','CEDIG','CEPOV','CEANU','CEPCC','CESBC','CECBB','CEOPV','CECSP','CEOHR','CEDRM','CEOHM','CECBU','CEOEZ','CEIND','CEMUD','CENTH','CEXJG','CEOFY','CEOHF','SPBCL','SPVFL','SPGAN','SPG0P','SPALZ','SPGDO','SPG1P','SPGCE','SPGVR','SPVAG','SPG0N','SPJDI','SPCDK','SPMRT','SPSC0','SPU31','SPJJP','SPANK','SPJDB','SPVYG','SPJ1D','SPVRB','SPBVT','SPCOU','SPPNT','SPJID','SPJJT','AMASL','AMSRT','AMOVB','AMSTO','AMBBD','AMCHM','AMGTL','AMTCN','AMAMD','AMARN','AMR25','AMCAE','AMPUR','AMATM','AMCT2','AMNNT','AMCB1','AMNV1','AMRCG','AMANS','AMSUC','AMVRT','AMVIV','AMJTD','AMED2','AMPRO','AMCTI','AMEDU','AMALN','AMTRR','AMMJS','AMZFR','AMRRC','AMADT','AMPHI','AMTOR','AMHBC','AMPSR','AMCUB','AMJRM','AMMSN','AMYHM','AMTML','AMRSS','AMVER','AMLGZ','AMGUA','AMCVF','AM5ST','AMRPO','AMPDA','AMITM','AMDUB','AMAXA','RJVDC','RJEGH','RJBRT','RJNST','RJMVT','RJAND','RJBMZ','RJROO','RJCCH','RJGGT','RJEGM','RJJDP','RJCHA','RJNSR','RJ1FU','RJLDP','RJJFT','RJEIT','RJMPA','RSBBC','PEOSR','PEORK','PEORU','PEETN','PEPNH','PEFTP','PEOLG','PEJSF','PERJR','PEVSI','PEMRZ','PEMRZ','PEATA','PEATA','PERES','PEDDC','PEILB','PERBC','PEIMI','PEIMZ','PEPRD','PEGDA','PEMCC','PEJIQ','PETHR','PEBPN','PEPNA','PEPJD','PECDC','PEBST','PEBTK','PESTW','PENPR','PENVD','PECPG','PERDP','PEAIR','PERMT','PETAM','PEVMU','PERLM','PEJSP','BAPBV','BACLB','BAMSS','BAALB','BAMPC','BARIB','BACBB','BABAM','BASCR','BAPAR','BACXI','BAPRA','BAACA','BASSB','BAEIT','BAACS','BABVS','BAPDL','BAJNE','BAMOI','BAMUS','BAAEP','BAMCD','BALDS','BABAT','BALGU','BAAMA','BA1FS','BA1MQ','BA1LS','BAALJ','BALPT','BAALL','BAEVF','BACBS','BABAO','BANPB','BASPR','BAHAM','SPIMR','SPMCL','SPIMG','SPSB3','SPSME','SPNPE','SPBAS','SPBTE','SPPSS','SPITL','SPTN2','SPXIG','SPJKL','SPRIL','SPOJU','SPOKJ','SPOS9','SPSFX','SPSOE','SPTMT','MAVAL','MACMG','MACHB','MACBD','MALBT','MACM2','MASVA','MAVPA','MARNA','MACFM','MACTD','MATUR','MAUFM','MATR2','MAJNM','MACHT','MAVHS','MAMCB','MAAHD','MAMC1','ESRBA','ESCLL','ESCYO','ESMAG','ESEJA','ESJAN','ESPRF','ESPLC','RSDIE'
	)
	GROUP BY UF, SIGLA_SITE
	) A
	ORDER BY CHAVE