-- DISPONIBILIDADES SPI

-- MENSAL SPI
SELECT TOP 30 ANO, MES, UF, DISPONIBILIDADE_2G AS DISP_2G, DISPONIBILIDADE_3G AS DISP_3G, DISPONIBILIDADE_4G AS DISP_4G, DISPONIBILIDADE_5G AS DISP_5G, DISPONIBILIDADE_GERAL AS DISP_GERAL, DISPONIBILIDADE_4G_5G AS DISP_4G_5G
FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_MENSAL_UF_HMM
WHERE ANO = 2024 AND UF = 'INTERIOR'
ORDER BY MES

-- DIARIA POR ALIADA
SELECT
DATA_REFERENCIA, ANO, MES, DIA, EMPRESA, DISPONIBILIDADE_2G AS DISP_2G, DISPONIBILIDADE_3G AS DISP_3G, DISPONIBILIDADE_4G AS DISP_4G, DISPONIBILIDADE_5G AS DISP_5G, DISPONIBILIDADE_GERAL AS DISP_GERAL, DISPONIBILIDADE_4G_5G AS DISP_4G_5G
FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_DIARIO_ALIADAS_HMM WITH(NOLOCK)
WHERE EMPRESA IN ('ABILITYSPI','TEL SP') AND ANO = 2024 AND MES = DATEPART(MONTH,GETDATE())
ORDER BY DIA

-- MENSAL POR ALIADA
SELECT
DATA_REFERENCIA, ANO, MES, EMPRESA, DISPONIBILIDADE_2G AS DISP_2G, DISPONIBILIDADE_3G AS DISP_3G, DISPONIBILIDADE_4G AS DISP_4G, DISPONIBILIDADE_5G AS DISP_5G, DISPONIBILIDADE_GERAL AS DISP_GERAL, DISPONIBILIDADE_4G_5G AS DISP_4G_5G
FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_MENSAL_ALIADAS_HMM WITH(NOLOCK)
WHERE EMPRESA IN ('ABILITYSPI','TEL SP') AND ANO = 2024
ORDER BY MES

-- SEMANAL POR CN
SELECT
ANO, SEMANA, CN, DISPONIBILIDADE_2G AS DISP_2G, DISPONIBILIDADE_3G AS DISP_3G, DISPONIBILIDADE_4G AS DISP_4G, DISPONIBILIDADE_5G AS DISP_5G, DISPONIBILIDADE_GERAL AS DISP_GERAL, DISPONIBILIDADE_4G_5G AS DISP_4G_5G
FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_SEMANAL_CN_HMM WITH(NOLOCK)
WHERE ANO = 2024 AND SEMANA >= 36 AND CN LIKE '1%'
ORDER BY SEMANA, CN

-- DIARIA POR CN
SELECT
ANO, MES, DIA, CN, DISPONIBILIDADE_2G AS DISP_2G, DISPONIBILIDADE_3G AS DISP_3G, DISPONIBILIDADE_4G AS DISP_4G, DISPONIBILIDADE_5G AS DISP_5G, DISPONIBILIDADE_GERAL AS DISP_GERAL, DISPONIBILIDADE_4G_5G AS DISP_4G_5G
FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_DIARIO_CN_HMM WITH(NOLOCK)
WHERE ANO = 2024 AND MES = DATEPART(MONTH,GETDATE()) AND CN IN (12,14,15,16,17,18,19)
ORDER BY DIA, CN

-- MENSAL POR CN
SELECT
ANO, MES, CN, DISPONIBILIDADE_2G AS DISP_2G, DISPONIBILIDADE_3G AS DISP_3G, DISPONIBILIDADE_4G AS DISP_4G, DISPONIBILIDADE_5G AS DISP_5G, DISPONIBILIDADE_GERAL AS DISP_GERAL, DISPONIBILIDADE_4G_5G AS DISP_4G_5G
FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_MENSAL_CN_HMM WITH(NOLOCK)
WHERE ANO = 2024 AND CN IN (12,14,15,16,17,18,19)
ORDER BY MES, CN

-- ====================================================================================================
SELECT
    ANO,
    MES, 
	UF,
    C.CLUSTER AS CLUSTER,
    C.REGIAO_CLUSTER,
    COUNT(DISTINCT SITE) AS QTDE_SITES, 
    ROUND(((1-(SUM(CASE WHEN TECNOLOGIA = 'WCDMA' AND TEMPO_CONTADOR_HMM >= 0 THEN TEMPO_CONTADOR_HMM END)/(SUM(CASE WHEN TECNOLOGIA = 'WCDMA' THEN COLETAS_HMM END)*60)))*100),2) AS DISP_3G,
    ROUND(((1-(SUM(CASE WHEN TECNOLOGIA = 'LTE' AND TEMPO_CONTADOR_HMM >= 0 THEN TEMPO_CONTADOR_HMM END)/(SUM(CASE WHEN TECNOLOGIA = 'LTE' THEN COLETAS_HMM END)*60)))*100),2) AS DISP_4G,
    ROUND(((1-(SUM(CASE WHEN TECNOLOGIA = '5G' AND TEMPO_CONTADOR_HMM >= 0 THEN TEMPO_CONTADOR_HMM END)/(SUM(CASE WHEN TECNOLOGIA = '5G' THEN COLETAS_HMM END)*60)))*100),2) AS DISP_5G,
    ROUND(((1-(SUM(CASE WHEN TECNOLOGIA <> 'GSM' AND TEMPO_CONTADOR_HMM >= 0 THEN TEMPO_CONTADOR_HMM END)/(SUM(CASE WHEN TECNOLOGIA <> 'GSM' THEN COLETAS_HMM END)*60)))*100),2) AS DISP_GERAL,
    ROUND(((1-(SUM(CASE WHEN TECNOLOGIA IN ('LTE','5G') AND TEMPO_CONTADOR_HMM >= 0 THEN TEMPO_CONTADOR_HMM END)/(SUM(CASE WHEN TECNOLOGIA IN ('LTE','5G') THEN COLETAS_HMM END)*60)))*100),2) AS DISP_4G_5G
    
FROM (
    SELECT
        YEAR(DATA_REFERENCIA) AS ANO,
        MONTH(DATA_REFERENCIA) AS MES,
        A.TECNOLOGIA,
        A.UF,
        B.CLUSTER,
        B.REGIAO_CLUSTER,
        CAST(TEMPO_CONTADOR_HMM AS FLOAT) AS TEMPO_CONTADOR_HMM,
        CAST(COLETAS_HMM AS FLOAT) AS COLETAS_HMM,
        A.SITE
    FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES A WITH(NOLOCK)
    INNER JOIN SISTEMA_MAESTRO..TBA_PLANTA_MOVEL B WITH(NOLOCK) ON A.UF = B.UF AND A.SITE = B.SIGLA_SITE
    LEFT JOIN INDICADORES_CORAN..TBA_DIVISAO_MUNICIPIOS_SP_FIXA C ON A.UF = 'SP' AND A.MUNICIPIO = C.MUNICIPIO
    WHERE YEAR(DATA_REFERENCIA) = 2024 AND A.UF = 'SP' 
) C
GROUP BY ANO, MES, UF, C.CLUSTER