-- =======================================
-- QTDE DE TAS POR DIA - REDE EXTERNA
-- =======================================
SELECT
B.*,
CEILING(PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY QTDE_TAS) OVER (PARTITION BY UF, MUNICIPIO)) AS Q3
FROM (
    SELECT
    DATA,
    UF,
    MUNICIPIO,
    CASE WHEN UF + '_' + MUNICIPIO IN ('AC_RIO BRANCO','AL_MACEIÓ','AP_MACAPÁ','AM_MANAUS','BA_SALVADOR','CE_FORTALEZA','DF_BRASÍLIA','ES_VITÓRIA','GO_GOIÂNIA','MA_SÃO LUÍS','MT_CUIABÁ','MS_CAMPO GRANDE',
                                    'MG_BELO HORIZONTE','PA_BELÉM','PB_JOÃO PESSOA',    'PR_CURITIBA','PE_RECIFE','PI_TERESINA','RJ_RIO DE JANEIRO','RN_NATAL','RS_PORTO ALEGRE','RO_PORTO VELHO','RR_BOA VISTA',
                                    'SC_FLORIANÓPOLIS','SP_SÃO PAULO','SE_ARACAJU','TO_PALMAS') THEN 'SIM' ELSE 'NÃO'
    END CAPITAL,
    COUNT(DISTINCT TA_REDE_EXTERNA) AS QTDE_TAS
    FROM (
    SELECT  
            CONVERT(DATE, DATA_REFERENCIA, 103) AS DATA,
            UF,
            MUNICIPIO,    
            TA_REDE_EXTERNA
    FROM REDE_EXTERNA..TBL_HIST_TAS_REDE_PROPRIA
    WHERE UF <> '-'
    -- ORDER BY DATA_REFERENCIA
    ) A
    -- WHERE MUNICIPIO = 'BELO HORIZONTE' --MUNICIPIO IN ('BELO HORIZONTE', 'VITORIA')
    GROUP BY DATA, UF, MUNICIPIO
    -- ORDER BY UF, MUNICIPIO, DATA
)B

-- =========================================
-- QTDE DE TAS POR DIA - PLANTA INTERNA
-- =========================================
SELECT
B.*,
CEILING(PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY QTDE_TAS) OVER (PARTITION BY UF, MUNICIPIO)) AS Q3
FROM (
    SELECT
    DATA,
    UF,
    MUNICIPIO,
    CASE WHEN UF + '_' + MUNICIPIO IN ('AC_RIO BRANCO','AL_MACEIÓ','AP_MACAPÁ','AM_MANAUS','BA_SALVADOR','CE_FORTALEZA','DF_BRASÍLIA','ES_VITÓRIA','GO_GOIÂNIA','MA_SÃO LUÍS','MT_CUIABÁ','MS_CAMPO GRANDE',
                                    'MG_BELO HORIZONTE','PA_BELÉM','PB_JOÃO PESSOA',    'PR_CURITIBA','PE_RECIFE','PI_TERESINA','RJ_RIO DE JANEIRO','RN_NATAL','RS_PORTO ALEGRE','RO_PORTO VELHO','RR_BOA VISTA',
                                    'SC_FLORIANÓPOLIS','SP_SÃO PAULO','SE_ARACAJU','TO_PALMAS') THEN 'SIM' ELSE 'NÃO'
    END CAPITAL,
    COUNT(DISTINCT TA_CAMPO) AS QTDE_TAS
    FROM (
    SELECT  
            CONVERT(DATE, DATA_REFERENCIA, 103) AS DATA,
            UF,
            MUNICIPIO,    
            TA_CAMPO
    FROM REDE_EXTERNA..TBL_PORTAL_CAMPO_HIST
    WHERE UF <> '-' AND CONVERT(DATE, DATA_REFERENCIA, 103) IS NOT NULL
    -- ORDER BY DATA_REFERENCIA
    ) A
    GROUP BY DATA, UF, MUNICIPIO
)B

-- ============================================================================================================================================================================================
/* 
SELECT  
            DATA_REFERENCIA,
            -- CONVERT(DATE, DATA_REFERENCIA, 103) AS DATA,
            UF,
            MUNICIPIO,    
            TA_CAMPO
    FROM REDE_EXTERNA..TBL_PORTAL_CAMPO_HIST
    WHERE UF <> '-' AND CONVERT(DATE, DATA_REFERENCIA, 103) IS NULL
ORDER BY TA_CAMPO DESC

-- ESTATISTICAS (TODO PERÍODO)
SELECT DISTINCT
  UF,
  MUNICIPIO,
  CAPITAL,
  CEILING(AVG(QTDE_TAS) OVER (PARTITION BY UF, MUNICIPIO)) AS MEDIA,
  CEILING(PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY QTDE_TAS) OVER (PARTITION BY UF, MUNICIPIO)) AS Q1,
  CEILING(PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY QTDE_TAS) OVER (PARTITION BY UF, MUNICIPIO)) AS MEDIANA,
  CEILING(PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY QTDE_TAS) OVER (PARTITION BY UF, MUNICIPIO)) AS Q3
FROM (
SELECT
  DATA,
  UF,
  MUNICIPIO,
  CASE WHEN UF + '_' + MUNICIPIO IN ('AC_RIO BRANCO','AL_MACEIÓ','AP_MACAPÁ','AM_MANAUS','BA_SALVADOR','CE_FORTALEZA','DF_BRASÍLIA','ES_VITÓRIA','GO_GOIÂNIA','MA_SÃO LUÍS','MT_CUIABÁ','MS_CAMPO GRANDE',
                                    'MG_BELO HORIZONTE','PA_BELÉM','PB_JOÃO PESSOA',    'PR_CURITIBA','PE_RECIFE','PI_TERESINA','RJ_RIO DE JANEIRO','RN_NATAL','RS_PORTO ALEGRE','RO_PORTO VELHO','RR_BOA VISTA',
                                    'SC_FLORIANÓPOLIS','SP_SÃO PAULO','SE_ARACAJU','TO_PALMAS') THEN 'SIM' ELSE 'NÃO'
  END CAPITAL,
  COUNT(DISTINCT TA_REDE_EXTERNA) AS QTDE_TAS
FROM (
  SELECT  
          CONVERT(DATE, DATA_REFERENCIA, 103) AS DATA,
          UF,
          MUNICIPIO,    
          TA_REDE_EXTERNA
  FROM REDE_EXTERNA..TBL_HIST_TAS_REDE_PROPRIA
  WHERE UF <> '-'
  -- ORDER BY DATA_REFERENCIA
) A
GROUP BY DATA, UF, MUNICIPIO
) B
WHERE CAPITAL = 'SIM'
ORDER BY UF, MUNICIPIO


-- ESTATISTICAS PARA ÚLTIMOS X DIAS
DECLARE @DIAS INT = 60
SELECT DISTINCT
  UF,
  MUNICIPIO,
  CAPITAL,
  CEILING(AVG(QTDE_TAS) OVER (PARTITION BY UF, MUNICIPIO)) AS MEDIA,
  CEILING(PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY QTDE_TAS) OVER (PARTITION BY UF, MUNICIPIO)) AS Q1,
  CEILING(PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY QTDE_TAS) OVER (PARTITION BY UF, MUNICIPIO)) AS MEDIANA,
  CEILING(PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY QTDE_TAS) OVER (PARTITION BY UF, MUNICIPIO)) AS Q3,
  SUM(QTDE_TAS) OVER (PARTITION BY UF, MUNICIPIO) AS SOMA
FROM (
        SELECT
            DATA,
            UF,
            MUNICIPIO,
            CASE WHEN UF + '_' + MUNICIPIO IN ('AC_RIO BRANCO','AL_MACEIÓ','AP_MACAPÁ','AM_MANAUS','BA_SALVADOR','CE_FORTALEZA','DF_BRASÍLIA','ES_VITÓRIA','GO_GOIÂNIA','MA_SÃO LUÍS','MT_CUIABÁ','MS_CAMPO GRANDE',
                                    'MG_BELO HORIZONTE','PA_BELÉM','PB_JOÃO PESSOA',    'PR_CURITIBA','PE_RECIFE','PI_TERESINA','RJ_RIO DE JANEIRO','RN_NATAL','RS_PORTO ALEGRE','RO_PORTO VELHO','RR_BOA VISTA',
                                    'SC_FLORIANÓPOLIS','SP_SÃO PAULO','SE_ARACAJU','TO_PALMAS') THEN 'SIM' ELSE 'NÃO'
            END CAPITAL,
            COUNT(DISTINCT TA_REDE_EXTERNA) AS QTDE_TAS
        FROM (
            SELECT  
                CONVERT(DATE, DATA_REFERENCIA, 103) AS DATA,
                UF,
                MUNICIPIO,    
                TA_REDE_EXTERNA
            FROM REDE_EXTERNA..TBL_HIST_TAS_REDE_PROPRIA
            WHERE UF <> '-' 
                -- AND CONVERT(DATE,DATA_REFERENCIA,103) BETWEEN GETDATE()-@DIAS AND GETDATE()
            --WHERE CONVERT(DATE,DATA_REFERENCIA,103) >= '2024-01-01' AND CONVERT(DATE,DATA_REFERENCIA,103) < '2024-02-01'
) A
GROUP BY DATA, UF, MUNICIPIO
) B
WHERE CAPITAL = 'SIM'
ORDER BY UF, MUNICIPIO




-- MÉDIA MÓVEL DA QTDE DE TAS POR DIA
SELECT
UF,
DATA, 
ROUND(AVG(QTDE_TAS) OVER (PARTITION BY UF ORDER BY DATA ROWS BETWEEN 15 PRECEDING AND CURRENT ROW),2) AS MM_QTDE_TAS
FROM
(
      SELECT
        DATA,
        UF,
        COUNT(DISTINCT TA_REDE_EXTERNA) AS QTDE_TAS
      FROM (
          SELECT  
            CONVERT(DATE, DATA_REFERENCIA, 103) AS DATA,
            UF,    
            TA_REDE_EXTERNA
          FROM REDE_EXTERNA..TBL_HIST_TAS_REDE_PROPRIA
          WHERE UF <> '-'
        -- ORDER BY DATA_REFERENCIA
      ) A
      --WHERE UF = 'MG'
      GROUP BY DATA, UF
) B
-- GROUP BY DATA, UF
ORDER BY DATA, UF */




-- QTDE DE ERBS AFETADAS A CADA 15 MINUTOS POR UF
/* SELECT DATA_REFERENCIA, UF, SUM(QTDE_ERBS_AFETADAS) AS QTDE_ERBS_AFETADAS
FROM REDE_EXTERNA..TBL_HIST_TAS_REDE_PROPRIA
WHERE UF <> '-'
GROUP BY DATA_REFERENCIA, UF
ORDER BY UF, DATA_REFERENCIA

-- QTDE ERBS AFETADAS POR UF POR DIA
SELECT  DATEPART(YEAR,CONVERT(DATETIME, DATA_REFERENCIA, 103)) AS ANO,
        DATEPART(MONTH,CONVERT(DATETIME, DATA_REFERENCIA, 103)) AS MES,
        DATEPART(DAY,CONVERT(DATETIME, DATA_REFERENCIA, 103)) AS DIA,
        UF,
        SUM(QTDE_ERBS_AFETADAS) AS QTDE_ERBS_AFETADAS
FROM REDE_EXTERNA..TBL_HIST_TAS_REDE_PROPRIA
WHERE UF <> '-'
GROUP BY DATA_REFERENCIA, UF
ORDER BY UF, ANO, MES, DIA

--MÉDIA DA QTDE DE ERBS AFETADAS POR DIA POR UF
SELECT  DATEPART(YEAR,CONVERT(DATETIME, DATA_REFERENCIA, 103)) AS ANO,
        DATEPART(MONTH,CONVERT(DATETIME, DATA_REFERENCIA, 103)) AS MES,
        DATEPART(DAY,CONVERT(DATETIME, DATA_REFERENCIA, 103)) AS DIA,
        UF,
        AVG(QTDE_ERBS_AFETADAS) AS QTDE_ERBS_AFETADAS
FROM REDE_EXTERNA..TBL_HIST_TAS_REDE_PROPRIA
WHERE UF <> '-'
GROUP BY DATA_REFERENCIA, UF
ORDER BY UF, ANO, MES, DIA */


/* -- ==================================================================================================================================================================================
-- QTDE DE TAS POR HORA
-- ==================================================================================================================================================================================
SELECT
B.*,
CEILING(PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY QTDE_TAS) OVER (PARTITION BY UF, MUNICIPIO)) AS Q3
FROM (
    SELECT
        DATA,
        UF,
        MUNICIPIO,
        CASE WHEN UF + '_' + MUNICIPIO IN ('AC_RIO BRANCO','AL_MACEIÓ','AP_MACAPÁ','AM_MANAUS','BA_SALVADOR','CE_FORTALEZA','DF_BRASÍLIA','ES_VITÓRIA','GO_GOIÂNIA','MA_SÃO LUÍS','MT_CUIABÁ','MS_CAMPO GRANDE',
                                        'MG_BELO HORIZONTE','PA_BELÉM','PB_JOÃO PESSOA',    'PR_CURITIBA','PE_RECIFE','PI_TERESINA','RJ_RIO DE JANEIRO','RN_NATAL','RS_PORTO ALEGRE','RO_PORTO VELHO','RR_BOA VISTA',
                                        'SC_FLORIANÓPOLIS','SP_SÃO PAULO','SE_ARACAJU','TO_PALMAS') THEN 'SIM' ELSE 'NÃO'
        END CAPITAL,
        COUNT(DISTINCT TA_REDE_EXTERNA) AS QTDE_TAS
    FROM (
        SELECT  
                CONVERT(DATETIME, DATA_REFERENCIA, 103) AS DATA,
                UF,
                MUNICIPIO,    
                TA_REDE_EXTERNA
        FROM REDE_EXTERNA..TBL_HIST_TAS_REDE_PROPRIA
        WHERE UF <> '-'
        -- ORDER BY DATA_REFERENCIA
    ) A
    -- WHERE MUNICIPIO = 'BELO HORIZONTE' --MUNICIPIO IN ('BELO HORIZONTE', 'VITORIA')
    GROUP BY DATA, UF, MUNICIPIO
    -- ORDER BY UF, MUNICIPIO, DATA
)B */


-- ==================================================================================================================================================================================
-- QTDE DE TAS POR HORA - REDE EXTERNA
-- ==================================================================================================================================================================================
WITH BASE AS (
  SELECT
    UF,
    MUNICIPIO,
    CASE WHEN UF + '_' + MUNICIPIO IN ('AC_RIO BRANCO','AL_MACEIÓ','AP_MACAPÁ','AM_MANAUS','BA_SALVADOR','CE_FORTALEZA','DF_BRASÍLIA','ES_VITÓRIA','GO_GOIÂNIA','MA_SÃO LUÍS','MT_CUIABÁ','MS_CAMPO GRANDE',
                                    'MG_BELO HORIZONTE','PA_BELÉM','PB_JOÃO PESSOA',    'PR_CURITIBA','PE_RECIFE','PI_TERESINA','RJ_RIO DE JANEIRO','RN_NATAL','RS_PORTO ALEGRE','RO_PORTO VELHO','RR_BOA VISTA',
                                    'SC_FLORIANÓPOLIS','SP_SÃO PAULO','SE_ARACAJU','TO_PALMAS') THEN 'SIM' ELSE 'NÃO'
    END CAPITAL,
    DATA_REFERENCIA,
    DATEPART(YEAR,CONVERT(DATETIME, DATA_REFERENCIA, 103)) AS ANO,
    DATEPART(MONTH,CONVERT(DATETIME, DATA_REFERENCIA, 103)) AS MES,
    DATEPART(DAY,CONVERT(DATETIME, DATA_REFERENCIA, 103)) AS DIA,
    DATEPART(HOUR,CONVERT(DATETIME, DATA_REFERENCIA, 103)) AS HORA,
    TA_REDE_EXTERNA
  FROM REDE_EXTERNA..TBL_HIST_TAS_REDE_PROPRIA
  WHERE UF <> '-' AND CONVERT(DATETIME,DATA_REFERENCIA,103) >= '2024-05-01 00:00:00.000' AND CONVERT(DATETIME,DATA_REFERENCIA,103) <= '2024-06-30 23:59:00.000'
)


SELECT
  DATA_REF,
  UF,
  MUNICIPIO,
  CAPITAL,
  CEILING(AVG(QTDE_EVENTOS) OVER (PARTITION BY UF, MUNICIPIO)) AS MEDIA,
  CEILING(PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY QTDE_EVENTOS) OVER (PARTITION BY UF, MUNICIPIO)) AS Q1,
  CEILING(PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY QTDE_EVENTOS) OVER (PARTITION BY UF, MUNICIPIO)) AS MEDIANA,
  CEILING(PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY QTDE_EVENTOS) OVER (PARTITION BY UF, MUNICIPIO)) AS Q3,
  QTDE_EVENTOS
  -- SUM(QTDE_EVENTOS) OVER (PARTITION BY UF, MUNICIPIO) AS SOMA
FROM (
  SELECT
      DATA_OK AS DATA_REF,
      UF,
      MUNICIPIO,
      CAPITAL,
      COUNT(DISTINCT TA_REDE_EXTERNA) AS QTDE_EVENTOS
  FROM (
    SELECT
      FORMAT(CONVERT(DATETIME,DATA_REFERENCIA,103), 'dd/MM/yyyy HH:00') AS DATA_OK,
      UF,
      MUNICIPIO,
      CAPITAL,
      TA_REDE_EXTERNA
    FROM BASE
  ) A
GROUP BY DATA_OK, UF, MUNICIPIO, CAPITAL
-- ORDER BY DATA_OK
) B
-- WHERE CAPITAL = 'SIM'
ORDER BY UF,MUNICIPIO, DATA_REF

-- ==================================================================================================================================================================================
-- QTDE DE TAS POR HORA - PLANTA INTERNA
-- ==================================================================================================================================================================================
WITH BASE AS (
  SELECT
    UF,
    MUNICIPIO,
    CASE WHEN UF + '_' + MUNICIPIO IN ('AC_RIO BRANCO','AL_MACEIÓ','AP_MACAPÁ','AM_MANAUS','BA_SALVADOR','CE_FORTALEZA','DF_BRASÍLIA','ES_VITÓRIA','GO_GOIÂNIA','MA_SÃO LUÍS','MT_CUIABÁ','MS_CAMPO GRANDE',
                                    'MG_BELO HORIZONTE','PA_BELÉM','PB_JOÃO PESSOA',    'PR_CURITIBA','PE_RECIFE','PI_TERESINA','RJ_RIO DE JANEIRO','RN_NATAL','RS_PORTO ALEGRE','RO_PORTO VELHO','RR_BOA VISTA',
                                    'SC_FLORIANÓPOLIS','SP_SÃO PAULO','SE_ARACAJU','TO_PALMAS') THEN 'SIM' ELSE 'NÃO'
    END CAPITAL,
    DATA_REFERENCIA,
    DATEPART(YEAR,CONVERT(DATETIME, DATA_REFERENCIA, 103)) AS ANO,
    DATEPART(MONTH,CONVERT(DATETIME, DATA_REFERENCIA, 103)) AS MES,
    DATEPART(DAY,CONVERT(DATETIME, DATA_REFERENCIA, 103)) AS DIA,
    DATEPART(HOUR,CONVERT(DATETIME, DATA_REFERENCIA, 103)) AS HORA,
    TA_CAMPO
  FROM REDE_EXTERNA..TBL_PORTAL_CAMPO_HIST
  WHERE UF <> '-' AND CONVERT(DATETIME,DATA_REFERENCIA,103) >= '2024-05-01 00:00:00.000' AND CONVERT(DATETIME,DATA_REFERENCIA,103) <= '2024-06-30 23:59:00.000'
)


SELECT
  DATA_REF,
  UF,
  MUNICIPIO,
  CAPITAL,
  CEILING(AVG(QTDE_EVENTOS) OVER (PARTITION BY UF, MUNICIPIO)) AS MEDIA,
  CEILING(PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY QTDE_EVENTOS) OVER (PARTITION BY UF, MUNICIPIO)) AS Q1,
  CEILING(PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY QTDE_EVENTOS) OVER (PARTITION BY UF, MUNICIPIO)) AS MEDIANA,
  CEILING(PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY QTDE_EVENTOS) OVER (PARTITION BY UF, MUNICIPIO)) AS Q3,
  QTDE_EVENTOS
  -- SUM(QTDE_EVENTOS) OVER (PARTITION BY UF, MUNICIPIO) AS SOMA
FROM (
  SELECT
      DATA_OK AS DATA_REF,
      UF,
      MUNICIPIO,
      CAPITAL,
      COUNT(DISTINCT TA_CAMPO) AS QTDE_EVENTOS
  FROM (
    SELECT
      FORMAT(CONVERT(DATETIME,DATA_REFERENCIA,103), 'dd/MM/yyyy HH:00') AS DATA_OK,
      UF,
      MUNICIPIO,
      CAPITAL,
      TA_CAMPO
    FROM BASE
  ) A
GROUP BY DATA_OK, UF, MUNICIPIO, CAPITAL
-- ORDER BY DATA_OK
) B
-- WHERE CAPITAL = 'SIM'
ORDER BY UF,MUNICIPIO, DATA_REF

-- ==================================================================================================================================================================================
-- QTDE DE TAS POR HORA - NOC_CORAN
-- ==================================================================================================================================================================================
WITH BASE AS (
  SELECT
    UF,
    MUNICIPIO,
    CASE WHEN UF + '_' + MUNICIPIO IN ('AC_RIO BRANCO','AL_MACEIÓ','AP_MACAPÁ','AM_MANAUS','BA_SALVADOR','CE_FORTALEZA','DF_BRASÍLIA','ES_VITÓRIA','GO_GOIÂNIA','MA_SÃO LUÍS','MT_CUIABÁ','MS_CAMPO GRANDE',
                                    'MG_BELO HORIZONTE','PA_BELÉM','PB_JOÃO PESSOA',    'PR_CURITIBA','PE_RECIFE','PI_TERESINA','RJ_RIO DE JANEIRO','RN_NATAL','RS_PORTO ALEGRE','RO_PORTO VELHO','RR_BOA VISTA',
                                    'SC_FLORIANÓPOLIS','SP_SÃO PAULO','SE_ARACAJU','TO_PALMAS') THEN 'SIM' ELSE 'NÃO'
    END CAPITAL,
    DATA_REFERENCIA,
    DATEPART(YEAR,CONVERT(DATETIME, DATA_REFERENCIA, 103)) AS ANO,
    DATEPART(MONTH,CONVERT(DATETIME, DATA_REFERENCIA, 103)) AS MES,
    DATEPART(DAY,CONVERT(DATETIME, DATA_REFERENCIA, 103)) AS DIA,
    DATEPART(HOUR,CONVERT(DATETIME, DATA_REFERENCIA, 103)) AS HORA,
    TA_CORAN
  FROM REDE_EXTERNA..TBL_PORTAL_NOC_CORAN_HIST
  WHERE UF <> '-' AND CONVERT(DATETIME,DATA_REFERENCIA,103) >= '2024-05-01 00:00:00.000' AND CONVERT(DATETIME,DATA_REFERENCIA,103) <= '2024-06-30 23:59:00.000'
)


SELECT
  DATA_REF,
  UF,
  MUNICIPIO,
  CAPITAL,
  CEILING(AVG(QTDE_EVENTOS) OVER (PARTITION BY UF, MUNICIPIO)) AS MEDIA,
  CEILING(PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY QTDE_EVENTOS) OVER (PARTITION BY UF, MUNICIPIO)) AS Q1,
  CEILING(PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY QTDE_EVENTOS) OVER (PARTITION BY UF, MUNICIPIO)) AS MEDIANA,
  CEILING(PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY QTDE_EVENTOS) OVER (PARTITION BY UF, MUNICIPIO)) AS Q3,
  QTDE_EVENTOS
  -- SUM(QTDE_EVENTOS) OVER (PARTITION BY UF, MUNICIPIO) AS SOMA
FROM (
  SELECT
      DATA_OK AS DATA_REF,
      UF,
      MUNICIPIO,
      CAPITAL,
      COUNT(DISTINCT TA_CORAN) AS QTDE_EVENTOS
  FROM (
    SELECT
      FORMAT(CONVERT(DATETIME,DATA_REFERENCIA,103), 'dd/MM/yyyy HH:00') AS DATA_OK,
      UF,
      MUNICIPIO,
      CAPITAL,
      TA_CORAN
    FROM BASE
  ) A
GROUP BY DATA_OK, UF, MUNICIPIO, CAPITAL
-- ORDER BY DATA_OK
) B
-- WHERE CAPITAL = 'SIM'
ORDER BY UF,MUNICIPIO, DATA_REF


















-- =====================================================================================

/* SELECT FORMAT(CONVERT(DATETIME,DATA_REFERENCIA,103), 'dd/MM/yyyy HH:00'), TA_REDE_EXTERNA FROM REDE_EXTERNA..TBL_HIST_TAS_REDE_PROPRIA WHERE FORMAT(CONVERT(DATETIME,DATA_REFERENCIA,103), 'dd/MM/yyyy HH:00') = '24/06/2024 21:00'



SELECT * FROM (
  SELECT
      MUNICIPIO,
      DATEPART(YEAR,CONVERT(DATETIME, DATA_REFERENCIA, 103)) AS ANO,
      DATEPART(MONTH,CONVERT(DATETIME, DATA_REFERENCIA, 103)) AS MES,
      DATEPART(DAY,CONVERT(DATETIME, DATA_REFERENCIA, 103)) AS DIA,
      DATEPART(HOUR,CONVERT(DATETIME, DATA_REFERENCIA, 103)) AS HORA,
      TA_REDE_EXTERNA
  FROM REDE_EXTERNA..TBL_HIST_TAS_REDE_PROPRIA
) A
WHERE ANO = 2024 AND MES = 4 AND DIA = 1 AND HORA = 11 AND MUNICIPIO = 'BELO HORIZONTE' */

-- ***************************************************************************************************************************************************************************************

-- ====================================================
-- QTDE DE TAs POR HORA POR UF - REDE EXTERNA
-- ====================================================
WITH BASE AS (
  SELECT
    UF,
    MUNICIPIO,
    CASE WHEN UF + '_' + MUNICIPIO IN ('AC_RIO BRANCO','AL_MACEIÓ','AP_MACAPÁ','AM_MANAUS','BA_SALVADOR','CE_FORTALEZA','DF_BRASÍLIA','ES_VITÓRIA','GO_GOIÂNIA','MA_SÃO LUÍS','MT_CUIABÁ','MS_CAMPO GRANDE',
                                    'MG_BELO HORIZONTE','PA_BELÉM','PB_JOÃO PESSOA',    'PR_CURITIBA','PE_RECIFE','PI_TERESINA','RJ_RIO DE JANEIRO','RN_NATAL','RS_PORTO ALEGRE','RO_PORTO VELHO','RR_BOA VISTA',
                                    'SC_FLORIANÓPOLIS','SP_SÃO PAULO','SE_ARACAJU','TO_PALMAS') THEN 'SIM' ELSE 'NÃO'
    END CAPITAL,
    DATA_REFERENCIA,
    DATEPART(YEAR,CONVERT(DATETIME, DATA_REFERENCIA, 103)) AS ANO,
    DATEPART(MONTH,CONVERT(DATETIME, DATA_REFERENCIA, 103)) AS MES,
    DATEPART(DAY,CONVERT(DATETIME, DATA_REFERENCIA, 103)) AS DIA,
    DATEPART(HOUR,CONVERT(DATETIME, DATA_REFERENCIA, 103)) AS HORA,
    TA_REDE_EXTERNA
  FROM REDE_EXTERNA..TBL_HIST_TAS_REDE_PROPRIA
  WHERE UF <> '-' AND CONVERT(DATETIME,DATA_REFERENCIA,103) >= '2024-05-01 00:00:00.000' AND CONVERT(DATETIME,DATA_REFERENCIA,103) <= '2024-06-30 23:59:00.000' 
)


SELECT
  DATA_REF,
  UF,
  CEILING(AVG(QTDE_EVENTOS) OVER (PARTITION BY UF)) AS MEDIA,
  CEILING(PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY QTDE_EVENTOS) OVER (PARTITION BY UF,HORA)) AS Q1,
  CEILING(PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY QTDE_EVENTOS) OVER (PARTITION BY UF,HORA)) AS MEDIANA,
  CEILING(PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY QTDE_EVENTOS) OVER (PARTITION BY UF,HORA)) AS Q3,
  QTDE_EVENTOS
  -- SUM(QTDE_EVENTOS) OVER (PARTITION BY UF, MUNICIPIO) AS SOMA
FROM (
  SELECT
      DATA_OK AS DATA_REF,
      UF,
      HORA,
      COUNT(DISTINCT TA_REDE_EXTERNA) AS QTDE_EVENTOS
  FROM (
    SELECT
      FORMAT(CONVERT(DATETIME,DATA_REFERENCIA,103), 'dd/MM/yyyy HH:00') AS DATA_OK,
      UF,
      HORA,
      CAPITAL,
      TA_REDE_EXTERNA
    FROM BASE
  ) A
GROUP BY DATA_OK, HORA, UF
-- ORDER BY DATA_OK
) B
-- WHERE UF = 'MG'
ORDER BY UF, DATA_REF

-- ====================================================
-- QTDE DE TAs POR HORA POR UF - PLANTA INTERNA
-- ====================================================
WITH BASE AS (
  SELECT
    UF,
    MUNICIPIO,
    CASE WHEN UF + '_' + MUNICIPIO IN ('AC_RIO BRANCO','AL_MACEIÓ','AP_MACAPÁ','AM_MANAUS','BA_SALVADOR','CE_FORTALEZA','DF_BRASÍLIA','ES_VITÓRIA','GO_GOIÂNIA','MA_SÃO LUÍS','MT_CUIABÁ','MS_CAMPO GRANDE',
                                    'MG_BELO HORIZONTE','PA_BELÉM','PB_JOÃO PESSOA',    'PR_CURITIBA','PE_RECIFE','PI_TERESINA','RJ_RIO DE JANEIRO','RN_NATAL','RS_PORTO ALEGRE','RO_PORTO VELHO','RR_BOA VISTA',
                                    'SC_FLORIANÓPOLIS','SP_SÃO PAULO','SE_ARACAJU','TO_PALMAS') THEN 'SIM' ELSE 'NÃO'
    END CAPITAL,
    DATA_REFERENCIA,
    DATEPART(YEAR,CONVERT(DATETIME, DATA_REFERENCIA, 103)) AS ANO,
    DATEPART(MONTH,CONVERT(DATETIME, DATA_REFERENCIA, 103)) AS MES,
    DATEPART(DAY,CONVERT(DATETIME, DATA_REFERENCIA, 103)) AS DIA,
    DATEPART(HOUR,CONVERT(DATETIME, DATA_REFERENCIA, 103)) AS HORA,
    TA_CAMPO
  FROM REDE_EXTERNA..TBL_PORTAL_CAMPO_HIST
  WHERE UF <> '-' AND CONVERT(DATETIME,DATA_REFERENCIA,103) >= '2024-05-01 00:00:00.000' AND CONVERT(DATETIME,DATA_REFERENCIA,103) <= '2024-06-30 23:59:00.000' 
)


SELECT
  DATA_REF,
  UF,
  CEILING(AVG(QTDE_EVENTOS) OVER (PARTITION BY UF)) AS MEDIA,
  CEILING(PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY QTDE_EVENTOS) OVER (PARTITION BY UF,HORA)) AS Q1,
  CEILING(PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY QTDE_EVENTOS) OVER (PARTITION BY UF,HORA)) AS MEDIANA,
  CEILING(PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY QTDE_EVENTOS) OVER (PARTITION BY UF,HORA)) AS Q3,
  QTDE_EVENTOS
  -- SUM(QTDE_EVENTOS) OVER (PARTITION BY UF, MUNICIPIO) AS SOMA
FROM (
  SELECT
      DATA_OK AS DATA_REF,
      UF,
      HORA,
      COUNT(DISTINCT TA_CAMPO) AS QTDE_EVENTOS
  FROM (
    SELECT
      FORMAT(CONVERT(DATETIME,DATA_REFERENCIA,103), 'dd/MM/yyyy HH:00') AS DATA_OK,
      UF,
      HORA,
      CAPITAL,
      TA_CAMPO
    FROM BASE
  ) A
GROUP BY DATA_OK, HORA, UF
-- ORDER BY DATA_OK
) B
-- WHERE UF = 'MG'
ORDER BY UF, DATA_REF


-- ====================================================
-- QTDE DE TAs POR HORA POR UF - NOC_CORAN
-- ====================================================
WITH BASE AS (
  SELECT
    UF,
    MUNICIPIO,
    CASE WHEN UF + '_' + MUNICIPIO IN ('AC_RIO BRANCO','AL_MACEIÓ','AP_MACAPÁ','AM_MANAUS','BA_SALVADOR','CE_FORTALEZA','DF_BRASÍLIA','ES_VITÓRIA','GO_GOIÂNIA','MA_SÃO LUÍS','MT_CUIABÁ','MS_CAMPO GRANDE',
                                    'MG_BELO HORIZONTE','PA_BELÉM','PB_JOÃO PESSOA',    'PR_CURITIBA','PE_RECIFE','PI_TERESINA','RJ_RIO DE JANEIRO','RN_NATAL','RS_PORTO ALEGRE','RO_PORTO VELHO','RR_BOA VISTA',
                                    'SC_FLORIANÓPOLIS','SP_SÃO PAULO','SE_ARACAJU','TO_PALMAS') THEN 'SIM' ELSE 'NÃO'
    END CAPITAL,
    DATA_REFERENCIA,
    DATEPART(YEAR,CONVERT(DATETIME, DATA_REFERENCIA, 103)) AS ANO,
    DATEPART(MONTH,CONVERT(DATETIME, DATA_REFERENCIA, 103)) AS MES,
    DATEPART(DAY,CONVERT(DATETIME, DATA_REFERENCIA, 103)) AS DIA,
    DATEPART(HOUR,CONVERT(DATETIME, DATA_REFERENCIA, 103)) AS HORA,
    TA_CORAN
  FROM REDE_EXTERNA..TBL_PORTAL_NOC_CORAN_HIST
  WHERE UF <> '-' AND CONVERT(DATETIME,DATA_REFERENCIA,103) >= '2024-05-01 00:00:00.000' AND CONVERT(DATETIME,DATA_REFERENCIA,103) <= '2024-06-30 23:59:00.000' 
)


SELECT
  DATA_REF,
  UF,
  CEILING(AVG(QTDE_EVENTOS) OVER (PARTITION BY UF)) AS MEDIA,
  CEILING(PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY QTDE_EVENTOS) OVER (PARTITION BY UF,HORA)) AS Q1,
  CEILING(PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY QTDE_EVENTOS) OVER (PARTITION BY UF,HORA)) AS MEDIANA,
  CEILING(PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY QTDE_EVENTOS) OVER (PARTITION BY UF,HORA)) AS Q3,
  QTDE_EVENTOS
  -- SUM(QTDE_EVENTOS) OVER (PARTITION BY UF, MUNICIPIO) AS SOMA
FROM (
  SELECT
      DATA_OK AS DATA_REF,
      UF,
      HORA,
      COUNT(DISTINCT TA_CORAN) AS QTDE_EVENTOS
  FROM (
    SELECT
      FORMAT(CONVERT(DATETIME,DATA_REFERENCIA,103), 'dd/MM/yyyy HH:00') AS DATA_OK,
      UF,
      HORA,
      CAPITAL,
      TA_CORAN
    FROM BASE
  ) A
GROUP BY DATA_OK, HORA, UF
-- ORDER BY DATA_OK
) B
-- WHERE UF = 'MG'
ORDER BY UF, DATA_REF




