

--MUNICÍPIOS RANSHARING

SELECT
UF,
MUNICIPIO,
CASE WHEN SUM(FLAG_EXCL_RAN) = 0 THEN 'SIM' ELSE 'NAO' END EXCLUSIVO_RAN_SHARING,
CASE WHEN SUM(FLAG_EXCL_VIVO) = 0 THEN 'SIM' ELSE 'NAO' END EXCLUSIVO_VIVO,
CASE WHEN SUM(FLAG_EXCL_RAN) <> 0 AND SUM(FLAG_EXCL_VIVO) <> 0 THEN 'SIM' ELSE 'NAO' END MISTO
FROM
(
    SELECT
    UF, 
    MUNICIPIO,
    CASE WHEN OPERADORA_RANSHARING = 'VIVO' THEN 1 ELSE 0 END FLAG_EXCL_RAN,
    CASE WHEN OPERADORA_RANSHARING <> 'VIVO' THEN 1 ELSE 0 END FLAG_EXCL_VIVO
    --CASE WHEN SUM(CASE WHEN OPERADORA_RANSHARING = 'VIVO' THEN 1 ELSE 0 END) = SUM(CASE WHEN OPERADORA_RANSHARING = 'VIVO' THEN 1 ELSE 0 END) THEN 'SIM'
    FROM SISTEMA_MAESTRO..TBA_PLANTA_MOVEL
    --WHERE MUNICIPIO = 'IPUÃ'
    GROUP BY UF, MUNICIPIO, OPERADORA_RANSHARING
    --ORDER BY UF, MUNICIPIO
) A
GROUP BY UF, MUNICIPIO
ORDER BY UF, MUNICIPIO



SELECT
UF,
MUNICIPIO,
IBGE,
CASE WHEN CLARO = 1 AND TIM = 0 AND VIVO = 0 THEN 'EXCLUSIVO CLARO'
     WHEN CLARO = 0 AND TIM = 1 AND VIVO = 0 THEN 'EXCLUSIVO TIM'
     WHEN CLARO = 0 AND TIM = 0 AND VIVO = 1 THEN 'EXCLUSIVO VIVO'
     WHEN CLARO = 1 AND TIM = 1 AND VIVO = 0 THEN 'CLARO/TIM'
     WHEN CLARO = 1 AND TIM = 0 AND VIVO = 1 THEN 'CLARO/VIVO'
     WHEN CLARO = 0 AND TIM = 1 AND VIVO = 1 THEN 'TIM/VIVO'
     WHEN CLARO = 1 AND TIM = 1 AND VIVO = 1 THEN 'CLARO/TIM/VIVO'
ELSE 'ERRO!'
END OPERADORA
FROM
(
    SELECT
    UF,
    MUNICIPIO,
    IBGE,
    CASE WHEN SUM(CLARO) > 0 THEN 1 ELSE 0 END CLARO,
    CASE WHEN SUM(TIM) > 0 THEN 1 ELSE 0 END TIM,
    CASE WHEN SUM(VIVO) > 0 THEN 1 ELSE 0 END VIVO
    FROM
    (
        SELECT
            UF, 
            MUNICIPIO,
            COD_IBGE_MUNICIPIO AS IBGE,
            CASE WHEN OPERADORA_RANSHARING = 'CLARO' THEN 1 ELSE 0 END CLARO,
            CASE WHEN OPERADORA_RANSHARING = 'TIM' THEN 1 ELSE 0 END TIM,
            CASE WHEN OPERADORA_RANSHARING = 'VIVO' THEN 1 ELSE 0 END VIVO
            
            --CASE WHEN OPERADORA_RANSHARING = 'VIVO' THEN 1 ELSE 0 END FLAG_EXCL_RAN,
            --CASE WHEN OPERADORA_RANSHARING <> 'VIVO' THEN 1 ELSE 0 END FLAG_EXCL_VIVO
            --CASE WHEN SUM(CASE WHEN OPERADORA_RANSHARING = 'VIVO' THEN 1 ELSE 0 END) = SUM(CASE WHEN OPERADORA_RANSHARING = 'VIVO' THEN 1 ELSE 0 END) THEN 'SIM'
        FROM SISTEMA_MAESTRO..TBA_PLANTA_MOVEL
        --WHERE MUNICIPIO = 'IPUÃ'
        GROUP BY UF, MUNICIPIO, COD_IBGE_MUNICIPIO, OPERADORA_RANSHARING
        --ORDER BY UF, MUNICIPIO
    ) A
    GROUP BY UF, MUNICIPIO, IBGE
    --ORDER BY UF, MUNICIPIO
) B
ORDER BY UF, MUNICIPIO