WITH PLANTA AS
(
	SELECT DISTINCT
			PLANTA.UF,
			PLANTA.MUNICIPIO,
			CLASS.CLASSIFICACAO,
			COUNT(DISTINCT SIGLA_SITE) AS QTDE_SITES
			--COUNT(DISTINCT CASE WHEN TECNOLOGIA = 'GSM' THEN CONCAT(PLANTA.UF, PLANTA.MUNICIPIO, SIGLA_SITE) END) AS PLANTA_WCDMA 
			--COUNT(TECNOLOGIA) OVER (PARTITION BY PLANTA.UF, PLANTA.MUNICIPIO ORDER BY PLANTA.UF, PLANTA.MUNICIPIO) AS QTDE_SITES_GSM
	FROM 
			SISTEMA_MAESTRO..TBA_PLANTA_MOVEL PLANTA
			LEFT JOIN SISTEMA_MAESTRO..AUX_CLASSIFICACAO_MUNICIPIOS CLASS ON PLANTA.UF = CLASS.UF AND PLANTA.MUNICIPIO = CLASS.MUNICIPIO
	--WHERE TECNOLOGIA = 'GSM' --AND PLANTA.UF = 'AM' AND PLANTA.MUNICIPIO = 'ITAPIRANGA'
	GROUP BY 
			PLANTA.UF, PLANTA.MUNICIPIO, CLASS.CLASSIFICACAO
),
PLANTA_GSM AS
(
SELECT
UF,
MUNICIPIO,
COUNT(DISTINCT CASE WHEN TECNOLOGIA = 'GSM' THEN CONCAT(PLANTA.UF, PLANTA.MUNICIPIO, SIGLA_SITE) END) AS QTDE_SITES_GSM,
COUNT(DISTINCT CASE WHEN TECNOLOGIA = 'WCDMA' THEN CONCAT(PLANTA.UF, PLANTA.MUNICIPIO, SIGLA_SITE) END) AS QTDE_SITES_WCDMA,
COUNT(DISTINCT CASE WHEN TECNOLOGIA = 'LTE' THEN CONCAT(PLANTA.UF, PLANTA.MUNICIPIO, SIGLA_SITE) END) AS QTDE_SITES_LTE,
COUNT(DISTINCT CASE WHEN TECNOLOGIA = '5G' THEN CONCAT(PLANTA.UF, PLANTA.MUNICIPIO, SIGLA_SITE) END) AS QTDE_SITES_5G
FROM SISTEMA_MAESTRO..TBA_PLANTA_MOVEL PLANTA
--WHERE UF = 'SE' 
GROUP BY UF, MUNICIPIO
)

SELECT
PLANTA.UF,
PLANTA.MUNICIPIO,
CLASSIFICACAO,
QTDE_SITES,
QTDE_SITES_GSM,
QTDE_SITES_WCDMA,
QTDE_SITES_LTE,
QTDE_SITES_5G
FROM PLANTA
LEFT JOIN PLANTA_GSM ON PLANTA.UF = PLANTA_GSM.UF AND PLANTA.MUNICIPIO = PLANTA_GSM.MUNICIPIO
ORDER BY PLANTA.UF, PLANTA.MUNICIPIO


--SELECT * FROM SISTEMA_MAESTRO..TBA_PLANTA_MOVEL
--WHERE MUNICIPIO = 'CRUZEIRO DO SUL' AND UF = 'AC' AND TECNOLOGIA = 'GSM'


