

DECLARE @DATA AS DATETIME, @DATA_FIM AS DATETIME, @HMM AS VARCHAR(5) = 'HMM', @AGRUPAMENTO AS VARCHAR(50) = 'REGIONAL', @TP_PERIODO VARCHAR(3) = 'M'

SET @DATA = GETDATE()-1

DECLARE @PERIODO AS VARCHAR(30)

SET @PERIODO = CASE WHEN @TP_PERIODO = 'W' THEN DATENAME(WW,@DATA) 
                    WHEN @TP_PERIODO = 'M' THEN CAST(DATEADD(MM,DATEDIFF(MM,0,@DATA),0) AS VARCHAR(30))--PRIMEIRO DIA DO MES
                    ELSE CONVERT(VARCHAR,@DATA,112) -- AS VARCHAR(30))
                    END
PRINT @PERIODO

;WITH CALCULO AS (
SELECT
     CASE WHEN @TP_PERIODO = 'M' THEN DATEADD(MM,DATEDIFF(MM,0,DATA_REFERENCIA),0) --PRIMEIRO DIA DO MES
          WHEN @TP_PERIODO = 'S' THEN DATEPART(W,DATA_REFERENCIA)
          ELSE DATA_REFERENCIA
     END AS PERIODO,
     REGIONAL = CASE WHEN @AGRUPAMENTO IS NOT NULL THEN
                         CASE WHEN A.UF = 'SP' THEN B.NOME_REGIONAL
                              WHEN A.UF IN ('BA', 'SE', 'AL', 'RN', 'PB', 'CE', 'PI', 'PE') THEN 'NE' 
                              WHEN A.UF = 'MG' THEN 'MG'
                              WHEN A.UF IN ('RJ', 'ES') THEN 'RJ/ES'
                              WHEN A.UF IN ('PR', 'SC', 'RS') THEN 'SUL'
                              WHEN A.UF IN ('AM', 'PA', 'MA', 'AP', 'RR') THEN 'NO'
                              WHEN A.UF IN ('AC', 'MS', 'MT', 'RO', 'DF', 'GO', 'TO') THEN 'CO'
                         END
               ELSE NULL 
               END,
     UF = CASE WHEN @AGRUPAMENTO IN ('UF', 'MUNICIPIO', 'SITE', 'ERB') THEN A.UF ELSE NULL END,
     MUNICIPIO = CASE WHEN @AGRUPAMENTO IN ('MUNICIPIO', 'SITE', 'ERB') THEN A.MUNICIPIO ELSE NULL END,
     SITE = CASE WHEN @AGRUPAMENTO IN ('SITE', 'ERB') THEN A.SITE ELSE NULL END,
     ERB = CASE WHEN @AGRUPAMENTO = 'ERB' THEN A.ERB ELSE NULL END,
     TECNOLOGIA = CASE WHEN TECNOLOGIA = 'GSM' THEN '2G' WHEN TECNOLOGIA = 'WCDMA' THEN '3G' WHEN TECNOLOGIA = 'LTE' THEN '4G' ELSE TECNOLOGIA END,
     TEMPO_CONTADOR = SUM(CASE WHEN @HMM = 'HMM' THEN TEMPO_CONTADOR_HMM ELSE TEMPO_CONTADOR END),
     COLETAS = SUM(CASE WHEN @HMM = 'HMM' THEN COLETAS_HMM ELSE COLETAS END)
FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES A WITH(NOLOCK)
LEFT JOIN INDICADORES_CORAN..TBA_DIVISAO_MUNICIPIOS_SP_FIXA B ON A.MUNICIPIO = B.MUNICIPIO AND A.UF = 'SP'
WHERE (TEMPO_CONTADOR_HMM >= 0 OR TEMPO_CONTADOR >=0 )
GROUP BY
CASE WHEN @TP_PERIODO = 'M' THEN DATEADD(MM,DATEDIFF(MM,0,DATA_REFERENCIA),0) WHEN @TP_PERIODO = 'S' THEN DATEPART(W,DATA_REFERENCIA)ELSE DATA_REFERENCIA END,
        CASE WHEN @AGRUPAMENTO IS NOT NULL THEN
                        CASE WHEN A.UF = 'SP' THEN B.NOME_REGIONAL
                             WHEN A.UF IN ('BA', 'SE', 'AL', 'RN', 'PB', 'CE', 'PI', 'PE') THEN 'NE' 
                             WHEN A.UF = 'MG' THEN 'MG'
                             WHEN A.UF IN ('RJ', 'ES') THEN 'RJ/ES'
                             WHEN A.UF IN ('PR', 'SC', 'RS') THEN 'SUL'
                             WHEN A.UF IN ('AM', 'PA', 'MA', 'AP', 'RR') THEN 'NO'
                             WHEN A.UF IN ('AC', 'MS', 'MT', 'RO', 'DF', 'GO', 'TO') THEN 'CO'
                        END
            ELSE NULL 
            END,
        CASE WHEN @AGRUPAMENTO IN ('UF', 'MUNICIPIO', 'SITE', 'ERB') THEN A.UF ELSE NULL END,
        CASE WHEN @AGRUPAMENTO IN ('MUNICIPIO', 'SITE', 'ERB') THEN A.MUNICIPIO ELSE NULL END,
        CASE WHEN @AGRUPAMENTO IN ('SITE', 'ERB') THEN A.SITE ELSE NULL END,
        CASE WHEN @AGRUPAMENTO = 'ERB' THEN A.ERB 
        ELSE NULL 
        END,
DATA_REFERENCIA,
CASE WHEN TECNOLOGIA = 'GSM' THEN '2G' WHEN TECNOLOGIA = 'WCDMA' THEN '3G' WHEN TECNOLOGIA = 'LTE' THEN '4G' ELSE TECNOLOGIA END

)

SELECT
*
FROM CALCULO
WHERE PERIODO >= @PERIODO AND PERIODO < CASE WHEN @TP_PERIODO = 'W' THEN DATENAME(WW,@DATA)
                                             WHEN @TP_PERIODO = 'M' THEN CAST(DATEADD(MM,DATEDIFF(MM,0,@DATA),0) AS VARCHAR(30)) --PRIMEIRO DIA DO MES
                                             ELSE @DATA + 1-- AS VARCHAR(30))
                                             END

-- SELECT * FROM REDE_EXTERNA..TBA_REGIONAL_UF_MUNICIPIOS


-- SELECT DATEADD(WW,DATEDIFF(WW,0,'2024-09-30'),0) 
-- SELECT EOMONTH(GETDATE())

-- SELECT DATEDIFF(YY,0,GETDATE())

-- 01/01/1900
-- SELECT TOP 10 * FROM SISTEMA_MAESTRO..TBF_DISPONIBILIDADE_SETORES