

SELECT
ANO,
SEMANA,
REGIONAL,
UF,
COUNT(DISTINCT TA) as QTDE_TAS
FROM
(
SELECT DATEPART(YEAR,DATA_REFERENCIA) AS ANO,
	   DATEPART(WK,DATA_REFERENCIA) AS SEMANA,
	   TA,
	   CASE WHEN REGIONAL = 'LESTE' THEN 'SUD' ELSE REGIONAL END AS REGIONAL,
	   UF
  FROM QUALIDADE..TBL_P4_ATIVOS
) A
WHERE ANO = 2023 AND SEMANA >=9 AND UF IN ('BA','SE','AL','CE','PB','PE','PI','RN','MG')
GROUP BY ANO, SEMANA, REGIONAL, UF
ORDER BY ANO, SEMANA, REGIONAL, UF

--SELECT MAX(DATA_REFERENCIA) FROM QUALIDADE..TBL_P4_ATIVOS
--GROUP BY DATA_REFERENCIA
--ORDER BY DATA_REFERENCIA
