
SELECT
	DATA_REFERENCIA,
    UF,
	COUNT(DISTINCT CASE WHEN NUMERO_DE_PRE_BAIXAS = 0 THEN TA END) AS PRE_BAIXA_0,
	COUNT(DISTINCT CASE WHEN NUMERO_DE_PRE_BAIXAS = 1 THEN TA END) AS PRE_BAIXA_1,
	COUNT(DISTINCT CASE WHEN NUMERO_DE_PRE_BAIXAS = 2 THEN TA END) AS PRE_BAIXA_2
  FROM [QUALIDADE].[dbo].[TBL_P4_ATIVOS]
  WHERE DATA_CRIACAO >= '2023-04-20 00:00:00.000' --AND UF = 'MG'
  GROUP BY UF, DATA_REFERENCIA
  ORDER BY  UF, DATA_REFERENCIA

  SELECT
    UF,
	COUNT(DISTINCT TA) AS QTDE_TAS
  FROM [QUALIDADE].[dbo].[TBL_P4_ATIVOS]
  WHERE DATA_CRIACAO >= '2023-04-20 00:00:00.000' and uf = 'MG'
  GROUP BY UF
  ORDER BY UF

  SELECT DISTINCT DATA_REFERENCIA, TA  FROM [QUALIDADE].[dbo].[TBL_P4_ATIVOS]
  WHERE DATA_CRIACAO >= '2023-04-20 00:00:00.000' AND UF = 'MG'
  ORDER BY DATA_REFERENCIA
  --GROUP BY DATA_REFERENCIA

