--============================================================================================================================
--REDE PRÓPRIA
--============================================================================================================================
SELECT
        A.TA_REDE_EXTERNA,
        CASE WHEN INFORMACOES.UF = 'SP' THEN DIVISAO.NOME_REGIONAL
        WHEN INFORMACOES.UF IN ('BA', 'SE', 'AL', 'RN', 'PB', 'CE', 'PI', 'PE') THEN 'NE' 
        WHEN INFORMACOES.UF IN ( 'MG', 'RJ', 'ES') THEN 'SUD'
        WHEN INFORMACOES.UF IN ('PR', 'SC', 'RS') THEN 'SUL'
        WHEN INFORMACOES.UF IN ('AM', 'PA', 'MA', 'AP', 'RR') THEN 'NO'
        WHEN INFORMACOES.UF IN ('AC', 'MS', 'MT', 'RO', 'DF', 'GO', 'TO') THEN 'CO'
        ELSE MUNICIPIOS.REGIONAL 
        END REGIONAL,
        INFORMACOES.UF AS UF,
        INFORMACOES.MUNICIPIO AS MUNICIPIO,
        MUNICIPIOS.CN AS CN,
        INFORMACOES.SITE AS SITE,
        A.ERBS_AFETADAS AS QTDE_ERBS_AFETADAS,
        FORMAT(INFORMACOES.DATA_CRIACAO,'dd/MM/yyyy HH:mm') AS DATA_CRIACAO,
        INFORMACOES.GESTOR_ATUAL,
        INFORMACOES.TIPO_BILHETE AS TIPO_BILHETE,
        SUM(ISNULL(DATEDIFF(MINUTE,INFORMACOES.VDA_DATA_INITIAL,INFORMACOES.VDA_DATA_FINAL),DATEDIFF(MINUTE,INFORMACOES.VDA_DATA_INITIAL, GETDATE()))) AS TEMPO_REDE_EXTERNA
FROM
    (SELECT TA_REDE_EXTERNA, SUM(ERBS_AFETADAS) AS ERBS_AFETADAS FROM REDE_EXTERNA..TBL_QTDE_ERBS_AFETADAS GROUP BY TA_REDE_EXTERNA) A
    INNER JOIN REDE_EXTERNA..INFORMACOES_TAS INFORMACOES ON INFORMACOES.TQA_CODIGO = A.TA_REDE_EXTERNA
    LEFT JOIN REDE_EXTERNA..TBA_UF_REGIONAL REGIONAL ON REGIONAL.UF = INFORMACOES.UF
    LEFT JOIN REDE_EXTERNA..TBA_MUNICIPIOS MUNICIPIOS ON MUNICIPIOS.UF = INFORMACOES.UF AND MUNICIPIOS.MUNICIPIO = INFORMACOES.MUNICIPIO
    LEFT JOIN INDICADORES_CORAN..TBA_DIVISAO_MUNICIPIOS_SP_FIXA DIVISAO ON INFORMACOES.MUNICIPIO = DIVISAO.MUNICIPIO AND INFORMACOES.UF = 'SP'
GROUP BY A.TA_REDE_EXTERNA,
         A.ERBS_AFETADAS,
         INFORMACOES.DATA_CRIACAO,
         INFORMACOES.GESTOR_ATUAL,
         INFORMACOES.UF,
         INFORMACOES.MUNICIPIO,
         MUNICIPIOS.CN,
         INFORMACOES.SITE,
         INFORMACOES.TIPO_BILHETE,
         MUNICIPIOS.REGIONAL,
         DIVISAO.NOME_REGIONAL
ORDER BY A.ERBS_AFETADAS DESC

--============================================================================================================================
--REDE SWAP
--============================================================================================================================
SELECT
    TA_INTERCONEXAO,
    EMPRESA,
    CASE WHEN OPERADORAS.UF = 'SP' THEN DIVISAO.NOME_REGIONAL
        WHEN OPERADORAS.UF IN ('BA', 'SE', 'AL', 'RN', 'PB', 'CE', 'PI', 'PE') THEN 'NE' 
        WHEN OPERADORAS.UF IN ( 'MG', 'RJ', 'ES') THEN 'SUD'
        WHEN OPERADORAS.UF IN ('PR', 'SC', 'RS') THEN 'SUL'
        WHEN OPERADORAS.UF IN ('AM', 'PA', 'MA', 'AP', 'RR') THEN 'NO'
        WHEN OPERADORAS.UF IN ('AC', 'MS', 'MT', 'RO', 'DF', 'GO', 'TO') THEN 'CO'
        ELSE MUNICIPIOS.REGIONAL
    END REGIONAL,
    OPERADORAS.UF AS UF,
    OPERADORAS.MUNICIPIO AS MUNICIPIO,
    MUNICIPIOS.CN AS CN,
    SITE,			
    SUM(ERBS_AFETADAS) AS ERBS_AFETADAS,
    FORMAT(DATA_CRIACAO,'dd/MM/yyyy HH:mm') AS DATA_CRIACAO,
    GESTOR_ATUAL,
    TIPO_REDE,
    --CAST( FLOOR((DATEDIFF(MINUTE,DATA_CRIACAO, GETDATE())) / 60) as varchar) + ':' + RIGHT('00' + CAST( FLOOR(((DATEDIFF(MINUTE,DATA_CRIACAO, GETDATE())) % 60)) as varchar), 2) as TEMPO_TA
    DATEDIFF(MINUTE, DATA_CRIACAO, GETDATE()) AS TEMPO_TA
    FROM TBL_OUTRAS_OPERADORAS OPERADORAS 
    LEFT JOIN TBA_UF_REGIONAL REGIONAL ON REGIONAL.UF = OPERADORAS.UF
    LEFT JOIN TBA_MUNICIPIOS MUNICIPIOS ON MUNICIPIOS.UF = OPERADORAS.UF AND MUNICIPIOS.MUNICIPIO = OPERADORAS.MUNICIPIO
    LEFT JOIN INDICADORES_CORAN..TBA_DIVISAO_MUNICIPIOS_SP_FIXA DIVISAO ON OPERADORAS.MUNICIPIO = DIVISAO.MUNICIPIO AND OPERADORAS.UF = 'SP'
    
WHERE TIPO_REDE <> 'ERB / Repetidor'
GROUP BY  TA_INTERCONEXAO,
          EMPRESA,                
          REGIONAL.SIGLA_REGIONAL,
          OPERADORAS.UF,
          OPERADORAS.MUNICIPIO,
          MUNICIPIOS.CN,
          SITE,			
          DATA_CRIACAO,
          GESTOR_ATUAL,
          TIPO_REDE,
          DIVISAO.NOME_REGIONAL

--============================================================================================================================
--TA ERB - Aberto com TA Raiz Fechado
--============================================================================================================================
SELECT TA
        ,CASE WHEN TA_ERB_ABERTO_TA_RE_FECHADO.UF = 'SP' THEN DIVISAO.NOME_REGIONAL
              WHEN TA_ERB_ABERTO_TA_RE_FECHADO.UF IN ('BA', 'SE', 'AL', 'RN', 'PB', 'CE', 'PI', 'PE') THEN 'NE' 
              WHEN TA_ERB_ABERTO_TA_RE_FECHADO.UF IN ( 'MG', 'RJ', 'ES') THEN 'SUD'
              WHEN TA_ERB_ABERTO_TA_RE_FECHADO.UF IN ('PR', 'SC', 'RS') THEN 'SUL'
              WHEN TA_ERB_ABERTO_TA_RE_FECHADO.UF IN ('AM', 'PA', 'MA', 'AP', 'RR') THEN 'NO'
              WHEN TA_ERB_ABERTO_TA_RE_FECHADO.UF IN ('AC', 'MS', 'MT', 'RO', 'DF', 'GO', 'TO') THEN 'CO'
              ELSE MUNICIPIOS.REGIONAL
        END REGIONAL             
        ,TA_ERB_ABERTO_TA_RE_FECHADO.UF
        ,TA_ERB_ABERTO_TA_RE_FECHADO.MUNICIPIO
        ,MUNICIPIOS.CN
        ,SITE
        ,FORMAT(DATA_CRIACAO,'dd/MM/yyyy HH:mm') AS DATA_CRIACAO
        ,GESTOR_ATUAL
        ,DATEDIFF(MINUTE, DATA_CRIACAO, GETDATE()) AS TEMPO
        --,CAST( FLOOR((DATEDIFF(MINUTE,DATA_CRIACAO, GETDATE())) / 60) as varchar) + ':' + RIGHT('00' + CAST( FLOOR(((DATEDIFF(MINUTE,DATA_CRIACAO, GETDATE())) % 60)) as varchar), 2) AS TEMPO           
FROM REDE_EXTERNA..TA_ERB_ABERTO_TA_RE_FECHADO
LEFT JOIN TBA_UF_REGIONAL REGIONAL ON REGIONAL.UF = TA_ERB_ABERTO_TA_RE_FECHADO.UF
LEFT JOIN TBA_MUNICIPIOS MUNICIPIOS ON MUNICIPIOS.UF = TA_ERB_ABERTO_TA_RE_FECHADO.UF AND MUNICIPIOS.MUNICIPIO = TA_ERB_ABERTO_TA_RE_FECHADO.MUNICIPIO
LEFT JOIN INDICADORES_CORAN..TBA_DIVISAO_MUNICIPIOS_SP_FIXA DIVISAO ON TA_ERB_ABERTO_TA_RE_FECHADO.MUNICIPIO = DIVISAO.MUNICIPIO AND TA_ERB_ABERTO_TA_RE_FECHADO.UF = 'SP'

--============================================================================================================================
--TA ERB - Sem TA Raiz Associado
--============================================================================================================================
SELECT TA
        ,CASE WHEN TA_ERB_RAIZ_NULO.UF = 'SP' THEN DIVISAO.NOME_REGIONAL
              WHEN TA_ERB_RAIZ_NULO.UF IN ('BA', 'SE', 'AL', 'RN', 'PB', 'CE', 'PI', 'PE') THEN 'NE' 
              WHEN TA_ERB_RAIZ_NULO.UF IN ( 'MG', 'RJ', 'ES') THEN 'SUD'
              WHEN TA_ERB_RAIZ_NULO.UF IN ('PR', 'SC', 'RS') THEN 'SUL'
              WHEN TA_ERB_RAIZ_NULO.UF IN ('AM', 'PA', 'MA', 'AP', 'RR') THEN 'NO'
              WHEN TA_ERB_RAIZ_NULO.UF IN ('AC', 'MS', 'MT', 'RO', 'DF', 'GO', 'TO') THEN 'CO'
              ELSE MUNICIPIOS.REGIONAL 
        END REGIONAL
        ,TA_ERB_RAIZ_NULO.UF
        ,TA_ERB_RAIZ_NULO.MUNICIPIO
        ,MUNICIPIOS.CN
        ,SITE
        ,FORMAT(DATA_CRIACAO,'dd/MM/yyyy HH:mm') AS DATA_CRIACAO
        ,GESTOR_ATUAL
        ,DATEDIFF(MINUTE, DATA_CRIACAO, GETDATE()) AS TEMPO
        --,CAST( FLOOR((DATEDIFF(MINUTE,DATA_CRIACAO, GETDATE())) / 60) as varchar) + ':' + RIGHT('00' + CAST( FLOOR(((DATEDIFF(MINUTE,DATA_CRIACAO, GETDATE())) % 60)) as varchar), 2) AS TEMPO
FROM REDE_EXTERNA..TA_ERB_RAIZ_NULO
LEFT JOIN TBA_UF_REGIONAL REGIONAL ON REGIONAL.UF = TA_ERB_RAIZ_NULO.UF
LEFT JOIN TBA_MUNICIPIOS MUNICIPIOS ON MUNICIPIOS.UF = TA_ERB_RAIZ_NULO.UF AND MUNICIPIOS.MUNICIPIO = TA_ERB_RAIZ_NULO.MUNICIPIO
LEFT JOIN INDICADORES_CORAN..TBA_DIVISAO_MUNICIPIOS_SP_FIXA DIVISAO ON TA_ERB_RAIZ_NULO.MUNICIPIO = DIVISAO.MUNICIPIO AND TA_ERB_RAIZ_NULO.UF = 'SP'


--========================================================================================================================
--QTDE DE TAs POR TEMPO
--========================================================================================================================

--REDE PRÓPRIA
SELECT
COUNT(CASE WHEN TEMPO_REDE_EXTERNA <= 240 THEN 1 ELSE 0 END) AS VERDE,
COUNT(CASE WHEN TEMPO_REDE_EXTERNA > 240 AND TEMPO_REDE_EXTERNA <= 720 THEN 1 ELSE 0 END) AS LARANJA,
COUNT(CASE WHEN TEMPO_REDE_EXTERNA > 720 THEN 1 ELSE 0 END) AS VERMELHO
FROM
(
SELECT
        A.TA_REDE_EXTERNA,
        CASE WHEN INFORMACOES.UF = 'SP' THEN DIVISAO.NOME_REGIONAL
        WHEN INFORMACOES.UF IN ('BA', 'SE', 'AL', 'RN', 'PB', 'CE', 'PI', 'PE') THEN 'NE' 
        WHEN INFORMACOES.UF IN ( 'MG', 'RJ', 'ES') THEN 'SUD'
        WHEN INFORMACOES.UF IN ('PR', 'SC', 'RS') THEN 'SUL'
        WHEN INFORMACOES.UF IN ('AM', 'PA', 'MA', 'AP', 'RR') THEN 'NO'
        WHEN INFORMACOES.UF IN ('AC', 'MS', 'MT', 'RO', 'DF', 'GO', 'TO') THEN 'CO'
        ELSE MUNICIPIOS.REGIONAL 
        END REGIONAL,
        INFORMACOES.UF AS UF,
        INFORMACOES.MUNICIPIO AS MUNICIPIO,
        MUNICIPIOS.CN AS CN,
        INFORMACOES.SITE AS SITE,
        A.ERBS_AFETADAS AS QTDE_ERBS_AFETADAS,
        FORMAT(INFORMACOES.DATA_CRIACAO,'dd/MM/yyyy HH:mm') AS DATA_CRIACAO,
        INFORMACOES.GESTOR_ATUAL,
        INFORMACOES.TIPO_BILHETE AS TIPO_BILHETE,
        SUM(ISNULL(DATEDIFF(MINUTE,INFORMACOES.VDA_DATA_INITIAL,INFORMACOES.VDA_DATA_FINAL),DATEDIFF(MINUTE,INFORMACOES.VDA_DATA_INITIAL, GETDATE()))) AS TEMPO_REDE_EXTERNA
FROM
    (SELECT TA_REDE_EXTERNA, SUM(ERBS_AFETADAS) AS ERBS_AFETADAS FROM REDE_EXTERNA..TBL_QTDE_ERBS_AFETADAS GROUP BY TA_REDE_EXTERNA) A
    INNER JOIN REDE_EXTERNA..INFORMACOES_TAS INFORMACOES ON INFORMACOES.TQA_CODIGO = A.TA_REDE_EXTERNA
    LEFT JOIN REDE_EXTERNA..TBA_UF_REGIONAL REGIONAL ON REGIONAL.UF = INFORMACOES.UF
    LEFT JOIN REDE_EXTERNA..TBA_MUNICIPIOS MUNICIPIOS ON MUNICIPIOS.UF = INFORMACOES.UF AND MUNICIPIOS.MUNICIPIO = INFORMACOES.MUNICIPIO
    LEFT JOIN INDICADORES_CORAN..TBA_DIVISAO_MUNICIPIOS_SP_FIXA DIVISAO ON INFORMACOES.MUNICIPIO = DIVISAO.MUNICIPIO AND INFORMACOES.UF = 'SP'
GROUP BY A.TA_REDE_EXTERNA,
         A.ERBS_AFETADAS,
         INFORMACOES.DATA_CRIACAO,
         INFORMACOES.GESTOR_ATUAL,
         INFORMACOES.UF,
         INFORMACOES.MUNICIPIO,
         MUNICIPIOS.CN,
         INFORMACOES.SITE,
         INFORMACOES.TIPO_BILHETE,
         MUNICIPIOS.REGIONAL,
         DIVISAO.NOME_REGIONAL
) Z



--Rede Própria
https://lucide.dev/icons/network
--Rede Swap
https://lucide.dev/icons/waypoints
--TA ERB - Sem TA Raiz Associado
https://lucide.dev/icons/rows-4
--TA ERB - Aberto com TA Raiz Fechado
https://lucide.dev/icons/rows-3



