DECLARE @COLUNAS_DINAMICAS AS NVARCHAR(MAX), @QUERY AS NVARCHAR(MAX)

SET @COLUNAS_DINAMICAS = 
STUFF((
	SELECT ',' + quotename(DATA) FROM( 	
		select
            distinct (CONVERT(varchar,DATA_REFERENCIA,103)) AS DATA
        from TBF_DISPONIBILIDADE_SETORES WHERE DATA_REFERENCIA BETWEEN '27/07/2020' AND '30/08/2020')A ORDER BY CONVERT(DATE,A.DATA) 
	for xml path('')),1,1,'')

print @COLUNAS_DINAMICAS

SET @QUERY = 
'SELECT * FROM
(SELECT convert(VARCHAR,DATA_REFERENCIA,103) AS DATA,UF,MUNICIPIO,CN,SITE,TECNOLOGIA,ERB,SETOR,ROUND(TEMPO_CONTADOR,2) as CELL_DOWNTIME
FROM TBF_DISPONIBILIDADE_SETORES
WHERE UF = ''SP'' AND (TECNOLOGIA = ''GSM'' OR TECNOLOGIA = ''WCDMA'' OR TECNOLOGIA = ''LTE'')) A
PIVOT (SUM(A.CELL_DOWNTIME) FOR A.DATA IN (' + @COLUNAS_DINAMICAS + ')) P ORDER BY CN,MUNICIPIO,SITE,TECNOLOGIA,ERB,SETOR'

print @QUERY

execute(@QUERY)
