--========================================================================
--PRIMEIRA TRAMITAÇÃO PARA CAMPO
--========================================================================
WITH TEMP AS (
		SELECT		    
			EVENTOS.ANO,
			EVENTOS.MES,
			EVENTOS.EVENTO,
			TIPO_BILHETE,
			EVENTOS.TIPO_REDE,
			EVENTOS.TIPO_TA,
			EVENTOS.PRIORIDADE,
			EVENTOS.REGIONAL,
			EVENTOS.GERENCIA,
			EVENTOS.UF,
			EVENTOS.CN,
			EVENTOS.MUNICIPIO,
			EVENTOS.SITE,
			EVENTOS.TIPO_SITE,
			EVENTOS.TIPO_ALARME,
			EVENTOS.GRUPO_CRIACAO,
			EVENTOS.USUARIO_CRIACAO,
			EVENTOS.CLASSIFICACAO_GRUPO_CRIACAO,
			EVENTOS.DATA_APRESENTACAO,
			EVENTOS.DATA_CRIACAO,
			EVENTOS.DATA_ENCERRAMENTO,
			EVENTOS.DATA_BAIXA,
			EVENTOS.GRUPO_BAIXA,
			EVENTOS.GRUPO_RESPONSAVEL_BAIXA,
			EVENTOS.USUARIO_RESPONSAVEL_BAIXA,
			EVENTOS.CLASSIFICACAO_GRUPO_BAIXA,
			EVENTOS.FLAG_BASELINE,
			EVENTOS.GESTOR_TRAM_CAMPO,
			EVENTOS.TEMPO_TRAM_CAMPO,
			EVENTOS.DATA_TRAM_CAMPO,
			LAG(VIDA.GRUPO,1,0) OVER (PARTITION BY VIDA.EVENTO ORDER BY VIDA.COD_VIDA) AS DE,
			LAG(VIDA.CLASSIFICACAO_GRUPO,1,0) OVER (PARTITION BY VIDA.EVENTO ORDER BY VIDA.COD_VIDA) AS CLASSIFICACAO_GRUPO_DE,
			VIDA.GRUPO AS PARA,
			VIDA.CLASSIFICACAO_GRUPO AS CLASSIFICACAO_GRUPO_PARA,
			VIDA.COD_VIDA

		FROM INDICADORES_CORAN..TBL_EVENTOS_FECHADOS EVENTOS WITH (NOLOCK)
			 INNER JOIN INDICADORES_CORAN..TBL_VIDA_FECHADOS VIDA ON VIDA.EVENTO = EVENTOS.EVENTO
	
		WHERE EVENTOS.ANO IN (2022, 2023) AND EVENTOS.MES IN (1,2) AND UF = 'SE'
		) 


SELECT
*
FROM
	(SELECT 
		ROW_NUMBER() OVER (PARTITION BY TEMP.EVENTO ORDER BY TEMP.COD_VIDA ) AS NL,
		TEMP.*
	FROM TEMP
	WHERE TEMP.CLASSIFICACAO_GRUPO_PARA LIKE '%CAMPO%' AND TEMP.CLASSIFICACAO_GRUPO_DE NOT LIKE '%CAMPO%'
	) A
WHERE A.NL = 1
ORDER BY A.EVENTO, A.COD_VIDA
	