SELECT 
CLASSIFICACAO_GRUPO_ENVIOU_CAMPO,
COUNT(*)
FROM (
	SELECT DISTINCT
		TAS.ANO,
		TAS.MES,
		TAS.EVENTO,
		TAS.TIPO_BILHETE,
		TAS.TIPO_REDE,
		TAS.TIPO_TA,
		TAS.PRIORIDADE,
		TAS.DATA_CRIACAO,
		TAS.DATA_ENCERRAMENTO,
		TAS.REGIONAL,
		TAS.GERENCIA,
		TAS.UF,
		TAS.CN,
		TAS.MUNICIPIO,
		TAS.SITE,
		TAS.TIPO_SITE,
		TAS.TIPO_ALARME,
		TAS.GRUPO_CRIACAO,
		TAS.USUARIO_CRIACAO,
		TAS.CLASSIFICACAO_GRUPO_CRIACAO,
		TAS.DE,
		CASE WHEN TAS.CLASSIFICACAO_GRUPO_CRIACAO = 'NOC' AND TAS.CLASSIFICACAO_GRUPO_DE IS NULL THEN 'NOC'
	    ELSE TAS.CLASSIFICACAO_GRUPO_DE END CLASSIFICACAO_GRUPO_DE,
		TAS.PARA,
		CLASSIFICACAO_GRUPO_PARA,
		TAS.GRUPO_RESPONSAVEL_BAIXA,
		TAS.CLASSIFICACAO_GRUPO_BAIXA,
		CASE WHEN PAG.TIPO_PAGAMENTO IS NOT NULL THEN PAG.TIPO_PAGAMENTO
		ELSE 'SOB DEMANDA' END TIPO_PAGAMENTO,
		DATA_TRAM_CAMPO,
		--DATA_PROCEDIMENTO,
		--PROCED.SIGLA_PROCEDIMENTO,
		--VALOR_PROCEDIMENTO,
		PROCED.GRUPO_PROCEDIMENTO AS GRUPO_ENVIOU_CAMPO,
		GRP_DIG.CLASSIFICACAO_GRUPO AS CLASSIFICACAO_GRUPO_ENVIOU_CAMPO
	FROM PLANO_TRANSFORMACAO..TBL_TAS_FECHADOS_TRAM_CAMPO TAS
		 LEFT JOIN PLANO_TRANSFORMACAO..TBL_TIPO_PAGAMENTO PAG ON PAG.UF = TAS.UF AND PAG.SITE = TAS.SITE
		 INNER JOIN PLANO_TRANSFORMACAO..TBL_PROCEDIMENTOS_FECHADOS PROCED ON PROCED.EVENTO = TAS.EVENTO
		 LEFT JOIN PLANO_TRANSFORMACAO..TBL_GRUPOS_DIG GRP_DIG ON GRP_DIG.GRUPO = PROCED.GRUPO_PROCEDIMENTO
	WHERE SIGLA_PROCEDIMENTO = 'ENC' AND DATA_TRAM_CAMPO = DATA_PROCEDIMENTO
	) A
GROUP BY CLASSIFICACAO_GRUPO_ENVIOU_CAMPO





 SELECT TOP 100
 *
 FROM PLANO_TRANSFORMACAO..TBL_TAS_FECHADOS_TRAM_CAMPO




--================================================================================================================
 SELECT DISTINCT
		TAS.ANO,
		TAS.MES,
		TAS.EVENTO,
		TAS.TIPO_BILHETE,
		TAS.TIPO_REDE,
		TAS.TIPO_TA,
		TAS.PRIORIDADE,
		TAS.DATA_CRIACAO,
		TAS.DATA_ENCERRAMENTO,
		TAS.REGIONAL,
		TAS.GERENCIA,
		TAS.UF,
		TAS.CN,
		TAS.MUNICIPIO,
		TAS.SITE,
		TAS.TIPO_SITE,
		TAS.TIPO_ALARME,
		TAS.GRUPO_CRIACAO,
		TAS.USUARIO_CRIACAO,
		TAS.CLASSIFICACAO_GRUPO_CRIACAO,
		TAS.DE,
		CASE WHEN TAS.CLASSIFICACAO_GRUPO_CRIACAO = 'NOC' AND TAS.CLASSIFICACAO_GRUPO_DE IS NULL THEN 'NOC'
	    ELSE TAS.CLASSIFICACAO_GRUPO_DE END CLASSIFICACAO_GRUPO_DE,
		TAS.PARA,
		CLASSIFICACAO_GRUPO_PARA,
		TAS.GRUPO_RESPONSAVEL_BAIXA,
		TAS.CLASSIFICACAO_GRUPO_BAIXA,
		CASE WHEN PAG.TIPO_PAGAMENTO IS NOT NULL THEN PAG.TIPO_PAGAMENTO
		ELSE 'SOB DEMANDA' END TIPO_PAGAMENTO,
		DATA_TRAM_CAMPO,
		--DATA_PROCEDIMENTO,
		--PROCED.SIGLA_PROCEDIMENTO,
		--VALOR_PROCEDIMENTO,
		PROCED.GRUPO_PROCEDIMENTO AS GRUPO_ENVIOU_CAMPO,
		GRP_DIG.CLASSIFICACAO_GRUPO AS CLASSIFICACAO_GRUPO_ENVIOU_CAMPO,
		ROOFTOP.TIPO AS TIPO
	FROM PLANO_TRANSFORMACAO..TBL_TAS_FECHADOS_TRAM_CAMPO TAS
		 LEFT JOIN PLANO_TRANSFORMACAO..TBL_TIPO_PAGAMENTO PAG ON PAG.UF = TAS.UF AND PAG.SITE = TAS.SITE
		 INNER JOIN PLANO_TRANSFORMACAO..TBL_PROCEDIMENTOS_FECHADOS PROCED ON PROCED.EVENTO = TAS.EVENTO
		 LEFT JOIN PLANO_TRANSFORMACAO..TBL_GRUPOS_DIG GRP_DIG ON GRP_DIG.GRUPO = PROCED.GRUPO_PROCEDIMENTO
         LEFT JOIN PLANO_TRANSFORMACAO..TBL_ROOFTOP ROOFTOP ON ROOFTOP.UF = TAS.UF AND ROOFTOP.SITE = TAS.SITE
	WHERE SIGLA_PROCEDIMENTO = 'ENC' AND DATA_TRAM_CAMPO = DATA_PROCEDIMENTO