SELECT DISTINCT
	ANO,
	MES,
	TAS.EVENTO,
	TIPO_BILHETE,
	TIPO_REDE,
	TIPO_TA,
	PRIORIDADE,
	DATA_CRIACAO,
	DATA_ENCERRAMENTO,
	REGIONAL,
	GERENCIA,
	TAS.UF,
	CN,
	MUNICIPIO,
	TAS.SITE,
	TIPO_SITE,
	TIPO_ALARME,
	GRUPO_CRIACAO,
	USUARIO_CRIACAO,
	TAS.GRUPO_CRIACAO,
	TAS.CLASSIFICACAO_GRUPO_CRIACAO,
	GRP3.CLASSIFICACAO AS CLASS_GRUPO_CRIACAO,
	GRP.GRP_NOME AS DE,
	CASE WHEN GRP3.CLASSIFICACAO = 'NOC' AND GRP.CLASSIFICACAO IS NULL THEN 'NOC'
	ELSE GRP.CLASSIFICACAO END CLASS_GRUPO_DE,
	--GRP.CLASSIFICACAO AS CLASS_GRUPO_DE,
	CLASSIFICACAO_GRUPO_DE,
	GRP2.GRP_NOME,
	GRP2.CLASSIFICACAO AS CLASS_GRUPO_PARA,
	CLASSIFICACAO_GRUPO_PARA,
	TAS.GRUPO_RESPONSAVEL_BAIXA,
	GRP4.CLASSIFICACAO AS CLASS_GRUPO_BAIXA,
	CASE WHEN PAG.TIPO_PAGAMENTO IS NOT NULL THEN PAG.TIPO_PAGAMENTO
	ELSE 'SOB DEMANDA' END TIPO_PAGAMENTO,
	DATA_TRAM_CAMPO,
	DATA_PROCEDIMENTO,
	PROCED.SIGLA_PROCEDIMENTO,
	VALOR_PROCEDIMENTO,
	PROCED.GRUPO_PROCEDIMENTO
FROM PLANO_TRANSFORMACAO..TBL_TAS_FECHADOS_TRAM_CAMPO TAS
	 LEFT JOIN PLANO_TRANSFORMACAO..TBL_GRUPOS GRP ON GRP.GRP_NOME = TAS.DE
	 LEFT JOIN PLANO_TRANSFORMACAO..TBL_GRUPOS GRP2 ON GRP2.GRP_NOME = TAS.PARA
	 LEFT JOIN PLANO_TRANSFORMACAO..TBL_GRUPOS GRP3 ON GRP3.GRP_NOME = TAS.GRUPO_CRIACAO
	 LEFT JOIN PLANO_TRANSFORMACAO..TBL_GRUPOS GRP4 ON GRP4.GRP_NOME = TAS.GRUPO_RESPONSAVEL_BAIXA
	 LEFT JOIN PLANO_TRANSFORMACAO..TBL_TIPO_PAGAMENTO PAG ON PAG.UF = TAS.UF AND PAG.SITE = TAS.SITE
	 INNER JOIN PLANO_TRANSFORMACAO..TBL_PROCEDIMENTOS_FECHADOS PROCED ON PROCED.EVENTO = TAS.EVENTO
 WHERE SIGLA_PROCEDIMENTO = 'ENC'








--EVENTOS REPETIDOS NA MESMA HORA
SELECT
*
FROM (
	SELECT
		UF,
		SITE,
		CONCAT(DATEPART(dd,DATA_TRAM_CAMPO),'/',DATEPART(mm,DATA_TRAM_CAMPO),'/',DATEPART(yyyy,DATA_TRAM_CAMPO)) AS DATA,--,'-',DATEPART(hh,DATA_TRAM_CAMPO),'h') AS DATA,
		COUNT(EVENTO) AS QTDE
	FROM TBL_EVENTOS_CAMPO
	GROUP BY UF,SITE,DATA_TRAM_CAMPO
	) A
WHERE QTDE <> 1
ORDER BY QTDE DESC,UF,SITE,DATA
--============================================================================================================================

	SELECT  DISTINCT EVENTO,
			CONVERT(VARCHAR, DATEDIFF(DAY, DATA_TRAM_CAMPO, DATA_ENCERRAMENTO)) + 'd '
			+ RIGHT('00' + CONVERT(VARCHAR, DATEDIFF(HOUR, DATA_TRAM_CAMPO, DATA_ENCERRAMENTO) % 24), 2) + ':'
			+ RIGHT('00' + CONVERT(VARCHAR, DATEDIFF(MINUTE, DATA_TRAM_CAMPO, DATA_ENCERRAMENTO) % 60), 2) + ':'
			+ RIGHT('00' + CONVERT(VARCHAR, DATEDIFF(SECOND, DATA_TRAM_CAMPO, DATA_ENCERRAMENTO) % 60), 2) AS DATA
	FROM PLANO_TRANSFORMACAO..TBL_EVENTOS_CAMPO
	ORDER BY EVENTO
