SELECT *
	FROM
		(SELECT
		REGIONAL,
		UF,
		MUNICIPIO,
		MAX(CASE WHEN MES = 1 THEN DISPONIBILIDADE_GERAL END) DISP_JAN,
		MAX(CASE WHEN MES = 2 THEN DISPONIBILIDADE_GERAL END) DISP_FEV,
		MAX(CASE WHEN MES = 3 THEN DISPONIBILIDADE_GERAL END) DISP_MAR,
		MAX(CASE WHEN MES = 4 THEN DISPONIBILIDADE_GERAL END) DISP_ABR,
		MAX(CASE WHEN MES = 5 THEN DISPONIBILIDADE_GERAL END) DISP_MAI,
		MAX(CASE WHEN MES = 6 THEN DISPONIBILIDADE_GERAL END) DISP_JUN,
		MAX(CASE WHEN MES = 7 THEN DISPONIBILIDADE_GERAL END) DISP_JUL,
		CLA.CLASSIFICACAO,
		ISNULL(PLA.TOTAL, 0) AS PLANOS_CADASTRADOS
		FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_MENSAL_MUNICIPIO_HMM CDT
		LEFT JOIN (SELECT UF AS UF_P, MUNICIPIO AS MUNICIPIO_P, CLASSIFICACAO FROM SISTEMA_MAESTRO..AUX_CLASSIFICACAO_MUNICIPIOS) CLA ON CDT.UF = CLA.UF_P AND CDT.MUNICIPIO = CLA.MUNICIPIO_P
		LEFT JOIN (SELECT UF AS UF_PL, MUNICIPIO AS MUNICIPIO_PL, COUNT(*) AS TOTAL FROM INDICADORES_CORAN..TBC_PLANO_ACAO GROUP BY UF, MUNICIPIO)PLA ON CDT.UF = PLA.UF_PL AND CDT.MUNICIPIO = PLA.MUNICIPIO_PL
		WHERE ANO = 2022
		GROUP BY UF, REGIONAL,MUNICIPIO, CLASSIFICACAO, TOTAL) B
	WHERE UF IN ('AL','CE','PB','PE','PI','RN')

--===============================================================================================================================================
USE INDICADORES_CORAN
SELECT *
	FROM
		(SELECT
		REGIONAL,
		UF,
		MUNICIPIO,
		MAX(CASE WHEN MES = 1 THEN DISPONIBILIDADE_GERAL END) DISP_JAN,
		MAX(CASE WHEN MES = 2 THEN DISPONIBILIDADE_GERAL END) DISP_FEV,
		MAX(CASE WHEN MES = 3 THEN DISPONIBILIDADE_GERAL END) DISP_MAR,
		MAX(CASE WHEN MES = 4 THEN DISPONIBILIDADE_GERAL END) DISP_ABR,
		MAX(CASE WHEN MES = 5 THEN DISPONIBILIDADE_GERAL END) DISP_MAI,
		CLA.CLASSIFICACAO,
		ISNULL(PLA.TOTAL, 0) AS PLANOS_CADASTRADOS
		FROM INDICADORES_CORAN..TBF_CELLDOWNTIME_MENSAL_MUNICIPIO_HMM CDT
		LEFT JOIN (SELECT UF AS UF_P, MUNICIPIO AS MUNICIPIO_P, CLASSIFICACAO FROM SISTEMA_MAESTRO..AUX_CLASSIFICACAO_MUNICIPIOS) CLA ON CDT.UF = CLA.UF_P AND CDT.MUNICIPIO = CLA.MUNICIPIO_P
		LEFT JOIN (SELECT UF AS UF_PL, MUNICIPIO AS MUNICIPIO_PL, COUNT(*) AS TOTAL FROM INDICADORES_CORAN..TBC_PLANO_ACAO GROUP BY UF, MUNICIPIO)PLA ON CDT.UF = PLA.UF_PL AND CDT.MUNICIPIO = PLA.MUNICIPIO_PL
		WHERE ANO = 2022 AND REGIONAL = 'NE'
		GROUP BY UF, REGIONAL,MUNICIPIO, CLASSIFICACAO, TOTAL) B
	WHERE CLASSIFICACAO = 'ROB'